### ISSUE TITLE
Qt6 tooltips illegible, not obeying Kvantum theme rules

### ISSUE THREAD

**Issue by geckolinux** [tsujan/Kvantum#1004]
Hi there, first of all, many thanks for Kvantum, which is the only viable option right now on the Linux desktop for theming Qt6 apps.

I noticed a bug in which tooltips in Qt6 don't obey the Kvantum theme rules, and in most Kvantum themes Qt tooltips are almost illegible. Here's an example of two very similar Qt apps, Clementine (Qt5) and Strawberry (Qt6) using the same KvYaru theme:

![Screenshot from 2024-09-03 00-49-56](https://github.com/user-attachments/assets/5e46e2ec-fa2c-4799-b91a-f31801be7161)

![Screenshot from 2024-09-03 00-50-01](https://github.com/user-attachments/assets/552a4432-4cba-4ba3-ae85-c278adea1fc9)

All other Qt6 apps that I have tested (qpwgraph, Calamares, qpdfview) have the same issue, whereas all Qt5 apps that I've tested render tooltips correctly.

I confirmed that `tooltip.text.color=white` . Here's the complete theme: [KvYaru#.kvconfig](https://github.com/user-attachments/files/16844149/KvYaru.kvconfig.txt)

This is with Kvantum 1.1.2  on openSUSE Tumbleweed.

**Comment by tsujan** [comment]
Not reproducible. All my Qt apps are Qt6-based.
