### ISSUE TITLE
Kvantum prevents palette changes with QWindowSystemInterface::handleThemeChange

### ISSUE THREAD

**Issue by ilya-fedin** [tsujan/Kvantum#1018]
That seem to happen due to this code:
https://github.com/tsujan/Kvantum/blob/5782f5bd7f41526560f859c502881686f89f502c/Kvantum/style/polishing.cpp#L1057-L1063

Would be nice if Kvantum wasn't doing this or the code had `palette.setResolveMask(0);` before the setPalette line (what would make Qt think the palette is not overridden by the application).

**Comment by tsujan** [comment]
I'm afraid, this has been explained so many times. Please search to find the reason yourself.

> That seem to happen due to this code...

Not just that. I've made sure that nothing could disturb Kvantum in this regard.

**Comment by ilya-fedin** [comment]
> I'm afraid, this has been explained so many times. Please search to find the reason yourself.

Hm. I tried to search `palette` through the issues but I mostly got issues about wrong text colors, compile errors, etc. Seems like it's not easily discoverable if you had to explain many times? Maybe actualize the comment to avoid further reports?

> Not just that. I've made sure that nothing could disturb Kvantum in this regard.

The problem I have is that Kvantum palette remains applied after the style is changed to another which doesn't really look correct.

**Comment by ilya-fedin** [comment]
Maybe restore the palette in unpolish at least?

**Comment by ilya-fedin** [comment]
Simple `app->setPalette(QPalette());` in `Style::unpolish(QApplication *app)` would make switching out of kvantum way better. Can we have it?

**Comment by tsujan** [comment]
Read https://doc.qt.io/qt-6/qwidget.html#palette-prop → last paragraph. There are also other places where Qt doc explains that not all styles follow palettes.

Read https://github.com/tsujan/Kvantum/issues/818#issuecomment-1216675739 for some details.

> The problem I have is that Kvantum palette remains applied after the style is changed to another...

If that happens, blame either those styles or the platform plugin. Palette management is the least a style should do, and a platform plugin is responsible for applying palettes correctly. I've never seen that with LXQt's plugin.

**Comment by ilya-fedin** [comment]
> If that happens, blame either those styles or the platform plugin. Palette management is the least a style should do, and a platform plugin is responsible for applying palettes correctly. I've never seen that with LXQt's plugin.

The problem is that most out-of-Qt-tree platform plugins do that incorrectly. They abuse Q(Gui)Application::setPalette/setFont, QIcon::setThemeName, etc, that are for applications to override platform palette/font/icon theme, not platform theme to inform update. The intended way is to use `QWindowSystemInterface::handleThemeChange()` and that is something Qt's in-tree platform themes do. This way checks whether font/palette/icon theme was overridden by application and will ignore the change in that case.

Kvantum uses the API meant for application to override the palette thus preventing any further palette changes done by `QWindowSystemInterface::handleThemeChange()`. If Kvantum really wants to do that, please revert the override when unpolishing so that `QWindowSystemInterface::handleThemeChange()` continues to work.

**Comment by tsujan** [comment]
An example of a platform plugin that does it correctly: https://github.com/lxqt/lxqt-qtplugin/blob/master/src/lxqtplatformtheme.cpp. KDE's platform plugin also does it correctly.

Kvantum already makes sure that there's no intrusion:
https://github.com/tsujan/Kvantum/blob/5782f5bd7f41526560f859c502881686f89f502c/Kvantum/style/polishing.cpp#L1203-L1213

Problems of other programs should be fixed by their devs.

**Comment by ilya-fedin** [comment]
> An example of a platform plugin that does it correctly: https://github.com/lxqt/lxqt-qtplugin/blob/master/src/lxqtplatformtheme.cpp.

That's not really the correct way. See how Qt itself does that:
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platforms/ios/quiwindow.mm#L59
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platforms/cocoa/qcocoatheme.mm#L256
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platformthemes/gtk3/qgtk3storage.cpp#L305
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platformthemes/gtk3/qgtk3theme.cpp#L87
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/gui/platform/unix/qgenericunixthemes.cpp#L912
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platforms/android/qandroidplatformtheme.cpp#L338
https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/plugins/platforms/windows/qwindowstheme.cpp#L784

And here's the code get triggered by thus function: https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/gui/kernel/qguiapplication.cpp#L2790

Which eventually gets here: https://github.com/qt/qtbase/blob/0b5874bc96f4d1a8cba4fe14ee0b3499cc04c8cd/src/gui/kernel/qguiapplication.cpp#L2790

It uses QPalette::resolve that checks the resolve mask: https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qpalette.cpp#L966

Thus if you don't reset the palette, Qt merges the palette instead of replacing.

QPalette default constuctor uses the application palette but resets the resolve mask: https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qpalette.cpp#L544 (so you can set it on unpolish to fix the change)

**Comment by tsujan** [comment]
Sorry that I have to lock this page. You comments are becoming long-winded and irrelevant.
