### ISSUE TITLE
Feature request: qqc2 style kvantum

### ISSUE THREAD

**Issue by hazel-bunny** [tsujan/Kvantum#1019]
Many apps, including both KDE and non-KDE apps, are moving to QML and/or QtQuick. Kvantum is unable to theme them. Kvantum themes, however, provide almost all elements and controls that an app needs. If there is an adaptation of Kvantum for QML and QtQuick, it will provide more visual consistency.

**Comment by tsujan** [comment]
doc → `Theme-Making.pdf` → A word about QML/Qt Quick

Install `qqc2-desktop-style` and set `QT_QUICK_CONTROLS_STYLE` to `org.kde.desktop`.
