### ISSUE TITLE
kvantum not following system colorscheme

### ISSUE THREAD

**Issue by m-abubakar** [tsujan/Kvantum#1024]
![image](https://github.com/user-attachments/assets/2aa48481-70a9-4715-b46e-307f73687677)

Hi,
   As seen in the above screenshot kvantum is not following system colors. The color stays the same (blue). 

Thank you for your work, really appreciate it.

**Comment by tsujan** [comment]
> kvantum not following system colorscheme

It shouldn't, because it's a _SVG-based_ style engine and has its own colors. The code makes sure that external palettes don't interfere with it. Also read the last paragraph https://doc.qt.io/qt-6/qwidget.html#palette-prop.

**Comment by tsujan** [comment]
If you use KDE, to make QML apps more compatible with Kvantum, apply the color scheme that comes with the active Kvanum theme or matches it — such schemes are included in Kvantum and are available when it's installed (completely). Please read Kvantum Manager → Change/Delete Themes.

**Comment by m-abubakar** [comment]
Ah ok, Thank you for your response.

So I want to achieve a transparent ui with above color. Do I have to create a theme for kvantum based on KvGlass to make this work ?

**Comment by tsujan** [comment]
Background translucency doesn't need a new theme (see Kvantum manager → Configure Active Theme → Compositing & General Look), but background color does.

See, e.g., https://github.com/tsujan/Kvantum/discussions/598 and https://github.com/tsujan/Kvantum/issues/818#issuecomment-1216675739 for more info.
