### ISSUE TITLE
Add kvantum-light as Widgget Style for eink-displays

### ISSUE THREAD

**Issue by ralf3u** [tsujan/Kvantum#1026]
On eink-displays kvantum and kavantum-dark as Widget Sytle makes no sense because there is no need for dark-mode.

The best would be to add kvantum-light as Widgget Style where the focused tab in PCManFM-Qt is underlined to see on eink-displays better which tab has focus.

**Comment by ralf3u** [comment]
>There are several light themes among the themes included in Kvantum.

I tried all LXQt Themes of the Widget Style `kvantum`. All of them have dark background.
Which light theme do you mean?

**Comment by tsujan** [comment]
Kvantum isn't an LXQt theme. You may have mistaken the LXQt theme with the name "Kvantum" for the Kvantum widget style.

If you haven't made that mistake, make sure you have installed Kvantum completely (distros like Ubuntu split it into multiple packages) and use `Kvantum Manager` to choose Kvantum themes.

**Comment by ralf3u** [comment]
>If you haven't made that mistake, make sure you have installed Kvantum completely (distros like Ubuntu split it into multiple packages) and use Kvantum Manager to choose Kvantum themes.

Just to be on the safe side:
In the main menu, in Preferences, in LXQt-Settings, in Appearance, in Widget Style, I select `kvantum`.
Then I install Kvantum completely.
And then there should be somewhere `Kvantum Manager` to choose Kvantum themes. Is that correct?

**Comment by ralf3u** [comment]
I did this in the terminal, like described in https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md:
```
sudo add-apt-repository ppa:papirus/papirus
sudo apt update
sudo apt install qt6-style-kvantum qt6-style-kvantum-themes
```
In LXQt-Settings I can see Kvantum Manager. I think that I should change something in `Configure Active Theme`. But how do I get the light theme?

**Comment by tsujan** [comment]
> I think that I should change something in Configure Active Theme.

No.

You should see many themes in the drop-down menu of `Change/Delete Theme`. Read and follow the explanation in the GUI.

**Comment by ralf3u** [comment]
In `Change/Delete Themes` I selected `KvArcYaru`. So now there is a underline on the focused tab in PCManFM-Qt, something what I was looking for.
In `Configure Active Theme`, in `Miscellaneous` I activated `Left aligned tabs`.

The only two things what I miss in PCManFM-Qt is:
- If I click in the menu on `Edit` there is no small border any more around all the items.
- If I select an item of `Edit`, like `Copy`, then the font does not change to white and the background does not change to dark.

Is there a possibility to solve the two things?

**Comment by tsujan** [comment]
Each theme has its own style. Find a theme that you're happy with, or make a new theme (extremely difficult).

BTW, `KvArcYaru` doesn't belong to Kvantum, although that's beside the point. Theme makers have created many themes for Kvantum.

**Comment by ralf3u** [comment]
Thank you for your help.

**Comment by tsujan** [comment]
You're welcome.

If you want a similar look with GTK apps, you could choose `KvGnome`. It should be among the themes if the packages that you've installed are standard.

**Comment by ralf3u** [comment]
>If you want a similar look with GTK apps, you could choose KvGnome.

I tried KvGnome. Then the two things of https://github.com/tsujan/Kvantum/issues/1026#issuecomment-2481671019 are solved. But then there are two other things:
- In the tool bar, the symbol for compact view that is active has unfortunately not any more a black border but a black background that is too intense for me.
- In the location bar, the current file has unfortunately not any more a black border but a black background that is too intense for me.

Because I don't know how to change these two things, I will stay for KvArcYaru. But thank you for the hint.
