### ISSUE TITLE
Add a "eInk" theme

### ISSUE THREAD

**Issue by ralf3u** [tsujan/Kvantum#1027]
In the near future eInk-displays will become more popular. So, what about the idea to add an `eInk` theme?

**Possible solution**
The theme `KvArcYaru` could be a good base to start with the creation of an `eInk` theme. Two things should be changed:
- If one click in PCManFM-QWt in the menu for example on `Edit` there is no small border around all the items. The best would be if there would be a small border around all the items.
- If one click in PCManFM-QWt in the menu for example on `Edit`, then the focused item of the list does not change its behavior in a clear visible form. The best would be if the background becomes black and the font becomes white of the focused item.

**Remark I**
In the current theme `KvGnome` the two things from above are solved, but:
- In the tool bar, the symbol for compact view that is active has unfortunately not any more a black border but a black background that is too intense.
- In the location bar, the current file has unfortunately not any more a black border but a black background that is too intense.

**Remark  II**
In the `eInk` theme, in `Configure Active Theme`, in `Miscellaneous`, `Left aligned tabs` should be activated by default.

**History**
This issue is based on the knowledge of #1026.

**Comment by tsujan** [comment]
I'm afraid I have no plan to add more themes or change the current themes that come with Kvantum. My focus is on the code.

There are many other Kvantum themes, and you might want to talk with their authors.

**Comment by ralf3u** [comment]
>[...] and you might want to talk with their authors.

Where do I get the information who the author of KvArcYaru is?
