### ISSUE TITLE
version 1.1.3 seems to ignore VLC opacity

### ISSUE THREAD

**Issue by Gpinchon** [tsujan/Kvantum#1029]
When using VLC with a semitransparent theme (namely [MacSequoia](https://github.com/vinceliuice/MacSequoia-kde)) it seems Kvantum ignores the opaque apps list and makes VLC's fullscreen UI semi transparent no matter what, making it unusable.

**Comment by tsujan** [comment]
Not reproducible, with MacSequoia either.

Make sure you haven't installed Kvantum or VLC in a nonstandard way, like with Flatpack.

**Comment by Gpinchon** [comment]
I realized I had an older version of the Kvantum runtime from flathub, removing all runtimes and reinstalling it from Discover kind of fixes the issue since it seems VLC now defaults to Breeze and is not using Kvantum anymore. Should I open an issue on VLC or Kvantum flatpak pages ?

**Comment by tsujan** [comment]
> since it seems VLC now defaults to Breeze

It's also possible that you (or your distro) have changed its setting about forcing window style.

**Comment by Gpinchon** [comment]
> It shouldn't, if you've installed it in a standard way.

I installed it via flatpak so maybe I'm missing a configuration key... The only thing I set accross all flatpaks are `QT_QPA_PLATFORMTHEME=kde` and `QT_STYLE_OVERRIDE=` (which removes any override previously set)

**Comment by tsujan** [comment]
Flatpak and other methods like it create false problems. Of course, they don't tell users about that in their advertisements.

**Comment by Gpinchon** [comment]
Yeah I saw that the flathub's runtime is severely outdated and that their bots keep failing to update it (because it won't update the dependencies). I created an issue to ask for a manual intervention.
