### ISSUE TITLE
Tabs auto align center?

### ISSUE THREAD

**Issue by dayflip** [tsujan/Kvantum#103]
I notice when I'm using Kvantum. Tabs in qt5 application such as pacman-qt, konsole, dolphin, FeatherPad. Tabs all align center. Is there away to align them left or right? ( left if possible ) or leave it as a global option to switch between the three?

**Comment by tsujan** [comment]
Yes, of course! Chek `Kvantum Manager` → `Configure Active Theme` → `Miscellaneous` → `Left aligned tabs` and then click the Save button. Apps should be restarted afterward. In the case of pcmanfm-qt, you could restart it from `LXQt Configuration Center` → `Session Settings`, or just log out and in.

In some of Kvantum's extra themes, tabs are left aligned by default. Anyway, their alignment can always be changed by the above checkbox.

**Comment by dayflip** [comment]
Thank you. I'm still learning about this new theme engine. Mostly with the change made in LXQt 11.0.

**Comment by tsujan** [comment]
Kvantum Manager has many options in its third page. You could play with them and if something goes wrong, you could always use the Restore button (that will appear after saving). Use the Help button for explanations!

**Comment by tsujan** [comment]
And yes, with LXQt, there's no need to log out. However, changing widget styles sometimes creates artifacts that will be removed after logging out and in.

**Comment by dayflip** [comment]
A little off topic. Any suggestion for changing the SVG image. Do you used inkscape? I do plain on making my own theme with this.

**Comment by tsujan** [comment]
Inkscape is the best. For theme making, read `doc/Theme-Config.pdf` and `doc/Theme-Making.pdf`!
