### ISSUE TITLE
Too long text size in panel buttons, small issue left

### ISSUE THREAD

**Issue by stefonarch** [tsujan/Kvantum#104]
Last commit works nicely thanks, but on my LXQt box the first letter is sometimes half blurred, I see this  mit all Kvantum themes I've tested; it's also  indipendent from icon size set in panel config. But it does not happen with every text that's too long, no clue yet when.
![schermata](https://cloud.githubusercontent.com/assets/10681413/19163391/0f0279c8-8bfc-11e6-8e02-b8b1a87b8b33.png)

**Comment by tsujan** [comment]
Strange! Which LXQt theme do you use? Please paste all of its TaskBar blocks here if there is any!

**Comment by stefonarch** [comment]
I use my slightly modified system theme, in fact it's here the cause:

> Plugin > QToolButton,
> Plugin > QWidget > QToolButton,
> Plugin > QWidget > QToolButton > QWidget > QToolButton,
> LXQtPanelPlugin > QToolButton {
>    margin: 2px 4px;
>    padding: 2px;
> }
 Will modify my theme. Closing.

**Comment by tsujan** [comment]
Yes, that's the cause because QStyle can't know about CSS margins and paddings. However, I re-open the issue temporarily to see if I could distinguish such cases. Now I'm busy with fixing a bug in FeatherPad but later I'll look into it.

**Comment by tsujan** [comment]
@stefonarch 
Please test the latest commit! Now it should work with margin and padding too.

**Comment by stefonarch** [comment]
Perfect, even with margin: 2px 6px
![schermata08](https://cloud.githubusercontent.com/assets/10681413/19189198/eede9dc0-8c96-11e6-82e9-3612167dbc84.png)

**Comment by tsujan** [comment]
Thanks for the report and test! I may change the logic of other similar workarounds too.
