### ISSUE TITLE
cant build on fedora

### ISSUE THREAD

**Issue by samuaz** [tsujan/Kvantum#108]
Hi tsujan, i having build problem on fedora 25:

````
[samuel@toshiba Kvantum]$ /usr/bin/qmake-qt5
[samuel@toshiba Kvantum]$ make
cd style/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/samuel/Kvantum-master/Kvantum/style/style.pro -o Makefile ) && make -f Makefile 
make[1]: se entra en el directorio '/home/samuel/Kvantum-master/Kvantum/style'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_Kvantum.o moc_Kvantum.cpp
moc_Kvantum.cpp: En la función miembro static ‘static void Kvantum::Style::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
moc_Kvantum.cpp:106:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 0: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])),(*reinterpret_cast< const QStyleOption*(*)>(_a[2])),(*reinterpret_cast< const QWidget*(*)>(_a[3])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:108:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 1: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])),(*reinterpret_cast< const QStyleOption*(*)>(_a[2])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:110:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 2: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:777: fallo en las instrucciones para el objetivo 'moc_Kvantum.o'
make[1]: *** [moc_Kvantum.o] Error 1
make[1]: se sale del directorio '/home/samuel/Kvantum-master/Kvantum/style'
Makefile:45: fallo en las instrucciones para el objetivo 'sub-style-make_first'
make: *** [sub-style-make_first] Error 2
[samuel@toshiba Kvantum]$ 
`

```

any ideas? Thanks

**Comment by tsujan** [comment]
Hi,

That message complains about "standardIconImplementation", which is only in Qt4. Perhaps, after compiling Kvantum against Qt4 (Qt5), you didn't use `make distclean` to clean the build directory and then tried to compile it against Qt5 (Qt4).

Please start with a clean source and follow the instructions in the file "INSTALL"!

BTW, isn't there any rpm for Kvantum in Fedora?

**Comment by samuaz** [comment]
no there is not a rpm in fedora or i never found it, there is one for opensuse13 but i dont know if is out to update. i did a make clean and the same error this is te output:

```
[samuel@toshiba Kvantum]$ /usr/bin/qmake-qt5
Info: creating stash file /home/samuel/Kvantum-master/Kvantum/.qmake.stash
[samuel@toshiba Kvantum]$ make
cd style/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/samuel/Kvantum-master/Kvantum/style/style.pro -o Makefile ) && make -f Makefile 
make[1]: se entra en el directorio '/home/samuel/Kvantum-master/Kvantum/style'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o ThemeConfig.o themeconfig/ThemeConfig.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o Kvantum.o Kvantum.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o KvantumPlugin.o KvantumPlugin.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o shortcuthandler.o shortcuthandler.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o x11wmmove.o drag/x11wmmove.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o windowmanager.o drag/windowmanager.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o blurhelper.o blur/blurhelper.cpp
/usr/lib64/qt5/bin/rcc -name defaulttheme themeconfig/defaulttheme.qrc -o qrc_defaulttheme.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o qrc_defaulttheme.o qrc_defaulttheme.cpp
/usr/lib64/qt5/bin/moc -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/samuel/Kvantum-master/Kvantum/style -I/usr/include/qt5 -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtX11Extras -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/6.2.1 -I/usr/include/c++/6.2.1/x86_64-redhat-linux -I/usr/include/c++/6.2.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/6.2.1/include -I/usr/local/include -I/usr/include Kvantum.h -o moc_Kvantum.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_Kvantum.o moc_Kvantum.cpp
moc_Kvantum.cpp: En la función miembro static ‘static void Kvantum::Style::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
moc_Kvantum.cpp:106:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 0: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])),(*reinterpret_cast< const QStyleOption*(*)>(_a[2])),(*reinterpret_cast< const QWidget*(*)>(_a[3])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:108:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 1: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])),(*reinterpret_cast< const QStyleOption*(*)>(_a[2])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:110:34: error: ‘class Kvantum::Style’ has no member named ‘standardIconImplementation’
         case 2: { QIcon _r = _t->standardIconImplementation((*reinterpret_cast< StandardPixmap(*)>(_a[1])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:777: fallo en las instrucciones para el objetivo 'moc_Kvantum.o'
make[1]: *** [moc_Kvantum.o] Error 1
make[1]: se sale del directorio '/home/samuel/Kvantum-master/Kvantum/style'
Makefile:45: fallo en las instrucciones para el objetivo 'sub-style-make_first'
make: *** [sub-style-make_first] Error 2
[samuel@toshiba Kvantum]$ 
```

**Comment by tsujan** [comment]
Then, there may be something wrong in your Qt5 installation. Have you installed Fedora-25 from its ISO image or did you upgrade your Fedor installatio to it?

**Comment by samuaz** [comment]
my installation is the fedora-25-workstation KDE spin from official iso, maybe they hava missing devel package?

**Comment by tsujan** [comment]
Oh, devel (dev) packages aren't usually included in ISO images. You need to have these packages:

libX11-devel
libXext-devel
qtbase5-devel
qt5-qtsvg-devel
qt5-qtx11extras-devel

Please see that the names may not be correct because I don't have Fedora but found their names on the Internet. Do you have the above packages installed?

**Comment by samuaz** [comment]
yes, i have all of those packages installed

**Comment by tsujan** [comment]
OK. I'll download and install fedora-25 on VirtualBox to see what's the problem. It may take a while.

**Comment by tsujan** [comment]
OK. I installed Fedora 25 on VitualBox and after installing the following packages, `qmake-qt5 && make` worked without any problem and Kvantum was compiled (use `sudo yum install ...` to install all the packages if some of them are missing):

gcc-c++
libX11-devel
libXext-devel
qt5-qtbase-devel
qt5-qtsvg-devel
qt5-qtx11extras-devel

A screenshot:

![fedora25](https://cloud.githubusercontent.com/assets/981076/21081699/3c34dbfc-bfe1-11e6-8dc1-f10e551ba356.png)

I was surprised to see that gcc-c++ wan't installed after installing Qt5 devel packages, so that I had to install it myself. I'll add a few lines to the file "INSTALL" for Fedora.

By the way, I started to use Linux with Fedora when the Fedora project was recently started and stayed with it for 2 years. Installing Frdora-25 on VirtualBox made me nostalgic ;)

**Comment by samuaz** [comment]
i allready have all of those packages, i try reinstall and build but the error persist i will try to make a fresh install of fedora and retry

**Comment by tsujan** [comment]
In my opinion, it's not a good idea to re-install any Linux distro. All problems can be solved in Linux. In all years that I've used Linux, I haven't needed to re-install any ditro, whether it was mine or my friends'. I remember instances of kernel panic that were fixed relatively easily. The Linux user learns how to fix things only if he/she doesn't re-install his/her distro on finding problems.

I'm sure this is a small problem that can be fixed easily. Anyway, it's surely *your* choice to re-install Fedora or not -- I just wanted to share my experience :)

**Comment by samuaz** [comment]
Hi, fresh install and only install: 
gcc-c++
libX11-devel
libXext-devel
qt5-qtbase-devel
qt5-qtsvg-devel
qt5-qtx11extras-devel

and the same error at build time, what it to is open a terminal in the source pad, do qmake-qt5 && make and the same output:

Gui -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -
moc_Kvantum.cpp: En la función miembro static ‘static void Kvantum::Style::qt
moc_Kvantum.cpp:106:34: error: ‘class Kvantum::Style’ has no member named ‘st
         case 0: { QIcon _r = _t->standardIconImplementation((*reinterpret_carpret_cast< const QWidget*(*)>(_a[3])));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:108:34: error: ‘class Kvantum::Style’ has no member named ‘st
         case 1: { QIcon _r = _t->standardIconImplementation((*reinterpret_ca
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
moc_Kvantum.cpp:110:34: error: ‘class Kvantum::Style’ has no member named ‘st
         case 2: { QIcon _r = _t->standardIconImplementation((*reinterpret_ca

**Comment by tsujan** [comment]
That's very strange! I downloaded the latest ISO (Fedora-KDE-Live-x86_64-25-1.3.iso) today and installed Fedora in English and with an Internet connection, i.e., in the standard way. Something should be definitely different in your case -- maybe the locale or....?

Anyhow, this isn't a Kvantum bug. I close this issue but feel free to add comments -- I'll read and reply to them.

**Comment by tsujan** [comment]
Good news: I started my Fedora 25 on VirtualBox, tried to compile Kvantum *for the second time*, and encountered exactly the same problem you reported here!

Bad news: Since the first compilation was successful, this is definitely a bug in Fedora 25.

I'll try to find a workaround.

**Comment by tsujan** [comment]
At last I found and added a workaround for this annoying Fedora problem. It works on VirtualBox. Please try the latest GitHub version! Thanks!

**Comment by tsujan** [comment]
Ignore my previous comment! I encountered more and more problems in Fedora 25 on VirtualBox. Something is seriously wrong with it. Therefore, I reversed the last commit.

This is the situation in Fedora-25 so far:

(1) Kvantum was compiled and installed correctly the first time (see the above screenshot);
(2) The second time, it couldn't be compiled, complaining about a missing function (as you reported);
(3) With some changes, it was compiled successfully but after installation, the system didn't recognize it.

Unfortunately, this situation isn't something I can handle because its source is outside Kvantum.

**Comment by tsujan** [comment]
For the record:

Fedora-25 doesn't see the preprocessor directive `#if` inside access modifiers (public, private, protected,...). If Qt4-related `#if` directives are removed from headers, Kvantum will be compiled and installed correctly on Fedora-25 but in that case, the Qt4 support will be removed -- something I don't intend to do.

I've seen no bug report yet, perhaps because Fedora-25 is new or because there aren't plenty of programs with `#if` inside their access modifiers (which is legal).

**Comment by tsujan** [comment]
I added CMake support for Qt5. Now you could compile and install Kvantum on Fedora 25 with these commands inside the source directory:
````
mkdir build && cd build
cmake ..
make
sudo make install
````
It works on VirtualBox.

Thanks for the report!
