### ISSUE TITLE
Look and Feel / KDE integration support

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#111]
Will be good if you integrate setting to kde. For example, kvantum have setting on ~/.config/Kvantum, but plasma have settings on ~/.config/rc-files. If i'm  create Look and Feel settings - kvantum theme not possible change, because setting contained on another folder. Maybe possible add this spport for Kvantum engine? Also will be good if you integrate kavntummanager to systemsettings5
![image](https://cloud.githubusercontent.com/assets/8083855/22061350/02da3d14-dd8e-11e6-9fa6-39c3ebe6217d.png)
See, used default kvatum theme - look and feel not supported
Look and Feel settings:
```
[kdeglobals][KDE]
widgetStyle=kvantum

[kdeglobals][General]
ColorScheme=Arc Dark

[kdeglobals][Icons]
Theme=Papirus-Dark

[plasmarc][Theme]
name=Arc-Dark

[kwinrc][org.kde.kdecoration2]
theme=__aurorae__svg__Arc-Dark

[kcminputrc][Mouse]
cursorTheme=breeze_cursors
```

**Comment by varlesh** [comment]
I know Kvantum this not only engine for KDE and used for others DE... but maybe this possible add support build-flag or option or etc...

**Comment by tsujan** [comment]
From the beginning, I've strongly preferred Kvantum to remain independent of KDE at all costs because I want it to work on all DE's without extra dependencies; KDE is heavy; KDE changes more than (and independently from) Qt; KDE has more bugs than Qt does; and so on... Therefore, I'll never make Kvantum dependent ok KDE.

That being said, Kvantum has mechanisms for being tuned not only to KDE but also to Gnome and some GTK DE's (the creator of QtCurve implemented most of them in Kvantum without extra dependency). I don't promise anything but it *may* be possible to set the Kvantum theme in the rc files. Actually, it's worth a try -- and thanks for the suggestion -- BUT NO PROMISE ;)

**Comment by varlesh** [comment]
Ok

**Comment by tsujan** [comment]
BTW, it's the fault of systemsettings5 that Kvantum Manager doesn't appear on it. See how gracefully LXQt's Configuration Center includes Kvantum Manager, among other things:

![config-center](https://cloud.githubusercontent.com/assets/981076/22063410/e1804eb4-dd93-11e6-9165-ecc7dc714b1d.png)

**Comment by tsujan** [comment]
I forgot to ask a basic question: Why isn't it possible to set the Kvantum Theme? The same way you change those rc files, you could create `~/.config/Kvantum/kvantum.kvconfig` with just this in it:
````
[General]
theme=YOUR_THEME
````

**Comment by varlesh** [comment]
because kde change settings only **rc**-files on `~/.config`

**Comment by varlesh** [comment]
For example:
[kdeglobals][KDE] - file **kdelobalsrc** section **KDE**
widgetStyle=kvantum - option **widgetStyle**

**Comment by tsujan** [comment]
Oh I'd completely misunderstood your words! You want to control the Kvantum theme from systemsettings5 and *without* Kvantum Manager? Why?! Isn't Kvantum Manager handy to you?

If so, that isn't possible because Kvantum isn't a KDE app. However, I may be able to make systemsettings5 include Kvantum Manager (as Adobe Flash does).

**Comment by varlesh** [comment]
No, i want support for Look an Feel settings only. If change Look and Feel theme - now kvantum theme not changed and used default theme (or selected previously), i need open kvantummanager and change theme it's spoil style for look and feel. On Look and feel now available only select engine, because this contained on rc-files on ~/.config

**Comment by varlesh** [comment]
For Example:
```
[kvantumrc][KDE]
theme=Arc
```
Now kvantumrc not availble on ~/.config and change the not possible on Look and Feel

**Comment by varlesh** [comment]
Look and Feel change options only from **~/.config/*rc** , but kvantum options contained on **~/.config/Kvantum** and now not possible change kvantum theme on Look and Feel, because it's impossible

**Comment by varlesh** [comment]
This settings contained on ~/.config folder only:
```
#file ~/.config/kdeglobals
#section KDE on file ~/.config/kdeglobals
#option widgetStyle on file ~/.config/kdeglobals section KDE
[kdeglobals][KDE]
widgetStyle=kvantum

#and etc...
```

**Comment by tsujan** [comment]
Let me see if I get it correctly this time! You want, for example, a new section in `~/.config/kdeglobals` to set the active Kvantum theme under KDE? For example:
````
[KDE]
...
widgetStyle=kvantum
kvantumTheme=arc
...
````

**Comment by varlesh** [comment]
Yes, if it's possible. Because i'm create pack for KDE customizations and will be good if kvantum theme changed too :)

**Comment by varlesh** [comment]
Maybe not **kdeglobals** - because it's kde file, maybe create your file on ~/.config... i don't know how better

**Comment by tsujan** [comment]
But you say it can be any file under `~/.config`, not necessarily `kdeglobals`. So, what's the difference with `~/.config/Kvantum/kvantum.kvconfig`? I mean, why do you insist that it should be under `~/.config` and not `~/.config/Kvantum`? That's what I don't understand yet.

**Comment by varlesh** [comment]
this not worked for recursive folders on `~/.config` only for files on `~/.config`

**Comment by tsujan** [comment]
Let's forget about Kvantum for a minute! Suppose you have a QtCurve theme instead (I chose QtCurve because it has KDE integration). How do you do it? You share its file with your users and after that, it's up to them to import and choose it in QtCurve or not. Am I right? The same is true for Kvantum. The difference is just that a Kvantum theme is a folder with a config file and an SVG image. It's up to the Kvantum user to import and activate it with Kvantum Manager. Otherwise, Kvantum would be like Breeze or Oxygen: a single theme with just different color schemes.

Frankly, I still don't know what I'm missing here.

**Comment by tsujan** [comment]
I mean that, with Kvantum, no theme is forced on users. Kvantum is all about flexibility, not enforcement.

**Comment by varlesh** [comment]
Yes, but default use default kvantum theme (or previously) and i want if user change Look and Feel > changed kvantum theme, because it's comfortably...
Also you can create Look and Feel settings or others kvThemes - it's very good

**Comment by varlesh** [comment]
QtCurve very old engine and created for KDE3-version... and this not standard for KDE

**Comment by tsujan** [comment]
QtCurve is still being developed under KDE, although not by its author.

Anyway, we've had a long conversation but I still don't get your point. Let's talk by using examples! Suppose (and *only* suppose) that I've added a `kvantumTheme` key to  `kdeglobals`. How do you want to ship your theme? Please give me a real example!

**Comment by varlesh** [comment]
I'm create fully pack for KDE - this contained look and feel settings, plasma theme, kvantum theme, colors, window decorations and etc... This pack installed form github or packge and already have all themes, settings and etc.
When user open systemsetting already available look and feel settings and after apply this look  and feel all changed.
But this not worked for kavntum, changed only `widgetStyle=kvantum`, kavantum theme not changed. User need run kvantummanager and select kvantum theme - it's not comfortable.

**Comment by tsujan** [comment]
How can I download the pack? I need to see what you say.

**Comment by varlesh** [comment]
You can instal my pack from github:
https://github.com/PapirusDevelopmentTeam/arc-kde#install--update
Remove script available too

**Comment by varlesh** [comment]
See, this Look and Feel setting for Breeze Dark:
```
[kdeglobals][KDE]
widgetStyle=Breeze

[kdeglobals][General]
ColorScheme=Breeze Dark

[kdeglobals][Icons]
Theme=breeze-dark

[plasmarc][Theme]
name=breeze-dark

[kcminputrc][Mouse]
cursorTheme=breeze_cursors

[kwinrc][WindowSwitcher]
LayoutName=org.kde.breeze.desktop

[kwinrc][DesktopSwitcher]
LayoutName=org.kde.breeze.desktop
```
This settings used for only 'widgetStyle=Breeze', because Breeze engine not have themes! But kvantum have themes

**Comment by tsujan** [comment]
OK! Let me first see the structure of your pack and I'll come back later! Right now, I'm a little busy.

**Comment by varlesh** [comment]
Please sorry for take your time... it's only enhancement and not critical :)

**Comment by tsujan** [comment]
No problem! I'm back with a simple solution:

You could just add the file `arc-kde-master/Kvantum/kvconfig` to your pack with 2 lines in it:
````
[General]
theme=Arc
````
and then, add a few lines to `install-arc-kde-home.sh` like this:
````
.....
cp --no-preserve=mode,ownership -r "$temp_dir/$gh_repo-master/Kvantum" ~/.config/
if [ -f ~/.config/Kvantum/kvantum.kvconfig ]; then
  mv ~/.config/Kvantum/kvantum.kvconfig ~/.config/Kvantum/kvantum.kvconfig-backup
fi
mv ~/.config/Kvantum/kvconfig ~/.config/Kvantum/kvantum.kvconfig
echo "=> Clearing cache ..."
.....
````

In this way, the current Kvantum setting is backed up too.

If you want, I could paste the whole file here.

**Comment by tsujan** [comment]
BTW, why don't you use SVG Cleaner? It can reduce the sizes of SVG files by 50% and that's good for memory usage. Its setting may seem complicated at first but once you set it up correctly, it'll work fine.

**Comment by tsujan** [comment]
I forgot to say that setting Kvantum theme in Look and Feel isn't possible simply because Kvantum is not (and will not) be a part of KDE. That level of integration means KDE dependency, not just tuning for KDE. As I mentioned earlier, Kvantum will remain dekstop-agnostic, although tuned to some desktops -- like KDE.

**Comment by varlesh** [comment]
thx for simple solution we think abut that :+1: 

> BTW, why don't you use SVG Cleaner? It can reduce the sizes of SVG files by 50% and that's good for memory usage. Its setting may seem complicated at first but once you set it up correctly, it'll work fine.

Thx, i'm forgot doing this

> I forgot to say that setting Kvantum theme in Look and Feel isn't possible simply because Kvantum is not (and will not be) a part of KDE. That level of integration means KDE dependency, not just tuning to KDE. As I mentioned earlier, Kvantum will remain desktop-agnostic, although tuned to some desktops -- like KDE.

It's ok, you developer - you main! :)

**Comment by tsujan** [comment]
Hello, @varlesh!

I added a feature that I'd wanted for a long time, namely, "transient scrollbars". They appear only when needed and disappear when not needed, as in GTK+. It's for Qt5 (Qt4 can't support it).

I think this feature is especially good with your themes. Could you please test it in the latest GitHub version when you have time? It can be enabled in `Kvantum Manager` → `Configure Active Theme` → `Compositing & General Look` → `Transient scrollbars`.

Thanks in advance!
