### ISSUE TITLE
non-root installation with qmake? 

### ISSUE THREAD

**Issue by LightServant** [tsujan/Kvantum#112]
I'm trying to install in a  corporate environment where I dont' have root access and can't do a sudo make install.
How can I provide an alternative installation path for qmake compilation? 

Is see in the top Makefile there is an INSTALL_DIR defined as $(COPY_DIR), but I don't wan to mess around with it.

kind regards,
Markus

**Comment by tsujan** [comment]
Installing a style plugin requiress acces to the Qt plugin directory, which is a root folder (`$$[QT_INSTALL_PLUGINS]/styles` in qmake and `${QT_PLUGINS_DIR}/styles/` in cmake)

You could install Kvantum Manager and kvantumpreview in your home directoy (by using `qmake PREFIX=...`, for example) but they would be useless without Kvantum itself, whose installation needs root access.

**Comment by LightServant** [comment]
That's a bummer! :(
Should be managable over system variables and alternative installation paths, for the engine to look at.

**Comment by tsujan** [comment]
`QT_INSTALL_PLUGINS` is a built-in property of qmake -- it can't be set as an environment variable. Qt recognizes style plugins only when they're put in the subdirectory `style` inside the plugin directory. Kvantum and other style plugins just use that subdirectory during installtion.

I don't know if Qt can be installed under home. If that's possible, it should be a very cumbersome process but in that case, Kvantum should be able to be installed under home too.

**Comment by tsujan** [comment]
Actually, I had the same question before making Kvantum years ago and came to the above-mentioned conclusion.

**Comment by LightServant** [comment]
Thanks, I'll have a look. :)

**Comment by tsujan** [comment]
You're welcome! If you find an info that contradicts what I said above, please tell me! Qt has its surprises ;)
