### ISSUE TITLE
segfault in wayland

### ISSUE THREAD

**Issue by gothmog123** [tsujan/Kvantum#114]
Hi, I'm running gnome wayland and trying run qt apps natively without xwayland and using kvantum. They simply segfault without any message. Any idea what could be wrong? Other qt styles work. Thanks.

**Comment by gothmog123** [comment]
Sorry I just realized this is a duplicate. Please delete. 

By the way I rebuilt kvantum and apps don't segfault but the ui is a bit weird - all the buttons are blinking...

**Comment by tsujan** [comment]
The latest github version supports wayland.

I don't see blinking with Weston. Could you please be more specific?

**Comment by tsujan** [comment]
Qt5 apps should be run in this way under wayland (for now):
````
QT_QPA_PLATFORM=wayland-egl MY_APP
````
Did you use the above command?

**Comment by gothmog123** [comment]
It's like the buttons are being pressed randomly on a toolbar constantly. Strange.

I used QT_QPA_PLATFORM=wayland MY_APP

**Comment by gothmog123** [comment]
I'm using the Arc theme which is not included in kvantum.

**Comment by tsujan** [comment]
I think you should use `wayland-egl`. Please also test with the KvArc theme (included in Kvantum)!

**Comment by gothmog123** [comment]
Seems like it's still the same. Don't worry about it, it's probably just something in my system - an ancient arch installation.

**Comment by tsujan** [comment]
OK. I'll leave this open for a while.

This is KvArc with Weston under KDE (the image is downscaled):

![weston](https://cloud.githubusercontent.com/assets/981076/24504976/848ec322-156d-11e7-9710-a8da664f3be1.png)

**Comment by gothmog123** [comment]
Thanks. I decided to go back to xorg and lxqt with kvantum, so I'm fine now.

**Comment by tsujan** [comment]
You're welcome!

Please report any problem related to Wayland here! Wayland isn't ready for use yet -- at least with Qt -- and lacks some features of x11. Hopefully, such drawbacks will be fixed soon. For now, my only way of testing programs under wayland is using Weston, although sometimes I test  with wayland Plasma too.

**Comment by tsujan** [comment]
I close this for now because I can't see any crash with wayland. Feel free to reopen it if there's any problem!
