### ISSUE TITLE
Apps themeing doesn't work

### ISSUE THREAD

**Issue by kal11** [tsujan/Kvantum#115]
Hello,

I putt some apps to work with different themes, I tried the bin name comma separated executable name and neither of them work..

**Comment by tsujan** [comment]
Which app(s) do you mean, specifically?

**Comment by kal11** [comment]
I have lotus notes installed trying to apply lighter/brighter theme to it from kvantammanager added the exec. Name and the bin name neither of them worked.

**Comment by tsujan** [comment]
I can't find Lotus Notes in AUR (Arch's repository). [Here](https://www.aldeid.com/wiki/IBM-lotus-notes-9.0.1-debian-7.5-64-bit-wheezy) is a Debian page about it, which shows that it isn't a Qt app (because it needs ia32-libs-gtk). Therefore, it isn't styled by Kvantum but by your GTK theme. Am I right?

**Comment by kal11** [comment]
That's is right, I just need to exclude it from my current applied theme :)

**Comment by tsujan** [comment]
If Lotus Notes is a GTK app, it can't be styled by any Qt style engine, so you don't need to do anything in Kvantum. I don't remember if GTK could have app-specific themes but you need to change a GTK setting, not a Qt one.

**Comment by kal11** [comment]
But before installing kvantum+arc-dark theme, lotus notes had different window colors, for example typing/text area background was white, now it's dark gray so I can't see..

**Comment by tsujan** [comment]
Maybe the arc-dark them also has a GTK component, so that when you installed it, you automatically used its GTK theme too. Where can I download it?

**Comment by kal11** [comment]
https://github.com/PapirusDevelopmentTeam/arc-kde

**Comment by tsujan** [comment]
No, it doesn't have a GTK theme. Yhat's your active GTK theme? You could run Firefox, for example, to know that. Tell me if it's dark.

**Comment by kal11** [comment]
Yes firefox is dark also

**Comment by tsujan** [comment]
OK. You have a dark GTK theme, probably for both gtk3 and gtk2. I don't know what it is (GTK arc-dark?) but Lotus Notes should be styled by *that* theme, not by Kvantum. Unfortunately, GTK doesn't have an easy way to give a specific app a different theme. So, if you want Lotus Notes to have a light theme, you should change your GTK theme, which will affect other GTK apps (and Firefox) too.

To be completely sure about that, you could attach a screenshot of Lotus Notes here.

Anyway, this isn't a Kvantum issue, so I close this but feel free to add comments (and that screenshot) if you have any question.

**Comment by tsujan** [comment]
BTW, instead of a screenshot, you could change the Kvantum theme by Kvantum Manager and see if Lotus Notes changes. Tell me the result.

**Comment by kal11** [comment]
![image](https://cloud.githubusercontent.com/assets/11075307/25315937/edb9b4c6-285d-11e7-8f8e-d1ecb6f3110e.png)
![image](https://cloud.githubusercontent.com/assets/11075307/25315941/0dd6e49a-285e-11e7-80f8-7b3aa58d0a9e.png)

**Comment by tsujan** [comment]
No, this isn't a Kvantum theme -- the KDE ArcDark doesn't have a light menubar or toolbar.

BTW, since Lotus Notes is somehow alien to Linux, it may have its own way of theming too.

**Comment by kal11** [comment]
Thank you I solved it, I kept changing GTK theme and relaunching notes it worked, thanks for the tip though

**Comment by tsujan** [comment]
You're welcome.
