### ISSUE TITLE
Kubuntu Installation Error

### ISSUE THREAD

**Issue by dhruvdutt** [tsujan/Kvantum#116]
> **dhruvdutt@dhruvdutt**: /Downloads/Kvantum-master/Kvantum$ ls
Arch   ChangeLog       color    doc      kvantummanager  kvantum.pro  README  themes
build  CMakeLists.txt  COPYING  INSTALL  kvantumpreview  NEWS         style
**dhruvdutt@dhruvdutt**: /Downloads/Kvantum-master/Kvantum$ sudo make install
make: *** No rule to make target 'install'.  Stop.
**dhruvdutt@dhruvdutt**: /Downloads/Kvantum-master/Kvantum$ sudo make
make: *** No targets specified and no makefile found.  Stop.

**Comment by tsujan** [comment]
I'm afraid this isn't the correct way of compilation and installation. Please read the file `INSTALL`! It covers all needed details in a step-by-step way.

**Comment by tsujan** [comment]
BTW, if you use Kubuntu LTS (16.04), you could download a deb package from here: https://github.com/tsujan/Kvantum/releases/tag/V0.10.4
