### ISSUE TITLE
OpenSUSE 42.2 installation error (CMake)

### ISSUE THREAD

**Issue by HeronSilva** [tsujan/Kvantum#119]
Hi there o/

When i try to install Kvantum I get the following error message:

```
CMake Error at style/CMakeLists.txt:2 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
```

I did some research on it, but still couldn't get it to work. Am I doing something wrong?

**Comment by tsujan** [comment]
You don't have some devel packages installed. I'm not familiar with OpenSUSE but you could solve your problem by installing all *Qt5 devel packages*. The file "INSTALL" tells which dev packages are needed under Arch or Debian based systems; perhaps it could help you find the corresponding packages under OpenSUSE.

BTW, a quick Internet search showed me that there are Kvantum rpm packages for OpenSUSE. See here for example: http://software.opensuse.org/package/kvantum

**Comment by HeronSilva** [comment]
Thank you for the quick response!

It worked after installing these packages:
libqt5-qtbase-devel
libqt5-svg
libqt5-qtsvg-devel
libqt5-qtx11extras-devel

I should have tried this before, my bad.

Thank you!

**Comment by tsujan** [comment]
Thanks for telling me about those packages! I'll add the OpenSUSE dependencies to "INSTALL".
