### ISSUE TITLE
Configuration doesn't stick in KDE

### ISSUE THREAD

**Issue by Vavency** [tsujan/Kvantum#121]
![screenshot_20170530_134533](https://cloud.githubusercontent.com/assets/14310648/26580574/5f5a2e94-4541-11e7-91b1-2debf7df7744.png)
> Top right: Oddly working theme. Top left and bottom right: Running applications before applying the theme. Bottom left: Started application after applying the theme.

Yay! More bugs with your favourite desktop environment. 

I have no idea why.

Distro: `Fedora 25 x64 KDE spin`
Plasma Version: `5.9.2`
KDE Framework: `5.34.0`
Qt Version: `5.7.1`
Kernel Version: `4.10.17.200.fc25.x86_64`

ldd outputs:

> ldd libkvantum.so 
        linux-vdso.so.1 (0x00007ffe581fd000)
        libQt5Svg.so.5 => /lib64/libQt5Svg.so.5 (0x00007f363fae3000)
        libQt5X11Extras.so.5 => /lib64/libQt5X11Extras.so.5 (0x00007f363fadb000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f363f79b000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f363f583000)
        libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f363ef1b000)
        libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f363ea73000)
        libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f363e5e3000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f363e25b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f363df4b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f363dd33000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f363d96b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f363d74b000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f363d533000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f363d2a3000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f363d07b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f363ce73000)
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f363cc0b000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f363c9d3000)
        libicui18n.so.57 => /lib64/libicui18n.so.57 (0x00007f363c55b000)
        libicuuc.so.57 => /lib64/libicuuc.so.57 (0x00007f363c1ab000)
        libicudata.so.57 => /lib64/libicudata.so.57 (0x00007f363a72b000)
        libpcre16.so.0 => /lib64/libpcre16.so.0 (0x00007f363a4bb000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f363a2b3000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f3639f9b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3639d93000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f3639d03000)
        /lib64/ld-linux-x86-64.so.2 (0x000055e475c6e000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f3639acb000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f3639813000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f363960b000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f363935b000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f363912b000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f3638eb3000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f3638c93000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3638a6b000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f3638863000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f363863b000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f3638423000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f363813b000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f3637f23000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3637d13000)

> ldd kvantumpreview
        linux-vdso.so.1 (0x00007fff0f1f5000)                                                                                                                                    
        libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f76939cb000)                                                                                                    
        libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f7693523000)                                                                                                            
        libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f7693093000)                                                                                                          
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7692d0b000)                                                                                                            
        libm.so.6 => /lib64/libm.so.6 (0x00007f76929fb000)                                                                                                                      
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f76927e3000)                                                                                                              
        libc.so.6 => /lib64/libc.so.6 (0x00007f769241b000)                                                                                                                      
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f76921fb000)                                                                                                          
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f7691f6b000)                                                                                                                    
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f7691d03000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f7691aeb000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f76918b3000)
        libicui18n.so.57 => /lib64/libicui18n.so.57 (0x00007f769143b000)
        libicuuc.so.57 => /lib64/libicuuc.so.57 (0x00007f769108b000)
        libicudata.so.57 => /lib64/libicudata.so.57 (0x00007f768f60b000)
        libpcre16.so.0 => /lib64/libpcre16.so.0 (0x00007f768f39b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f768f193000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f768ef8b000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f768ec73000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f768ea6b000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f768e9db000)
        /lib64/ld-linux-x86-64.so.2 (0x000055612c7a9000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f768e7a3000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f768e463000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f768e24b000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f768df93000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f768dce3000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f768dab3000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f768d83b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f768d61b000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f768d3f3000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f768d1eb000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f768cfc3000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f768cdab000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f768cac3000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f768c8ab000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f768c683000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f768c473000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f768c26b000)

> ldd kvantummanager
        linux-vdso.so.1 (0x00007ffe985f5000)
        libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007fdda490b000)
        libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007fdda4463000)
        libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007fdda3fd3000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fdda3c4b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdda393b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdda3723000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdda335b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdda313b000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007fdda2eab000)
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007fdda2c43000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fdda2a2b000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fdda27f3000)
        libicui18n.so.57 => /lib64/libicui18n.so.57 (0x00007fdda237b000)
        libicuuc.so.57 => /lib64/libicuuc.so.57 (0x00007fdda1fcb000)
        libicudata.so.57 => /lib64/libicudata.so.57 (0x00007fdda054b000)
        libpcre16.so.0 => /lib64/libpcre16.so.0 (0x00007fdda02db000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdda00d3000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007fdd9fecb000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fdd9fbb3000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fdd9f9ab000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007fdd9f91b000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558069693000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007fdd9f6e3000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007fdd9f3a3000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007fdd9f18b000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007fdd9eed3000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fdd9ec23000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fdd9e9f3000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fdd9e77b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fdd9e55b000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fdd9e333000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007fdd9e12b000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fdd9df03000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007fdd9dceb000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007fdd9da03000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007fdd9d7eb000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fdd9d5c3000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fdd9d3b3000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007fdd9d1ab000)

**Comment by tsujan** [comment]
> More bugs with your favourite desktop environment.

My favorite DEs are LXQt and Enlightenment but I like KDE too ;)

I've never seen such a scene under KDE! Why is the top left window translucent? I guess you'd used a translucent style/effect before applying Kvantum and that style hasn't done its job on quitting (hasn't removed translucency) or, if it's about an effect, it's interfering with Kvantum. Please change the style to Breeze, remove any translucency effect, and then change the style to Kvantum! Please also tell me from where that translucency comes.

**Comment by tsujan** [comment]
For the sake of certainty, I logged into Plasma 5.9.5 (Manjaro). This is the default Kvantum theme:

![kvantum](https://cloud.githubusercontent.com/assets/981076/26584221/53cfc374-455d-11e7-8de6-4b11c71d4112.jpg)

Please also note that Kvantum comes with many extra themes, some of which support translucency, blurring and more.

**Comment by Vavency** [comment]
![screenshot_20170530](https://cloud.githubusercontent.com/assets/14310648/26584763/a73c3796-4552-11e7-9890-cbf685b6d72f.png)

No worries. Same story, default Kvantum theme.

**Comment by tsujan** [comment]
This screenshot is different from the first one -- something has changed. Now, System Settings and Kvantum Manager are OK (apart from the edited image) but Dolphin still has translucency and the desktop settings dialog is "impossible" (some of its buttons aren't drawn by Kvantum).

Apparently, your KDE installation doesn't let the previously applied style go away completely. I'm curious to know why that happens. What's different about your system?

> I used home brewed transparent theme in the first screen cap.

With which style engine? If you edited the default Kvantum theme to make it translucent, the translucent background element may be missing or it may have an incorrect name (ID) in your SVG file. (For a translucent version of the default Kvantum theme, you could use KvantumAlt and enable its translucency with Kvantum Manager.)

**Comment by Vavency** [comment]
Kvantum, modified KvRoughGlass. Need those files?

Looks like Plasma bug more than Kvantums fault.

**Comment by tsujan** [comment]
> Kvantum, modified KvRoughGlass. Need those files?

I thought all screenshots had been taken with the default Kvantum theme. If not, yes, please give me a link to your Kvantum theme!

> Looks like Plasma bug more than Kvantums fault.

I had Plasma 5.9.2 months ago but it didn't have such a problem. My Plasma version is  5.9.5 now.

**Comment by Vavency** [comment]
![screenshot_20170530_180726](https://cloud.githubusercontent.com/assets/14310648/26590734/0fad1f5a-4564-11e7-83b9-f1d6849e38a1.png)
Clearly something is wrong. Look at the search bar. (Using KvDefault)

[KvRoughGlass_new.zip](https://github.com/tsujan/Kvantum/files/1038704/KvRoughGlass_new.zip)

First screen cap was taken using this theme, the latter captured using default by your request. 

I had to compile from source since there's no RHEL packages and the likelihood that being the cause is slim. 

Do you know which directories/files Qt/Plasma use to store theme information? I might have borked up some file permissions while migrating from openSUSE.

**Comment by tsujan** [comment]
Although your theme is too translucent (I think that's intentional), it's OK here:

![your_theme](https://cloud.githubusercontent.com/assets/981076/26591967/8cc61ed2-4574-11e7-8ce4-c9412a08c508.png)

Those black backgrounds in your screenshot are the window color without translucency (#0000005a). So, for whatever reason, the KDE version you have doesn't support something like "#0000005a", while mine does. Try to use only 6-digit colors under `GeneralColors` and create translucency only through translucent elements in your SVG file instead!

> Do you know which directories/files Qt/Plasma use to store theme information?

Plasma doesn't have anything to do with the widget style; it only stores the Plasma theme.

**Comment by tsujan** [comment]
> I might have borked up some file permissions while migrating from openSUSE.

KDE has a lot of config files with various names in `~/.config` and also in `~/.local/share`. Yes, if the permissions are wrong, weird things will happen but let's suppose that isn't the case for now.

**Comment by Vavency** [comment]
I tried both methods, didn't work except for occasional dialogue box and desktop settings. Any idea what else could be interfering? 

So far suspects are Plasma and Qt or even worse SeLinux somehow blocking it.

**Comment by tsujan** [comment]
> I tried both methods, didn't work except for occasional dialogue box and desktop settings.

I assure you that Kvantum can't cause this. Some widgets are based on QML, in which case they may not support translucency and may have a black bg (because of "#0000005a"). However, Dolphin should be translucent, as in my last screenshot.

> Any idea what else could be interfering?

Because of those black backgrounds, it can be a compositing issue but I can't be sure.

Does any translucent theme that comes with Kvantum shows a similar symptom? Try KvCurves3d and enable its translucency in Kvantum Manager → Configure Active Theme → Compositing & General Look → Translucent windows (and, perhaps, Blurring for translucent windows).

> So far suspects are Plasma and Qt or even worse SeLinux somehow blocking it.

Qt 5.7.1 is OK (5.8.X, which I have, is buggy). I've had the same Plasma version. I don't know about SeLinux or how it could block compositing.

**Comment by tsujan** [comment]
Oh, can it be the case that you have no compositing? Is compositor enabled in System Settings → Display and Monitor → Compositor?

**Comment by Vavency** [comment]
![screenshot_20170530_205426](https://cloud.githubusercontent.com/assets/14310648/26597356/64df7822-457a-11e7-8e02-b750c29c5058.png)
I got it working in a clean home folder.

**Comment by tsujan** [comment]
I wonder why your windows don't have shadow. Is compositing enabled?

**Comment by Vavency** [comment]
Compositor is enabled by default in KDE.
