### ISSUE TITLE
Dark font color on dark background in Gwenview

### ISSUE THREAD

**Issue by Tichy** [tsujan/Kvantum#122]
This problem is shown only in the path bar. See screenshot.

![shot-2017-06-01_17-34-28](https://cloud.githubusercontent.com/assets/2348771/26687755/d72f9c6e-46f0-11e7-8ec7-b19647a5be51.png)

**Comment by tsujan** [comment]
You haven't applied the color scheme (Kvantum, in this case); have you? Applying the color scheme is recommended on the second page of `Kvantum Manager`.

![gwenview](https://cloud.githubusercontent.com/assets/981076/26688208/4afad5da-4707-11e7-8364-5c32b5f624f2.png)

Some KDE apps rely on the color scheme for some of their elements; Qt apps don't.

**Comment by tsujan** [comment]
Also apply the corresponding color scheme when you change the theme with `Kvantum Manager`.

**Comment by Tichy** [comment]
That's my fault. To be fair, I'm not using a full KDE environment, but only some applications with Enlighentment as WM, so I don't know how to change the color scheme... 😞

**Comment by tsujan** [comment]
> That's my fault.

It's not your fault but KDE's inconsistent behavior.

> I don't know how to change the color scheme...

If you use KDE apps, you should install `systemsettings` (V5.x.x) -- it may have a different name in your distro -- otherwise you couldn't change some settings.

**Comment by Tichy** [comment]
Is systemsettings even in Arch, but it doesn't show the appearance settings. I guess I have to install something more.
Anyway. No problem. I'm off topic here, so I'll try to find a solution by myself. :)

**Comment by tsujan** [comment]
I was working under LXQt when I saw your first comment but now, I'm in Enlightenment, using Qt apps. `systemsettings` (from AUR) works fine under both DEs -- Gwenview sees the color scheme. However, I have a relatively complete installation of KDE (which I use only rarely). So, you might be right about needing something more: breeze, oxygen,...?

**Comment by Tichy** [comment]
I found it. I had to install plasma-desktop with all his dependencies. Now I managed to install the color scheme and gwenview looks fine. :)
