### ISSUE TITLE
Big icons in tooltips [KDevelop5] 

### ISSUE THREAD

**Issue by audoban** [tsujan/Kvantum#123]
![spectacle ns7054](https://user-images.githubusercontent.com/7884292/26998629-090653f2-4d4c-11e7-95af-7a8ec8afa0d1.png)

This defect can be reproduced with KvAr Dark, Kv Arc, Arc, Arc Dark theme, but probably this happens with any theme.

My version of kvantum is `v0.10.4`

**Comment by tsujan** [comment]
Those tooltips are not drawn by Kvantum but by Kdevelop itself. In the following screenshot, I've intentionally made a "warning tooltip" in Kdevelop and the icon is OK:

![kdevelop](https://user-images.githubusercontent.com/981076/27002205-a0324cd2-4df0-11e7-92a9-8f11619e0f51.png)

It makes no difference which Kvantum theme is activated; icons are always fine. The Kdevekop version is 5.1.1 here. If you have the same version, the problem might still be in how Kdevelop uses your icon theme.

Are those big icons also shown when you switch the theme to Breeze?

**Comment by tsujan** [comment]
Yet another screenshot, whose tooltip is more similar to the tooltip of your screenshot:

![kdevelop1](https://user-images.githubusercontent.com/981076/27002240-e4c28a0a-4df1-11e7-9903-266d59c793ba.png)

**Comment by audoban** [comment]
Hello @tsujan, Thank you so much for your theme engine I really like it.

> hose tooltips are not drawn by Kvantum but by Kdevelop itself. In the following screenshot, I've intentionally made a "warning tooltip" in Kdevelop and the icon is OK:

> Are those big icons also shown when you switch to Breeze?

Yes, you have reason. However the icon theme has not relation, KDevelop take the icon size from the configuration of size for the Panel. On the last screenshot the size had been set to 256px.

32px for the Panel
![spectacle kn2304](https://user-images.githubusercontent.com/7884292/27002605-918dd452-4dab-11e7-8b9c-c8cd6d9926e1.png)

KvArc , Papirus icon theme and Panel icon size set to 32
![spectacle lh2304](https://user-images.githubusercontent.com/7884292/27002566-ce462df0-4daa-11e7-8c2b-679a28a89720.png)

However hasn't sense that Kdevelop take the size of icon with respect to Panel, I will report this to the KDevelop team. Anyway, thank you very much 👍.

**Comment by tsujan** [comment]
Glad to know that your problem is solved!

Yes, I knew that the problem wasn't in the icon theme but in *how Kdevelop used it*.

I agree that Kdevelop shouldn't use the panel icon size in those tooltips.
