### ISSUE TITLE
Konsole not use transparent menubar

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#125]
Konsole menubar use ID: `window-normal`, but without transparent. It's possible fixed?
![image](https://user-images.githubusercontent.com/8083855/27180154-78d64d58-51c1-11e7-8cce-0eae6cd0fb09.png)
kde neon 20170608
konsole 17.04.2
kvantum 0.10.4
plasma 5.10.1
KDE Frameworks 5.34
Qt 5.7.1
https://github.com/PapirusDevelopmentTeam/arc-kde/issues/36

**Comment by tsujan** [comment]
This is not  a bug.

Kvantum can make a window translucent only if it isn't already so. Konsole and QTerminal have hard-coded translucency, so, Kvantum doesn't touch their windows. In other words, the translucency of such apps isn't Kvantum's responsibility.

Another example is LXQt panel, whose possible translucency can be caused only by its stylesheet and if that stylesheet doesn't have transparency, Kvantum can't make the panel translucent.

**Comment by tsujan** [comment]
BTW, is there a special reason that you don't activate transient scrollbars in your Kvantum themes?

**Comment by varlesh** [comment]
Thx for support.
> BTW, is there a special reason that you don't activate transient scrollbars in your Kvantum themes?

GTK 2-apps not used this style scrollbars, but i like single style for all apps

**Comment by varlesh** [comment]
and user can enable transient scrollbars on kvantummanager config, if needed

**Comment by tsujan** [comment]
> GTK 2-apps not used this style scrollbars, but i like single style for all apps

Recently I've seen that gtk3 does't use "overlay" scrollbars either but I like them ;)

> and user can enable transient scrollbars on kvantummanager config, if needed

Yes :)

In some recent commits, I added the ability to set some variables in terms of font height (see the file "Theme-Config"). I started to use it with some gtk-like Kvantum themes and thought you might also want to try it with your themes.

**Comment by varlesh** [comment]
Ok, thx for info :) Kvantum need develop as part KDE software and used by default!
