### ISSUE TITLE
text.press.color option not worked for MenuBarItem

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#126]
On My theme Arc for focus and pressed used different colors:
```
[MenuBarItem]
inherits=PanelButtonCommand
interior.element=menuitem
frame=false
text.margin.top=3
text.margin.bottom=3
text.margin.left=5
text.margin.right=5
text.press.color=#ffffff
text.focus.color=#5c616c
```
**text.press.color** option not worked for **MenuBarItem**. See (**File**) on config #ffffff but apply #5c616c (it's focus color)
![image](https://user-images.githubusercontent.com/8083855/27182801-06a51308-51cc-11e7-80dc-70e4e47a66ec.png)

**Comment by tsujan** [comment]
Not all widgets have all states. Since the pressed state didn't have much sense for menubar items, I removed it for text. However, for me to see if there's any bg/fg inconsistency, could you please give me a download link for the theme in the screenshot?

**Comment by tsujan** [comment]
I mean  the whole theme: kvconfig + SVG file.

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/Kvantum/Arc
or scripts install/remove:
https://github.com/PapirusDevelopmentTeam/arc-kde#arc-kde-installer

**Comment by tsujan** [comment]
When the cursor is on a menubar-item or menu-item, Qt sees it as "pressed", while when the item is clicked, Qt sees it as "toggled". I'm sure you know this because of the SVG elements you've used.

However, since the starting days of Kvantum, I chose the focus text color for both pressed and toggled states. I admit that was a mistake. Now, I should see if that mistake could be corrected in a backward compatible way. I'll let you know as soon as I reach a conclusion.

Thanks for this report!

**Comment by tsujan** [comment]
Sorry, I corrected a typo in the above explanation about "toggled" and "pressed".

**Comment by tsujan** [comment]
OK, I found a solution and made a commit. Luckily, you don't need to change anything in your theme -- just install the latest git Kvantum:

![arc](https://user-images.githubusercontent.com/981076/27192554-15938986-5211-11e7-9eb2-cb38e2546ddd.png)

This is the simple rule:

If under MenuBarItem and/or MenuItem, `text.toggle.color` or `text.press.color` exists, it'll be used for toggle (hover) or pressed (clicked) state, but if one of them is missing, `text.focus.color` will be used instead.

The real reason for all this is that, actually, there's no focus state for menu and menubar items but calling them focused sounds natural when the cursor is on them. So, in all my themes (including KvArc), I've used the same SVG element for both toggled and pressed states of menu(bar) items.

`text.focus.color` is kept as fallback and also for backward compatibility. I'll add the required info to the documentation.

Please close this issue if everything is all right!

**Comment by varlesh** [comment]
big thx, i'm try this later 👍

**Comment by varlesh** [comment]
@tsujan All fine:
![image](https://user-images.githubusercontent.com/8083855/27198624-804c47ae-5202-11e7-886f-25485e84db06.png)

**Comment by tsujan** [comment]
Thanks for testing!
