### ISSUE TITLE
Just thought I let you know that I managed to mess around with the deb builds

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/Kvantum#138]
So that the build procedure automatically builds qt4-only binaries if Qt5 is less than 5.4, but the qt4 and qt5 plugins plus qt5 binaries if qt5>=5.4.  It depends on lsb-release detecting the distro name, and then a list of the distros with a new enough qt5 in the rules file...plus some logic with the build-depends in the control file. At least for me, this means I can just upload one set of sources to the OBS for all distros. The rules file has some clunky workarounds, but it's the debhelper plus overrides style that Debian policy prefers nowadays...

https://build.opensuse.org/package/show/home:stevenpusser:kvantum/kde-style-kvantum

Sources:  http://download.opensuse.org/repositories/home:/stevenpusser:/kvantum/Debian_9.0/

**Comment by tsujan** [comment]
Thank you very much for telling me about that! I have to find a way to inform Debian users -- maybe in release comments or in a separate file added to the source.
