### ISSUE TITLE
need help with this translation string

### ISSUE THREAD

**Issue by omni6** [tsujan/Kvantum#141]
hey,

really odd thing, look here: 
![screenshot_20170729_222958](https://user-images.githubusercontent.com/24492439/28748054-c558eb40-74ad-11e7-99a3-986cfa3d7b4e.png)

the string in linguist is `W<br>W<br>W`

![screenshot_20170729_223112](https://user-images.githubusercontent.com/24492439/28748055-ca395e92-74ad-11e7-9030-88684734213a.png)

i need to know how to get the variable for the config file...

**Comment by tsujan** [comment]
> the string in linguist is W<br>W<br>W

Please leave it untranslated! It was used only to set a preliminary size for the widget and I should make it untranslatable later.

> i need to know how to get the variable for the config file...

There's no need to that. The path, in the second screenshot, is set by the app.

If you encounter any other problem, you could also consult the Esperanto translation (kvantummanager_eo.ts) and, of course, you could ask me any question here.

**Comment by omni6** [comment]
ok, thx
