### ISSUE TITLE
Leaves dark colors after Kvantum is unselected

### ISSUE THREAD

**Issue by yurivict** [tsujan/Kvantum#143]
When I select and then unselect Kvantum, other styles are displayed with dark colors left over from Kvantum.

version 0.10.4 from the FreeBSD port, qt-5.7.1

**Comment by tsujan** [comment]
Do you change the color scheme after deselecting Kvantum? A screenshot with explanation?

**Comment by yurivict** [comment]
Here is the screen video demoing the problem in Qt5 application:

![ui-style-kvantum](https://user-images.githubusercontent.com/271906/28858300-8fe860ea-7704-11e7-8923-29ad424aa9c3.gif)

**Comment by tsujan** [comment]
OK. This isn't a bug or problem in Kvantum. Any app that changes the style should also update all widgets. The app in the video doesn't do so. For example, I can't see such a problem in Qt Designer.

The reason why that happens only with Kvantum is that Kvantum has its own palettes and doesn't use any external color scheme (although color schemes are needed under KDE). Since the app in the video doesn't update widgets correctly, the palette colors are shown with the next style.

**Comment by tsujan** [comment]
Since you didn't tell which desktop environment you have or what that app is, I should be little telepathic to provide you with more information because there are also 2 other possibilities, none of which is related to Kvantum:

(1) Your DE may not have a color scheme of its own;
(2) That style changing app may not provide any color palette.

**Comment by yurivict** [comment]
My desktop environment is xfce4. The app is closed source. But it does this on this combobox change:
```
((QApplication*)QApplication::instance())->setStyle(style);
```

What is missing in the combobox callback?

> Any app that changes the style should also update all widgets. The app in the video doesn't do so.

All widgets are updated when other styles are switched. The whole app window changes style.

(http://doc.qt.io/qt-5/qapplication.html#setStyle-1)

**Comment by tsujan** [comment]
> All widgets are updated when other styles are switched.

Other styles use the default palette while Kvantum has its own.

> The app is closed source. But it does this on this combobox change:

> ((QApplication*)QApplication::instance())->setStyle(style);

I can't say anything certain when I don't have the source but `QApplication::setStyle` is not enough for updating all widgets. This may be needed:
```cpp
Q_FOREACH(QWidget *widget, QApplication::allWidgets())
{
    QEvent event (QEvent::ThemeChange);
    QApplication::sendEvent (widget, &event);
}
```
And even with that, if a style has no color palette of its own (unlike Kvantum), the same thing might happen again. Kvantum doesn't let its colors be set by an outside sourse; other styles may do.

Maybe a look at Qt designer's source could be of help but it's a lot of code.

**Comment by tsujan** [comment]
In short, I'm sure this is about the lack of own color palettes in the case of all styles except for Kvantum.

BTW, as far as I know, xfce4 can't set a color palette for Qt apps. The only DE's that can do that are KDE and LXQt.

**Comment by yurivict** [comment]
This:

> Q_FOREACH(QWidget *widget, QApplication::allWidgets())
> {
>     QEvent event (QEvent::ThemeChange);
>     QApplication::sendEvent (widget, &event);
> }

doesn't help.

I tried to add this:
```
  if (style != "kvantum") {
    qApp->setPalette(this->style()->standardPalette());
    qApp->setStyleSheet("");
  }
```

This somewhat improved the situation. Some colors come back after switching back from kvantum. Switching many times between other styles brought all colors back.

The problem is that Qt defines the interface for styles, with ```setStyle()``` function, but Kvantum de-facto breaks this system. This might be a bug in Qt itself as well.

IMO, you need to publish a solution to this. Otherwise, how can people use kvantum in apps allowing multiple styles?

**Comment by tsujan** [comment]
> The problem is that Qt defines the interface for styles, with setStyle() function, but Kvantum de-facto breaks this system. This might be a bug in Qt itself as well.

This isn't a bug in Qt or Kvantum. As mentioned above, Kvantum is the only Qt style engine (as far as I know) that defines it own color palette. I had a hard time to make it in such a way that it won't be influenced by other palettes. Actually, I'm a little happy that it might influence other styles in the way you described ;)

The "problem" is the DE. No one expects a Qt color management from a non-Qt environment like xfce4. The same thing will happen under all non-Qt DE's. Only KDE and LXQt support that.

**Comment by yurivict** [comment]
I just ran it from kde - the problem is still there.
kde-4.14.3

**Comment by tsujan** [comment]
kde-4.14.3 doesn't support Qt5.

**Comment by tsujan** [comment]
Now that you work with Qt4, take a look at `qtconfig-qt4`! Apparently, the same thing happens with it but it has color buttons that show how palettes are defined. Change the colors and another palette will be created.

**Comment by tsujan** [comment]
Moreover, when I change the style from Kvantum to another one under KDE (the latest version) and LXQt (latest), no color is transferred to the new style. That's because these DE's has their own Qt plugins, which they use in their style-changing apps, which change the style *in all apps*.
