### ISSUE TITLE
Dotted frames in Kvantum

### ISSUE THREAD

**Issue by Void97** [tsujan/Kvantum#145]
Hi, I recently installed the latest Kvantum build and I noticed that there's a dotted frame around selected items with both defaut theme and third-party themes (like Arc-transparent), as you can see in the screenshots:
![screenshot_20170806_213643](https://user-images.githubusercontent.com/15859553/29006439-32a42a32-7af0-11e7-90b6-566d03d300c4.png)
![screenshot_20170806_213916](https://user-images.githubusercontent.com/15859553/29006453-6a264c2e-7af0-11e7-8f65-9b3df046f90a.png)

**Comment by tsujan** [comment]
That's "focus rectangle". A few months ago, I realized the practical importance of focus rectangles and added them to all extra themes as well as the default theme. IMO, a style without focus rectangle is incomplete.

**Comment by tsujan** [comment]
BTW, like any other element, focus rectangle can be removed from any theme by adding:
````
[Focus]
frame=false
````

**Comment by Void97** [comment]
Ok, I didn't realize it was your design intent. Thank you for your explanation

**Comment by tsujan** [comment]
You're welcome!

I forgot to add the the focus rectangle isn't necessarily dotted; for example, it isn't  dotted for KvAmbiance (although it is for KvAmbience). Everything is determined by the SVG image and also by the Focus section of the theme in question.

**Comment by Void97** [comment]
Thanks again for the clear explanation!
