### ISSUE TITLE
Is dolphin supposed to work with a transparent theme outside KDE5?

### ISSUE THREAD

**Issue by rbn42** [tsujan/Kvantum#148]
Hi, 
Is dolphin supposed to work with a transparent theme outside KDE5? Its background is not transparent on compiz0.8. But I tried [some dirty hack on  kvantum-qt5 0.10.4-1](https://github.com/tsujan/Kvantum/files/1236780/diff.txt) to make it work. 

Screenshots for pcman-qt, kate and dolphin
Before 
![before](https://user-images.githubusercontent.com/8784753/29491515-26bf905e-85b2-11e7-9e25-80f7313b2846.png)
After
![after](https://user-images.githubusercontent.com/8784753/29491514-26be7912-85b2-11e7-9542-7362e81a6fab.png)

**Comment by tsujan** [comment]
Kvantum's translucency doesn't depend on any DE; it just needs a compositor. So, yes, Dolphin can be translucent anywhere -- even under Enlightenment. No patch is needed for that.

This is Dolphin with Compiz under LXQt, styled by Kvantum:

![dolphin](https://user-images.githubusercontent.com/981076/29491655-6e3485fc-8576-11e7-8692-3e4336d171eb.png)

**Comment by rbn42** [comment]
Hi tsyjan,
Thank you for your quick reply. I am sorry, but dolphin+kvantum just dont work for my DE (compiz0.8 on updated ArchLinux), both pcman+kvantum and dolphin+qtcurve works.
I am not very familiar with this, but IMO, Qt::WA_TranslucentBackground is not correctly set for the main window widget of dolphin and kate for any reason I can't imagine.

**Comment by tsujan** [comment]
> compiz0.8 on updated ArchLinux

I use Compiz 0.8 (reloaded) too ;)

For Dolphin's view to be translucent, these conditions should be satisfied:
(1) A Compositor (which you have);
(2) A translucent window bg in the theme;
(3) Translucency should be enabled under Kvantum Manager → Compositing & General Look; and
(4) "Transparent Dolphin view" should be enabled under Kvantum Manager → Hacks.

Now, if you're sure that all the above conditions are fulfilled in your case, the only remaining possibility is that something may have changed in Dolphin -- which is very unlikely. Here, its version is 17.04.3-1. What is its version for you?

**Comment by rbn42** [comment]
Yes, I think I have all these conditions above satisfied, otherwise, pcman-qt can't be translucent too.
Actually, while I am talking about dolphin, all programs from KDE5, like dolphin and kate, are not translucent. And my dolphin version is 17.04.3.

I am glad you are on compiz 0.8 too, so I am more confident now to try aggressively. It is **qt5ct**! I was using qt5ct to switch between breeze, kvantum and qtcurve. 
Setting QT_STYLE_OVERRIDE=kantum directly solved this issue.

**Comment by tsujan** [comment]
>  I was using qt5ct to switch between breeze, kvantum and qtcurve.

Interesting! I have no clue how `qt5ct` could interfere with Kvantum translucency for KDE apps but I'm sure that the problem should be in `qt5ct` because Kvantum treats all DE's equally.

Under any DE, you could install `lxqt-qtplugin` and set the environment variable `QT_QPA_PLATFORMTHEME` to `lxqt`; then you could control the style by using `lxqt-config`.

> I am glad you are on compiz 0.8

Compiz 0.8 has a very high quality. I hope there will be good programs like it for wayland too but until wayland gets stable, I prefer Compiz to all other x11 compositors.

**Comment by ShayBox** [comment]
If you set `QT_STYLE_OVERRIDE` at all qt5ct wont apply its settings like double click, but without it set kvantum wont enable transparency on dolphin.

**Comment by tsujan** [comment]
qt5ct issues should be reported to its developer(s).

For any Qt widget style to work properly, there should be something called "Qt platform integration". Whether a DE has a decent Qt platform integration or not is outside my control. KDE and LXQt do.

**Comment by ShayBox** [comment]
Update if anyone was following this issue, perhaps if you know how to fix the issue internally here's your chance: https://sourceforge.net/p/qt5ct/tickets/65/

**Comment by tsujan** [comment]
Although this thread is old, since I mentioned Wayland in one place, I'd like to add that KWin's Wayland support has improved a lot since 2017. A nice and light blur effect, desktop cube, kwin scripts,... are supported under Wayland now. However, X11 is still the winner.
