### ISSUE TITLE
Overlay scrollbar contrast

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#149]
A while back I noted that the KvArc scrollbars blended in with the view selection highlight (blue on blue) - so that if multiple items were selected, you could not see the scrollbar. You fixed this for KvArc, but it also affects some others:

- KvAmbiance
- KvAmbience
- KvCurves3d (Only slightly)
- KvGnome
- KvGnomeAlt
- KvGnomeDark
- KvGnomish
- KvSimplicity (Only slightly)

With KvAmbiance being (to my eyes at least) the worst affected.

**Comment by tsujan** [comment]
Thanks for the list! I'll set `transient_groove` to `true` for them and will add `transient_groove` to Kvantum Manager as an option.

BTW, today, I added a new theme (alongside many little fixes) which you might find interesting because it's simpler than KvArc. Its name is KvAdapta and matches the GTK theme Adapata (but isn't its clone).

**Comment by CDrummond** [comment]
Yeah, I noticed that - which prompted me to upgrade, and check the styles out. I used to use the 'Pop' Gtk theme for a while (its based upon Adapta, but with brown colours).

As to KvAdapta, not 100% about the toolbar text colours - in Cantata at least, the toolbar text seems a little dark. But, that's just my opinion (and you know what they say about those :-) )

**Comment by tsujan** [comment]
Yes, the "light" text is a bit dark in Adapta. I didn't want to clone it but tried to use the same text colors:

![test_color](https://user-images.githubusercontent.com/981076/29664961-2523009a-88e7-11e7-9fa4-4f2483c31358.png)

I just forgot to do the same thing for menu-bar ;)

Might make a "KvAdapataAlt" with lighter text and some changes.

**Comment by tsujan** [comment]
Also made the transient groove appear only when needed because it was ugly without item-views.
