### ISSUE TITLE
Clementine and Konsole menubar text

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#157]
@tsujan Hi! Please help, i don't know why clementine and konsole use another color text for menu:
![image](https://user-images.githubusercontent.com/8083855/30237287-e12f3d76-953f-11e7-9b16-6e69eb0051ca.png)

**Comment by varlesh** [comment]
ouh, i found `window.text.color`... But it's strange. This not broken compability with Darker themes?

**Comment by varlesh** [comment]
Yes.. see kvantum window text:
![image](https://user-images.githubusercontent.com/8083855/30237327-c070eac0-9540-11e7-9e1d-a486cbb14dd8.png)
It's possible fix?

**Comment by varlesh** [comment]
i fix this... sorry

**Comment by varlesh** [comment]
@tsujan OMG i'm tortured with Darker theme ))
How you fix widget class for SMPlayer main panel on KvAdapta?

**Comment by varlesh** [comment]
Used toolbar color on SMPlayer panel. Why?
![image](https://user-images.githubusercontent.com/8083855/30238038-f607368a-954f-11e7-8abf-e00b09709f09.png)

**Comment by tsujan** [comment]
@varlesh I wasn't near my computer.

I don't get it; what's the problem? Could you please be more specific? Kvantum includes several dark themes and also dark-and-light themes; there's no readability problem in any of them.

**Comment by tsujan** [comment]
If you want me to help in fixing problems of a specific theme, please give me a link for downloading it.

**Comment by tsujan** [comment]
> Used toolbar color on SMPlayer panel. Why?

SMPlayer bottom panel is a toolbar. You could play with the key `single_top_toolbar`. If it's set to `true`, only the top toolbar is drawn as a toolbar.

**Comment by varlesh** [comment]
@tsujan Thx i'm already fix that ))

> If you want me to help in fixing problems of a specific theme, please give me a link for downloading it.

later, when complete yet... i'm now add arrow indicators, very more arrows )

@tsujan Why you don't use original colors for text on window KvAdapta?
See left sidebar on Nautilus used lighter colors:
![image](https://user-images.githubusercontent.com/8083855/30238589-c1497e2a-955a-11e7-8e2b-9b0f527e5911.png)

**Comment by tsujan** [comment]
>  i'm now add arrow indicators, very more arrows

Yes, light-and-dark themes may need several arrows, especially "flat-" ones. You could use the normal state and SVG cloning as far as possible. There are several examples among Kvantum extra themes.

>  Why you don't use original colors for text on window KvAdapta? See left sidebar icons (text) on Nautilus used lighter colors:

I used `gtk3-widget-factory` as the base. Nautilus or other apps may be customized by GTK themes. `gtk3-widget-factory` is always the standard.

**Comment by tsujan** [comment]
BTW, In light-and-dark themes, the toolbar and menubar normal text colors are very important. If they're wrong, they will result in unreadable texts.

**Comment by varlesh** [comment]
> BTW, In light-and-dark themes, the toolbar and menubar normal text colors are very important. If they're wrong, they will result in unreadable texts.

@tsujan Yes, for example on Arc Themes used different colors for GTK2 and GTK3 too... it's confused me

I'm upload Arc Darkerhttps://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/Kvantum/ArcDarker

I'm bad know Kvantum skills :(

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30238748-6cee564e-955e-11e7-8839-09b9ef81fbda.png)

**Comment by tsujan** [comment]
It seems beautiful.

Right now, I'm in the middle of something; will download and test your theme later.

**Comment by varlesh** [comment]
@tsujan Not bad looking )
Need add and fix `arrow/tarrow` indicators. And i think my theme have more errors

**Comment by tsujan** [comment]
It's OK. We will find and fix probable problems. I usually find my mistakes the day after I make a theme ;)

**Comment by varlesh** [comment]
@tsujan Hi. Please help :)
Why Kvantum ignore `text.normal.color=#d3dae3` on `ToolbarButton`? Used `#ffffff`
[ArcDarker.tar.gz](https://github.com/tsujan/Kvantum/files/1290658/ArcDarker.tar.gz)

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30250480-330bf0be-9660-11e7-9baa-c84a596030ab.png)

**Comment by varlesh** [comment]
Also i try change color on KvAdapta to `text.normal.color=#ff55ff`, but color `#ff55ff` not applied. Always used `#ffffff`

**Comment by tsujan** [comment]
@varlesh Now I'm very busy with another project but I think the following explanation should solve your problem:

When the toolbar buttons are NOT grouped, as is the case with your theme, they take their *normal* color from the toolbar normal color (under the section [Toolbar]) *because they aren't drawn until pressed or hovered* (nothing will be drawn until then). You should add a suitable `text.normal.color` under [Toolbar].

Feel free to add other comments here; I'll read theme as soon as I have time.

**Comment by varlesh** [comment]
Ouh, sorry.
But on theme set `group_toolbar_buttons=false` and not nothing.
Also Toolbar have this color too:
```
[Toolbar]
inherits=PanelButtonCommand
frame=true
frame.bottom=4
frame.left=4
frame.right=4
text.normal.color=#d3dae3
text.focus.color=#d3dae3
text.press.color=#d3dae3
text.toggle.color=#d3dae3
text.bold=false
```
Used Kvantum 0.10.4 Git version 20170621

**Comment by tsujan** [comment]
I set `toolbutton_style=2` (just for testing) and `text.normal.color=red` under [Toolbar] ans the result is correct:

![test](https://user-images.githubusercontent.com/981076/30250750-28c1d764-9669-11e7-8d15-93ca759220f2.png)

Kvantum 20170621 is too old ;) There have been lots of fixes and changes since then. Please update your Kvantum installation and report back! Thanks in advance!

**Comment by tsujan** [comment]
And this is a funny screenshot with Dolphin:

![dolphin](https://user-images.githubusercontent.com/981076/30250783-abad587e-9669-11e7-9fbb-cee6b9f26633.png)

**Comment by tsujan** [comment]
BTW, you don't need to set any color other than normal under [Toolbar] because, for example, when a toolbar button is pressed, a panel will be drawn for it and so, its own press color will be used.

**Comment by tsujan** [comment]
@varlesh Maybe we're speaking about different things because, in the last screenshot you attached, there's no text. If you mean that the icon color is white on toolbar, that's what KDE does and Kvantum supports, namely, *symbolic icons*. Do you mean that?

**Comment by varlesh** [comment]
I'm not understand. I mean `ToolbarButton`, not `Toolbar`. Icons (text) on Button not used color from config.

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30250888-51dda814-9667-11e7-98f6-d7425343e00f.png)
Icon on button white `#ffffff`, it's wrong color, because on config set `#d3dae3`

**Comment by varlesh** [comment]
@tsujan You can chek this on KvAdapta too, replace color to `#ff55ff`:
[ToolbarButton]
frame.element=tbutton
interior.element=tbutton
indicator.element=tarrow
text.normal.color=#ff55ff
text.focus.color=white
text.press.color=white
text.toggle.color=white
text.bold=true

**Comment by varlesh** [comment]
symbolic icons - not. Dolphin not use symbolic icons. But icon color, yes :)

**Comment by tsujan** [comment]
> Icon on button white #ffffff

@varlesh I explained above about ICON COLOR. Kvantum NEVER sets the the icon color (no style engine does); it just supports KDE's symbolic icons (white on dark background and black on light backgrounds) plus selection tinting, which should be disabled in light-and-dark icons (`no_selection_tint=true`).

> symbolic icons - not. Dolphin not use symbolic icons. But icon color, yes :)

Those icons are called symbolic; they have a property in their SVG file and KDE makes them either white or black by reading that property. Gnome has its symbolic icons too but KDE's way of making them black or white is better.

**Comment by tsujan** [comment]
We also implemented them in LXQt.

**Comment by varlesh** [comment]
But Gnome use color from GTK theme for symbolic icons. It's possible use on Kvantum too?

**Comment by tsujan** [comment]
The support for such icons in Qt should be added to DE. As I said above, Kvantum just recognizes that support; the icons are colored by the DE -- more precisely, by its icon engine.

**Comment by tsujan** [comment]
If you run dolphin under Gnome, you'll see that sometimes there's black on dark or white on light background with some dark-and-light theme because Gnome doesn't have a Qt icon engine -- although one can run LXQt's icon engine under Gnome or any other DE.

**Comment by tsujan** [comment]
Edited my last comment (added "AND WITH BREEZE ICON THEME").

**Comment by varlesh** [comment]
Hm, it's interesting.
I know about CSS Class for SVG-icons. And My Theme (Papirus icon theme) support this with Breeze engine.
For example:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
 <defs>
  <style type="text/css" id="current-color-scheme">
   .ColorScheme-Text { color:#5c616c; } .ColorScheme-Highlight { color:#5294e2; }
  </style>
 </defs>
 <path style="fill:currentColor;opacity:1" class="ColorScheme-Text" d="M 8 1 C 4.137 1 1 4.137 1 8 C 1 11.863 4.137 15 8 15 C 11.863 15 15 11.863 15 8 C 15 4.137 11.863 1 8 1 z M 8 3 C 9.0194 3 9.959 3.28763 10.75 3.8125 L 3.8125 10.75 C 3.28763 9.95898 3 9.0194 3 8 C 3 5.2407 5.2408 3 8 3 z M 12.1875 5.25 C 12.71237 6.04102 13 6.9806 13 8 C 13 10.7592 10.7592 13 8 13 C 6.9806 13 6.041 12.71237 5.25 12.1875 L 12.1875 5.25 z"/>
</svg>
```
PS: But i don't want open request on KDE bugtracker, because all my requests ignored.
I apologize for delaying you and thx for support :+1:

**Comment by tsujan** [comment]
> But i don't want open request on KDE bugtracker, because all my requests ignored

They have been very busy. I gave them a patch for Dolphin several months ago but it was seen only recently -- and now I don't have time to updated it ;)

Even if the symbolic icons are colored, this question will arise: which color should be used? Kvantum extends the current Qt colors but the icon engine can't know about that. Gnome has only one "style engine", so the symbolic icons can be colored.

The only cases in Qt that icons can be *tinted* are (1) on mouse-over and (2) on selecting. Selection tinting should be disabled with dark-and-light themes (as is disabled in your theme).Both tints use the highlight color and nothing else.

> I apologize for delaying 

No need to an apology! You're always welcome to comment and ask questions.
