### ISSUE TITLE
kvantum-qt5 is now in arch [community]

### ISSUE THREAD

**Issue by omni6** [tsujan/Kvantum#158]
kvantum-qt5 0.10.4-1 @ [[community]](https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/)

**Comment by tsujan** [comment]
Thanks!

There are enormous amount of changes since V0.10.4. I'll release V0.10.5 after testing the latest features.

**Comment by omni6** [comment]
yes... about the rising activity around kvantum... finally this project gets the attention it deserves. 
:+1:

**Comment by ArchangeGabriel** [comment]
I was in fact waiting to see if a 0.10.5 release would happen before packaging given the amount of changes but went away anyway since Breeze is really ugly. Now I have a wonderful Arc theme. :)

**Comment by tsujan** [comment]
0.10.4 is good for now. I have still some work to do before releasing 0.10.5.

And I agree that Breeze is ugly ;) Even KDE3 had a better default look.

**Comment by omni6** [comment]
afaik breeze and arc theme were the only ones with matching gtk themes.  now i have installed kvadapta and adapta-gtk-theme and i really lovin it. waiting for the dark variant ;)

**Comment by tsujan** [comment]
@omni6 
The irony is that I made Kvantum to keep distance from GTK but the first thing I did was remaking some of my own GTK themes in Kvantum (KvBeige, KvDarkRed, KvGray) and after that I made KvArc, KvAmbiance and KvAdapata -- and also KvGnome which is not far from an old version of Adwaita ;)

**Comment by omni6** [comment]
i try to avoid gtk and qt4 apps generally and its almost possible to run a clean qt5 system, but for a few applications (just 4) i have no alternative. i like it uniform. not really necessary but nice.

i have to show you ... this goes OT ;)
![screenshot_20170913_210226](https://user-images.githubusercontent.com/24492439/30395638-1cc14188-98c7-11e7-91af-db574ed4bf51.png)

**Comment by tsujan** [comment]
> i have to show you ... this goes OT ;)

What a nice harmony!

**Comment by omni6** [comment]
thank you!
