### ISSUE TITLE
KVantum default theme

### ISSUE THREAD

**Issue by azubieta** [tsujan/Kvantum#159]
At nxos (nxos.org) we would like to set our own kvantum theme (kvnomad) as default for all users instead the current default theme. Is there a way of achieving this besides putting the kvantum configs in  "/etc/skel".

Thanks
And good work :+1:

**Comment by tsujan** [comment]
No, there isn't! The "inheritance rules" are the reason: all themes get their undefined elements/variables from the default theme and if the latter is changed, other themes will be broken. The default theme is an inseparable part of Kvantum.

**Comment by tsujan** [comment]
BTW, I downloaded KvNomad from here https://github.com/nomad-desktop/nomad-kvantum-theme. It's elegant and simple but I found an issue in it: the value of `inactive.highlight.color` (under the GeneralColors section) is `#f5f5f5`, which makes inactive selected texts unreadable. It should be dark like `highlight.color`.

**Comment by tsujan** [comment]
Another small problem is KvNomad: there are no "menu-shadow-hint-..." rectangles (there should be 4 of them), although there are "menu-shadow-.." elements and `menu_shadow_depth` is set to 5. That causes a wrong submenu overlap and also makes blurring incorrect if it's enabled under KDE.

The same is true for "tooltip-shadow-hint-...".

**Comment by azubieta** [comment]
Thanks! If you find another would you mind to open an issue [there](https://github.com/nomad-desktop/nomad-kvantum-theme)

**Comment by tsujan** [comment]
As soon as I find some free time, I'll make a PR (or 2) there.

**Comment by tsujan** [comment]
Made a [PR](https://github.com/nomad-desktop/nomad-kvantum-theme/pull/2).

**Comment by tsujan** [comment]
Now it's possible to have a global config file `$XDG_CONFIG_DIRS/Kvantum/kvantum.kvconfig`. It can set the start theme as well as app-specific themes. Its format is that of `~/.config/Kvantum/kvantum.kvconfig`.

V0.10.6 will be released soon.
