### ISSUE TITLE
different looking qt5 listview/treeview headers/expanders

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#16]
well seems they are still using the fusion/default syle in qt5

qt4 vs. qt5:

http://i.imgur.com/c9lskp2.png

**Comment by tsujan** [comment]
Yes, I know about that (-> line 4328 in Kvantum.cpp). It's specific to Qt designer. In Qt4 designer, they used the pushbutton style for its Widget Box headers, which was a wrong choice. In Qt5 designer, they've added a consistent new style for those headers. So it isn't about a bug.

**Comment by sixsixfive** [comment]
ahh, OK ;)
