### ISSUE TITLE
Screenshots ?

### ISSUE THREAD

**Issue by jcelerier** [tsujan/Kvantum#160]
Would it be possible to put some screenshots of an example app styled with Kvantum on the README ? For instance by taking a Qt widgets example : http://doc.qt.io/qt-5/gallery.html

**Comment by tsujan** [comment]
Good idea! I don't know why that didn't occur to me before.

I'll add some screenshots but it might take a while because I should choose between the themes.

**Comment by tsujan** [comment]
Added several small screenshots with various themes to give an idea about Kvantum to those that haven't tried it yet. They're inside the kvantum folder and are included in `README.md` (which was `README` previously). I might change some of them later. Thanks for the suggestion!

**Comment by jcelerier** [comment]
thanks, they're very nice and give a pretty good idea !
