### ISSUE TITLE
Kvantum ignore Systemsetting - Effects on Plasma

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#161]
Kvantum not applied on Systemsetting - Effects window, used colors from color-schemes
![image](https://user-images.githubusercontent.com/8083855/30520152-f97ddca0-9bb8-11e7-8f12-30daaab461f7.png)

**Comment by varlesh** [comment]
With default theme too:
![image](https://user-images.githubusercontent.com/8083855/30520162-3d3933ae-9bb9-11e7-95ed-7320595913e6.png)

**Comment by varlesh** [comment]
LOG:
```
kcmshell5 kcmkwineffects
Icon theme "elementary" not found.
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Adwaita" not found.
Icon theme "Mint-X" not found.
Icon theme "gnome" not found.
WARNING: Cannot find style "org.kde.desktop" - fallback: "/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/Styles/Desktop"
Constructing a KPluginInfo object from old style JSON. Please use kcoreaddons_desktop_to_json() for "/usr/lib/x86_64-linux-gnu/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so" instead of kservice_desktop_to_json() in your CMake code.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/kwin-effect.desktop, tried ("/home/alex/.local/share", "/usr/share/usr/share/xsessions/plasma", "/usr/local/share", "/usr/share", "/var/lib/snapd/desktop") and ":/kservicetypes5/kwin-effect.desktop"
```

**Comment by tsujan** [comment]
Some kde apps use the color scheme directly. Desktop effect settings page is among them. Its design has problems. For example, it doesn't use the highlight color and the highlighted text color correctly. As you can see in your attached log, this isn't Kvantum's fault but a problem in KDE system settings.

Some of such problems are because of QML; some others are caused by bad design.

**Comment by tsujan** [comment]
In short, apply the corresponding color scheme, close KDE system settings, and open it again.

**Comment by tsujan** [comment]
An example with kvAdapta:

![kvadapta](https://user-images.githubusercontent.com/981076/30521804-b25be872-9bda-11e7-918c-ec2f156cc785.png)

Don't expect the highlight colors to be correct though ;)

**Comment by varlesh** [comment]
Ok... I hope this will be fixed on new systemsettings:
https://anditosan.wordpress.com/2017/09/06/system-settings-progress/

**Comment by tsujan** [comment]
I don't know... Before Plasma5, KDE devs started to talk about how it would be great. What I saw afterward wasn't great at all; it was simply a big regression. They started to use QML and suddenly, because of it, the look of KDE became so elementary -- so ugly -- as if we were in 1980s again.

I don't get it why the talk about "future" so much. In LXQt, we add new features or make big changes but don't have time to say a single word about them. In short, I'm not optimistic about the future of KDE, although I'll be really glad if they make it better than what it is now.

**Comment by tsujan** [comment]
And I should add that a lot of time is wasted just for setting up a new site for KDE development. If only KDE was developed on github, I could send them a lot of PRs. But contributing to KDE isn't easy with its new site. Why not github, I don't understand....

**Comment by varlesh** [comment]
@tsujan Oh yes!!! i'm worked with phabricator and arc (i'm co-author Breeze icon theme), it's very uncomphortable... But now, i'm not develop anymore on KDE. I like github ))
And yes, i  fully agree with you - Plasma 5 it's big regression

**Comment by varlesh** [comment]
@tsujan If you interested fix some bugs on KDE, please see this:
https://bugs.kde.org/show_bug.cgi?id=366062
All non-KDE and non-Qt apps have wrong rendering.
More info i'm post here:
https://github.com/psifidotos/Latte-Dock/commit/b9fa04bc3298ca7f44c3f7ce5a94ba79c919e4ad

**Comment by tsujan** [comment]
@varlesh Under KDE, my focus was on Dolphin and file management. I'm not familiar with the code of Plasma.

As for Dolphin, I'd removed its 1-sec delay, fixed a bug and added folder selection on going up. But after big changes to pcmanfm-qt (through libfm-qt), I had no time to work on Dolphin anymore.

**Comment by tsujan** [comment]
If only each day had 25 hours ;)

**Comment by trmdi** [comment]
> If only KDE was developed on github..., I could send them a lot of PRs. But contributing to KDE isn't easy with its new site

Oh, what a pity! KDE could be much better if it had your PRs.
In fact, you can use arc, it's very easy to use. I hope one day you would give it a try.

I don't say QML is good or bad, but qml apps have a different style compared to other like Dolphin. I hate that.

Is there any way to make qml app's windows transparent like Dolphin, Konsole?

**Comment by tsujan** [comment]
@trmdi 

QQC2 (QML) apps are drawn very differently. KDE tries to enforce `QStyle` on them (`QStyle` is for real widgets, like those of Qt apps) but QQC2 isn't compatible with `QStyle`. What is sacrificed in this process may not seem much with elementary styles like Fusion and Breeze but the problem will be quite visible if Kvantum is used: other style plugins may "hide" the full extent of the problem by not using the full power of `QStyle`.

QML apps may be made translucent by their own styles but not when `QStyle` is artificially enforced on them. Of course, the WM may be able to make them translucent but that's not what we mean by window translucency.

QQC2 *may* be good in some places but definitely not in config GUIs, let alone in whole GUIs of apps. The more it's used, the more quality is sacrificed for the ease of coding.

**Comment by tsujan** [comment]
As a side note, see what they've done with System Settings → Color in Plasma 5.16. More and more QML… :(

QQC2 is Qt's fast food. OK, fast food may be good once or twice a week but more than that means really bad taste ;)

**Comment by trmdi** [comment]
I feel QML app's performance is not as good as Qt Widget app. SystemSetting > Icons is an example. I feel they are another kind of electron apps. :(

**Comment by tsujan** [comment]
> I feel they are another kind of electron apps

Good comparison :) Both feel nonnative, as if designed for mobile phones.

**Comment by trmdi** [comment]
Ah, I just read again this: https://www.reddit.com/r/kde/comments/9p8uwm/comment/e8224t5

You said:
> kvantum-dark (widget style) is for themes that have a dark variant.

Do I need to use it for KvMojave-dark?
Should I switch between kvantum vs kvantum-dark widget style when switching between KvMojave and KvMojave Dark?
Is there any different?

**Comment by tsujan** [comment]
> Do I need to use it for KvMojave-dark?

I've never had any use for `kvantum-dark`. It's there for Gnome users because it gives a dark Gnome title-bar to a Qt app that is run with `APP -style kvantum-dark` (which can be included in its desktop entry).

So, if you don't use Gnome, you could ignore `kvantum-dark`.

**Comment by tsujan** [comment]
Moreover, `kvantum-dark` only works for a theme KvT that has a dark variant named KvTDark. I haven't followed Gnome in regard to light and dark themes because, with Kvantum, any theme can be given to any app and, with KWin, title-bars can be changed too.

**Comment by Davide-sd** [comment]
> QQC2 (QML) apps are drawn very differently. KDE tries to enforce `QStyle` on them (`QStyle` is for real widgets, like those of Qt apps) but QQC2 isn't compatible with `QStyle`. What is sacrificed in this process may not seem much with elementary styles like Fusion and Breeze but the problem will be quite visible if Kvantum is used: other style plugins may "hide" the full extent of the problem by not using the full power of `QStyle`.

Hello @tsujan , do you know where I could find the code responsible for forcing `QStyle` over QQC2 elements?

**Comment by tsujan** [comment]
> do you know where I could find the code responsible for forcing QStyle over QQC2 elements?

See qqc2-desktop-style
