### ISSUE TITLE
another style for kcapacitybar

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#162]
Default kcapacitybar on Kvantum looking not modern style:
![image](https://user-images.githubusercontent.com/8083855/30775690-25cd7ffe-a0aa-11e7-89b6-49a1ccdb4b06.png)
How draw this widget? Maybe possible use Breeze style for KDE?
![image](https://user-images.githubusercontent.com/8083855/30775721-6662dd70-a0aa-11e7-8276-6e1d74485817.png)

**Comment by varlesh** [comment]
This looking as QtCurve :)

**Comment by varlesh** [comment]
Yes, i know about `kcapacitybar_as_progressbar=true` but on dolphin not possible use text with some modern styles.
For example, Adapta style. Font on pattern not good looking (if pattern not fully filled).
![image](https://user-images.githubusercontent.com/8083855/30775764-492d8902-a0ab-11e7-9663-69b8eb09eaba.png)

**Comment by tsujan** [comment]
I intentionally haven't put the progress text in front of its bar in Kvantum because, IMO, that's a *design flaw*, although it might be called "modern". The reason is that several progressbars may be used in a column and if *their texts have different sizes*, their patterns will look weird and will be misleading. On the other hand, in your second screenshot (with Breeze), you can see how the text wastes the available space. That's while Kvantum doesn't waste any space with such a bad design. The following screenshot is taken with KvAdapta. It's clean, quite readable and elegant.

![kvadapta](https://user-images.githubusercontent.com/981076/30775934-3b006170-a0aa-11e7-9254-9157885ee6b3.png)

Yes, the text will be removed if the progress height is *too small*. That's an option I added to Kvantum for the sake of flexibility. The height is the theme maker's choice, after all.

Last but not least, Breeze's progressbars occupy the same space; they don't save any space, in contrast to their look.

I remember that I had the same discussion with an old Kvantum user and he saw my point quickly.

**Comment by varlesh** [comment]
@tsujan But maybe ad option for use breeze style? Or maybe it's possible show notification free space with cursor hower on kcapacitybar?

See and compare, really progressbar looking good (on qbittorrent) but on Dolphin it's not good with text ( dolphin have this good option - show free spase on statusbar, more FM not have yet):
![image](https://user-images.githubusercontent.com/8083855/30776034-0ee4a9f6-a0b0-11e7-8f59-9b961d130aea.png)

**Comment by varlesh** [comment]
For icon size show notification:
![image](https://user-images.githubusercontent.com/8083855/30776058-733921ca-a0b0-11e7-877e-048b5941a60b.png)
But not for kcapacitybar free space :(

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/30776098-79d303c4-a0b1-11e7-9a29-277e16d6c935.png)
See, it's looking cool. But need need only notification with "space status" (use tooltip widget style). It's possible on kvantum as option?

**Comment by tsujan** [comment]
I found a (minor) problem in drawing kcapacitybar. First, I should fix that. Afterward, I'll think about adding an option for the text in front of the bar under certain conditions. All these might take a while because I'm busy with other projects now but I'll do them and will tell you here.

**Comment by varlesh** [comment]
Big thx, i wait!

**Comment by tsujan** [comment]
I had a little time and wrote a preliminary code (not pushed yet -- only offline) but before going further, let me check the result with you: Do you mean the following progressbars?

![progress](https://user-images.githubusercontent.com/981076/30777372-d85fe696-a0c5-11e7-9c14-304b220f560e.png)

**Comment by tsujan** [comment]
I couldn't sleep before finishing it ;) The were lots of calculations but I think it's OK now:

![kde](https://user-images.githubusercontent.com/981076/30778091-50f89108-a0d9-11e7-824a-c6e7a3d6b801.png)
 
I'll test it for a day or 2 and make a commit if there's no issue.

**Comment by varlesh** [comment]
@tsujan Very cool! I like it!

**Comment by tsujan** [comment]
OK, I pushed the changes for the new code to be tested by you. You could put the progress text in front of the progress bar just by setting `progressbar_thickness` to value *less than* the text (font) height. There was no need to another key :)

There's only one exception that should have text inside bar and that's `KisSliderSpinBox` (only used by digiKam). So, `progress.indicator.text.color` still needs to be set correctly and the SVG elements should be complete.

I changed KvAdapta(Dark) accordiingly:

![new_progress_text](https://user-images.githubusercontent.com/981076/30783796-00cc4d3c-a156-11e7-9f02-074e8620839b.png)

I still prefer not to use this design in most themes included in Kvantum ;)

**Comment by varlesh** [comment]
@tsujan Worked fine, you awesome THX!!!
![image](https://user-images.githubusercontent.com/8083855/30784668-701211d6-a16a-11e7-8590-a7d294360490.png)

Also one question - when 0.10.5 release?

**Comment by tsujan** [comment]
Thanks for testing!

> Also one question - when 0.10.5 release?

I have a plan to release it in 2 weeks, at most -- if I don't encounter any problem in the code.

**Comment by tsujan** [comment]
BTW, I'll add text margin to the new progress text soon. As you can see in your last screenshot, text right margin has no effect yet.

**Comment by varlesh** [comment]
It's aurorae without borders. Yes, little pixel need add

**Comment by tsujan** [comment]
Added a fixed 3px margin -- larger margins might cause problems. I think it's OK now:

![margin](https://user-images.githubusercontent.com/981076/30785432-75e4b588-a173-11e7-8072-7da6fe334bd9.png)

**Comment by varlesh** [comment]
Great :+1:
