### ISSUE TITLE
Tooltip shadow not used on dolphin preview

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#163]
For preview (folder, file) on window shadows not used for Dolphin.
For example, KvAdapta:
![image](https://user-images.githubusercontent.com/8083855/31001632-669b7c16-a4f6-11e7-86e0-db7d60596c0c.png)
For toolbar all fine, but not for preview:
![image](https://user-images.githubusercontent.com/8083855/31001668-94f2be1c-a4f6-11e7-82a6-7089e570b954.png)

**Comment by varlesh** [comment]
Sorry, it's happend for other apps too. For example, systemsettings window:
![image](https://user-images.githubusercontent.com/8083855/31001763-472e91be-a4f7-11e7-8c7a-bac48e531bdf.png)

**Comment by tsujan** [comment]
The strange thing is that those tooltips *have* shadow with some Kvantum themes:

![1](https://user-images.githubusercontent.com/981076/31014652-dc73da0a-a528-11e7-9f0e-63b0dcffb8ea.png)
![2](https://user-images.githubusercontent.com/981076/31014653-dc7b56a4-a528-11e7-9688-912e1f940c04.png)

I'll investigate why they're shadowless with some themes.

**Comment by tsujan** [comment]
With this report, you actually helped me solve a very old problem with those custom tooltips of KDE. Thanks!

Now, the unusual tooltips of KDE should be OK. Please test the latest git Kvantum and close this issue if it's really fixed.

**Comment by varlesh** [comment]
@tsujan :+1:  Ok, only later...

**Comment by tsujan** [comment]
@varlesh Take your time!

Such small problems are the reason I've delayed the next release. Please report any other issue you might find in the next 2 weeks!

**Comment by varlesh** [comment]
Ok, if found

**Comment by varlesh** [comment]
@tsujan worked, thx for fast fixing :) 
![image](https://user-images.githubusercontent.com/8083855/31018444-2be44caa-a53d-11e7-8ef5-c9c08c486ad7.png)

**Comment by tsujan** [comment]
Your'e welcome! And thanks for reporting and testing!

**Comment by tsujan** [comment]
By the way, those dark links on the dark background in your fist screenshot are because of `link.color`. Either `link.color` should be chosen so that it's readable on both light and dark backgrounds or I should see if I can do something in the code. Although I don't think it's possible now, I'll look into it later.

**Comment by tsujan** [comment]
I looked into the tooltip link color issue: it isn't a Kvantum issue; it happens with Breeze and other style too and is a KDE issue.
