### ISSUE TITLE
[Question] What color you set for push button background in  Kvantum Adapta  (light and dark)

### ISSUE THREAD

**Issue by ceyhunnabiyev** [tsujan/Kvantum#165]
Hi @tsujan , I don't know this is the bug, or problem is related to qt5ct:
![screenshot from 2017-10-03 01-42-19](https://user-images.githubusercontent.com/5506156/31309743-577d58ec-ab9c-11e7-9775-898eee87e509.png)

![screenshot-20171007201704-681x732](https://user-images.githubusercontent.com/5506156/31309767-97339834-ab9c-11e7-866b-2383f2474971.png)

**Comment by tsujan** [comment]
I'll investigate it but, at first glance, that push-button seems to have a hard-coded background color (`#d4d0c8`) without a hard-coded foreground color.

**Comment by ceyhunnabiyev** [comment]
Thanks for fast answer!! Can this be fixed? Or this issue related to qt5ct?

**Comment by tsujan** [comment]
Most probably, it's a problem in qt5ct. However, I'll look into it when I find some free time and will tell you about it.

**Comment by tsujan** [comment]
OK, this is definitely a qt5ct issue. In its source, it has `AppearancePage::setPalette()`, which sets a wrong palette. The color `#d4d0c8` belongs to qt5ct, not to Kvantum. In the case of push buttons, Kvantum checks if their background color is different from the real button color of the theme and if so, considers them as "color buttons", i.e. it uses the other color instead of the SVG element. That other color (#d4d0c8`) is (wrongly) enforced by qt5ct.

This wouldn't happen if the palette wasn't set when it didn't need to be set (i.e. when the Default button was checked) or if the correct palette was set.

Sorry, nothing can be done in Kvantum.

**Comment by tsujan** [comment]
Oh, sorry for the technical terms I used in the above explanation! In simple words:

Style engines like Breeze or Fusion don't define their own colors but get their colors (palettes) from an outside source. That's while Kvantum defines its own palette but, unfortunately, qt5ct doesn't respect it in its preview area.

**Comment by ceyhunnabiyev** [comment]
@tsujan,  please  can you example in application that push button works fine? Maybe it only shows wrong in qt5ct.

**Comment by tsujan** [comment]
Run `kvantumpreview` in terminal and you'll see a lot of push buttons in the first tab ;)

**Comment by tsujan** [comment]
All push buttons are OK -- as they should be; the issue is only about qt5ct preview ;)

**Comment by ceyhunnabiyev** [comment]
Yes works fine in Gnome, thanks for this and  sorry for wasting your time...

**Comment by tsujan** [comment]
You're welcome.

**Comment by ceyhunnabiyev** [comment]
@tsujan , I see 162 commits after latest release. May you make new release out ,especially for Kvantum Adapta , for example 0.10.5. I am going to do some customizations on Kvantum Adapta in Manjaro. For this it gonna be useful..

**Comment by tsujan** [comment]
I'll release V0.10.5 in a week, after testing the latest changes to be sure that there's no issue.

**Comment by ceyhunnabiyev** [comment]
Thanks..

**Comment by tsujan** [comment]
V0.10.5 is released just now :)

**Comment by ceyhunnabiyev** [comment]
Thank you for release, @tsujan.

**Comment by tsujan** [comment]
@ceyhunnabiyev Thank you for your feedback!

BTW, a few minutes ago, I found a problem in otter-browser, that could be seen only with some Kvantum themes (not with KvAdapta). I reported the issue at its github page with some explanation.
