### ISSUE TITLE
[Suggestion] Default Adapta selection color(#00bcd4) for combo, menu item highlight color 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [tsujan/Kvantum#166]
Hi @tsujan , what is the color of combo, menu item highlight color? The highlight I didn't noticed so much. 
![screenshot-20171022154204-266x204](https://user-images.githubusercontent.com/5506156/31861653-28b7982c-b742-11e7-8daf-9a4e26b92c9e.png)

What do you think about it?  it should be a little bit darker?

**Comment by tsujan** [comment]
That depends on the active Kvantum theme and whether combo popups are drawn as menus. if combo popups are drawn as menus -- as they are in the theme you use -- the menu-item SVG element is used for drawing the background, *not the highlight color*. Open a menu and you'll see that menu items have exactly the same SVG background.

I guess the theme you use is KvAdapta, whose menu-item SVG background is chosen in such a way that it looks exactly like the Adapta GTK theme.

**Comment by ceyhunnabiyev** [comment]
@tsujan , Thanks for your answer, what color is used for the background?

**Comment by tsujan** [comment]
If you mean the menu background, again it's not a color but the SVG element "menu-normal". But if you mean the window background, it's `window.color`, which is `#fafbfc`.

**Comment by ceyhunnabiyev** [comment]
@tsujan , I mean this (blueish or grey):
![screenshot-20171022164039-213x33](https://user-images.githubusercontent.com/5506156/31862006-d0e91f16-b747-11e7-911b-a4519f9a3513.png)

**Comment by tsujan** [comment]
As explained above, it isn't a color but consists of 18 SVG elements whose names start with 'menuitem-". Of course, those SVG elements have colors and, in this special case, all of them are `e8e9ea` but you couldn't change that in the config file. If you want to change the shapes or colors of those elements, you should edit the SVG file, which means making a different theme based on KvAdapta. KvAdapta is made to match Adapta; hence, those elements and their color.

It's good to play with Kvantum SVG files. Kvantum has so many themes and you could start with any one. Please read the comprehensive documentation included in the source (in the "doc" directory).

**Comment by ceyhunnabiyev** [comment]
`e8e9ea`, that is I need. Many thanks  and sorry for wasting your time..

**Comment by tsujan** [comment]
No problem and you're welcome.
