### ISSUE TITLE
Release tarballs or git tags

### ISSUE THREAD

**Issue by v00d00** [tsujan/Kvantum#167]
Hey,

I see you diligently update the NEWS and change log files, but there don't seem to be any tags on the repository for versions?

Do I just take the commit that you bumped the version as a release commit?

Ideally it would be great to have tags, or even github releases!

**Comment by v00d00** [comment]
Sigh, I was in the toplevel kvantum folder looking at the README, so didnt see the releases where I expected, sorry for the noise.

Looking forward to 0.10.6

**Comment by tsujan** [comment]
Hi,

Since V0.10.5, I started to add an annotated tag for every release. In the file "NEWS", I add the latest change date and the version of the next release for the sake of completeness. Usually, I have a TODO list for the next release but it changes a lot because, sometimes, I find small issues and fix them or new ideas may come to my mind, so I don't include it in the source.

Please tell me if some info is missing!

**Comment by tsujan** [comment]
BTW, Kvantum was my first repository on GitHub and I put it inside the folder "Kvantum/Kvantum" by mistake :) Later, I preferred not to change that because many users had got used to it. I also found a "good thing" about it: the latest commit text could be seen immediately at GitHub.

**Comment by ArchangeGabriel** [comment]
The latest commit text is always visible at the top for the current folder. So there is no “good thing” about it, but there would be quite a bad thing about moving: making history harder to view. ;)

**Comment by tsujan** [comment]
> So there is no “good thing” about it

I know but I should justify my old mistake ;)

Anyhow, PKGBUILD, deb folder and, probably, rpm depend on this nested structure and I don't want to break them. It's harmless, after all.

**Comment by v00d00** [comment]
Actually git is smart enough to know you moved the files, so history will be preserved even if you got rid of the useless folder...

**Comment by ArchangeGabriel** [comment]
You can still retrieve history through git, yes. But I’m not sure about GitHub interface, I remember seeing files being moved and their history starting to the commit which moved them.

**Comment by tsujan** [comment]
@v00d00 @ArchangeGabriel 

My main reason for not changing this is that, as I said above, I don't want break packagers' works. Yes, "Kvantum/Kvantum" is unusual but it doesn't do any harm at all. People have found and will find all files easily, although with a small surprise ;)
