### ISSUE TITLE
Kvantum middle click on scrollbars has no effect

### ISSUE THREAD

**Issue by NickLion** [tsujan/Kvantum#168]
Middle click is commonly used to scroll to position, but Kvantum just does nothing. I've tried several themes and haven't seen any difference. Is this just not implemented?

**Comment by tsujan** [comment]
In Kvantum, it's the *left-click* -- which is easier than the middle-click

**Comment by NickLion** [comment]
Yes, it's simpler, however there are two "buts":
1. Habit. A lot of people used to use middle click.
2. Compatibility. There are not only Qt applications (and other widget styles, like Breeze), middle click works there, but not left click.
So, IMHO, it's better to get both left click and middle click to work. As middle click does nothing ATM, there is no any breakage of behaviour.

**Comment by tsujan** [comment]
Wrong habits aren't for Kvantum. Actually, I've had a hard time to correct bad habits many developers have when it comes to Qt styling. Long story short, QStyle is much more flexible than what's in Breeze or Fusion, and Kvantum makes use of that. Scrollbar left-clicking is just one example among so many.

Why didn't I make that optional? To create a better habit ;)

**Comment by NickLion** [comment]
I do really understand your motivation. But just pessimistic that GTK or Java Swing will follow this. Thank for your attention anyway :)

**Comment by tsujan** [comment]
> But just pessimistic that GTK or Java Swing will follow this

gtk2 had an option for it. In gtk3, left clicking does the same thing but with a delaying animation (see `gtk3-widget-factory`). So, Java is alone.

You may have seen that Kvantum has a great amount of options -- not just in Kvantum Manager and, definitely, much more than other Qt style engines -- but an option for this would be inviting self-torture ;)

**Comment by NickLion** [comment]
Hm, gtk2 with Adwaita has this behaviour, but gtk3 does not, at least in `gtk3-widget-factory` and Gtk3 MySQL-Workbench left click does page scroll, not scroll to position. Maybe there is an option for that too.

**Comment by tsujan** [comment]
On second thought, I decided to add a key for it (to Kvantum Manager) but with left-click as the default. If users want the hard way, they should change the setting deliberately.

Should study all options before making a commit.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/0a6924c77bc5306a886b75a0cfe36b59932ae729

The new option is at Kvantum Manager → Configure Active Theme → Hacks → Scroll jump with middle click.

**Comment by NickLion** [comment]
Thanks for the option!

**Comment by tsujan** [comment]
You're welcome!

I showed your comments to a friend of mine and when I saw both of you had the same opinion, democracy prevailed ;)
