### ISSUE TITLE
Some Kvantum themes switch off subpixel font rendering

### ISSUE THREAD

**Issue by NickLion** [tsujan/Kvantum#169]
This is strange bug (or feature?). Some themes, like KvAdapta, KvAdaptaDark, KvArc switch off subpixel rendering (text in widgets become gray rendered) while other, like KvFlatLight, KvGnome, KvOxygen are keeping subpixel rendering.

**Comment by tsujan** [comment]
This has nothing to do with rendering. In some themes, text colors may have translucency or be gray. For example, the text color of KvAdapta is `#000000c8`.

Themes like KvAdapta and KvArc are made to match their gtk counterparts; hence their (text) colors.
