### ISSUE TITLE
focus bug?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#17]
it seems there is some bug with here, since i can't really describe it i made a short video:

https://drive.google.com/file/d/0B_2_dsXrefR-VjRNNDFDSVFJS1k/view?usp=sharing

also the application:
https://github.com/aarnt/octopi/tree/master/notifier/octopi-notifier

**Comment by tsujan** [comment]
I saw two things in your video:
(1) The top panel was flickering;
(2) The Octopi menuitem had a color not found in Glare;

Which problem do you mean? Does Octopi have the same menuitem color with fusion? Does the panel flicker with QtCurve or other styles too?

**Comment by tsujan** [comment]
Besides, the green icon shows up correctly with Kvantum but not with Fusion. Why?

**Comment by sixsixfive** [comment]
>(1) The top panel was flickering;

thats the bug

>Besides, the green icon shows up correctly with Kvantum but not with Fusion. Why?

actually it should not display if the icon is green - but for some reason it is displayed with kvantum

also with qtcurve its the same as with fusion(no icon, unitl an update is available(yellow or red icon))

>(2) The Octopi menuitem had a color not found in Glare;

nah, thats the because of the included colorscript ( https://github.com/sixsixfive/Glare/blob/master/Glare-misc/changecolor.sh )

**Comment by tsujan** [comment]
> actually it should not display if the icon is green...

But according to octopi-notifier -> mainwindow.cpp -> line 590, it should show the green icon too. Also this video shows a green icon: https://www.youtube.com/watch?v=2y6d7k7_1t0

Is the panel compiled with Qt4? Qt4 panels have problem with Qt5 tray icons, even in KDE. If so, recompile Octopi with Qt4 and see if its tray icon works OK.

**Comment by sixsixfive** [comment]
nah the panel is the xfce4-panel und it uses gtk2, i will do a few more tests.Do you now any other panel that supports intelligent autohide?

**Comment by tsujan** [comment]
> Do you now any other panel...

No, I don't know about DE-independent panels. In old times, under Gnome, I used Cairo-Dock.

> it uses gtk2...

So, the problem may be outside Qt5.

I'm still curious as to why the green icon isn't shown with Fusion.  I can't install Octopi on Debian, so I wait for your tests. I suggest you try its Qt4 version if possible.

**Comment by tsujan** [comment]
BTW, I was wrong about Qt4 panels having problem with all Qt5 tray icons. The only Qt5 app I know that has systray icon is my own. Its icon works OK under KDE. You could download and easily compile it for Qt5 from here:

https://dl.dropboxusercontent.com/u/7793460/feathernotes.tar.gz

Please keep it for your personal use because I haven't uploaded it anywhere. And please tell me if you've downloaded it as soon as possible so that I delete the file. Looking forward to your test!

**Comment by tsujan** [comment]
Strangely enough, I succeeded in compiling octopi-notifier for Qt5 and running it under KDE, on Debian. The problem you mentioned didn't happen. This is a video: https://dl.dropboxusercontent.com/u/7793460/octopi_on_debian.mkv

**Comment by sixsixfive** [comment]
well i did some futher investigation and it seems the xfce4-panel is unable to display qt5 systray icon(strange that they work with kvantum)

i tried this tiny app http://qt-apps.org/content/show.php/meteo-qt?content=167733

https://drive.google.com/file/d/0B_2_dsXrefR-ZjRETXc1R0NKMFU/view?usp=sharing

**Comment by sixsixfive** [comment]
+close this now, because ( i guess) its a bug releated to the xfce panel

**Comment by tsujan** [comment]
Still a mystery why the tray icon was shown with Kvantum in the first place, although it made xfce4-panel flicker. That may have something to do with the Qt SVG renderer, but I don't know how.
