### ISSUE TITLE
[Arch, kde-plesma5.11]Correctly installed but can not run the manager

### ISSUE THREAD

**Issue by hcnhcn012** [tsujan/Kvantum#170]
Installing with : 
`$ sudo pacman -S kvantum-qt5 kvantum-theme-adapta kvantum-theme-arc`

And Also : 
[papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)

Theme is changed to adapta.

Then run the manager

Terminal Throws:
`$ kvantummanager`
`Icon theme "ubuntu-mono-dark" not found.`
`Icon theme "gnome" not found.`

**Comment by tsujan** [comment]
Your description was so short that I can't know what the problem is. Doesn't Kvantum work? Doesn't Kvantum Manager work?.... Please be a little more specific!

Those messages in the terminal aren't related to Kvantum.

**Comment by hcnhcn012** [comment]
![desktop screenshot](https://user-images.githubusercontent.com/19546977/33518162-84592c82-d7cb-11e7-9e4e-594bf7fa536f.png)


Yes, When I open the manager it shows this

**Comment by tsujan** [comment]
Are GUI apps styled by Kvantum? Please also attach a small screenshot of a Qt5 or KDE app, like Dolphin!

Does the command `kvantumpreview` work in terminal?

**Comment by hcnhcn012** [comment]
Kde app and kvantumpreview work really well, maybe the something have not installed through the Arch’s pacman, i am trying to reinstall it through the source

**Comment by tsujan** [comment]
> Kde app and kvantumpreview work really well

Strange!

**Comment by tsujan** [comment]
But your previous screenshot doesn't show that. The above dialog isn't styled by Kvantum but by Breeze.

**Comment by tsujan** [comment]
For the sake of certainty, I recompiled and reinstalled kvantummanager. This is Kvantum Manager with the KvGnomish theme:

![kvantummanager](https://user-images.githubusercontent.com/981076/33518730-6741a136-d7af-11e7-9a39-1ef7eff8c084.jpg)

What if you uninstall `kvantum-theme-adapta` and `kvantum-theme-arc` and only install Kvantum? Those packages don't belong to Kvantum.

**Comment by omni6** [comment]
Try kvantum-qt5-git

**Comment by tsujan** [comment]
Yes, [this](https://aur.archlinux.org/packages/kvantum-qt5-git/) should be fine. A problem with the non-git PKGBUILD? Various PKGBUILDs are also included in the source but @omni6's will work well.

**Comment by hcnhcn012** [comment]
Yes, I tried ` kvantum-qt5-git`, the problem is the same.

I also found that there is no `kvantum` options in widget style

but I can find the color theme `kvantum`

![desktop screenshot](https://user-images.githubusercontent.com/19546977/33522047-ccec7fb0-d81d-11e7-889e-37cb90dcd00c.png)
![google](https://user-images.githubusercontent.com/19546977/33522048-cd4f41ea-d81d-11e7-9075-60add9df9b3d.png)

Dependencies is good of kvantum.

**Comment by hcnhcn012** [comment]
Can you please tell me the widget folder so I can check it out whether I correctly install it ?

**Comment by hcnhcn012** [comment]
IT WORKS!!! After install from the source !!! Thanks!

There are some problem in PKGBUILD in deed.

THANKS !

**Comment by tsujan** [comment]
> IT WORKS!!! After install from the source !!!

Happy to know that your problem is solved :)

> There are some problem in PKGBUILD in deed.

kvantum-qt5-git works without problem here; it correctly creates `/usr/lib/qt/plugins/styles/libkvantum.so`. That was the file missing from your previous installation.

That being said, there are warnings in the cmake compilations. Some cmake rules have changed. I'll look into them.

**Comment by tsujan** [comment]
@hcnhcn012
To see if CMAKE 3.10 could cause a problem, I used `pacaur -S kvantum-qt5-git` on another computer and although there were warnings about CMP0071 -- something new in CMAKE 3.10 -- Kvantum was compiled and installed correctly. Of course, I had to use the `--force` option with `pacman` because I'd installed Kvantum manually before.

I'll try to remove the CMP0071 warnings in a backward compatible way (some systems don't have CMAKE 3.10 yet) but they don't affect compilation.

Anyhow, since you successfully compiled and installed Kvantum from the source, your problem with pacman/CMAKE can't be in Kvantum.

**Comment by ArchangeGabriel** [comment]
Well what would be much more interesting to me is to know if there is an issue with the package in the official repo of ArchLinux…

**Comment by tsujan** [comment]
> Well what would be much more interesting to me is to know if there is an issue with the package in the official repo of ArchLinux...

Although I may be wrong, I think there's no package but a good [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kvantum-qt5-git), which creates a good package out of the latest git Kvantum.

**Comment by ArchangeGabriel** [comment]
I’m referring to [this](https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/), which OP tried to install as stated in the first post.

**Comment by tsujan** [comment]
@ArchangeGabriel 

You're right, hcnhcn012 had installed that package.

**Comment by omni6** [comment]
@ArchangeGabriel 
I think there was something odd with his system. official and git version doesn't work but selfcompiled... isn't it the same, git and selfcompiled!? 
for me both versions working fine. 

I had the same issue some time ago as i was on [kde-unstable], some kde stuff not yet compiled against new qt5 version...

**Comment by tsujan** [comment]
>  if you are on [kde-unstable], it is likely kvantum-qt5 would need a rebuild indeed.

Theoretically speaking, a rebuild shouldn't be needed because Kvantum doesn't use private Qt headers and is independent of KDE. However, KDE *itself* may not recognize Qt plugins when it's in a transition state.

**Comment by ArchangeGabriel** [comment]
`[kde-unstable]` is not limited to KDE program, it also contains next Qt version (5.10 currently). Or are you saying that rebuilding `kvantum` for Qt 5.10 wouldn’t be needed?

**Comment by tsujan** [comment]
> Or are you saying that rebuilding kvantum for Qt 5.10 wouldn’t be needed?

I always rebuild Kvantum when Qt's second version number changes but Kvantum always works *before* the rebuild because it doesn't depend on private headers. Qt 5.10 shouldn't break the current Kvantum build, unless the upgrade to 5.10 isn't complete yet (for example, when `qt5-x11extras` is still 5.9).
