### ISSUE TITLE
Issue with KvArcDark in Dolphin

### ISSUE THREAD

**Issue by tenten8401** [tsujan/Kvantum#175]
When applying KvArcDark I get an odd issue with the disk space progress bar in Dolphin:
![image](https://user-images.githubusercontent.com/6174343/35225186-97e49208-ff55-11e7-914d-f0e272a51a4c.png)

**Comment by tsujan** [comment]
yes, that was an old problem and is already fixed in the latest git version:

![dolphin](https://user-images.githubusercontent.com/981076/35226447-98d6b826-ffa0-11e7-8726-197e7fbe33d7.png)

Please try the latest git if possible, although I'll make a new release soon.

**Comment by tenten8401** [comment]
My bad. This can be closed now, but I can't do it from email.

**Comment by tsujan** [comment]
Thanks for the confirmation! It was about some fonts like Noto. I'll test it again with Noto to be sure.

Closing for now.
