### ISSUE TITLE
Mouse-over artifcats in toolbars

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#176]
In the following screen shot (of Qt Designer) I have let the mouse hover over the 4 rightmost icons.

![kvantum-toolbar](https://user-images.githubusercontent.com/1141694/35749211-c26ff2f0-0848-11e8-992b-b8fb1ae1819c.png)

A similar thing is also happening to the menubar - it was a daker colour, and then becomes lighter. 

This is all under GNOME shell with X.org

**Comment by tsujan** [comment]
It's most probably caused by what I call "the hover bug". I've included some workarounds for it but it's worse than that. There are several reports on the Qt bug tracker, some of which are fixed and the rest are simply denied.

To reproduce it with Qt designer, right click on a toolbar button and then close the context menu by clicking somewhere else. The problem isn't specific to Kvantum but it can't be easily seen with Fuison, for example.

BTW, wasn't you the first developer who reported this problem on the Qt bug tracker?

**Comment by CDrummond** [comment]
No, when I reported the bug it was that buttons stated in the hover state after then menu was pressed. All I did was hover the mouse over - no presses. And the menubar is affected too.

I first noticed the issues with Cantata. If I start Cantata using KvAmbiance, the background of the time label (on the far right) is lighter than the rest of the toolbar. If I switch windows an back its gone, until I hover over the label.

I don't recall seeing this issue with KvAbiance before - so it _might_ be a GNOME shell issue. I thought it was my old Kvantum, so I updated to master, and same issue.

**Comment by tsujan** [comment]
> No, when I reported the bug it was that buttons stated in the hover state after then menu was pressed.

I remember that but, IMO, it's just one example of a general problem Qt5 has with states. The problem in question has been denied/ignored, although I can reproduce it with all style plugins (in the [above-mentioned way](https://github.com/tsujan/Kvantum/issues/176#issuecomment-362677657)). I opened https://bugreports.qt.io/browse/QTBUG-63806 just to give Qt devs an undeniable example but, except for adding a useless label (P3: Somewhat important), nothing has been done.

> I don't recall seeing this issue with KvAbiance before - so it might be a GNOME shell issue.

I can't reproduce it either -- under LXQt, KDE or Gnome-Shell. However, my installed Gnome-Shell is old. Could you test under an environment other that Gnome-Shell or similar GTK DEs?

**Comment by tsujan** [comment]
An hour ago, I upgraded gnome-shell to V3.26.2 and still couldn't reproduce the problem. I tried xorg as well as wayland. The Qt version is 5.10.0 (previously, on the machine with gnome-shell, it was 5.9),

Since KvAmbiance has no state-change animation, Kvantum can't be the cause. It's also unlikely that gnome-shell can affect Qt apps. If it was a driver issue, you should see it in non-Qt apps too. The cause should be related to Qt but, maybe, not Qt itself.

I'm very suspicious of the `QT_QPA_PLATFORMTHEME` you use.

**Comment by CDrummond** [comment]
Think I know what the issue is now. I've been using Ubuntu's new 'communitheme' - which is the new community developed GNOME session and Gtk theme that _might_ be default for 18.04 (but probably not, as its not yet complete). This is the one I talked to you about creating the Kvantum theme for.

Now, as I use QGnomePlatform QPA theme - this tries to set a matching Kvantum theme, and falls back to Adwaita-Qt if it can't find one. For communitheme, there is no matching Kvantum theme. So, what is happening is that QGnomePlatform theme is setting Adwaita-Qt as the apps theme, I start my apps with `--style kvantum` (to test with). This then sets the apps to use Kvantum. I _think_, however, that as Adwaita-Qt has been applied before Kvantum was set, that the Adwaita-Qt theme _might_ still have some event filter, or colour settings, still being applied.

If I run GNOME shell using the standard Ubuntu session, then Ambiance is set as Gtk theme, QGnomePlatform sets Qt theme to Kvantum with KvAmbiance - and all is OK.

So, sorry think this is not in fact a Kvantum issue - if anything its probably an Adwaita-Qt issue. Not sure there is much Kvantum can do, especially if its an eventFilter still being used from Adwaita.

Sorry for wasting your time. I'll close this issue.

**Comment by tsujan** [comment]
> This is the one I talked to you about creating the Kvantum theme for.

And for which I'll make a matching Kvantum theme.

> I think, however, that as Adwaita-Qt has been applied before Kvantum was set, that the Adwaita-Qt theme might still have some event filter, or colour settings, still being applied.

It may not be the *theme* but the Qt platform integration *plugin* (QT_QPA_PLATFORMTHEME) that causes this problem. I still don't know which source provides the plugin and which one is the theme but will investigate that later.

> especially if its an eventFilter still being used from Adwaita

Which would mean a bad `QStyle::unpolish()`.

**Comment by CDrummond** [comment]
AFAICT, the communitheme is not yet ready for a matching Kvantum theme - things are still a little in flux. But, it does look nice :-)

While I can't 100% guarantee the fault is **not** in QGnomePlatform, I'm pretty sure it is not. As stated, if I set the Gtk theme to Ambiance, then KvAmbiance is automatically set and there are no issues. It's only if the system has chosen Adwaita-Qt, but then the app (via --style) chooses Kvantum is there an issue.

My guess is that you are correct, with the `::unpolish()`
