### ISSUE TITLE
Kvantum has fuzzier font rendering compared to Breeze

### ISSUE THREAD

**Issue by flipwise** [tsujan/Kvantum#177]
Hello there,

first off all thank you for this really nice theme engine. I've been trying it out with a KvantumAdapta
theme, but noticed that using Kvantum has a slightly negative effect on font rendering quality. Fonts are rendered a bit fuzzier and a bit darker than with Breeze. I've attached two screenshots here. The difference isn't really that big, but hopefully you can see it. I'm also not sure if it has anything to do with the test environment, but I'd be happy to test the issue out.

Breeze:
![screenshot_20180204_162848](https://user-images.githubusercontent.com/26850445/35779660-dcca66ae-09c8-11e8-8440-1fe85e9c637d.png)
Kvantum:
![screenshot_20180204_162934](https://user-images.githubusercontent.com/26850445/35779659-dcadae6a-09c8-11e8-85cd-8eda51b37f9b.png)

**Comment by tsujan** [comment]
Oh, that depends on the Kvantum *theme* you use. Kvantum can define much more text colors than Breeze can. For example, its text color can have alpha or shadow. Each theme defines its own text colors.

**Comment by tsujan** [comment]
As another example, see the tab text colors of this Kvantum theme (see the image full-size):

![theme](https://user-images.githubusercontent.com/981076/35780144-979acc1c-09ec-11e8-81e6-76729eea1e60.png)

**Comment by flipwise** [comment]
Oh, I apologize, you right. I just tried out the Arc theme and the fonts are rendered as well as with Breeze. It's the KvAdapta theme that has some weird setting that makes fonts fuzzy. Thank you!

**Comment by tsujan** [comment]
>  It's the KvAdapta theme that has some weird setting that makes fonts fuzzy.

Some of Kvantum themes are fair clones of GTK themes and I made them because Kvantum's good users wanted them under GTK environments. `KvAdapta` was made to look like (an old version of) `Adapta`; hence those pale colors.

Most Kvantum users like GTK-like themes but I prefer and use the other kinds of Kvantum themes and, once in a while, change the active theme here.

**Comment by flipwise** [comment]
No, no, it's not about text color at all actually, but about font rendering. I don't know how to describe it best, but with KvAdapta it almost looks as if subpixel rendering is disabled or something. It's very subtle, but if you check those two screenshots above you can see that, for example, "V" in "Vaults" is fuzzier with KvAdapta. What I mean by fuzziness is that the two lines that make up the letter "V" should just be two straight and sharp lines, but if there is fuzziness, that means that it looks as if there are some pixels around those lines. The fonts are more sharp/crisp with Breeze or some other Kvantum theme.

**Comment by tsujan** [comment]
@flipwise That has nothing to do with "font rendering". As I mentioned above, the base text color of KvAdapta has *alpha*: it is NOT black but `#000000c8`.

**Comment by CDrummond** [comment]
But, is using alpha here on the text a good idea? If it makes the rendering worse, then why not use a grey colour for text as opposed to using alpha? At least in this instance it would improve the rendering.

**Comment by flipwise** [comment]
I wanted to show you two Kvantum themes with the same text color, but I can't find really a match. What I've found though is that "Kv" prefixed themes have fuzzy font rendering (or just don't respect system settings), whereas others don't. Here's an example of "KArc" vs "Arc" theme. With the KArc theme you can distinctly see there are pixels around fonts which makes them look fuzzier. I know it looks like it's just the text color that's different, but the rendering is also changed; it reminds me of when subpixel rendering or lcdfilter are turned off.

Arc Kvantum theme:
![screenshot_20180204_194534](https://user-images.githubusercontent.com/26850445/35781655-cfc6dec6-09e4-11e8-878f-bbb601a9fb42.png)
KArc Kvantum Theme
![screenshot_20180204_194555](https://user-images.githubusercontent.com/26850445/35781653-cfa8e2cc-09e4-11e8-8e86-6ae112ef6afc.png)

But this might actually be a much better example because the fonts just might be of the same color. 

KvArcDark
![screenshot_20180204_200055](https://user-images.githubusercontent.com/26850445/35781778-64968a3c-09e6-11e8-905d-e2822b589f5b.png)
ArcDarker
![screenshot_20180204_200118](https://user-images.githubusercontent.com/26850445/35781779-64b1344a-09e6-11e8-827e-605febd18d83.png)

Can you notice that the fonts are more crisp with the "ArkDarker" theme? Here is one spot where you can notice the pixel distortion: look at "Open New Window". Now look at the letter "N" in "New". Get really close to the screen and can you see that it looks as if there are transparent-ish pixels to the left of "N", whereas that doesn't happen with "ArcDarker"? Or also notic how jagged the first line that makes "W" in "Window" is with KArcDark. 

I hope I explained it as well as I could have. I see these things from pretty far away because my eye is very sensitive to it, but if you've not dabbled into it before, you need to get really close to see that there is a difference.

**Comment by tsujan** [comment]
This isn't about eye sensitivity but is a trick your mind does to you. I think you've got a little obsessive and don't want to accept the facts I mention again and again. I give you just one more example:

The menu-item text color is `#5c616c` with Arc, while it's `#000000c8` with KvArc -- the latter color has *alpha* = *translucency*

I always encourage users to tell me about probable problems; bug reports are always welcome. However, this isn't a bug; Kvantum has no special "font rendering" of it own but, contrary to Breeze, it can have translucency with text. When a text is translucent, it might look just a little "blurry".

And, for the record, no "V" consists of straight lines. All "Vs", on all monitors, consist of tiny rectangles called "pixels". Use a magnifier and you'll see that!

**Comment by flipwise** [comment]
Hmm yes, it's a design choice and we'll have to agree to disagree then that adding translucency to text is a good idea. I still think that the evidence shows that it makes the fonts look worse, but there are Kvantum themes which don't use it so it's not that big of a deal.

**Comment by r-o-o-t-y** [comment]
i think there should be an option to turn it on and off (or have kvantum calculate the difference between a font with alpha compositing and without)... but there's a glaring difference, however small it may be to the untrained (or indifferent) eye

and no i _**don't**_ think flipwise's mind's playing tricks on him

**Comment by tsujan** [comment]
Kvantum is highly configurable. You could change everything, including font colors. Please read the documentation or, at least, the explanations Kvantum Manager provides!

>  it's one of the main reasons i still use breeze instead of a kvantum theme

You have right to use anything you like. I'll get nothing if you use Kvantum, as the developer of Breeze will get nothing if you use Breeze. Most open-source developers do coding because it's fun. There are some people who enjoy their work; there are others who don't.

**Comment by r-o-o-t-y** [comment]
Yeah I'll check out the manual, thanks for the tip.

> I'll get nothing if you use Kvantum, as the developer of Breeze will get nothing if you use Breeze.

That's not exactly true, is it? Because if users overwhelmingly favor for example, Breeze, Breeze is going to garner more support, from users and developers alike.

> Most open-source developers do coding because it's fun. 

Debatable. A lot of open-source software is geared toward commercial application.

> There are some people who enjoy their work; there are others who don't.

Neither here nor there?

**Comment by flipwise** [comment]
Maybe this suggestion to be able to disable text translucency for each theme would actually be really nice to implement. 

Kvantum definitely beats out Breeze in terms of how many options it offers and this would make it even better. It's also a matter of just looking better than Breeze then and while some themes definitely do beat Breeze, this issue with how texts look like is a bit of a hindrance. Also I should add the argument that forcing this translucency option also necessarily results in a discrepancy between how text looks like in Qt and GTK apps, and the goal is to have it look as uniform as possible.

**Comment by tsujan** [comment]
> That's not exactly true

It's true for me. If someone likes it when I freely share my work with him/her, it'll be good. If not, it won't concern me.

> Debatable

Not to me. I know why I do coding: because it's fun. Honestly, I wouldn't write a single line of code if it wasn't fun.

It's really not important to me whether 99% of Qt users like Breeze or even Fusion. According to *my* taste, it's a shame that they're so elementary and ugly. Even QtCurve wasn't something I could tolerate. So, I made Kvantum and, of course, shared it with others.

Please also note that I made Kvantum *configurable* not for myself (why should I?) but for *users*.

**Comment by tsujan** [comment]
Oh, there's something else too:

> and the goal is to have them look as uniform as possible.

It was never my goal; I mean it! I wanted to have a highly configurable style engine, so that I could make whatever theme I like with it. When I saw that others started to do the same thing only a month after I started Kvantum, I realized that some people might have the same ideas.

The ability to support GTK-like themes is just a byproduct of Kvantum's flexibly. It has never been the goal -- most GTK themes aren't elegant to my eyes.

**Comment by NickLion** [comment]
@flipwise 
> No, no, it's not about text color at all actually, but about font rendering.
That's both true and untrue. I have the same effect, if text is rendered with alpha (translucent) then subpixel antialiasing is off and grey-scale antialiasing is used instead. I'm not sure where the problem is. But it is about font rendering and color (it's alpha component).

**Comment by flipwise** [comment]
Ah, it's good to know I wasn't crazy and that it did have *something* to do with font rendering, whatever the real cause and the mechanism behind it were. 

If the issue of GTK and Qt uniformity was rejected (even though most users probably want this), then the issue that the Kv_ themes do not respect the user's choice for subpixel rendering should be raised .

Does using alpha necessarily have to result in messing with subpixel rendering or is this some sort of a bug? 

Either way it would be really useful to have an option to turn off alpha for each theme.

**Comment by NickLion** [comment]
That's not Kvantum problem. You can create simple Qt application, set palette with alpha less than 255 and you'll see same effect. This is somewhere in Qt, FreeType or between them. I'm not sure. It may be even QPA dependent.

**Comment by flipwise** [comment]
That is good to know, the problem should be reported to Qt then, although for example I reported a problem with kerning and which has been confirmed, but sitting for the past few months.

Hence why not add a toggle to Kvantum Manager to set alpha to 255, that is, disable translucency. I don't do coding, but I reckon it shouldn't be so difficult and it's also very much in line with what Kvantum is trying to do - give the users more theming power *at their fingertip*.

I also noticed that you reported this before, but with no result. @tsujan this is three people now that saying they see text translucency impacts font rendering. What's more, @NickLion has gone a step further and done research to confirm these suspicions. It would be really helpful to have an easy way of configuring this, instead of having to edit theme files.

**Comment by tsujan** [comment]
>  @tsujan this is three people now that saying they see text translucency impacts font rendering

Three users see the difference between alpha and complete opaqueness as an extremely important issue (otherwise, this discussion wouldn't become so long). First they said it was a Kvantum problem; now they think it's a Qt problem. I respect their opinions and experiments but see no problem to solve.

If you like a Kvantum theme but not its translucent font colors: Kvantum manager → Configure Active theme → press Save button and then, change font colors to your taste.

**Comment by r-o-o-t-y** [comment]
> If you like a Kvantum theme but not its translucent font colors.

Stop it with the strawman already :D The issue at hand is not whether anyone here likes or dislikes translucent font colors, but rather the fact that the fonts get ruined when they're put through Kvantum (regardless of if it's Qt's fault). And telling people to choose different font colors to avoid the problem (and it **_is_** a problem) is as useful a piece of advice as is telling them to buy a Mac. In other words, not very.

**Comment by tsujan** [comment]
> but rather the fact that the fonts get ruined

That's my point: it isn't a "fact" but an exaggeration. Instead of thinking in terms of "ruins", "buying Mac" or "short of perfection", one can objectively and simply expect a difference between `#31363b` and `#000000c8`.

**Comment by tsujan** [comment]
@NickLion 
I really like to see Qt dev's reaction. If you see this as a bug, would you please report it at the Qt bug tracker and attach a simple code with a translucent text color? The reason why I don't do so is just that I don't believe there's a bug.

**Comment by tsujan** [comment]
And please don't give them a link to this page because they might get confused ;) Attaching a simple code would be enough.
