### ISSUE TITLE
Translucent Windows option breaks Dolphin's video previewing 

### ISSUE THREAD

**Issue by flipwise** [tsujan/Kvantum#178]
Description: Dolphin only shows a black square when playing video in its Information Panel view if the Translucent Windows option is turned on for any chosen Kvantum theme. 

Steps to reproduce: 
1. Turn on Translucent Windows (bug reproducible even if opacity decrease is set at 0%)
2. Turn on Information Panel in Dolphin (shortcut: F11)
3. Try playing whichever supported video file in the Information Panel

Effect: Audio still comes out, but there is no video.

Kvantum version: 0.10.5-1

Video works with the Translucent Windows option turned off or with Breeze.

**Comment by tsujan** [comment]
That's an old problem Dolphin has with window translucency. I remember that it was reproducible with oxygen-transparent, QtCurve and Bespin too, sometimes randomly.
