### ISSUE TITLE
error: ‘nullptr’ was not declared in this scope

### ISSUE THREAD

**Issue by DukhiAatma** [tsujan/Kvantum#179]
error: ‘nullptr’ was not  declared in this scope
hi, i am new to linux and just migrated from windows a few hours ago. i'm getting  this error while executing make command 

error: ‘nullptr’ was not declared in this scope

i followed this tutorial : https://stackoverflow.com/questions/16509932/using-qt-creator-c-11-nullptr-is-keyworded   but there is still same error.

**Comment by tsujan** [comment]
Your g++/gcc version is too old. You need, at least V5.3.1 and even with V5.3.1, you could compile the Qt5 Kvantum *only with qmake*, not with cmake (that's the way I make deb package for Ubuntu LTS 16.04).

If your distro is so old, you probably won't need the Qt5 Kvantum but its Qt4 version. Please read the file `INSTALL` to know how you could do so.

**Comment by DukhiAatma** [comment]
Actually I'm using kubuntu 16 latest version. I also did dist-upgrade

**Comment by DukhiAatma** [comment]
root@Kubuntu:$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@Kubuntu:$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tsujan** [comment]
> root@Kubuntu:$ gcc --version......

Your g++ version is enough for compiling Kvantum against Qt5. I just tested on VirtualBox with Kubuntu LTS and Kvantum was successfully compiled with:
```
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake && make
```
You could also use the deb package I attach for Ubuntu LTS [in the page of the latest release](https://github.com/tsujan/Kvantum/releases/tag/V0.10.5).

**Comment by DukhiAatma** [comment]
thank you for helping !!!!!!! and thanks for making cool stuff !!!!

**Comment by tsujan** [comment]
You're welcome.

I always try to support Ubuntu/Kubuntu LTS and add a deb package for it with every new release, as far as possible.

The next release will be published soon and, with it, I'll add the last deb package for Ubuntu 16.04. After that, (K)Ubuntu LTS 18.04 will come.
