### ISSUE TITLE
Ubuntu 14.04.2 Installation of kvantum 0.8.15-11 deb with QApt removes video driver packages

### ISSUE THREAD

**Issue by wolfland** [tsujan/Kvantum#18]
With the release of Ubuntu 14.04.2 iso's on 20150219 comes a new 3.16 version of the kernel and
new graphics stack. Unfortunetly Canonical decided not to make the 3.16 kernel part ot the normal update process to 14.04.2.

This leaves users to either completely rebuild their distro's from scratch using the new 14.04.2 iso's with the 3.16 kernel and graphics stack or perform a risky manual update process if they want to include the 3.16 kernel and graphics stack in any existing distro installations. 

This means that anyone making debs for 14.04.2 will now have to deal with both kernel versions (e.g. 3.13 and 3.16) since the 14.04.2 kernel update is optional for existing installations but included in the new iso's.

After doing the manual install of the 3.16 kernel and graphics stack on my 14.04.2 KDE distro I saw the new Kvantum 0.8.15-11 version and proceeded to install it using QApt like I have in the past.

Unfortunately QApt decided to uninstall the mesa video driver package associated with the 3.16 kernel and install the 3.13 version instead probably because the deb was built against the 3.13
kernel and graphics stack which trashed the machine.

After more than a few cuss words I was able to get the correct driver packages back on the machine
and it is working ok again. 

This is going to cause a "nightmare from hell" for anyone trying to make debs for Ubuntu 14.04.2 as
you will not be able to tell if the target machine has the 3.13 kernel and graphics stack or the 3.16
kernel and graphics stack at build time(e.g. I assume you will have to build 2 debs one for each kernel package).

 Thanks again Canonical !!!.

From my perspective I guess the safe thing to do is to compile from source for the mean time for
new versions of Kvantum as I certainly don't expect you to build 2 different debs.

I am already building from source for my 32bit laptop so it won't be a hassle to do the one 64bit
machine with KDE as well.

I opened this issue for information purposes so that you would know that this would come up with
Ubuntu 14.04.2 users that have either installed from 14.04.2 iso's or done the manual upgrade from
the 3.13 kernel to the 3.16 kernel and graphic stack.

If for some reason you decided to make 2 debs or find some more creative way to solve the problem
and need me to do some testing l will be glad to help.

Thanks,
WolfLand

**Comment by tsujan** [comment]
Thanks for telling me about that!

> Unfortunately QApt decided to uninstall the mesa video driver package associated with the 3.16 kernel...

That's really strange because:
(1) I built the deb package with kernel 3.16 from Debian Testing;
(2) The package has no kernel dependency.
The mesa dependency is any version of libgl1-mesa-glx and all version dependencies have the >= sign.

I would be grateful if you tell me exactly which dependency (in the control file of the deb package) caused the mesa uninstallation. You could find it without making any change to your sytem by just trying to intall the dependencies one by one (without the actual installation).

But before that, please see if the same thing happens when you try to install the deb package with gdebi-kde or with "sudo dpkg -i". Isn't QApt buggy?

Waiting for your reply!

**Comment by tsujan** [comment]
> ...the safe thing to do is to compile from source for the mean time for new versions of Kvantum...

I forgot to add that Kvantum's dependecies haven't changed since v0.8.6.

**Comment by wolfland** [comment]
Tsujan,

           I should have been more clear in my problem description. What 
actually happened was
           that QApt just decided to download and install the 
libgl1-mesa package without even
           prompting yes or no to allow the change. It also did not list 
any dependency change
           as being required. I have not seen this before when using 
QApt  to install Kvantum and
           have never seen anything like this with gdebi or any other 
package app. I think you are
           right on the QApt buggy diagnosis.

           I will try the dpkg command or gdebi-kde tomorrow before I 
get tied up with the next
           14.04.2 kernel upgrade I have to do and let you know what 
happens..

          The package I had to reinstall was 
"libegl1-mesa-drivers-lts-utopic" and I had to use
          "sudo apt-get install -f" to get it to reinstall due to 
complaints about unsatisfied dependencies.

          I decided to go ahead and compile from source for both 32bit 
and 64bit machines just to be
          safe and everything is working fine.

          Hopefully dpkg or gdebi-kde will at least prompt yes/no before 
doing anything rash but at least
          I know how to recover if something weird happens again.

          I will certainly refrain from using QApt in the future as it 
definitely can't be trusted.

Thanks Again
WolfLand

**Comment by tsujan** [comment]
It's quite possible that during your manual installation of kernel-3.16 on Ubuntu, some dependency conflicts arose, which resulted in QApt's wrong behavior later. I searched in http://packages.ubuntu.com and couldn't find any dependency of kvantum_0.8.15-11_amd64.deb that could create a conflict in Utopic or Vivid. However, I wait for your tests.

**Comment by tsujan** [comment]
A better guess:
your active repository was Trusty while you manually installed linux-image-3.16.0 and its related packages from Utopic and QApt correctly tried to downgrade those packages when you started to install Kvantum's deb package with it. If so, QApt would do the same thing with any other package with the libgl1-mesa-glx dependency.

**Comment by wolfland** [comment]
Tsujan,

           I installed gdebi-kde and used it to install the 
Kvantum_0,8,15-11_amd64,deb file.  No
           dependencies were found by gdebi and everything worked as 
intended.

           What ever went wrong yesterday did not repeat itself.

           I also did a dpkg --list | grep utopic to ensure the update 
to the 3.16 kernel and graphics stack
           pulled in the correct "trusty" versions and it did(see 
attached file).

           I wonder if there is some "transitive" dependency issue that 
does not readily show up or if
           QApt just went nuclear for some unknown reason. Sometimes a 
dependency issue can be
           several or more packages deep and not known about until a 
problem like this occurs. I wish
           QApt would have at least recognised that something was wrong 
and warned or prompted
           so that the problem could have been caught and looked at 
instead of just downloading files
           and installing them without warning.

           If I get a chance either today or tomorrow I will try and 
live boot a 14,04.2 KDE 64bit in one
           of my test machines and install Kvantum with either gdebi-kde 
or dpkg and see if I can get
           the problem to occur again in an "native" 3.16 kernel build. 
Maybe there is an unknown
           transitive dependency somewhere that was corrected when I 
fixed my machine. I did have
           to use sudo apt get install -f because of unsatisfied 
dependencies after the initial problem
           occured so if the problem is fixed in my upgraded install it 
makes sense that it would not
           happen again when I tried to reinstall the Kvantum deb today.

           In the future I will stick to gdebi-kde since I have used 
it's gnome counterpart for many years
           and it has never let me down.

           I will let you know what happens with the live 14.04.2 test.

Thanks again
WolfLand
On 02/22/2015 03:10 AM, tsujan wrote:
>
> It's quite possible that during your manual installation of 
> kernel-3.16 on Ubuntu, some dependency conflicts arose, which resulted 
> in QApt's wrong behavior later. I searched in 
> http://packages.ubuntu.com and couldn't find any dependency of 
> kvantum_0.8.15-11_amd64.deb that could create a conflict in Utopic or 
> Vivid. However, I wait for your tests.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/tsujan/Kvantum/issues/18#issuecomment-75424959>.
>


rc  libegl1-mesa-lts-utopic:amd64               10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the EGL API -- runtime
rc  libgbm1-lts-utopic:amd64                    10.3.2-0ubuntu1~trusty2                              amd64        generic buffer management API -- runtime
rc  libgl1-mesa-dri-lts-utopic:amd64            10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the OpenGL API -- DRI modules
rc  libgl1-mesa-glx-lts-utopic:amd64            10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the OpenGL API -- GLX runtime
rc  libglapi-mesa-lts-utopic:amd64              10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the GL API -- shared library
rc  libgles1-mesa-lts-utopic:amd64              10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the OpenGL|ES 1.x API -- runtime
rc  libgles2-mesa-lts-utopic:amd64              10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the OpenGL|ES 2.x API -- runtime
rc  libopenvg1-mesa-lts-utopic:amd64            10.3.2-0ubuntu1~trusty2                              amd64        free implementation of the OpenVG API -- runtime
rc  libwayland-egl1-mesa-lts-utopic:amd64       10.3.2-0ubuntu1~trusty2                              amd64        implementation of the Wayland EGL platform -- runtime
rc  libxatracker2-lts-utopic:amd64              10.3.2-0ubuntu1~trusty2                              amd64        X acceleration library -- runtime
ii  linux-generic-lts-utopic                    3.16.0.30.23                                         amd64        Complete Generic Linux kernel and headers
ii  linux-headers-generic-lts-utopic            3.16.0.30.23                                         amd64        Generic Linux kernel headers
ii  linux-image-generic-lts-utopic              3.16.0.30.23                                         amd64        Generic Linux kernel image
rc  xserver-xorg-core-lts-utopic                2:1.16.0-1ubuntu1.2~trusty2                          amd64        Xorg X server - core server
rc  xserver-xorg-lts-utopic                     1:7.7+7ubuntu2~trusty1                               amd64        X.Org X server
rc  xserver-xorg-video-intel-lts-utopic         2:2.99.914-1~exp1ubuntu4.2~trusty1                   amd64        X.Org X server -- Intel i8xx, i9xx display driver
rc  xserver-xorg-video-modesetting-lts-utopic   0.9.0-1build1~trusty1                                amd64        X.Org X server -- Generic modesetting driver
rc  xserver-xorg-video-openchrome-lts-utopic    1:0.3.3-1build2~trusty1                              amd64        X.Org X server -- VIA display driver
rc  xserver-xorg-video-vmware-lts-utopic        1:13.0.2-3ubuntu1~trusty1                            amd64        X.Org X server -- VMware display driver

**Comment by tsujan** [comment]
Yes, a (transitory) dependency problem is an acceptable hypothesis. However, I'm not sure that QApt did something wrong (see my last comment): manual kernel upgrading in distros like Ubuntu is a tricky task.

> In the future I will stick to gdebi-kde...

I recommend the straightforward command "sudo dpkg -i PACKAGE(S)" for downloaded deb packages; the Python dependency of gdebi-kde sometimes gets broken, at least in Debian.

**Comment by wolfland** [comment]
Tsujan,

            J just tested the Kvantum 0.8.15-11 deb on a native 3.16 
14.04.2 KDE iso running in live
            mode. Kvantum installed fine with dpkg -i once the Qt5 
dependencies were satisfied and
            worked as intended. I think we can write this one off due to 
QApt.

           I think I will stick with dpkg -i like you recommend in the 
future and stay away from the
           package installers.

Thanks again,

WolfLand

**Comment by tsujan** [comment]
Thank you for the time and effort you put into this! So, I close this issue but feel free to add further comments to or even reopen it if needed.
