### ISSUE TITLE
No "ToolbarLineEdit" section

### ISSUE THREAD

**Issue by 2yangk23** [tsujan/Kvantum#180]
There is an option to style ToolbarButton, but no such option for ToolbarLineEdit.

Example:
![screenshot_20180218_141600](https://user-images.githubusercontent.com/7710340/36357693-8316d036-14b6-11e8-97d6-432eb18f19ff.png)

**Comment by tsujan** [comment]
I know and vaguely remember that there was a serious issue about that. Such things aren't supported by Qt; I've enforced them in Kvantum.

I'll look into it later and will tell you about the result. Thanks for mentioning it!

**Comment by tsujan** [comment]
I remembered the problem:

"ToolbarLineEdit" would be useful for a light line-edit on a dark toolbar -- or conversely. However, the text of a line-edit isn't drawn by Kvantum and its color is always `QPalette::Text`. If (1) the line-edit was always reported as a widget to `QStyle` and (2) its text color was always determined by its widget palette, a "ToolbarLineEdit" would be possible. However, (1) and/or (2) may be contradicted by some apps and the result would be dark text on dark bg (or light text on light bg).

"ToolbarButton" is different; its text is drawn by Kvantum and there will be no dark text on dark bg (unless the app code has a bug).

And after all, your above screenshot is quite stylish ;)
