### ISSUE TITLE
Color variants for theme

### ISSUE THREAD

**Issue by NickLion** [tsujan/Kvantum#183]
This is not a real issue, just wishlist.

It'd be good to have different color variants of themes. Maybe make theme to be able to depend on color palette (but I know you don't want to make depends on kde, so unsure it's a solution, as I'm unsure is pure Qt palette full enough), maybe using something like https://github.com/KDE/svgmod. Or to have some list of css color variants for svg.

So, if you'll have time and inspiration, please consider this :)

**Comment by tsujan** [comment]
> So, if you'll have time and inspiration, please consider this :)

I'm afraid it's impossible -- It isn't about time; Kvantum is much more complex than that.

The colors you see are just partly those of `QPalette`. Kvantum mostly uses the colors of the SVG file. `QSvgRenderer` doesn't support `css` and even if it did, it would be useless for complex SVG gradients.

The colorization of symbolic icons by KDE/LXQt (dark on light backgrounds and conversely) is minimal; it requires an SVG file with a single, monochromic, flat shape (hence the word "symbolic").
