### ISSUE TITLE
Option to change themes using terminal

### ISSUE THREAD

**Issue by LedBass** [tsujan/Kvantum#191]
Hi, I just had an idea for an enhancement

Is it possible to add an option to change themes by invoking terminal commands? it would be great for some automation (E.g. changing themes according to the time of the day, a light one for day and a dark one for night)

I would do it my self if I had more C++ skills and submit a pull request my self

Thanks

**Comment by tsujan** [comment]
If you change the active theme with command line, the running apps should be restarted to see it because Kvantum doesn't interfere with them. IMO, it's the responsibility of the DE to deal with running apps.

Kvantum Manager doesn't have command-line options because I found no use for them. However, something like this can be useful. For example:
```
kvantummanager -set KvBeige
kvantummanager -add KvDarkRed konsole,qterminal
```
I'll try to do it when I find time.

**Comment by tsujan** [comment]
Done in the latest git version. Please check `kvantummanager --help`.

**Comment by CluelessTechnologist** [comment]
> Done in the latest git version. Please check `kvantummanager --help`.

Is there a reason why `kvantummanager --set THEME` requires a GUI? If I run it over SSH I get "cannot open display". I can run it in a terminal though and it doesn't seem to open any GUI.

I'm using Kvantum Manager 1.0.7  on Debian 12.

**Comment by tsujan** [comment]
> Is there a reason why kvantummanager --set THEME requires a GUI?

It doesn't. It uses only `QStringList`, `QDir` and `QSettings`.

> If I run it over SSH I get "cannot open display"

It maybe related to `getenv("XDG_CONFIG_HOME")`, `QDir::homePath()`, or something else related to Qt., but that's just a guess.

**Comment by CluelessTechnologist** [comment]
> EDIT: Most probably `QApplication` does that. It can be put after those command options in the code, but I'm not sure about probable side effects. Better safe than sorry...

So there is no way to run it without a display server when setting a theme? 
BTW I just tried `export DISPLAY=:0 && kvantummanager -set gruvbox-kvantum` via SSH but then kvantum-manager just opens on my host desktop without setting the theme.

**Comment by tsujan** [comment]
> but then kvantum-manager just opens...

It should. There's no `-set` option; it's `--set`. See `kvantummanager --help`

**Comment by CluelessTechnologist** [comment]
> > but then kvantum-manager just opens...
> 
> It should. There's no `-set` option; it's `--set`. See `kvantummanager --help`

Oh silly me. Now it works. So that's one possible workaround. Unfortunately that requires the host to have a working display manager though.
