### ISSUE TITLE
compilation on openSUSE TW

### ISSUE THREAD

**Issue by AndriusWild** [tsujan/Kvantum#194]
I tried to compile and got this error:

```
CMake Error at style/CMakeLists.txt:5 (find_package):
  By not providing "FindQt5Svg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Svg", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
I tried  to install packages `sudo zypper in libx11 libxext qt5-base qt5-svg qt5-x11extras qt4 qt5-tools` 

but they don't exist in SUSE repos:

```
No provider of 'libx11' found.
'libxext' not found in package names. Trying capabilities.
No provider of 'libxext' found.
'qt5-base' not found in package names. Trying capabilities.
No provider of 'qt5-base' found.
'qt5-svg' not found in package names. Trying capabilities.
No provider of 'qt5-svg' found.
'qt5-tools' not found in package names. Trying capabilities.
No provider of 'qt5-tools' found.
'qt5-x11extras' not found in package names. Trying capabilities.
No provider of 'qt5-x11extras' found.
```

Do you know if they have different names in openSUSE by chance?
I have `libX11-6 libXext6 libQt5X11Extras5 libqt5-qtbase-devel libQt5Svg5 libqt5-qttools-devel libQt5X11Extras5` installed

Thanks in advace for any tips.

**Comment by tsujan** [comment]
I know that, in Fedora (which is RPM-based like OpenSUSE), the packages are:
```
gcc-c++ >= 5
libX11-devel
libXext-devel
qt5-qtbase-devel >= 5.7
qt5-qtx11extras-devel >= 5.7
qt5-qtsvg-devel >= 5.7
qt5-qttools-devel >= 5.7
```
I think the names are similar in OpenSUSE. Please find them by using the above-mentioned names and tell me if they are correct! I don't have OpenSUSE but like to add its required packages to the `INSTALL` file -- OpenSUSE being an important distro.

Actually, I didn't have Fedora either (my distro is Arch based) but a Fedora user kindly told me about those names.

**Comment by AndriusWild** [comment]
Installation of these packages fixed the issue:

> libqt5-qtsvg-devel
> libqt5-qtsvg-private-headers-devel
> libqt5-qttools-devel
> libqt5-qtbase-devel
> libqt5-qtx11extras-devel

Are are version 5.10 on Tumbleweed

**Comment by AndriusWild** [comment]
libext is libXext-devel and libXext6

**Comment by tsujan** [comment]
So, even in 2 RPM-based systems, the names are different! I'll add the info to `INSTALL`.

**Comment by tsujan** [comment]
BTW, Kvantum doesn't need `libqt5-qtsvg-private-headers-devel`.
