### ISSUE TITLE
Kvantum can work on MS Windows too

### ISSUE THREAD

**Issue by celibol** [tsujan/Kvantum#199]
KvAntum On Windows For QT Application

![kvantum](https://user-images.githubusercontent.com/202543/38877747-0effd3de-4268-11e8-851c-4b0d8fe0d5d0.png)

**Comment by tsujan** [comment]
Congratulations! I never thought it could work on MS Windows too. I guess you've made lots of changes to the code.

Why didn't you upload it to your github page?

**Comment by celibol** [comment]
No many code changes...

Only simply changes

**Comment by celibol** [comment]
![kvantum](https://user-images.githubusercontent.com/202543/38879210-7305ba62-426b-11e8-91e6-1f928d4f5e31.png)

**Comment by celibol** [comment]
It's source code and some other screenshot

https://github.com/celibol/kvantum-on-windows-with-QT

**Comment by celibol** [comment]
Thanks QT

Tyanks tsujan for kvantum
