### ISSUE TITLE
Increase popup menus padding without compositing

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#20]
Hello!

I'm trying to find a way to increase the padding of popup menus without compositing, already searched the documentation somewhat related, but without success. Is that possible? Or some frame specific setting not yet documented?

![Kvantum pop menus padding print](http://i.imgur.com/FHtruh0.png)

**Comment by tsujan** [comment]
Do you mean the horizontal space between a submenu and its main menu or the vertical space between menuitems?

The vertical space between menuitems can be adjusted with size.minheight (or even with text.margin.top and text.margin.bottom) under the MenuItem section.

The horizontal space between a menu and its submenu can be adjusted with menu_shadow_depth (General section), menu frame widths (Menu section) and a proper menu frame element ONLY IF compositing is available. Without compositing, the menu frame width could be 2px at most because a width greater that 2px could create ugly corners.

However, even without compositing, you could create a horizontal space INSIDE menus by adjusting text.margin.left and text.margin.right under the MenuItem section. And I think you mean that, don't you?

**Comment by franksouza183** [comment]
Thanks for reply!

I mean the horizontal space between the border (some possible frame.left?) And the menu item:
![Kvantum pop menus padding print](http://i.imgur.com/3gFz8L6.png)

**Comment by tsujan** [comment]
Thanks for the screenshot! Now I get what you mean;.

Checkboxes and radiobuttons don't obey "text.margin.left". They have a constant 2px distance from the menu frame, whose width is 2px at most without compositing.

I don't remember why I implemented that limitation. I'll try to make checkboxes and radiobuttons obey "text.margin.left" if there's no side effect.

It's now past midnight here. Tomorrow I'll consider that possibility (and some others). I'll tell you about it soon.

**Comment by franksouza183** [comment]
Many many thanx! And thank you for your hard work !!

**Comment by tsujan** [comment]
I forgot to tell you that there's still a way to make that space wider: you could use "frame=true" under MenuItem, give an invisible SVG rectangle to menuitem frames and adjust "frame.left" under MenuItem. Please test that too!

**Comment by franksouza183** [comment]
Yes, it works!

![Kvantum pop menus padding print](http://i.imgur.com/VeqpaKR.jpg)

Many thanx!!

**Comment by franksouza183** [comment]
Oh, looks like it is using the corners of the buttons, not the menuitem-normal-top/bottom/left/right ...

**Comment by tsujan** [comment]
I'm still awake  ;) I think your svg elements for menuitem frames aren't invisible in your last screenshot. You should first choose a name with "frame.element=NAME" under the MenuItem section and then do NOT draw any svg element for those frames or just draw invisible ones if you like.

**Comment by tsujan** [comment]
I mean, if you don't set "frame.element=menuitem", the PanelButtonCommand frames will be used because MenuItem inherits PanelButtonCommand. I think that's the problem with your menuitems.

**Comment by franksouza183** [comment]
Yes, perfect, I saw now that it is described in "Interior and Frames" section
on documentation, sorry, my fault ;)

**Comment by tsujan** [comment]
Not really your fault! Kvantum is very flexible and that flexibility may cause such mistakes, which even I have made sometimes ;)

As I saide above, I reopened this issue.

**Comment by franksouza183** [comment]
Oh, sorry, I did not get about the "reopen" ;) many thanx!

**Comment by tsujan** [comment]
I made a change to the code. Now checkboxes and radiobuttons on menuitems obey the value of "text.margin.left" under the MenuItem section (or "text.margin.right" for RTL). The space between them and the icon or text is governed by "text.iconspacing", as if they are icons themselves.

So, with the latest update, you won't need to add invisible frames to menuitems anymore. Just adjust "text.margin.left" as you like. Please test that and tell me about the result. If you use the deb package I put on kde-look.org, you'll have to wait until tomorrow for me to update it.

There's still another feature I have to consider, so I leave this issue open for now.

**Comment by franksouza183** [comment]
It seems ok:
![Kvantum pop menus padding print](http://i.imgur.com/ndNmyt3.jpg)

**Comment by tsujan** [comment]
Thanks for your quick test!
The other feature is about removing the 2-px limit on the menu frame width without compositing so that you could make the left blue strip of your menus wider if you like. But that will be really for tomorrow ;)

**Comment by tsujan** [comment]
I removed the 2-px limit from the menu frame thickness without compositing. Now horizontal and vertical menu frames can also have different thicknesses.

You could adjust the width of your blue menu stripe by changing "frame.left" (or "frame.right", which makes no difference) under the Menu section. Just remember that menu frames can't be invisible without compositing and that the widths of their right and left frames are always the same and equal to the maximum of "frame.left" and "frame.right".

You could close this issue if you're satisfied with the changes I made. And please don't forget to tell me the name of your theme if you upload it.

**Comment by franksouza183** [comment]
Wow, it works beautifully!
![Kvantum pop menus padding print](http://i.imgur.com/RtuxcC7.jpg)
Line width increased to 3px, just to test ( the width is really 2px, which coincidentally was the limit ). And ok, I'll tell you the download link so I upload, missing just a few refinements. Thanks for that! I will close the issue, for me it seems all ok.

**Comment by tsujan** [comment]
You're very welcome. Looking forward to your elegant theme!
