### ISSUE TITLE
KvAntum On Windows For QT

### ISSUE THREAD

**Issue by celibol** [tsujan/Kvantum#200]
Dark Theme
![kvantum](https://user-images.githubusercontent.com/202543/38878046-c02c8792-4268-11e8-81ca-02d3bbccf59f.png)

KvSimplicity
![kvantum](https://user-images.githubusercontent.com/202543/38878177-04b4dfd6-4269-11e8-8fa0-670d2679c573.png)

kvCurves3D
![kvantum](https://user-images.githubusercontent.com/202543/38878346-65a6f72a-4269-11e8-96e5-34ca31295a6d.png)

KvAdapta
![kvantum](https://user-images.githubusercontent.com/202543/38878617-0722f4b4-426a-11e8-8d6d-da78ce2183f1.png)

KvAdaptaDark
![kvantum](https://user-images.githubusercontent.com/202543/38878667-236b7c7c-426a-11e8-960a-71d60cea3b37.png)

**Comment by tsujan** [comment]
You could have attached the images to https://github.com/tsujan/Kvantum/issues/199. Please continue the discussion (if any) there. Thanks!

**Comment by patlecat** [comment]
@celibol 
Awesome stuff dude. Why are you not updating it anymore? This is what many Windows devs have been waiting for all their life!
