### ISSUE TITLE
Bugs render with Dolphin

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#202]
It's strange bug... 
This bug reproduced on KvAdapta and other themes
Step for reproduce:
- open Dolphin
- disable menubar (Ctrl+M)
- open Help - About Dolphin
Result > toolbar widget have bugged render

Video bug preview: https://youtu.be/AitYYSHfaD4
https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/51

**Comment by tsujan** [comment]
This should be a bug in Dolphin's code. Even if had time, I wouldn't think about a workaround because it would hide the issue. Please report it to Dolphin's developers!

**Comment by tsujan** [comment]
And please note:

As a workaround, you could set `inactive.highlight.color` to a color slightly different from `highlight.color` in your themes.

There's a unreported Qt bug about inactiveness. Dolphin somehow triggers it. Making the inactive highlight color (slightly) different from the highlight color hides that bug.

**Comment by varlesh** [comment]
Thanks for solution :) different `inactive.highlight.color` & `highlight.color` solved bug render... But i'm not understand why disabled style for toolbar with openned "About" window

**Comment by varlesh** [comment]
normal:
![image](https://user-images.githubusercontent.com/8083855/39095543-4b34eb02-4653-11e8-9477-f84c662d818d.png)
open "About Dolphin" window:
![image](https://user-images.githubusercontent.com/8083855/39095559-8417c2b4-4653-11e8-9c8a-e308156164d1.png)

See on "normal" used color `#303030` and shadow. But when open "About Dolphin" - style disabled and used background color `#212121` without shadow

**Comment by varlesh** [comment]
i'm change and this not solved problem:
```
[GeneralColors]
highlight.color=#338dd6
inactive.highlight.color=#338dd5
```

- Kvantum 0.10.5
- Qt 5.10.0
- KDE Frameworks 5.45
- KDE Neon distro

**Comment by tsujan** [comment]
Kvantum can't make magic and fix a Dolphin bug ;)

I may just include a workaround for the Qt bug in Kvantum (Qt's inactive state is a mess when active and inactive highlight colors are the same) but Dolphin's developers should know why their app has such a weird behavior when the toolbar is drawn by an SVG element. Definitely not mu job.

**Comment by varlesh** [comment]
On Breeze engine this not reproduce.... and i think KDE Devs refuse fix that 
You know KDE Devs :)

**Comment by tsujan** [comment]
> On Breeze engine this not reproduce

And it shouldn't. Since when does Breeze draw widgets with SVG elements?! Breeaze/Fusion can never be a point of reference for Kvantum.

The problem is that some developers think their apps are OK whenever they look OK with "usual" style engines like Fusion/Breeze, while they do wrong things in their codes. Kvantum *reveals* those wrong things.

**Comment by varlesh** [comment]
https://bugs.kde.org/show_bug.cgi?id=393394

**Comment by tsujan** [comment]
I'll just add a workaround for the Qt bug and explain that bug in a comment inside the code without reporting it -- you know Qt developers ;) I'll tell you when it's done. The Dolphin bug should be fixed by Dolphin's devs.

**Comment by varlesh** [comment]
Ok.
@tsujan will be good if you explain technical details for Dolphin dev if needed (on kde.bug tracker)...
because i'm not programmer

**Comment by tsujan** [comment]
The workaround is here: https://github.com/tsujan/Kvantum/commit/6d25e5d40fcfca142ada0f6afc8cb78b76497593

With it, you won't need to change anything in your themes. Please note that Dolphin's magic isn't related to this but it can be tolerated now.

Thanks for reminding me of that old Qt bug!
