### ISSUE TITLE
Kvantum Linux Mint 18.2 Cinnamon Edition

### ISSUE THREAD

**Issue by sheilambadi** [tsujan/Kvantum#204]
How can I use Kvantum in Linux Mint 18.2 Cinnamon edition. 
This is what I get while using Kvantum Manager
![kvantum](https://user-images.githubusercontent.com/25798203/39257728-e51fdb28-48ba-11e8-9947-d98385debb0b.png)

**Comment by tsujan** [comment]
Please read the file `INSTALL`.

Please also note that Kvantum is for *Qt apps*, while Cinnamon is a GTK environment. So, you need a tool, like `qt5ct`, to change the Qt style to Kvantum under Cinnamon. Then, your Qt apps, if any, will be styled by it.

Kvantum is usually used under Qt environments like KDE or LXQt.
