### ISSUE TITLE
Muon Discover use system colors

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#205]
Muon Discover not fully aplied kvantum style and use system colors for some elements from systemsettings
![image](https://user-images.githubusercontent.com/8083855/39520367-6ced07dc-4e1b-11e8-94b2-e45774b2b116.png)
First, i'm report this on KDE bug tracker:
https://bugs.kde.org/show_bug.cgi?id=393602
But dev say:
>Please report to Kvantum. Tested here, worked properly.

It's possible fixed on kvantum?
sourcers (if needed):
https://github.com/KDE/discover

**Comment by varlesh** [comment]
Example with Kvantum default theme:
![image](https://user-images.githubusercontent.com/8083855/39520509-f92e86a8-4e1b-11e8-8aac-45bd480d4363.png)

**Comment by tsujan** [comment]
That response doesn't make sense to me: "Tested here, worked properly." Tested what, how?! I think that KDE dev didn't understand your report at all; why replying then?

I'll look into Discover's source to see if a workaround is possible. If no workaround is possible, I might be able to tell you in which part of Discover's source the problem is. However, that needs time and I'm very busy.

BTW, I'll add 2 new features to Kvantum soon. They are relevant to your Adapta theme too. I'll tell you there when they're ready.

**Comment by tsujan** [comment]
OK, no time should be wasted on Discover. When you make an app with QML and Kirigami, you couldn't expect more. I really don't understand why people make apps in QML (can't they code in Qt?!) but nothing can be done for that in a Qt style engine. 

The right response to your report could have been something like this: "Sorry, I made this app using QML."

**Comment by varlesh** [comment]
> BTW, I'll add 2 new features to Kvantum soon. They are relevant to your Adapta theme too. I'll tell you there when they're ready.

ok, thx for you support :)

**Comment by tsujan** [comment]
You're welcome and sorry that I can't do anything about Discover! QML+Kirigami may be good on mobile but is a disaster in a desktop platform.

The new features I mentioned above are about dark line-edits and combo-boxes on dark toolbars of light Adapata themes. After I push the commit, I'll open an issue on your Adapta github page to tell you about them; close it afterward.

**Comment by varlesh** [comment]
You are the best developer I know - always help and solve problem. And i like Kvantum - it's best engine.
Thank you, Tsu! :)

**Comment by tsujan** [comment]
Thanks for the kind words! I feel happy when others enjoy what I enjoy and try to make it better by their reports. A program would have a low quality without good users who report its bugs or want more features. Fortunately, GitHub makes both easy.
