### ISSUE TITLE
theme request: Mint-Y

### ISSUE THREAD

**Issue by NikoKrause** [tsujan/Kvantum#207]
Hey, I'm using Linux Mint with the Mint-Y-Darker theme. I stumbled upon kvantum and think it's pretty nice.

Mint-Y / Mint-Y-Darker /Mint-Dark is based on Arc / Arc-Darker / Arc-Dark.

Since you're having the Arc themes, maybe you could add the Mint-Y themes as well?
I'd appreciate it.

https://github.com/linuxmint/mint-themes/tree/master/src/Mint-Y

**Comment by tsujan** [comment]
Thanks for your suggestion! I'll think about it.

**Comment by tsujan** [comment]
I checked Mint-Y. A Kvantum clone is quite possible but I didn't find its look good enough.

Please note that I don't have time to make a Kvantum copy of every GTK theme. The clones I made were about special GTK themes.

Closing this...
