### ISSUE TITLE
Arc improvements

### ISSUE THREAD

**Issue by NikoKrause** [tsujan/Kvantum#208]
Compare red selected areas in the following screenshots.

Default GTK app with Arc theme:
![screenshot-window-2018-06-06-003436](https://user-images.githubusercontent.com/8415124/41006806-540454a0-6923-11e8-96c9-16016e0f7b22.png)

In QT apps (here Okular) with KvArc there's too much space at the top and left:
![screenshot-window-2018-06-06-003355](https://user-images.githubusercontent.com/8415124/41006828-6922757e-6923-11e8-88e1-5d5773a15d87.png)
 

The menus in GTK apps have a small blank space at the top and the bottom:
![screenshot-window-2018-06-06-003622](https://user-images.githubusercontent.com/8415124/41006883-9cb295f4-6923-11e8-819b-7d734c683231.png)

The menus in QT apps have a small blank space at the top, but not at the bottom:
![screenshot-window-2018-06-06-003639](https://user-images.githubusercontent.com/8415124/41006913-b921e6e0-6923-11e8-842b-c450ac9ba388.png)

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/0e06809b141ead3b5166c0bdfe1332483702c5db

Didn't have time to add a space to the bottom of KvArckDark's menus but they look OK because of darkness.

Restore default settings if you've customized the theme. Thanks for the report!

**Comment by NikoKrause** [comment]
Thank you very much. Looks nicer now.
I noticed this in your PR:
![screenshot-area-2018-06-06-124113](https://user-images.githubusercontent.com/8415124/41033478-04b1aea2-6987-11e8-8d9f-c1b46c4158d1.png)

The second (blue) slider in the svg looks weird. Is this on purpose?

**Comment by tsujan** [comment]
> The second (blue) slider in the svg looks weird. Is this on purpose?

It doesn't have any effect. Different elements can be put in different places of the SVG image but I usually put related elements near each other to find them quickly.

And no, it wasn't intentional. That element was moved after I rounded some values.

**Comment by tsujan** [comment]
A few minutes ago, I added 1px to the menu bottom shadow and cleaned up slider SVG elements (no visual change).
