### ISSUE TITLE
SVG element for disk space indicator in dolphin

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#21]
What svg element affects the disk space indicator in dolphin?
![Kvantum pop menus padding print](http://i.imgur.com/qprqcMz.jpg)

I tested with Kvantum default theme and Glassy too, but both did not affect this element.

KDE 4.13.3

**Comment by tsujan** [comment]
That's a hard-coded style and can't be changed with any theme. Its colors are taken from the theme main colors though.

**Comment by franksouza183** [comment]
Oh, I see, thank you! Closing...

**Comment by tsujan** [comment]
I added a new hack to Kvantum Manager for drawing all these "KCapacityBars" like ordinary progressbars. The hacking key is "kcapacitybar_as_progressbar". Please see if it works for you too.

**Comment by franksouza183** [comment]
Yes, it seems ok.
![Kvantum pop menus padding print](http://i.imgur.com/sMOUSsb.jpg)
Every update that you do, the engine looks like it is more perfect, thank you !!

**Comment by tsujan** [comment]
You're welcome! New themes like yours give me new ideas for making Kvantum still more flexible.

**Comment by grtprsn** [comment]
Exactly What is in the picture on the first post.
adding the Kvantum style override environment variable to the session and then rebooting would cause the gage to disappear. and just a "20G free space" text for example , in its place.
It just happened. about a days ago.
It was ok before the system update.
I am using arch linux. I tested both community ```kvantum-qt5``` package and also the ```kvantum-git```  from AUR.

**Comment by tsujan** [comment]
> adding the Kvantum style override environment variable to the session

Very knowledgeable! Kvantum "overrides environment variable to the session"! I doubt that a real reply would make sense here.

**Comment by grtprsn** [comment]
:)
Indeed. the point was: "without that hack the image above would happen". which wasn't the case two days ago when I started to update my arch via pacman.
right now if I don't explicitly do the override I get the mismatch usage gauge and if I do I just get the text in its place.
is it by design?
would it be fixed?
thanks

**Comment by tsujan** [comment]
@grtprsn If you've encountered a bug, please open an issue and describe the problem clearly. I really appreciate bug reports.

The only that has change in git is that, now, `kcapacitybar_as_progressbar` is `true` by default, so that if a theme maker forgets it, KDE's capacity bars will be drawn as ordinary progressbars. This isn't a bug.

**Comment by grtprsn** [comment]
anyhow;
I really appreciate what you are doing here. thank you.
I just wanted to report that I have that issue. out of no where I faced with the capacity bar not respecting the McMojave plasma theme. both set at system setting and qtconfig app.
I hope you take Kvantum to the whole new level.
😍

**Comment by tsujan** [comment]
I can't reproduce it with KvMojave:

![dolphin](https://user-images.githubusercontent.com/981076/75326580-1fc8a700-5890-11ea-8ff4-f4a29382ff29.png)

Is `Kvantum Manager` → `Configure Active Theme` → `Hacks` → `Show KCapacityBar as progressbar` checked?

**Comment by tsujan** [comment]
> I faced with the capacity bar not respecting the McMojave plasma theme

Plasma theme isn't related to Kvantum. In Dolphin, capacity bars should be drawn as any other progressbar if you use Kvantum. Plasma doesn't take its theme from Kvantum.

**Comment by grtprsn** [comment]
well thanks I didn't know that.
and yes it was enabled by default.  
thanks.

**Comment by tsujan** [comment]
> as you can see there is only the zoom slider and no progressbar.

That's very strange! It isn't normal.The text is elided too.

I enabled the zoom slider but capacity bar is still OK:

![zoom_slider](https://user-images.githubusercontent.com/981076/75335092-25c58480-589e-11ea-9844-1a47c5975bbc.png)

When you right click on a folder and click Properties, do you see the "Free space" capacity bar inside the dialog as a progress-bar? If not, please attach a screenshot.

**Comment by tsujan** [comment]
Also, please tell me the versions of `dolphin`, `plasma-desktop` and `qt5-base` on your system (use `pacman -Qi ...` to get them). Here, they are 19.12.2-1, 5.18.1-1 and 5.14.1-2, respectively.

**Comment by grtprsn** [comment]
```
Version         : 19.12.2-1
Description     : KDE File Manager
Architecture    : x86_64
URL             : https://kde.org/applications/system/dolphin/
Licenses        : LGPL
Groups          : kde-applications  kdebase
Provides        : None
Depends On      : baloo-widgets  knewstuff  kio-extras  kcmutils  kparts  kinit
                  phonon-qt5
Optional Deps   : kde-cli-tools: for editing file type options [installed]
                  ffmpegthumbs: video thumbnails [installed]
                  kdegraphics-thumbnailers: PDF and PS thumbnails
                  konsole: terminal panel [installed]
                  purpose: share context menu [installed]
Required By     : kdebase-meta  konqueror
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 9.15 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Tue 04 Feb 2020 03:09:28 PM +0330
Install Date    : Sat 22 Feb 2020 10:00:34 PM +0330
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

Name            : plasma-desktop
Version         : 5.18.2-1
Description     : KDE Plasma Desktop
Architecture    : x86_64
URL             : https://www.kde.org/workspaces/plasmadesktop/
Licenses        : LGPL
Groups          : plasma
Provides        : None
Depends On      : polkit-kde-agent  libxkbfile  kmenuedit  systemsettings  ksysguard
                  baloo  knetattach
Optional Deps   : plasma-nm: Network manager applet [installed]
                  powerdevil: power management, suspend and hibernate support [installed]
                  kscreen: screen management [installed]
                  ibus: kimpanel IBUS support
                  scim: kimpanel SCIM support
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 35.52 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Tue 25 Feb 2020 07:47:07 PM +0330
Install Date    : Wed 26 Feb 2020 12:32:59 AM +0330
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : qt5-base
Version         : 5.14.1-2
Description     : A cross-platform application and UI framework
Architecture    : x86_64
URL             : https://www.qt.io
Licenses        : GPL3  LGPL3  FDL  custom
Groups          : qt  qt5
Provides        : None
Depends On      : libjpeg-turbo  xcb-util-keysyms  xcb-util-renderutil  libgl  fontconfig
                  xdg-utils  shared-mime-info  xcb-util-wm  libxrender  libxi  sqlite
                  xcb-util-image  mesa  tslib  libinput  libxkbcommon-x11  libproxy
                  libcups  double-conversion  md4c
Optional Deps   : qt5-svg: to use SVG icon themes [installed]
                  qt5-wayland: to run Qt applications in a Wayland session [installed]
                  qt5-translations: for some native UI translations
                  postgresql-libs: PostgreSQL driver
                  mariadb-libs: MariaDB driver
                  unixodbc: ODBC driver
                  libfbclient: Firebird/iBase driver
                  freetds: MS SQL driver
                  gtk3: GTK platform plugin [installed]
Required By     : appstream-qt  attica  bluez-qt  breeze-gtk  karchive  kcodecs  kconfig
                  kcoreaddons  kdnssd  kholidays  kitemmodels  kitemviews  kjs
                  kuserfeedback  kwayland  kwidgetsaddons  libaccounts-qt  libdbusmenu-qt5
                  libqtxdg  modemmanager-qt  networkmanager-qt  packagekit-qt5  phonon-qt5
                  polkit-qt5  poppler-qt5  prison  python-pyqt5  qca  qt5-declarative
                  qt5-multimedia  qt5-script  qt5-sensors  qt5-styleplugins  qt5-svg
                  qt5-tools  qt5-x11extras  quazip  signond  simplescreenrecorder  solid
                  sonnet  syntax-highlighting  threadweaver
Optional For    : avahi  cmake  libde265  openal  pinentry  v4l-utils
Conflicts With  : qtchooser
Replaces        : None
Installed Size  : 63.35 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Tue 11 Feb 2020 01:23:04 AM +0330
Install Date    : Sat 22 Feb 2020 09:42:37 PM +0330
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by grtprsn** [comment]
it is the second screen shot
https://i.imgur.com/pZgw4R4.png
btw: the zoom slider has nothing to do with the space indicator.
It just don't show up for me (if I set style override system environment).
and it if I don't set ```QT_STYLE_OVERRIDE ``` as system env I get exactly like the this:
https://cutt.ly/dr8dnWW

**Comment by grtprsn** [comment]
https://i.imgur.com/uuY2VpW.png
this is the screentshot without style-override

**Comment by tsujan** [comment]
> and it if I don't set QT_STYLE_OVERRIDE

Wait a minute! Why do you set `QT_STYLE_OVERRIDE`? Aren't you under KDE? If not, do you use qt5ct?

**Comment by grtprsn** [comment]
I am under kde.
if I don't do that then : https://i.imgur.com/uuY2VpW.png.

PS: Do I need qt5ct under kde plasma 5?

**Comment by tsujan** [comment]
> Do I need qt5ct under kde plasma 5?

Never! If you have it, uninstall it, then log out and log in again.

If you don't have qt5ct and the problem still persists, I have no clue about its cause. As I mentioned, it isn't reproducible here. So, we may have to wait until someone encounters the same issue and gives us more info.

**Comment by tsujan** [comment]
Oh, if your screenshots are taken with KvMojave that's included in Kvantum, they show that you don't use KDE's Qt plugins. Something outside Kvantum is definitely wrong.

**Comment by grtprsn** [comment]
well; thank you so much for your attention.
no qt5ct and still the same condition.
I guess we have to wait and see.
my take on this subject as follows:
a. I had an 6 month old archlinux(kde plasma5 installation).
b. I updated it regularly.
c. I had no problem with it.
d. all the time I was using kvantum with McMojave theme.
e. I had to format the whole drive and install arch from a new net install .iso from scratch.
--> and now I am facing this issue.
>> I am suspecting that you have some config files produced by old install on your system which gives you  the desired result.  
On the other hand I that have the fresh install I am facing this issue?
Does it make sense?

**Comment by tsujan** [comment]
> I am suspecting that you have some config files produced by the old install...

I don't think so because that's just a simple widget in Dolphin; nothing more. It can't be related to important things like drive formatting.

I'm curious how it's possible; will add a comment here if I find anything. For now, I have no clue and, fortunately, it isn't a sign of a serious problem.

**Comment by grtprsn** [comment]
> I'm curious how it's possible; will add a comment here if I find anything. For now, I have no clue and, fortunately, it isn't a sign of a serious problem.

yes  I agree with you. 
💯 
♥️

**Comment by Fosssil** [comment]
Same issue is coming again in hyprland

**Comment by tsujan** [comment]
> Same issue is coming again in hyprland

It can only be caused by the version of Dolphin you have. They change the code of that widget once in a while and make strange mistakes sometimes. It's OK with dolphin 24.05.1-1 from Arch; a screenshot taken in LabWC:

![dolphin](https://github.com/tsujan/Kvantum/assets/981076/1a013a0e-d1d0-4f71-b628-ceabb378ab6f)
