### ISSUE TITLE
Split code in Kvantum.cpp?

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#211]
Kvantum.cpp is >18000 lines of code. Perhaps this could be refactored into smaller files?

**Comment by tsujan** [comment]
Yes, I'll do it sooner or later but in a way that doesn't make its changing hard to me. Working with a single file has been easier until now, perhaps, because of the nature of the program.

**Comment by CDrummond** [comment]
I agree. Only reporting as its part of the Ubuntu community discussion on using Kvantum - likewise for the license change and XDG_DATA_DIRS

**Comment by tsujan** [comment]
> I agree. Only reporting as its part of the Ubuntu community discussion on using Kvantum

You and I are familiar with things they couldn't know of ;)

I leave this open because the idea occurred to me too. However, I haven't found a practical way of doing it yet. All those functions are closely related to each other and are documented on a single page of Qt doc.

**Comment by CDrummond** [comment]
Well, that theme searching code be separated out :-)

**Comment by tsujan** [comment]
I agree. Your codes might need a separate file too.

**Comment by tsujan** [comment]
Splitting done. `Kvantum.cpp` is still big but it wasn't my goal to reduce its size at all costs; just separated event filtering, polishing and rendering from it but left theme searching code there for now. I can read it more easily now ;) I  might do more splitting later.
