### ISSUE TITLE
unused variable menu

### ISSUE THREAD

**Issue by mmiat** [tsujan/Kvantum#212]
in debian testing with kvm disabled i've this message when make install:

> Kvantum.cpp: In member function ‘virtual bool Kvantum::Style::eventFilter(QObject*, QEvent*)’:
Kvantum.cpp:2841:23: warning: unused variable ‘menu’ [-Wunused-variable]
       else if (QMenu *menu = qobject_cast<QMenu*>(o))

but it seems working well

**Comment by tsujan** [comment]
That's a harmless compiler warning. `menu` is used only with Qt >= 5.11 but, sooner or later, all distros will have such a Qt.

However, thanks for your report!

**Comment by tsujan** [comment]
Since it might take a while for Qt 5.11 to come into Debian Testing, I silenced the compiler in https://github.com/tsujan/Kvantum/commit/ebc3ec088a1ae185ae6e3b724f0bee5f3c5ed740 . Please test!
