### ISSUE TITLE
TeXstudio font of dictionary entries in rightclick menu

### ISSUE THREAD

**Issue by NikoKrause** [tsujan/Kvantum#213]
I use TeXstudio. And when a word is misspelled, it is highlighted/underlined in red (e.g. like it is done here in GitHub). When I right-click on the misspelled word, I get suggestions on how to spell the word correctly. This words are usually bold in other theme, but not in Kvantum themes.
See screenshot with KvArc (the top 2 words are the suggestions):
![screenshot-area-2018-06-12-134430](https://user-images.githubusercontent.com/8415124/41289172-2aed196e-6e49-11e8-9fa7-846daa9314a1.png)
The same with Gtk theme:
![screenshot-area-2018-06-12-134526](https://user-images.githubusercontent.com/8415124/41289200-4ae56f5a-6e49-11e8-8caf-7358d25b958a.png)

Plus the third entry says "Add to dictionary". It is italic with gtk and normal font with Kvantum.

Not sure if you can do something about this.

**Comment by tsujan** [comment]
> Not sure if you can do something about this.

I can, by adding just three lines of code:

![texstudio](https://user-images.githubusercontent.com/981076/41295571-22428ebc-6e70-11e8-9b93-e99152941d80.png)

Long story made short, other Qt styles don't have font property definitions; Kvantum enforces its own font properties but could also show more tolerance.

However, TeXstudio has serious problems with light-and-dark themes. I'll see if I could include a workaround for them in a single commit.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/66409f41a0ab851ac8a8bf1aadecaceeb748c2ee

Texstudio has color customization; so, no workaround is needed.

**Comment by NikoKrause** [comment]
Thank you! Works flawlessly.
