### ISSUE TITLE
Maia variant of adapta theme

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#216]
I would like to change the blueish flavor of adapta dark for the more greenish flavor characteristic of manjaro. They provide a color theme that chages many colors in an appropriate way but some colors I'm unable to change. For example in many lists the current selection persists in blue no matter that in the color schema there is no more blue colors. I event changed the colors in the kvconfig file but again to no avail. Probably this blue color is somewhere in the svg file for the adapta theme. How should I change it? Is it customizable? In theory it seems like a very simple change (I see no gradients or whatever, just plain blueish to plain greenish).

**Comment by memeplex** [comment]
Alternatively, is it possible to disable the 1px border around some widgets (for example, focused lists) without modifying the svg file? I got the green flavored adapta svg but I dislike that 1px border, otherwise it's fine.

**Comment by memeplex** [comment]
Transparent Dolphin view!!!! This is it. Now all makes sense. I'm closing this and thank you for such a customizable engine.

**Comment by tsujan** [comment]
For the list selection color, you should change 2 things: (1) the color of `itemview` elements in the SVG file (you could do that without Inkscape too) and (2) the value of `highlight.color` as well as `inactive.highlight.color` in the kvconfig file.

List selection borders can be changed by changing the values `frame.top/bottom/...` and `text.margin.top/bottom/...` under the `[ItemView]` section. Set at least one of them to 1; otherwise selections will look too tight.

Manjaro already has `kvantum-theme-adapta`, which is a collection of KvAdapata flavors. As a Manjaro user, I helped them by adding some features and fixing some small issues and might do so again once in a while.

Transparent Dolphin view is a feature I added in old times ;)

**Comment by tsujan** [comment]
My mistake: I meant `kvantum-manjaro`, not `kvantum-theme-adapta`. `kvantum-manjaro` includes `KvAdaptaMaia`, among other things.

**Comment by memeplex** [comment]
Thanks for the explanation!

I requested them for a more suble focus indicator:
https://gitlab.manjaro.org/artwork/themes/kvantum-manjaro/issues/3. There
are other cases besides dolphin where these 1px rectangles are unaesthetic
(for example, the side panels in okular). I'm not sure if that can be
generalized in a safe way so as to add a not so app specific hack to
kvantum.
​

**Comment by tsujan** [comment]
Please also note that margins and spacings can be hard-coded. The Qt style sets a default most apps should be happy with but sometimes a developer may need other values.

**Comment by memeplex** [comment]
I understand, I was just afraid that this were a general "focused item"
setting and that the more specific "focused frame" (or whatever it's called
in qt/kde parlance) couldn't be changed without breaking the general case.

**Comment by tsujan** [comment]
I don't know what you mean by "focus indicator". The focus rectangle? A screenshot could be very helpful.

**Comment by tsujan** [comment]
If you mean the dotted focus rectangle like this:

![focus](https://user-images.githubusercontent.com/981076/41491762-6c7b1aec-7110-11e8-934e-9dec23af510b.png)

then, it can be disabled by setting `frame.top/bottom/..` to zero or just setting `frame=false` under the `[Focus]` section.

Focus rectangles can be helpful when using keyboard with list-views but it's up to the theme maker to include them in his/her theme. If they're missing, they will be so everywhere. I wouldn't call them ugly.

**Comment by memeplex** [comment]
See for example:


There are two things to take into account here:

1. The rectangle at the left *is useful*, it's just that it is ugly, a
brighter version of the base color would look better.

2. The selected item in the toolbar (and in general other
selected/focused/whatever -not quite sure here- items) has the same color
and, in this case, it's ok, it's in the spirit of the theme itself.

I would like to change the green at the left while keeping the green at the
toolbar.

Is it clearer now?

**Comment by tsujan** [comment]
> Is it clearer now?

No! Apparently, we're talking about different things. I attached a screenshot. You also need to do so and explain your point by referring to it. This is about *graphic* user interface after all ;)

**Comment by memeplex** [comment]
Sorry I'd sent an image in my previous message (email) but not as an attachment, it seems to have been lost in the way. Here it is:

![image](https://user-images.githubusercontent.com/2845433/41492686-0ed1b330-70d7-11e8-8556-fac074bcd909.png)

**Comment by tsujan** [comment]
One picture is worth a thousand words :)

The left rectangle is the focused "GenericFrame" while the toolbar underline is about toggled toolbar buttons.

I don't see the focused GenericFrame ugly in this theme. As you found, it can be removed from Dolphin by using a hacking option in Kvantum Manager.

However, If you want to change its color, search for `common-focused` elements in the SVG file by using Inkscape (`common` is chosen under `[GenericFrame]` in the kvconfig file) and change the green colors.

You could also remove the focused GenericFrame totally by removing all `common-focused` elements from the SVG file. Some of my non-flat themes don't have it but I think it's good with flat themes, although it isn't so important.

**Comment by memeplex** [comment]
Great! Thank you for all the info.

I'm going to bother you with one more question, sorry.

Do you know why the green color of manjaro adapta could be taking effect inside windows but not at the desktop? (see screenshot, that is one example, but in every menu and toolbar of the desktop the blue of vanilla adapta persists).

![screenshot_20180615_204405](https://user-images.githubusercontent.com/2845433/41493515-608be806-70de-11e8-95fa-cbb5eeb8d214.png)

**Comment by tsujan** [comment]
You're welcome.

The KDE desktop uses the Plasma theme, not the widget style.

**Comment by memeplex** [comment]
Oh, inspecting the files I guess the workspace is a total different beast, at least from the gui there is no widget style setting for the workspace although the setting exists in .config/kdeglobals and is set to Breeze. I assume it's the adapta theme (not the manjaro kvantum theme) that is setting it.

**Comment by tsujan** [comment]
Actually, the KDE desktop uses parts of the widget style too. It depends on which part of the desktop we're speaking about. For example, right click menus are drawn by the widget style (Kvantum) but, sometimes, you might need to log out and log in again to see the new theme (a KDE problem).

If after a log-out/in the desktop colors are the same as before, that means they're taken from the Plasma theme, not from the widget style (Kvantum).

**Comment by memeplex** [comment]
I think the best way to achieve consistency here between the desktop, the
widgets and gtk would be to go vanilla adapta and forget about maia (or
tolerate a non-maia desktop).

**Comment by tsujan** [comment]
Isn't there a Maia Plasma theme?

**Comment by memeplex** [comment]
Indeed it is! I didn't know about it. Nevertheless it's not up to the
quality of https://github.com/PapirusDevelopmentTeam/adapta-kde. I think I
will tolerate the bright blue for now :) and request the papirus team for a
maia variant of their theme. Thanks again!
