### ISSUE TITLE
Using qt5ct menus are transparent

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#217]
Using qt5ct inside gnome I get the transparent menus that are shown in the screenshot. I tried many themes, including some of the ones provided by vanilla kvantum, and the problem persists.
![image](https://user-images.githubusercontent.com/2845433/41502472-ecd7c980-7190-11e8-8f16-73ea97209d9c.png)

**Comment by tsujan** [comment]
What if you close and open the app (Kvantum Manager) again?

**Comment by memeplex** [comment]
It's the same, the problem is not just in kvantummanager but in every qt app inside gnome.

**Comment by memeplex** [comment]
Ok, I think it's one of the qss provided by qt5ct that is doing `QFrame { border: none }`

**Comment by memeplex** [comment]
It doesn't have the same effect with other engines tough.

**Comment by memeplex** [comment]
You need to apply fusion-fixes.qss (in the style sheets tab) to reproduce this. The contents of the file are:

```
QMenuBar, QMenu, QToolBar, QStatusBar, QFrame, QScrollBar {
    border: none;
}
QTabBar::tab:selected {
    color: palette(bright-text);
}
QScrollBar {
    background: palette(dark);
}
QScrollBar::handle {
    background: palette(highlight);
    border-radius: 4px;
}
QScrollBar::add-line, QScrollBar::sub-line {
    background: palette(window);
}
```

The simplest change that allows me to reproduce the effect is the one mentioned a couple of comments above.

**Comment by memeplex** [comment]
I tried many things.

1. All variants of 0px, changing the border color, etc. for QFrame results in transparent menus.

2. Targeting QTableView fixes the issue with calibre without transparent menus.

3. Targeting QTableView **and** QListView result in transparent menus, but QTableView **xor** QListView not, this is weird!

**Comment by memeplex** [comment]
No, sorry about 3 above, I should have said QTableView and/xor QListWidget, and that way it's not so weird after all. For now my workaround is:

```
QListWidget, QTableView, QTableWidget {
    border: none
}
```

**Comment by tsujan** [comment]
I'm now with my second computer and tried qt5ct under gnome-shell: Kvantum is fine.

> You need to apply fusion-fixes.qss (in the style sheets tab) to reproduce this.

That stylesheet is a VERY bad idea. You can't use it and expect Kvantum to be happy. Whay are you using such a thing?!

**Comment by memeplex** [comment]
Because many things looks really bad under themes like adapta dark maia. Remember your dolphin and pcmanfm hacks? Well the same happens in many places. Mostly these are lists and tables where the focus is obvious because there is an active cursor inside the widget itself, but you get that rectangle **all the time**. I know I'm a bit picky about this things, but in this cases I don't think I'm over reacting, probably the manjaro people provide that style sheets to fix their theme and better match the more polished one in gnome.

**Comment by tsujan** [comment]
Stylesheets always interfere with the widget style (QStyle). Their effects are defferent with defferent styles. Fusion, Breeze, QtCurve.. are all similar to each other: they draw everything in their codes. Kvantum is very different because it puts SVG elements together, considering so many factors; damage one of them and you'll see weird effects.

> Remember your dolphin and pcmanfm hacks?

Yes. I explained how you could change the theme according to your taste. Never use a stylesheet to change a widget style. Stylesheets can be used safely only in *Qt apps that include proper codes for them*; then there will be no difference between Kvantum and other styles (unless the stylesheet is incomplete).

I close this because it isn't a Kvantum issue but feel free to tell about your experiments -- I'll read them.

**Comment by memeplex** [comment]
Ok, thank you very much!

**Comment by tsujan** [comment]
> I think their widget theme is supposed to be used with kvantum, at least their gnome edition configures qt5ct with kvantum and includes those qss

I have no clue what they might do under gnome but I installed qt5ct-0.35-2 with pacman on Manjaro and saw no problem under Gnome-shell.

BTW, I use gnome-shell when I want to do harsh tests on Qt apps. I don't know how Kvantum works without qt5ct here. I may have activated LXQt's plugin under gnome-shell but I don't remember how ;)

**Comment by tsujan** [comment]
A question, out of curiosity:

What happens (with the same settings as before) if you disable compositing with Kvantum Manager?

**Comment by memeplex** [comment]
Composite is disabled by default and I'm unable to change that (the
checkbox is disabled).

**Comment by tsujan** [comment]
The checkbox is disabled and unchecked?

**Comment by tsujan** [comment]
If the checkbox is disabled and unchecked, Go to Kvantum Manager → Miscellaneous → Respect current DE if possible and uncheck it first. Then "Disable composite effects" will be enabled and you could check it.

**Comment by memeplex** [comment]
Sorry it was **enabled** by default. I did as you said but saw no
difference regarding the transparency after disabling composite.

**Comment by tsujan** [comment]
OK, I found the reason why those combo popups are transparent in your case -- and they are NOT menus but combo popups. There's a comment in `Kvantum.cpp` that explains everything:

https://github.com/tsujan/Kvantum/blob/5d47d034ae58efd5bb3469747b702e6248bb1aec/Kvantum/style/Kvantum.cpp#L1591

In this case, the intruding style is a stylesheet and Kvantum tries to keep its sovereignty but it has no chance against a stylesheet, which ruins everything. Stylesheets always override QStyle in Qt.

As a workaround, you could uncheck `Kvantum Manager → Configure Active Theme → Miscellaneous → Combo popup as menu`.

However, I emphasize that qt5ct's stylesheets should NOT be used with Kvantum. They not only make combo popups transparent but disable transient scrollbars (not found in any other Qt style), make scrollbars very ugly, fill menubar items with an ugly color, etc.

**Comment by memeplex** [comment]
Great! You're one of the most responsive devs I've met in my life!

**Comment by tsujan** [comment]
Thank you! I've learned that observant users are the best asset to an open-source developer. So, he'd better be responsive ;)
