### ISSUE TITLE
weird text color issue at least on plasma-pa

### ISSUE THREAD

**Issue by ahjolinna** [tsujan/Kvantum#218]
for some reason in plasma-pa advance tab section the "Advance Output Configure" text uses the color from anything that is behind in the background (from app to wallpaper).

this doesn't happen with breeze or kvantum-dark just with basic kvantum (at least using adapta & materia theme).

I haven't notice this issue anywhere else ...yet, and this "issue" has existed for a while at least from plasma 5.12.x I just have been lazy to report this :D 

[demo video (1mb)](https://www.dropbox.com/s/tc1uzqt716umf6n/vokoscreen-2018-06-17_21-42-37.mkv?dl=0)

-------

system spec:

```
inxi -bxx 
System:    Host: linux-khll Kernel: 4.17.1-1-default x86_64 bits: 64 compiler: gcc v: 8.1.1 
           Desktop: KDE Plasma 5.13.0 tk: Qt 5.11.0 dm: sddm Distro: openSUSE Tumbleweed 20180615 
Machine:   Type: Desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x serial: <root required> 
           UEFI: American Megatrends v: 3606 date: 02/22/2018 
CPU:       Quad Core: Intel Core i5-6600K type: MCP arch: Skylake-S speed: 4139 MHz min/max: 800/4300 MHz 
Graphics:  Card-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 390.67 bus ID: 01:00.0 chip ID: 10de:13c2 
           Display: x11 server: X.Org 1.19.6 driver: nvidia resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 390.67 direct render: Yes 
Network:   Card-1: Intel Ethernet Connection I219-V driver: e1000e v: 3.2.6-k port: N/A bus ID: 00:1f.6 
           chip ID: 8086:15b8 
Drives:    HDD Total Size: 19.89 TiB used: 19.11 TiB (96.1%) 
Info:      Processes: 328 Uptime: 1h 07m Memory: 15.61 GiB used: 6.38 GiB (40.8%) Init: systemd v: 237 
           runlevel: 5 target: graphical.target Compilers: gcc: 8.1.1 alt: 7/8 Shell: bash v: 4.4.23 
           running in: yakuake inxi: 3.0.10 
```

I had this problem on arch as well with plasma 5.12.x...I think even 5.11.x (before I moved to openSUSE half a year ago)

**Comment by ahjolinna** [comment]
@tsujan : yeah also suspect that this is a plasma-pa/qml issue but highly doubt KDE is interested checking this issue out as this doesn't affect breeze. I wonder why I have this problem just with basic/light kvantum not dark version

Also I'm using plasma5.13 + Qt5.11 (as I'm on tumbleweed, not leap 15)

**Comment by tsujan** [comment]
Good news: I could see something like in your screencast (but not exactly the same thing) under Manjaro/Arch and found the cause: QML is a mess with translucent text colors.

KvAdapta themes (its various versions) use translucent text colors. Qt can handle them correctly but QML cannot. Once I made those colors completely opaque, the QML issue disappeared.

So, this is really a QML issue. I don't think a workaround is possible but will tell you as soon as I'm sure. Anyhow, QML will change heavily sooner or later.

**Comment by tsujan** [comment]
With the latest commit, I added an option as `Kvantum Manager → Configure Active Theme → Hacks → Opaque (text) colors`. You could activate it if you can't tolerate this QML bug, in which case, a log-out and log-in will be needed for the Plasma to see the new setting.

**Comment by ahjolinna** [comment]
Okay thanks I'll try out, but is this something that should be reported to Qt/qml?

**Comment by tsujan** [comment]
> is this something that should be reported to Qt/qml?

To report a bug to the Qt bug tracker, you should provide them with a sample code and I have no time for that. If you tell them to install Kvantum to see how terrible QML is, they will close the report immediately.

On the other hand, when it comes to styling, QML is full of bugs. In an inconsistent, it partly uses QStyle and partly has its own styling, so its platform integration is terrible. Its lack of good platform integration is made almost hidden by elementary styles like Fusion and Breeze. Fusion and Breeze don't go beyond an elementary usage of QStyle. Things like translucent text colors, translucent/styled window backgrounds, inactive states, dark-and-light themes, transient scrollbars,... are out of question with them.
