### ISSUE TITLE
Breeze theme

### ISSUE THREAD

**Issue by E5ten** [tsujan/Kvantum#219]
If you happen to find any time, would you consider making the breeze/breeze dark theme for kvantum?

**Comment by tsujan** [comment]
Sorry, I can't because I dislike Breeze's look and feel. Kvantum [0.10.6](https://github.com/tsujan/Kvantum/releases/tag/V0.10.6) has `KvDynamo`, which was inspired by older versions of Breeze but wasn't made by me.

**Comment by simoniz0r** [comment]
I would also like to see a Breeze Dark theme.

**Comment by simoniz0r** [comment]
I'm not trying to be mean at all, but I can't at all bring myself to understand how you can say that you won't create a Breeze theme for kvantum because you `dislike Breeze's look and feel`, but you find this to be acceptable lol:

![image](https://user-images.githubusercontent.com/16279904/41877128-c4c08da4-7895-11e8-8a3d-92d0bfbb0b8d.png)

**Comment by tsujan** [comment]
If someone doesn't understand the simple fact that tastes differ, he/she couldn't have a constructive talk with anyone.

Breeze is ugly to me, while it's brilliant to you -- I have no problem with that. However, it's easy to understand that I won't waste my time for making something I dislike.

**Comment by simoniz0r** [comment]
I understand that tastes differ, but I'm not sure how you find that bold, itallic font in your titles to be appealing at all.

Also, breeze is very popular.  IMO, throw your personal tastes aside and create a theme that would quite possibly bring a lot of new users to kvantum.

**Comment by simoniz0r** [comment]
Alrighty then; I'll be avoiding your repos in the future.

**Comment by Vistaus** [comment]
I'm sorry for bumping this, but I just wanted to let the OP know that someone recently created a Breeze theme for Kvntum: https://github.com/Luwx/Breeze-Kvantum

**Comment by tsujan** [comment]
@Vistaus  Thanks for the info!

Its screenshot is nice. I hope the theme is made professionally; will try it when I find time.
