### ISSUE TITLE
Some texts become transparent under Plasma/KDE

### ISSUE THREAD

**Issue by psifidotos** [tsujan/Kvantum#220]
When using the kvantum engine there are cases that some text elements of the plasma desktop become transparent.

krunner text is green because the underlying background is green:
![default](https://user-images.githubusercontent.com/2216474/41824267-30cef47a-7816-11e8-9bcf-7a6cc2453526.png)

krunner text is red because the underlying background is red:
![default](https://user-images.githubusercontent.com/2216474/41824276-5608029a-7816-11e8-997f-570538422b31.png)

In Active Window Control settings, the disabled texts are red because the underlying background is red:
![default](https://user-images.githubusercontent.com/2216474/41824292-8a04e306-7816-11e8-8c67-0280c57b5a73.png)

**Comment by tsujan** [comment]
Already discussed here: https://github.com/tsujan/Kvantum/issues/218

As a workaround fo this QML issue, you could use the latest git Kvantum and  check `Kvantum Manager` → `Configure Active Theme` → `Hacks` → `Opaque (text) colors`; then log out and log in again.

**Comment by psifidotos** [comment]
this fixed the Active Window Control issue but it didnt the krunner one

**Comment by tsujan** [comment]
> this fixed the Active Window Control issue but it didnt the krunner one

Will examine krunner later.

**Comment by tsujan** [comment]
I saw krunner. It was as you said. That's definitely a bug in KDE and I'm afraid that no workaround comes to my mind in this case.

However, here, once a text is typed, the color will be opaque.

**Comment by mgoldshteyn** [comment]
I don't see an entry for `Opaque (text) colors`

**Comment by tsujan** [comment]
> I don't see an entry for Opaque (text) colors

Removed because the bug was fixed in Qt 5.14.1. If there's still a bug in KDE/QML, it should be fixed in them.
