### ISSUE TITLE
How to register kvantum (without using qt5ct) in QT_QPA_PLATFORMTHEME?

### ISSUE THREAD

**Issue by unihorn78** [tsujan/Kvantum#221]
Subj

How to register kvantum (without using qt5ct) in QT_QPA_PLATFORMTHEME?

export QT_QPA_PLATFORMTHEME=kvantum (Kvantum, kvantum-style, etc) does not work.

**Comment by tsujan** [comment]
`QT_QPA_PLATFORMTHEME` is about the Qt platform theme (plugin), while Kvantum is a style plugin and is about `QT_STYLE_OVERRIDE`. The second variable requires the first to be set. The first one needs a "Qt platform-theme plugin".

Qt DEs (KDE, LXQt) automatically activate their own platform-theme plugin; the user just chooses the style (Kvantum, for example) and one of its themes.

Under non-Qt DEs, qt5ct, [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform), or lxqt-qtplugin,... can be used. All of them are about the variable `QT_QPA_PLATFORMTHEME` that you mentioned.

**Comment by tsujan** [comment]
An example:

Under Enlightenment, I set `QT_QPA_PLATFORMTHEME` to `lxqt` and `QT_STYLE_OVERRIDE` to `kvantum` (with small letters). Of course, I have installed lxqt-qtplugin (and its config) for the first variable.

**Comment by unihorn78** [comment]
Thank you so much.

I made "export QT_STYLE_OVERRIDE = kvantum"

And it all worked.

**Comment by tsujan** [comment]
You're welcome.

So, on your system, `QT_QPA_PLATFORMTHEME` was already exported in a proper way.

**Comment by spikespaz** [comment]
Sorry to necro this thread but... I would like to know if anyone is aware of what component of KDE handles the theming. I find that all of the options presented look *very* bad with some Qt programs, and I never noticed a single issue on KDE. If I can rip that out to replace qt5ct, you would be my hero.

**Comment by tsujan** [comment]
> what component of KDE handles the theming

Its Qt plugins, namely, its platform-theme plugin (`/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so`) and its icon engine plugin (`/usr/lib/qt/plugins/iconengines/KIconEnginePlugin.so`). The first one allows style changing, the second one handles icons, both through KDE's System Settings . You can't "rip them out".

But if you have a full KDE installation, you might be able to use this command outside KDE to run APP:
```
export XDG_CURRENT_DESKTOP=KDE && APP
```

Similarly, if you have a full LXQt installation, you could use this command outside LXQt:
```
export XDG_CURRENT_DESKTOP=LXQt && APP
```

**Comment by spikespaz** [comment]
If I wanted the fewest packages from either desktop environment possible, what route would you take? Can I just install KDE settings and get those two plugins, or get the packages that work together without the entire plasma desktop metapackage?

**Comment by tsujan** [comment]
> Can I just install KDE settings and get those two plugins

Probably, those plus `kiconthemes`, but they depend on a lot of other packages.

However, it's unusual to install so many packages just for use outside KDE. That's why `qt5ct` has been made. It has its own independent platform-theme plugin.
