### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by vmorenomarin** [tsujan/Kvantum#225]
Hi. 

Thanks by your work.

I need to know how to change the color to the toolbar in Dolphin. I want modify KvArk (modified) for toolbar color match with titile color of the window.

Which parameter I have to set in the KvArc#.kvconfig file?

Thanks by your attention!

![screenshot_20180712_113906](https://user-images.githubusercontent.com/13444664/42646989-30d82dd2-85c8-11e8-8bf0-207246963660.png)

**Comment by tsujan** [comment]
There are various ways to do so. For example, in `KvArc#.kvconfig`, we have these line:
```
[Toolbar]
inherits=PanelButtonCommand
indicator.element=toolbar
indicator.size=5
text.margin=0
frame=false
interior.element=menubar
frame.element=menubar
text.normal.color=#000000c8
text.focus.color=black
frame.bottom=0
frame.expansion=0
```
Add `interior=false` below `frame.expansion=0` and you'll get what you want.

For menu-bar, also change these lines:
```
[MenuBar]
inherits=PanelButtonCommand
frame.element=menubar
interior.element=menubar
frame.bottom=0
frame.expansion=0
```
by changing "menubar" to "menubar1" (which doesn't exist in the SVG image).

Another way is pasting `KvArc.svg` as `~/.config/Kvantum/KvArc#/KvArc#.svg` and changing the colors of "menubar-" elements in Inkscape but the above-mentioned method is much easier. There are other ways too...

**Comment by vmorenomarin** [comment]
Thanks a lot. Works as you said.

If I want a particular color?

**Comment by tsujan** [comment]
You're welcome.

> If I want a particular color?

Then leave the kvconfig file as it was and edit the "menubar-" elements inside `~/.config/Kvantum/KvArc#/KvArc#.svg` with Inkscape, as mentioned above. With some experience with Inkscape, you could also create your own theme out of KvArc.

Some simple colors are defined under `[GeneralColors]` in the kvconfig file. The other colors (and gradients) are inside the SVG image.

**Comment by tsujan** [comment]
BTW, recently I corrected a mistake in some KDE color schemes that come with Kvantum, including `KvArc.colors`, so that their Breeze title-bar colors are the colors of their tool-bars/menu-bars now. So, if you use KWin with the Breeze title-bar, you'll see a uniform color on the top of windows. There are also good forks of Breeze, like [SierraBreeze](https://github.com/ishovkun/SierraBreeze/) and [BreezeBlurred](https://github.com/alex47/BreezeBlurred/).
