### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by agaida** [tsujan/Kvantum#229]
Hi, mind a new release? (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889075)
Sees that Kvantum has some fans - which is a good thing - but really would like to have a current release to introduce in debian.

**Comment by tsujan** [comment]
Telepathy? Today, I was thinking about a new release and wrote a summary. Will release 0.10.7 in a few days.

As for fans, I always thought FeatherPad would be the winner but Kvantum is unique in several ways.

**Comment by tsujan** [comment]
BTW, I'll make a new release for FeatherPad (and the first release of FeatherNotes) too.

**Comment by agaida** [comment]
sounds good

**Comment by tsujan** [comment]
And thanks for thinking about introducing it to Debian! Yesterday, a user wanted a deb package and I didn't have a link; just explained the cmake compilation because Debian users may have problem with qmake (its place).

**Comment by agaida** [comment]
https://salsa.debian.org/lxqt-team/qt5-engines-kvantum/tree/experimental-snapshots/latest/debian

**Comment by tsujan** [comment]
Thanks! What's the best thing to add to README for sid users?

**Comment by tsujan** [comment]
OK.

BTW, like LXQt, I recommend everyone use the latest git versions of my apps because they're really stable. Arch users have no problem in this regard. Your experimental snapshots are a great help by covering Debian :)

**Comment by agaida** [comment]
and even better - i wrote some tools like git snapshot to manage it - part of debians lxqt-build-tools :)

**Comment by tsujan** [comment]
Released [0.10.7](https://github.com/tsujan/Kvantum/releases/tag/V0.10.7)

I might try to focus on wayland in the next release. Both Qt and KDE devs are working on it and we might be able to have in with KWin under LXQt -- but not in the near future.
