### ISSUE TITLE
Move files?

### ISSUE THREAD

**Issue by agaida** [tsujan/Kvantum#230]
Is it possible to move files from ./Kvantum to ./ for the next release?

**Comment by tsujan** [comment]
It's too late. Kvantum was my first repository on GitHub and I made that mistake. All package sources and all links will be broken if I correct it; so, I accepted it as a peculiarity -- compensated by the quality of Kvantum ;)

**Comment by agaida** [comment]
ok - no problem, thats what repack scripts are for - uscan can be great

**Comment by tsujan** [comment]
Sorry for this inconvenience, hoping that it happens only once, at the beginning.
