### ISSUE TITLE
Krusader with Kvantum becomes not very responsive

### ISSUE THREAD

**Issue by NickLion** [tsujan/Kvantum#231]
When Kvantum (e8c4a55) style is used, Krusader (2.7.0) becomes not very responsive. It looks like it is slowly painted. Press Tab to switch to other panel and that action is delayed, scroll too. At Krusader start it behaves well, after a while becomes more and more slow.
If switch to Breeze, Krusader behaves fine.

**Comment by tsujan** [comment]
I can't think of anything in Kvantum that could make Krusader slow or non-responsive. Moreover, I can't reproduce this with Krusader (2.7.0) and the latest Kvantum. Which Kvantum theme did you use with Krusader?

**Comment by NickLion** [comment]
I've tried different themes, currently, I'm using MateriaLight from store.kde.org. If I'll keep Tab pressed now Krusader switches from panel to panel only 2-3 times per second, while at Krusader start with Kvantum and always with Breeze it's flashing.

**Comment by tsujan** [comment]
Here, keeping Tab pressed causes fast flashing and I'd also tested that in the above-mentioned experiment.

I'll also test MateriaLight later.

**Comment by NickLion** [comment]
Yes, it doesn't happens at start and I'm not sure why exactly this appears. Using krusader, switching desktops or some other operations. That might be a krusader bug, but for some reason it appears with kvantum, but not breeze. Maybe some tip how to debug this?

**Comment by tsujan** [comment]
> Yes, it doesn't happens at start

I think using Krusader for half an hour is far from the start ;) I switched desktop multiple times and even moved Krusader to other virtual desktops (with KWin) but saw no change.

I tried `Materia` and `MateriaBlur` too: no delay either.

Maybe I haven't understood it correctly. How exactly do you know that Krusader is painted slowing? You press Tab and there's a delay in changing the pane? How many seconds? Isn't there some process using a lot of CPU time elsewhere (you could check that in several ways)?

> Maybe some tip how to debug this?

I have no clue. I'm curious to know how to reproduce what you see. Please tell me if you find a reliable way of reproducing it.

**Comment by tsujan** [comment]
To be sure that the problem is about Krusader, you could use Dolphin instead of it for a while and see what happens.

**Comment by NickLion** [comment]
> How exactly do you know that Krusader is painted slowly?
Well, I do not know that for sure. It just looks like. It's just not too much changes when Tab is pressed and reproducible only with Kvantum, so… most possible it's linked to painting or maybe size/layout calculation. It's very possible this is Krusader problem, not Kvantum (which isn't happened with breeze for some reason), as I can't remember such problem with Krusader 2.6, though I'm updating Kvantum too, so that's not 100%.

> You press Tab and there's a delay in changing the pane? How many seconds?
Yes, about 300-400ms. Sometimes more.

> Isn't there some process using a lot of CPU time elsewhere (you could check that in several ways)?
Sorry, didn't mentioned, checked that, no sign of any process using CPU a lot, except Krusader itself. When Tab is pressed persistently Krusader uses 100% of one core and switching rather slowly, so that's doesn't looks like some waiting, it doing something.

> you could use Dolphin instead
Yeah, I'll try but that's not that simple, I'm doing a lot with Krusader.

PS Wow, I've started Krusader about 15 minutes ago, just started it, and switched to Falkon and it's already in slow-mode and delay is about 800ms %)
Scrolling looks fine, but panel or tab switching and directory changing is slow. If this behaviour was reproducible with other styles, I'd thought it something with IO :-/
Dolphin is fine so far. I'm really in doubts what causes this behaviour.

**Comment by NickLion** [comment]
Hm, I've run `sleep 10 && gdb /usr/bin/krusader $(pgrep krusader)` switched to krusader, pressed Tab and waited. Here is [backtrace](https://susepaste.org/view/raw/39779312). Not much kvantum there…

**Comment by NickLion** [comment]
Tried that several times to be sure that's not random. It's not, bt top is roughly same on Tab or directory changing or window maximize/restore (which is slow too, btw, here is it's bt — renamed to .log, github doesn't want to upload .bt — [krusader-max-rest.log](https://github.com/tsujan/Kvantum/files/2231098/krusader-max-rest.log) )

**Comment by tsujan** [comment]
Thanks for your detailed explanation! So, Krusader crashed this time.

Although I can find no problem -- neither in the code nor when Krusader is actually running -- with the bt you provided, it isn't fair to keep this issue closed.

` Kvantum::Style::getStylableToolbarContainer` is mentioned in your bt but I couldn't find any problem in it.

So far, the only thing that comes to my mind is your Kvantum installation. Three weeks ago, I split some source files. Could you please re-install Kvantum from a clean source directory taken from GitHub?

**Comment by tsujan** [comment]
I found this but it may not be relevant: https://bugs.kde.org/show_bug.cgi?id=392133 . The reporter says, "The leak does occur consistently and without any action; it's enough to start Krusader and leave it alone."

**Comment by trmdi** [comment]
Could you reproduce the bug with a new fresh user ? What distro are you using? Have all the packages been updated ?
I can't reproduce it on my oS Tumbleweed system running the latest commit version of Kvantum.

**Comment by tsujan** [comment]
@trmdi Thanks for your comment! I add that I have the latest stable Krusader-2.7.0 from AUR (under Manjaro) and see no problem either.

**Comment by NickLion** [comment]
I'm building Kvantum in OBS, so it's clean everytime. Maybe, I've done something wrong there or some historical stuff is bad. [Here I build it](https://build.opensuse.org/package/show/home:NickLion:qt5:Unstable/kvantum).

**Comment by NickLion** [comment]
> Could you reproduce the bug with a new fresh user ?
I'll try that later.

> What distro are you using?
openSUSE Tumbleweed

> Have all the packages been updated ?
Yes, currently not that latest snapshot but not old — 20180722.

**Comment by trmdi** [comment]
> I'm building Kvantum in OBS, so it's clean everytime. 
> Yes, currently not that latest snapshot

These could probably be the cause.
Please try the official version of Krusader, or update your oS.

**Comment by tsujan** [comment]
The source inside [kvantum-0.10.7.git.20180722T175923.e8c4a55-1.1.src.rpm](https://build.opensuse.org/package/binary/home:NickLion:qt5:Unstable/kvantum/openSUSE_Tumbleweed/i586/kvantum-0.10.7.git.20180722T175923.e8c4a55-1.1.src.rpm) is up-to-date.

**Comment by tsujan** [comment]
@NickLion You might be able to solve this mystery by compiling and installing Kvantum *directly* -- not through OBS.

**Comment by NickLion** [comment]
Ok, thanks @tsujan @trmdi , so I'll try to update to the next snapshot, check new user and remove RPM and install from sources. I'll write here about results. Any other suggestions?

**Comment by tsujan** [comment]
Installing from the source will exclude some possibilities.

**Comment by NickLion** [comment]
Some progress. OS update haven't changed anything. Currently I'm trying to reproduce on new user — haven't reproduced so far (it's not stably reproduced on my user as well, so not sure about reason), but I'm mostly on default settings, next will try to set settings of Plasma, Krusader and Kvantum closer to what I'm using.

**Comment by tsujan** [comment]
Did you compile and install Kvantum from its git source?

**Comment by NickLion** [comment]
Yes, sorry for delay, currently using locally built and installed f5200a2.

**Comment by tsujan** [comment]
> currently using locally built and installed

And it still happens?

**Comment by NickLion** [comment]
Sadly, yes.

**Comment by tsujan** [comment]
Very strange! For a full day, I used Krusader as my file manager (reluctantly, because it doesn't have some things I need) and encountered no problem.

**Comment by NickLion** [comment]
@tsujan I believe it depends on some settings, I'll try to detect which one (or combination).

**Comment by tsujan** [comment]
> I believe it depends on some settings

Please tell me if you find them. Theoretically speaking, I can't think of any setting in any app that could cause a problem in Kvantum but practically -- who knows? -- weird things can happen ;)

**Comment by tsujan** [comment]
Ok, a shot in the dark (based on the theory of "weird-things-in-codes"):

I added a commit based on the following assumptions -- please test again with the latest git Kvantum!

Your attached log showed a problem with `qt_qFindChildren_helper`, which is a private function belonging to Qt. So, I jumped into conclusion by assuming that, somehow, Krusader creates hundreds of thousands of child objects after a while (in which case, it should have a *serious* bug). Therefore, instead of searching all of its child objects, I changed the code so that only its immediate child objects are searched.

The commit in question is a small optimization for all cases and is generally good.

**Comment by NickLion** [comment]
Well you are good at shooting in the dark :) Thanks! Krusader looks fine with this change, tested during a couple of days. So I'm closing this bug as with this optimization it's not seen anymore (and it's not a Kvantum bug after all). Bad thing is I still haven't found exact reason for this Krusader behaviour, but that's for Krusader bug report. Thanks again!

**Comment by tsujan** [comment]
Thanks for your confirmation!

Krusader should have a memory leak. However, Kvantum shouldn't be affected by such cases. That wouldn't come to my mind without your good report.
