### ISSUE TITLE
rename bug with enabled alpha channel base color

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#234]
Bug reproduced If use `base.color` with alpha channel on Dolphin:
for example `base.color=#30303082`
result (rename `test test` to `123 123`):
![image](https://user-images.githubusercontent.com/8083855/43379836-851efc16-93df-11e8-973b-98af40cdaf2c.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/materia-kde/issues/18

**Comment by varlesh** [comment]
Theme:
[MateriaBlur.tar.gz](https://github.com/tsujan/Kvantum/files/2239849/MateriaBlur.tar.gz)

**Comment by tsujan** [comment]
> if use base.color with alpha channel on Dolphin

Please *never* do that! Quoting myself in `Theme-Making.pdf` → `Dealing with exceptions`:

"(3) Always use an opaque color for `base.color` (under `GeneralColors`); otherwise, item-views of some applications might show what is “behind” them (because of a bug in those applications)."

Thanks!

**Comment by tsujan** [comment]
The problem can happen anywhere, not just in Dolphin. Read `Theme-Making.pdf` → `Dealing with exceptions` to know why such problems happen.

**Comment by tsujan** [comment]
Good news:

I may have found a way to save your theme, as far as possible. I'll make a commit after some tests and will tell you when it's ready.

Reopening...

**Comment by varlesh** [comment]
Big thx @tsujan  :)

**Comment by tsujan** [comment]
@varlesh Finding a workaround for all apps may be impossible but I'll try my best to add a workaround for Dolphin at least.

**Comment by varlesh** [comment]
ok :+1:

**Comment by tsujan** [comment]
Done! Please test the latest git Kvantum and tell me the result! If it's successful, you could tell your users to install the latest git Kvantum.

Please note that a translucent base color is still tricky and can result in strange things here and there. However, I liked the risk you'd taken. So, please tell me if anything goes wrong! I might not be able to find a workaround but I could try at least ;)

BTW, I think Kvantum is the only widget style that partially supports translucent base colors :)

**Comment by varlesh** [comment]
Ok, i try it now

**Comment by varlesh** [comment]
I check this with Dolphin and KTorrent and this worked fine!!!!
You are a wizard and awesome!!! Very Cool. Big thx :smiley:

**Comment by tsujan** [comment]
Thank you for testing! In future, I might find a better way of detecting special widgets for removing base translucency from them.
