### ISSUE TITLE
Header hack detection if needed

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#236]
Borders on header widget sometime superimposed on window borders. Then we have two borders. It's not good looking if we want tiny (1 px) borders for all widgets.
For example, on my theme Materia Blur i'm hack this manually, but not good way - i'm disable `header-normal-top` (make transparent or draw as window color without border):
![image](https://user-images.githubusercontent.com/8083855/43438678-8d13b68e-94a0-11e8-9209-646bceab9276.png)
If use normal border i'm have two borders - border window and header:
![image](https://user-images.githubusercontent.com/8083855/43438735-ccd99360-94a0-11e8-9026-d330c1b54bdd.png)
I know, it's not kvantum issue, but maybe this posible hacked? I mean if header widget not superimposed on window - kvantum fix that.
Also this happened with left and right header borders.

**Comment by varlesh** [comment]
It's not critical for me, because mostly apps looking good... :)

**Comment by tsujan** [comment]
You want something like this:

![header](https://user-images.githubusercontent.com/981076/43439486-a916064a-94a8-11e8-8054-82feec8fcb67.png)

Am I right? If so, it's already possible (the above screenshot is a modified Kvantum theme). You could try this: 
```
[HeaderSection]
inherits=PanelButtonCommand
interior.element=header
frame.element=header
frame.top=0
frame.bottom=1
frame.left=1
frame.right=1
...
```
Then, make the elements `header-normal-left` and `header-normal-right` completely transparent in the SVG file and add the element `header-separator` if it doesn't exist. (There are other ways too)

There will be a minor drawback in list-views but it's tolerable.

Tonight (or tomorrow), I might edit `KvCommunitheme` to make it like the above screenshot.

Was the above explanation helpful?

**Comment by varlesh** [comment]
Yes, i know about `frame.top=0` - it's similarly solution as use transparency or window color for `header-normal-top`.
But i think it's application bug, because mostly popular apps good working.
Qmmp draw strange widgets:
![image](https://user-images.githubusercontent.com/8083855/43440144-4a91068e-94a7-11e8-8e56-1be8874c6789.png)
Thx for header-separator, it's very good solution)))
Sorry for disturb you and thx for help.
closed

**Comment by tsujan** [comment]
Oh, yes, that's a (small) problem in Qmmp and is visible with Fusion too:

![qmmp](https://user-images.githubusercontent.com/981076/43440636-4839cda2-94ad-11e8-8198-6ce497d58ed1.png)

BTW, I found and fixed (worked around) some rare issues with translucent base colors. I'll make a commit tonight (or tomorrow) for them.

**Comment by tsujan** [comment]
Not related to this: IMHO, `audacious-qt5` + `audacious-plugins-qt5` is much better and cleaner than Qmmp. It's available on AUR (Arch git repository) -- I don't know about other distros.
