### ISSUE TITLE
build for Qt5 and Qt4 together

### ISSUE THREAD

**Issue by KottV** [tsujan/Kvantum#24]
Greetings, and thank you for this nice engine!

I think, it's time to make separate qt5 and qt4 options in build instruction, thus we can build both libraries at same time. It would very-very usefull for automatic build system (no requirements for separate builds).
I guess it  possible with cmake only(or autotools), but maybe there is a more easy way.

**Comment by tsujan** [comment]
I use this rules file for making a deb package that contains both plugins for Debian: https://dl.dropboxusercontent.com/u/7793460/rules
By contrast, most package maintainers (deb, rpm, arch) prefer separate packages for Qt4 and Qt5.

**Comment by tsujan** [comment]
Oh, you mean something like cmake. It occurred to me but I've always preferred qmake over cmake. However, I'll think about it.

**Comment by KottV** [comment]
Let me explain why i put this issue :)
rpm cannot have two build sections in spec file (macros for build and packaging), so i have to prepare two different package build sets, that's not critical, but inconvenient a bit

**Comment by KottV** [comment]
but, in single spec very possible to separate compiled and installed files with dependencies in different packages

**Comment by tsujan** [comment]
> rpm cannot have two build sections in spec file...

Are you sure about that? I thought the same thing about deb but it turned out to be wrong after I experimented with the rules file (the counterpart of spec file). That was the reason I added a link above. 
For now I have no rpm based system to test but I may install one on VirtualBox when I have free time.

**Comment by tsujan** [comment]
To be more specific, I added the Qt5 build/installation AFTER the Qt4 one and apparently in the installation section of the rules file. And that worked. distclean was an asset.

**Comment by KottV** [comment]
I did a dirty hack to workaround. Put make install (qmake, make, make install, make distclean, qmake-qt5, make, make install) in %build section and leave %install section empty. On local machine that's worked:)
Will try on build server later. But, I still think it's not nice way :)

**Comment by tsujan** [comment]
I'd call that an elegant innovation instead of a "dirty hack" ;)
However, I'll try to add a cmake file as I don't think cmake and qmake are mutually exclusive.

**Comment by tsujan** [comment]
I'm working on CMakeLists files but that alone would make no difference for packaging unless Kvantum is divided into two separate directories, one for Qt4 and the other for Qt5 (like in QtCurve). That division is something I've avoided from start.

As far as I see, the distclean trick in the rules/spec file is the best approach but if you know of a better one (without separate Qt4 and Qt5 branches), please tell me.

**Comment by KottV** [comment]
Well. I think, no one will kill me, if i use such trick in build service. So, there the packages for openSUSE: http://software.opensuse.org/package/kvantum

**Comment by tsujan** [comment]
OK. Just a suggestion: The doc folder in the source (containing documentation on theme config and theme making) could go the doc installation folder.

After reading the spec file decription section, I realized that I shouldn't have referred to QuantumStyle when describing Kvanum in README. I'll change that later. This is the description I use in the deb package:

    Kvantum is an SVG-based theme engine for Qt4/Qt5 and KDE. It has a default dark theme but goes far beyond it: you could make themes with very different looks and feels for it and Kvantum will let you control almost every aspect of Qt widgets.

**Comment by KottV** [comment]
I added extra documentation to -doc package and changed description

**Comment by tsujan** [comment]
Excellent!

**Comment by tsujan** [comment]
CMake support is added (mainly for Fedora, that has problem with qmake). Closing this.
