### ISSUE TITLE
Colors fields on Konsole colors edit window

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#25]
Hi @tsujan , I found a problem in Konsole profile editor, specifically on colors edit window. It seems that Kvantum engine is not properly treating the colors fields, see:

#### Oxygen style:

![Kvantum print](http://i.imgur.com/ReumYoP.jpg)

#### Kvantum style:

![Kvantum print](http://i.imgur.com/WtHrYIY.jpg)

**Comment by tsujan** [comment]
Wow! That's a hell of a bug! I'll investigate it now. Thanks a lot!

**Comment by tsujan** [comment]
It's fixed now.
Thanks again for telling me about it! Please close this issue after confirming the fix.

**Comment by franksouza183** [comment]
It works, many thanks!

**Comment by tsujan** [comment]
Yet another fix: Now the text colors of such view-items are also correct. See ksysguard for an example (the only one I could find).

**Comment by franksouza183** [comment]
Ok, testing ...

**Comment by franksouza183** [comment]
Now the big question: how I define these colors? Cyan exploded my eyes XD

![Kvantum print](http://i.imgur.com/yxPdeZC.jpg)

**Comment by tsujan** [comment]
Those colors are defined in ksysguard's code and I can't find anywhere to set them.
Before your reported this bug, they weren't drawn at all with Kvantum but now they are. I just removed their alpha channels to be able to decide on their text colors.

**Comment by franksouza183** [comment]
All right! Anyway, it's a great improvement, many thanks!

**Comment by tsujan** [comment]
You're welcome!
