### ISSUE TITLE
No deb packages for 10.0.6 and later?

### ISSUE THREAD

**Issue by douglasg14b** [tsujan/Kvantum#253]
Came here to grab a .deb for Ubuntu and noticed that there are none for 10.0.6 and later.

**Comment by tsujan** [comment]
No, because I'm not a Debian for a long time. But Kvantum deb packages will be made for Debian experimental soon -- they may already exist but I'm not a good source of info in this regard ;)

**Comment by douglasg14b** [comment]
https://launchpad.net/~papirus/+archive/ubuntu/papirus  seems to maintain one
