### ISSUE TITLE
[wishlist] allow separate style for bottom/right tabs

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#255]
With some themes (QTStep for example), neither using the top tabs as is, nor mirroring them looks right. how about something like an optional 'tab-south/west/east-normal' framesvg?

**Comment by tsujan** [comment]
Adding separate images for non-top tabs (and other widgets that can have different orientations) would bloat the code and the SVG image alike. Moreover, it could result in various issues in the case of some widgets.

There are enough parameters that can change how non-top tabs are drawn, like `attach_active_tab` and `mirror_doc_tabs` -- if the first is `true` and the second is `false` and if the top tabs are raised, then the LTR right and bottom tabs will be sunken, and conversely. This symmetry is quite logical and acceptable, IMO.

I downloaded and tried QTStep a few minutes ago. IMO, its tabs are OK (raised → sunken):

![qtstep](https://user-images.githubusercontent.com/981076/45439021-fdf45800-b6cd-11e8-8193-518312287a5a.png)

BTW, I was impressed to see how many Kvantum themes you've made with that motif :)
