### ISSUE TITLE
`active_tab_overlap` doesn't work with separators and `no_active_tab_separator=true`

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#256]
there is the option 'active_tab_overlap', which allows for chromium-like tabs, but only for active tabs. why not also for inactive tabs?

btw,
i tried to emulate this by using tab separators + no_active_tab_separator, but when i set active_tab_overlap=true, active_tab_overlap doesn't seem to work anymore.

**Comment by tsujan** [comment]
Sorry to say that it isn't feasible.

`active_tab_overlap` is among Kvantum properties that I was able to enforced -- Qt doesn't have such a parameter -- and there is a lot of code in Kvantum source for it. It may be possible to add it for inactive tabs but the amount of the required code frightens me ;)

**Comment by andbgr** [comment]
would it be possible to make active_tab_overlap work when separators are present and no_active_tab_separator=true?

or if not, maybe add something to the documentation that these two options don't work together

**Comment by tsujan** [comment]
> would it be possible to make active_tab_overlap work when separators are present and no_active_tab_separator=true?

Interesting! I should think about it or remember probable reasons why I made it so. Reopening for now.

**Comment by tsujan** [comment]
It *was* a bug: I'd added the key `no_active_tab_separator` later but forgot to take it into account in this case. It's fixed in https://github.com/tsujan/Kvantum/commit/26f5b90c66d4cb661ced7a15917145b489f75589 . Please update to the latest git version!

Thanks for finding and telling me about it!
