### ISSUE TITLE
[wishlist] center_scrollbar_handle

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#258]
i feel bad for posting so many at once...

scrollbar indicator size only affects width (assuming horizontal scrollbar) of the indicator, but height is stretched to the full height of the scrollbar. i made a round dot as an indicator, so i worked around this by using an invisible rectange, but i'll have to change that rectangle if i change the scrollbar size.

i propose something like center_scrollbar_handle, analogous to center_toolbar_handle, which would make height=width.

**Comment by tsujan** [comment]
> i feel bad for posting so many at once...

Don't feel bad! I'll examine all your reports, one by one, whenever I find time.

Reports may show problems to fix and even if not, the explanations that close them could serve as references in case similar reports are made.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/0fc61af5517e2d4fcc9cf6a2d7c74da769c4c699

The key is `center_scrollbar_indicator` and is `false` by default. Thanks for the suggestion!
