### ISSUE TITLE
different indicator for editable combos when combo_as_lineedit=true

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#260]
the issue: if there is a high contrast between combo and lineedit colors, the combo indicator of editable combos may be invisible if combo_as_lineedit=true.

possible solution:
use an indicator specified under [LineEdit] for editable combos only when combo_as_lineedit=true?

(for an example, look at the QTStepBrownpunk theme)

**Comment by tsujan** [comment]
> for an example, look at the QTStepBrownpunk theme

I will but do you know about "flat indicators" (Theme-Making.pdf → “Flat” Indicators and High Contrast)?

**Comment by tsujan** [comment]
OK, I tool a look at QTStepBrownpunk. You should add something like this (last line):
```
[LineEdit]
inherits=PanelButtonCommand
frame.top=2
frame.bottom=1
frame.left=2
frame.right=1
frame.element=lineedit
interior.element=lineedit
indicator.element=view-arrow-down
```
Or you could add a special indicator element for it (not needed).

Then:

![qtstepbrownpunk](https://user-images.githubusercontent.com/981076/45444240-326f1080-b6dc-11e8-9f01-655102287a7d.png)

QTStepBrownpunk is what I call a light-and-dark theme. Qt doesn't support such themes but I've tried my best to enforce them. Please tell me if you encounter any problem with them! This one wasn't a real problem.

**Comment by andbgr** [comment]
correct me if i'm doing this wrong, here's what i currently do:

use 'arrow'  (colored like button text) for all widgets that use button background colors

use 'flat-arrow' (colored like window text) for all widgets that use window background colors (like menus)

use 'view-arrow' (colored like view text) for all widgets that use view background colors (currently only vertical spin indicators which are also drawn entry-style, but this one i'd use for entry-style combos if i could)

**Comment by andbgr** [comment]
oh, apologies.
for some reason i assumed this didn't work, but it does.
will fix it in my theme, sorry for the waste of time.

**Comment by tsujan** [comment]
> for some reason i assumed this didn't work, but it does

Believe me when I say that I've tested myriads of combinations. I too may sometimes think there's a problem but later I find that my SVG image or kvconfig file is wrong ;)

That being said, I'll be glad if such bugs are found and reported -- because I'll have something to fix :D
