### ISSUE TITLE
KvAmbiance capacity bar broken

### ISSUE THREAD

**Issue by Ivanwah91** [tsujan/Kvantum#263]
I've noticed that the capacity bar in the KvAmbiance theme displayed text incorrectly:

![capacity_bar_broken](https://user-images.githubusercontent.com/43323519/45601363-04573c80-ba0c-11e8-9d56-40144985bdc3.png)

Upon further investigation, I found out that there is a possible typo in the config file. It says `progressbar_thickness=3font`. If I change that to `progressbar_thickness=font` it displays correctly:

![capacity_bar_fixed](https://user-images.githubusercontent.com/43323519/45601378-5ac47b00-ba0c-11e8-8396-9d353716dc31.png)
I don't know if that was a typo or if the value `3font` is supposed to do something different than `font`, but so far everything works fine with that change.

**Comment by tsujan** [comment]
First, thanks for reporting!

This should be a Kvantum bug that appears with some fonts. I'll fix it soon.

> I don't know if that was a typo

No, it isn't a typo. `progressbar_thickness=3font` means that the *maximum* progress thickness is 3 times the font height.

**Comment by Ivanwah91** [comment]
Thanks for the quick reply. I'll leave it at `font`for now since it works well for me, but I'll experiment with some other fonts. The one I'm using is Open Sans, if that helps you in any way.

**Comment by tsujan** [comment]
Fortunately I was able to reproduce it with Noto. It doesn't happen with Dejavu, for example.

**Comment by Ivanwah91** [comment]
I think it depends on the size of the font. It happens to me with DejaVu if I set it to size 10 or higher but if I set it to 9 or lower it displays correctly. With Open Sans if I set it to anything higher than 8 it's bugged. Ubuntu font works with size 10 or lower.
If I have to guess I think it has something to do with how high Dolphin allows elements to be in its status bar.

**Comment by tsujan** [comment]
> I think it depends on the size of the font.

You're right.

> If I have to guess I think it has something to do with how high Dolphin allows elements to be in its status bar.

Exactly! Dolphin enforces a height there. The fix is easy but I found a flaw in progressbar height calculations; it isn't related to capacity bars and may not be detectable but I prefer to fix everything in a single commit.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/8e793e27a85438d3c18bf572e67fd9290db4b9e7

Thanks again for reporting this bug!

If you test the latest git Kvantum and see the problem again, please tell me to reopen this!

**Comment by tsujan** [comment]
Good to know that! I tested with various fonts but forgot about font sizes.
