### ISSUE TITLE
Ubuntu's "Yaru"

### ISSUE THREAD

**Issue by tsujan** [tsujan/Kvantum#264]
Ubuntu's "Communitheme" is renamed as "Yaru". Small changes are made too. It may be a good time to update Kvatum's "KvCommunitheme". I won't change its name -- it shows the origin of Yaru, after all, and who knows, they may change "Yaru" too.

**Comment by CDrummond** [comment]
Please, consider adding a KvYaru - that way with QGnomePlatform it will automatically be used.

**Comment by tsujan** [comment]
@CDrummond Do Ubuntu users know about Communitheme → Yaru? I found it only yesterday but if they do, KvYaru is OK with me -- I don't want symlinks (one them with 2 names).

BTW, strange that GTK3 "inactive" states don't work under KWin or Compiz-reloaded (they did work before)! I had to take screenshots from inside Gnome a few minutes ago.

**Comment by CDrummond** [comment]
Yes. Communitheme was **only** the development name. When it is released (as part of 18.10) it will by Yaru. There is no more Communitheme.
