### ISSUE TITLE
Use the local color setting from the applications

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#265]
Some KDE apps like Kate, Krita... when you use Breeze, you can use another color scheme for them instead of the global setting. (E.g. Kate, go to Setting > Color Setting) But Kvantum overrides that setting.
Can you make Kvantum use such that setting from the applications ?

**Comment by tsujan** [comment]
The developers of apps like Kate, Krite... think in terms of KDE's GUI limits. Frankly, if I was satisfied with those limits, I wouldn't think about an SVG style engine, whose colors go beyond a simple color scheme (although each Kvantum theme should have one in its `kvconfig` file).

That being said, you could always assign different themes to different apps by using Kvantum Manager.

**Comment by tsujan** [comment]
An example of theme assigning:

![example](https://user-images.githubusercontent.com/981076/45924437-10139900-bf0d-11e8-9033-7eecb22310ff.png)

Here, different Breeze title-bars are also assigned by using `systemsettigs5 → Window Management`.

**Comment by AchmadFathoni** [comment]
In Linux you can force krita to respect kvantum's theme by using this comman
`KRITA_NO_STYLE_OVERRIDE=1 krita`

**Comment by tsujan** [comment]
Yes, I've set `KRITA_NO_STYLE_OVERRIDE` to 1 at session startup for a year or so -- this page was made in 2018. Krita doesn't have any problem with window translucency here, although I mostly use GIMP.

**Comment by AchmadFathoni** [comment]
> Yes, I've set `KRITA_NO_STYLE_OVERRIDE` to 1 at session startup for a year or so -- this page was made in 2018. Krita doesn't have any problem with window translucency here, although I mostly use GIMP.

Well, my newest Krita 4.3.0 have opaque windows by default. If I remember correctly the previous 4.2.9 is the last version that respect Kvantum's theme.

**Comment by tsujan** [comment]
I have Krita 4.3.0 too.

Since I don't use Krita (I have it only to check some things once in a while), I can't be sure that it's 100% OK with translucency but I haven't encountered any problem.

Anyhow, the opaque list can always be used with apps that have bad problems with translucency.

**Comment by AchmadFathoni** [comment]
here the Krita comparison:
Without tweak
![bad](https://user-images.githubusercontent.com/26775746/87786042-7ea0b400-c863-11ea-9515-a75949126ebc.jpg)
tweaked
![good](https://user-images.githubusercontent.com/26775746/87786066-895b4900-c863-11ea-9ecf-eacd2c78c087.jpg)

**Comment by tsujan** [comment]
It seems we're talking about different things.

I only mean that, with `KRITA_NO_STYLE_OVERRIDE` set to `1` (which, of course, makes Krita respect the active widget style, like a normal app), Krita has no problem with Kvantum's window translucency here, so that, I don't need to put it in the opaque list.

**Comment by AchmadFathoni** [comment]
`KRITA_NO_STYLE_OVERRIDE=1`  is buggy now. It seems like it converts all my mouse input on canvas to middle click. I can't draw anything because my canvas is getting dragged when I try to. Can anybody confirm this?

**Comment by tsujan** [comment]
Which version of Krita? Here, Krita 4.4.3 is OK with `KRITA_NO_STYLE_OVERRIDE=1`.

**Comment by tsujan** [comment]
> Do you think that this problem have any relation with kvantum?

I can see no problem here. `KRITA_NO_STYLE_OVERRIDE` is set to `1` and the app style is the latest version of Kvantum.

**Comment by AchmadFathoni** [comment]
> > Do you think that this problem have any relation with kvantum?
> 
> I can see no problem here. `KRITA_NO_STYLE_OVERRIDE` is set to `1` and the app style is the latest version of Kvantum.

Well, I able to narrow it down even more. Using any kvantum's default theme fix this problem, except my modified KvAdaptaDark.

**Comment by tsujan** [comment]
Please attach your modified KvAdaptaDark as a zip file for me to see whether I could reproduce the issue with it.

**Comment by AchmadFathoni** [comment]
Here https://filebin.net/o66sk4ifqn5uj8g2

**Comment by tsujan** [comment]
Oh, you've enabled "Kinetic scrolling" in your modification. As its tooltip says:

```
Warning: Qt's kinetic scrolling has bugs and may
seriously interfere with other jobs.
```
Disable "Kinetic scrolling" and there will be no problem.

I don't think such cases can be excluded from kinetic scrolling by the code but I'll do some tests.

Thanks!

**Comment by tsujan** [comment]
I excluded Krita's painting window and some other widgets from kinetic scrolling: https://github.com/tsujan/Kvantum/commit/e941cdd7dc36ec5c762c4678a014a3c6b47efadf

Now, kinetic scrolling can be used with Krita.
