### ISSUE TITLE
X11 independent "X11 Drag" for Qt≥5.11

### ISSUE THREAD

**Issue by tsujan** [tsujan/Kvantum#268]
Qt 5.11 has new bugs related to X11 and, as a result, the X11 drag shows a problem that isn't in its code and can be seen with Breeze too.

Since Qt's X11 bugs haven't been (completely) fixed in recent years, I don't think they will be fixed ever. So, I should make the X11 drag independent of X11 by using a method I learned from @CDrummond -- with small changes.

There is no need to change the name "X11 Drag" because (for now) `QWidget::move()` doesn't work under Wayland (a serious Wayland/Qt issue).

**Comment by trmdi** [comment]
Just curious, can you show me how to see the bug? Or give me the link that describles the bug?

**Comment by tsujan** [comment]
The bug -- which didn't exist before Qt5.11 -- can be reproduced in the following way inside KDE, with Breeze and Kvantum alike:

(1) Drag a window from its menubar, toolbar or anywhere possible but NOT from its titlebar;
(2) After dragging is finished, put the mouse cursor over a button without clicking -- or over a widget that has tooltip.

The result: there will be no hover effect -- or no tooltip will be shown -- until you click on an empty space inside the window.

I'd [reported](https://bugreports.qt.io/browse/QTBUG-69081) a more important form of this bug and it was fixed in Qt 5.11.2. However, in my report, I'd said that my descrition was "a simple way – but not the only way – to reproduce the issue". Most Qt devs don't know what "X11 drag" means and I have no time to explain.

**Comment by tsujan** [comment]
Since Qt5 was started, there has been so many bugs related to X11, none of which existed in Qt4. Some are fixed, some not, but the bad thing is that, once in a while, another X11 related bug shows up or, worse, a fixed one reappears again.... I'v got tired of reporting.

**Comment by trmdi** [comment]
Ok, I got it. I think they are like you who have lots of things to do, so they can't be aware of all bugs, they need help from the community. There is no deadline in the free software world. So, just relax and help the community when you have free time. For a better world. :D

**Comment by tsujan** [comment]
> I think they are like you

I don't judge persons but their works. In the case of Qt, the work is done by so many devs and I can't tell who has done the good work and who is doing it bad. But I can tell what's good and what's not: Qt5's X11 hasn't been good so far.

**Comment by tsujan** [comment]
Read [this](https://bugreports.qt.io/browse/QTBUG-36862?focusedCommentId=368105&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-368105) just as one example among several and you'll know why I'm tired ;)

**Comment by tsujan** [comment]
I close this because no workaround was possible as far as I tested various methods -- and they were so many ;)

**Comment by tsujan** [comment]
After hours of stubbornness, I found a beautiful workaround, which works under KWin at least (KDE devs should make a similar change if they become aware of the problem).

Technically speaking, although `QWidget::move` is buggy, `QWindow::setFramePosition` works like a charm with the native handle of the window (not widget).

Will test it for a few days before committing.

**Comment by tsujan** [comment]
Workaround added in https://github.com/tsujan/Kvantum/commit/d6df3a340e3bf86b3258562c4296fa7b31edef4b

It works even under Enlightenment, so it should work everywhere.

**Comment by andryNoor** [comment]
It works, but some kwin Desktop Effects don't work properly. (e.g Translucency Effect, when dragging from any empty space, the Effect doens't work)

**Comment by tsujan** [comment]
> e.g Translucency Effect, when dragging from any empty space, the Effect doens't work

But I made, tested and am using it under KWin and with a translucent theme. Translucency and blurring are OK here.

Could you please be more specific and describe the steps to reproduce the issue you see?

**Comment by tsujan** [comment]
Oh, if you mean the effects that are related to moving windows from their title-bars, they are related to how kwin manages X11 and shouldn't be seen with this new dragging. The new dragging is *purely* based on Qt and if, at some time, the current problems in KDE/Qt's Wayland support are fixed, it'll work under Wayland too.

However, all Kvantum's effects -- including translucency -- work with the new dragging.

**Comment by andryNoor** [comment]
I'm using your KvMojave, too (I love it).

BlurI mean Translusency Effect in KDE Plasma System Settings

> > e.g Translucency Effect, when dragging from any empty space, the Effect doens't work
> 
> But I made, tested and am using it under KWin and with a translucent theme. Translucency and blurring are OK here.
> 
> Could you please be more specific and describe the steps to reproduce the issue you see?

I'm using your KvMojave, too (I love it).

I mean Translusency Effect in KDE Plasma System Settings. not Kvantum effect.
1). I activate Translucency Effect and Wobbly Windows in System Setting > Desktop Behavior > Desktop Effects
2). Translucency and Wobbly effects work fine when moving from their titlebars, but not from their empty space.

I recorded it, here is the video https://streamable.com/44s0t
