### ISSUE TITLE
Icon size problem  on KDE system settings

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#27]
It seems there is a problem with the Kvantum themes affecting the icons sizes in KDE system settings, where it are not following the size settings defined in the "Advanced" tab on icons settings module, look:

![Kvantum print](http://i.imgur.com/ditaKIY.png)

**Comment by tsujan** [comment]
Interesting observation! I'll look into it tomorrow. Thanks for reporting!

**Comment by franksouza183** [comment]
Many thanks!

**Comment by tsujan** [comment]
I got some time to solve this riddle. It wasn't a bug. Non-KDE themes like Cleanlooks behave the same way. Being independent from KDE, Kvantum follows Qt rules for icon sizes and not the KDE ones.

However, I considered this case as a feature request and made an exception for it. Now Kvantum behaves like Oxygen and QtCurve. You should just quit and run systemsettings to see that the sizes of those icons change now.

**Comment by franksouza183** [comment]
Awesome! Testing right now ...

**Comment by franksouza183** [comment]
Works like a charm:

![Kvantum print](http://i.imgur.com/APv2ZQ9.jpg)

Many thanks for the improvement, every day Kvantum is more perfect!

**Comment by tsujan** [comment]
You're very welcome and thanks for your suggestions! So I close this issue.
