### ISSUE TITLE
Text alignment needs to be adjusted according to KDE's new HiG redesigns 

### ISSUE THREAD

**Issue by flipwise** [tsujan/Kvantum#280]
Hi there,

Kvantum (and other widget styles) needs to be adjusted because the KDE's new design style of configuration widows unforunately only looks alright with a particular kind of alignment. This new style is present in Dolphin, some System Settings kcms and possibly some other configuration windows of programs. 

See the bug I've reported here: https://bugs.kde.org/show_bug.cgi?id=400235

This is what it's supposed to look like: 
![image](https://user-images.githubusercontent.com/26850445/47440947-76f7cc80-d7af-11e8-8a45-dd9165190fef.png)

This is how Kvantum and some other widget styles align it:
![image](https://user-images.githubusercontent.com/26850445/47440767-22545180-d7af-11e8-92b2-fa27eb7ef61a.png)

**Comment by tsujan** [comment]
There is nothing wrong with the second screenshot. And there is no global way of aligning texts in all widget styles. Each widget style can align widget texts in its own way. Actually, in Kvantum, each Kvantum theme can have its own alignments.

The words "looks alright" (in this report) and "affected/unaffected" (in your KDE report) don't make much sense in this regard.

**Comment by flipwise** [comment]
I was trying to point out that these gaps that now occur between the option text and the option itself are not good UI design. The redesign is done in a way that can only look good if the alignment of the text is on the right, as they've set it for Breeze.

![screenshot_20181024_184851](https://user-images.githubusercontent.com/26850445/47447493-ef658a00-d7bd-11e8-9ee4-ae88d95d66e6.png)

**Comment by Pointedstick** [comment]
So this is an issue with the particular Kvantum theme in use and not the Kvantum theming engine itself?

**Comment by tsujan** [comment]
> So this is an issue with the particular Kvantum theme in use and not the Kvantum theming engine itself?

This isn't an issue at all. Each style has its own metrics. Kvantum makes most of them configurable. Presupposing constant values for QStyle parameters (as some devs do) is wrong.

**Comment by tsujan** [comment]
> I was trying to point out that these gaps that now occur between the option text and the option itself are not good UI design.

That GUI isn't designed by me -- although it has no problem: everything is neatly left-aligned in all columns.

**Comment by flipwise** [comment]
> So this is an issue with the particular Kvantum theme in use and not the Kvantum theming engine itself?

All of the default Kvantum themes I've tested behave the same, and Arc and Adapta as third-party themes as well.

**Comment by flipwise** [comment]
I also see now that the checkboxes are not properly vertically aligned with their respective text. Even if we claim that alignment of the text of the left is okay, this is definitely a regression. They're tilted upwards and this happens with the other widget styles that haven't adapted to the redesign.

**Comment by tsujan** [comment]
> They're tilted upwards and this happens with the other widget styles that haven't adapted to the redesign.

I really don't know what you think about what you call "redesign" but I can't take responsibility for others' works, good or bad.

BTW, the word "regression" joins the other words I mentioned above; it has a precise meaning that apparently you don't care about.

**Comment by flipwise** [comment]
It was simply properly aligned before and now it's not. Have a look at the comparison between Oxygen and Kvantum:

![screenshot_20181024_193804](https://user-images.githubusercontent.com/26850445/47450110-a5cc6d80-d7c4-11e8-9dc2-27198ff31434.png)
![screenshot_20181024_193405](https://user-images.githubusercontent.com/26850445/47450111-a5cc6d80-d7c4-11e8-8f5e-e299b1ce8cdd.png)

I'm just posting here based on the forwarding info I got from KDE because it seems like they can't address this.

**Comment by tsujan** [comment]
That only means this: https://github.com/lxqt/lxqt/issues/1433 . Please read my explanation in the first commit and ignore QML.

A correct UI:

![alignment](https://user-images.githubusercontent.com/981076/47450485-35c4e400-d7d2-11e8-82b0-79d73bc77ce6.png)

**Comment by cfeck** [comment]
See QStyle::SH_FormLayoutLabelAlignment

**Comment by tsujan** [comment]
It's `Qt::AlignLeft` in kvantum (inherited from `QCommonStyle`) and every Qt designer should consider that it can be anything in any style plugin, as clearly explained in https://github.com/lxqt/lxqt/issues/1433.

**Comment by tsujan** [comment]
I just quote myself -- the main part:

"Don't presuppose any fixed value for any QStyle parameter -- whether it is an integer, a color or a Boolean -- because it is a PARAMETER!"

**Comment by flipwise** [comment]
Actually it seems that I've made the mistake attributing it all to a redesign; there were already design elements in KDE before that ideally asked for a right alignment, it's just that from what I'm seeing they're more prominent now with the change to the HiG and applying it in various places = trying to be consistent. 

Either way it's a bit unfortunate and it would be ideal if either the HiG didn't ideally presuppose a right alignment or if all the widget styles could be adjusted for this, but it's not the end of the world. Thanks for looking into this.

**Comment by tsujan** [comment]
> if all the widget styles could be adjusted for this

The best thing about Qt is that it's highly flexible. That's true with `QStyle` too. And that's why Kvantum is possible. That kind of "adjustment" would mean poorness. Fortunately, it isn't possible.

It's Qt designers'/developers' responsibility to respect this flexibility/richness in their codes. Bad news: some don't. Good news: it's completely possible.

**Comment by flipwise** [comment]
Maybe it can be somehow handled in the KDE code without changing their design vision. In certain places such as in the fonts settings module the text is, strange enough, aligned on the right.

![image](https://user-images.githubusercontent.com/26850445/47453931-2e034080-d7ce-11e8-9cff-07c1f89a535a.png)
