### ISSUE TITLE
[Request] Help to make a new theme.

### ISSUE THREAD

**Issue by Ste74** [tsujan/Kvantum#282]
Hi there, i m a part of Manjaro linux core team. In all of our editions ( official and community ) we use kvantum to manage the style with gtk and qt applications.
Recently adapta theme was dropped from the author so we have started a little search to find other themes gtk based desktop. After some research we have found [matcha theme](https://github.com/vinceliuice/matcha) in the **sea** variation. So i have started a little project to hack [arc-kde theme](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/Kvantum) to match with matcha-sea theme.
[Here](https://gitlab.manjaro.org/artwork/themes/kvantum-manjaro/tree/devel/Kvantum/KvMatchaSea) i have uploaded my work but i have two issue at the moment: 
i can't see the description of kvantum on the main page of the application
![matcha-message](https://user-images.githubusercontent.com/11218234/47460449-d3261500-d7de-11e8-9bfb-f85a9606d61c.png)
and i can't see the topbar box
![matcha-box](https://user-images.githubusercontent.com/11218234/47460537-05d00d80-d7df-11e8-99f1-97dad4a3e0ec.png)
Can you take a look and help us ?

Thank you in advance 
Stefano Capitani
Manjaro Linux

**Comment by tsujan** [comment]
Hi,

> i m a part of Manjaro linux core team

And I am a Manjaro user :)

> Can you take a look and help us ?

With pleasure! I've done that before.

I may be busy for a short time but will definitely look into it.

**Comment by Ste74** [comment]
Thank you so much :smile: and good to know you are a manjaro user :wink: ..
If you need access at the repository please ping me and we can do it :wink:

**Comment by tsujan** [comment]
I've never used gitlab (am not a member either). If it was on github, I could make a PR. Is it the same on gitlab -- same commands and same methods?

Anyway, I could attach it as a zip file here. So, there will be no problem.

**Comment by tsujan** [comment]
Done. The theme is attached as a zip file.

Sometimes Kvantum themes are as complex as GTK themes. I added some elements, corrected SVG frame widths (they should be proportional to frame sizes of the kvconfig file), made use of SVG cloning, and modified the kvconfig file (added/changed some keys) but kept the look and feel as it was.

Don't forget to set the KDE title-bar color (in the color scheme) to the toolbar color (I didn't include the color scheme). 

If you have any question, feel free to ask me.

[KvMatchaSea.zip](https://github.com/tsujan/Kvantum/files/2513636/KvMatchaSea.zip)

**Comment by Ste74** [comment]
Hi, sorry for delay..
i'm a little busy with my real work.. Thank you i package it and pushing in our repo 

> Don't forget to set the KDE title-bar color (in the color scheme) to the toolbar color (I didn't include the color scheme).

do you mean :p ? I always use gnome DE, never used  others DEs for a long time :p..

**Comment by tsujan** [comment]
> i'm a little busy with my real work

Take your time.

> I always use gnome DE

Kvantum should work fine under gnome-shell. I test it once in a while there. The good codes related to gnome belong to @CDrummond, who uses gnome-shell.

**Comment by tsujan** [comment]
> i package it and pushing in our repo

Feel free to edit it however you want; it's 90% your work.
