### ISSUE TITLE
Qt5 scrollwheel jump workaround not working

### ISSUE THREAD

**Issue by sammoth** [tsujan/Kvantum#289]
I have built kvantum-qt5-git from the AUR on Arch and enabled the Qt5 scrollwheel workaround, but I still seem to get the bug.

eg. if I right click in Dolphin to open the context menu, left click to close it and scroll one click down, the view will jump up reliably.

Anything I can do to help debug this?

**Comment by tsujan** [comment]
Oh, you are right. I'd never checked Dolphin. It somehow doesn't let Kvantum receive the wheel event. I should look into its code to know why.

However, the workaround prevents bad jumps in all apps that are fully drawn by Kvantum. Most apps are but, unfortunately, Konsole's view isn't, for example.

Please note that the workaround only prevents jumps; it can't control *the direction of the first scrolling* -- there's no way to know that -- so, the first wheel turn is sometimes suppressed, sometimes in the wrong direction *but not with a jump*.

**Comment by sammoth** [comment]
Ah yes you are right, I get the same results. The workaround works in Kate for example, just not Dolphin. Actually it works very well in Kate for me - I almost always get the jump in the other direction but I couldn't produce any movement in the wrong direction with the workaround active.

**Comment by tsujan** [comment]
> The workaround works in Kate for example, just not Dolphin. 

I'll investigate Dolphin's code. The problem can be related to its `KItemListContainerViewport`.

> I couldn't produce any movement in the wrong direction with the workaround active.

You're lucky ;) I get it a lot but it's tolerable because it isn't a jump anymore and is limited to the first wheel turn.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/d7afe40e4329aa945c9890afb3d9e84ec918126d . Please upgrade!

I had to cheat because Dolphin cheated first ;)

Although I close this issue, feel free to add comments if needed or tell me about similar issues -- or, perhaps, how it isn't fixed for you (in that case, I'll reopen it).

Thanks for the report!

**Comment by sammoth** [comment]
Thank you so much! It works great. I cannot express just how much this will improve my quality of life :grin:

Glad I found out about Kvantum via this issue too!

**Comment by tsujan** [comment]
You're welcome.

I was tormented by it for a long time until, suddenly, this simple workaround came to my mind. The discussion at Qt bug tracker was very helpful.
