### ISSUE TITLE
Hide Keyboard Accelerators

### ISSUE THREAD

**Issue by r0skar** [tsujan/Kvantum#296]
Hi, First of all great work!

I was wondering if its possible to hide all keyboard accelerators? Using the `Breeze` widget style, it can be configured in the `Configure Breeze` dialog like so  (first drop-down menu), but for the `Kvantum` widget style, there is no such option.

![screenshot_20181111_115751](https://user-images.githubusercontent.com/33655345/48312089-e5a79900-e5a9-11e8-937e-498ad033fa29.png)

**Comment by r0skar** [comment]
Nevermind... Just after submitting the issue, I found the option `Underline shortcuts with Alt` in the Kvantum manager under `Miscellaneous`. Sorry for the noise.

**Comment by tsujan** [comment]
Yes, Kvantum has had it for a very long time.
