### ISSUE TITLE
Blur behind window not working after restoring it from system tray

### ISSUE THREAD

**Issue by r0skar** [tsujan/Kvantum#297]
I am not sure whether this is actually a Kvantum or a Plasma issue. I noticed that, the blur behind windows is lost, when the window is minimized to the system tray and than restored. To see what I mean, I included two screenshots of KeepassXC.

**Initial load:** Blur works.
![spectacle_20181111_135753](https://user-images.githubusercontent.com/33655345/48313296-69698180-e5ba-11e8-8e76-82c3edab7dd3.png)

**After restoring from tray:** Blur is lost.
![spectacle_20181111_135811](https://user-images.githubusercontent.com/33655345/48313302-87cf7d00-e5ba-11e8-859b-2ff0d15cca56.png)

P.S. As you can see in the screenshots, the global menu button in the titlebar is also lost upon restoring, but this is definitely a plasma issue, which makes me think the blur issue is too(?)

**Comment by tsujan** [comment]
Not a Kvantum issue. Kvantum has specific conditions for blurring windows; the window in question doesn't satisfy those conditions after being iconified and restored. The reason is inside its code, not in Kvantum
