### ISSUE TITLE
some issues / some whishes ;)

### ISSUE THREAD

**Issue by ghost** [tsujan/Kvantum#3]
so i played a bit with your theme engine and have encountered a few issues:
- the quantum style inkscape extensions are missing which makes theme creation a pain
- there is no way to set extra arrows for the menuitem, the same is also true for arrows in treeviews (eg pim settings exporter>shortcut editor), both use usually the hilightcolor as focused/hover bg so they shoud allow different arrows
- there should be a way to disable mouse tracking on the menubar it seems the focus font color is set when the mouse hovers
- insensitive menubar items are unthemed eg: scribus
- the toolbarhandle is scaled vertically  would be nice if it would have a fixed size since its a grip not a seperator
- there is a tinyt pink stipe in the kdewallet assistent(ok maybe thats a missing seperator in my theme;)
- the about dialog>autors email website / links are displayed as a toolbar
- vlcs media treeview will not use the selected text color
- a setting to make fonts bold would be nice ;)

---

in general it would be much easier if we could use multiple svg files instead of one huge(eg one file for each section or element)

also my current(unfinished) theme:
https://drive.google.com/file/d/0B_2_dsXrefR-WWM1aHM0NlhfVTQ/view?usp=sharing

and how it should look like:
https://github.com/sixsixfive/themes/tree/master/Glare

**Comment by tsujan** [comment]
I succeeded in finding a workaround for issues like that in VLC's media treeview you mentioned above. Now VLC has that issue with all engines except for the latest Kvantum when a light theme has dark selected treeview items ;)

**Comment by sixsixfive** [comment]
nice that works,  i recently switchd my main distro - so they are now some pkgbuils in the AUR https://aur.archlinux.org/packages/kvantum-kde4-colorscheme-svn/

**Comment by tsujan** [comment]
Nice up-to-date packages! One of these days, when I have enough time, I should try Arch. The last time, its installation on VirtualBox caused me a real headache ;)

**Comment by sixsixfive** [comment]
>I should try Arch. The last time, its installation on VirtualBox caused me a real headache ;)

that and because it's available with openrc instead of systemd is the reason why is use manjaro https://manjaro.github.io ;)

**Comment by sixsixfive** [comment]
@post 3>(4) Scribus is a GTK+Python app. Could you give me a Qt example?

took a while but: http://imgur.com/ygLIZRc

**Comment by tsujan** [comment]
As for Scribus you are right. I don't remember why I thought it was GTK.
But would you please explain which issue that image is supposed to show and how I could reproduce it? You had said, "insensitive menubar items are unthemed." What do you mean by "insensitive"?

**Comment by tsujan** [comment]
Never mind! You mean "disabled". I could see that in Scribus and will look into it. Thanks for your persistence ;)

**Comment by tsujan** [comment]
The fix was so easy:
![2037](https://cloud.githubusercontent.com/assets/981076/7380355/98455cf4-ee10-11e4-9511-b655be8483c9.png)
I'll include it in the next commit ( tomorrow, perhaps).

**Comment by tsujan** [comment]
If the reason you wanted a textless progressbar was because the text was unreadable inside the progress indicator, now you could use a new key under the GeneralColors section, namely "progress.indicator.text.color" (see Theme-Config.pdf).

For Glare, you could set it to white and set "textless_progressbar" to false again.
