### ISSUE TITLE
Use different settings of the same theme for certain applications

### ISSUE THREAD

**Issue by leggettc18** [tsujan/Kvantum#301]
I might just be missing something but I've been scratching my head at this for a few days and online resources on Kvantum are not too plentiful...
I would like to have Dolphin be see through but still have the same theme (KvArc) as the rest of my system. Right now I have my entire system on KvArc, and Dolphin on KvArkDark with the transparency settings applied. Is there a way to do this? I imagine I could at least make a copy of KvArc with a slightly different name if I at least knew where the themes were stored.

**Comment by tsujan** [comment]
> I imagine I could at least make a copy of KvArc with a slightly different name if I at least knew where the themes were stored.

Please see `Kvantum Manager` → `Configure Active Theme` and `Kvantum Manager` →  `Application Themes`.
