### ISSUE TITLE
reduce_window_opacity by 100?

### ISSUE THREAD

**Issue by veggero** [tsujan/Kvantum#306]
Hi,
I wanted to ask why isn't it possible to set reduce_window_opacity to 100%, but it's limited to 90%. I understand why most users would not want that, but at least giving it as an option could be a good idea. Is there a technical limitation?
Thanks.

**Comment by tsujan** [comment]
No technical limitation; it's simply impractical. Such values need sane upper/lower limits; this isn't the only case.

However, you could give a totally transparent window background to your theme.
