### ISSUE TITLE
Dolphin theming issue

### ISSUE THREAD

**Issue by wpVbeT90qr8eGEjcgZwLTG-LLo9PZ5Vh** [tsujan/Kvantum#307]
Hello,
I have a problem with dolphin:

![image](https://user-images.githubusercontent.com/45522504/49333078-53931f00-f5b0-11e8-8ce8-3d136101f745.png)

As you can see dolphin is using a totally different theme than system settings from KDE and kvantum manager.

Any other qt app is using the proper (MateriaBlur) theme (Kate, Kdenlive, keepassx, spectacle [...]).
Only dolphin have this issue.

Also, neofetch is reporting 
"Theme: KvOxygen [KDE], Materia-dark [GTK2/3]"
as my theme, which according to all places in the system settings and kavntum manager (as visible on the screenshot) is **not**.

------
OS: ArchLinux
KvantumManager: 0.10.8
dolphin: 18.08.3

**Comment by tsujan** [comment]
> Only dolphin have this issue.

There's no issue. You've assigned KvOxygen to dolphin. Remove the assignment in Kvantum manager → Application Themes.

**Comment by wpVbeT90qr8eGEjcgZwLTG-LLo9PZ5Vh** [comment]
@tsujan Thank you! Are there any plans for making this setting more visible? Like some information at the bottom with list of applications that are using "per application" theme?

**Comment by tsujan** [comment]
> Are there any plans for making this setting more visible? 

The list can be quite long. Moreover, you even don't need to search for assigned themes/apps but could simply click `Remove List` and then `Save`.
