### ISSUE TITLE
Kvantum and kdesudo

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#31]
Hi @tsujan , Is there any way to apply Kvantum engine in root mode by using the command "kdesudo"? With "sudo" command is fine, but when I try to apply the theme with kdesudo style returns to oxygen, take a look in the screenshot:

![Kvantum print](http://i.imgur.com/WRShjGS.jpg)

**Comment by franksouza183** [comment]
Ok, it's not a bu in Kvantum, as seen here: https://bugs.kde.org/show_bug.cgi?id=295995

The workaround, as mentioned in the link was to change the widget-style through the "kdesudo qtconfig".

Closing ...

**Comment by tsujan** [comment]
OK. I prefer to leave root apps as they are but, in my case, root Qt apps automatically get the Kvantum default theme while root KDE apps remain with Oxygen.
