### ISSUE TITLE
Semantic versioning without a "V" ahead of it

### ISSUE THREAD

**Issue by krisives** [tsujan/Kvantum#313]
In issue #110 a lot of discussion takes place about automatically rebuilding packages so users of Debian-based distros can make use of a Personal Package Archive (PPA). However, I'm not aware of any place where these packages are actually rebuilding automatically from this repository.

To remedy this I have created a build recipe on Launchpad that does that, but it has a small problem where the package version has to be hard-coded since this repository doesn't conform to the semantic versioning standard since it has a "V" prefixed to it.

Would it be possible to add a tag without the "V" ahead of it so that the build tools are capable of using the `{latest-tag}` substitution variable so that Debian packages automatically get the correct version as this repository is updated?

Thanks!

**Comment by krisives** [comment]
The recipe is located here: https://code.launchpad.net/~krisives/+recipe/kvantum-daily

The packaging information is located here: https://github.com/krisives/Kvantum-packaging

Once this repository no longer has the "V" prefix I can change the recipe to use the `{latest-tag}` substitution variable instead of the hard coded version of `0.10.8` currently.

**Comment by tsujan** [comment]
Thanks for packaging Kvantum but I really don't think that a simple `V` can cause any problem. I use that `V` in all my repositories that include releases, most of which are packaged for important distros, Debian included.

**Comment by krisives** [comment]
Can you point me to some of the places where they are packaged for Debian?

**Comment by krisives** [comment]
Also while I have your attention which do you prefer credited as the author, `Pedram Pourang` or `Tsu Jan`?

**Comment by tsujan** [comment]
> Can you point me to some of the places where they are packaged for Debian?

Debian itself: https://packages.debian.org/unstable/x11/qt5-style-kvantum and https://packages.debian.org/sid/qt5-style-kvantum-themes

> which do you prefer credited as the author, Pedram Pourang or Tsu Jan

My real name is the first one; `Tsu Jan` is just my "dev name" at github and other coding places.
