### ISSUE TITLE
Dragging from non-draggable widgets (mainly toolbar buttons), not just empty space.

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#317]
GTK headerbars allow you to drag from any non-draggable widget in the CSD headerbar, which gives you a much bigger and more consistent area to grab the window. Would be nice to have this in Kvantum.

**Comment by tsujan** [comment]
Dragging from places like toolbar buttons would be a big mistake for obvious reasons. GTK3's design is ridiculous; its window cannot be dragged from a lot of empty areas but it can be dragged from toolbar buttons!

**Comment by ripefig** [comment]
@tsujan I've used it extensively and I liked it a lot (for the first time in a while I could easily move windows with just the mouse). 

I don't think it's ridiculous at all - it's actually quite intuitive, when you have a headerbar or a toolbar that's visually blended with the titlebar. With a KDE apps, I can't do that anymore cause a) hunting for whitespace isn't worthwhile b) you can't use the whitespace to drag inactive windows c) titlbar's too thin and blended with the toolbar, so it's too much aiming to grab it.

Of course it's a matter of taste, but having Gnome headerbars are miles ahead when it comes to window dragging.

**Comment by tsujan** [comment]
There are codes in Kvantum to *prevent* dragging from inappropriate widgets. Sorry, I don't have time to explain why dragging should never be done from a button, a view, a scroll-bar, etc. It is NOT a matter of taste at all.

BTW, if GTK+-3 wasn't ridiculous, I'd never come to Qt and there would be no Kvantum.

**Comment by ripefig** [comment]
> from a button, a view, a scroll-bar

You need dragging to interact with views and scrollbars, you don't need dragging to interact with toolbar buttons. Dragging a window from a view or a scrollbar would be nonsensical.
