### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by Ste74** [tsujan/Kvantum#318]
Hi @tsujan, sorry for bother you again, can you help me to correct this theme?
I have build a dark variant for Matcha theme but i have some issue with the button or menu item if not focused. Here the WIP commit
https://gitlab.manjaro.org/artwork/themes/kvantum-manjaro/commit/ad3202650cce63797b0d78227df9008b65416d1e

Thank again
Stefano

**Comment by tsujan** [comment]
I'm afraid I'm very busy with coding, so that I might not have time soon.

**Comment by tsujan** [comment]
I'm really sorry for the long delay. I was extremely busy not only with my github projects but, especially, with LXQt 0.14.X -- lots of work had to be done on libfm-qt/pcmanfm-qt. Fortunately, everything went smoothly, as intended :)


`KvMatchaDarkSea` was mostly OK. I just made a few changes to the `kvconfig` file and SVG image. The corrected theme is attached to this comment.

[KvMatchaDarkSea.zip](https://github.com/tsujan/Kvantum/files/2957567/KvMatchaDarkSea.zip)

**Comment by Ste74** [comment]
Thank you so much, don't worry :smile:

**Comment by tsujan** [comment]
I usually do things fast; this one was a surprise to me too ;) 3 months!
