### ISSUE TITLE
Inactive symbolic icons in ItemView on Dolphin change color

### ISSUE THREAD

**Issue by trgeiger** [tsujan/Kvantum#324]
I'm having a weird issue with the symbolic icons in the Places panel of Dolphin. I looked through the other issues and found some helpful info, but nothing that led me to a solution for this.

As you can see in this screenshot, the selected element in the Places panel on the left of dolphin has the symbolic icon properly set to the dark color like the text.
![screenshot_20190113_214923](https://user-images.githubusercontent.com/18582917/51095894-b6660180-177d-11e9-9f58-93276ec11edd.png)

However, when I click outside the window and lose focus, the icon reverts to a white color. I have been unable to find any solution. Here's what it looks like:
![screenshot_20190113_215526](https://user-images.githubusercontent.com/18582917/51095957-1c528900-177e-11e9-9606-230a655fd366.png)

I've removed any inactive states from my .kvconfig file and trying "Ignore Inactive State" hasn't helped at all.

What am I missing?

**Comment by tsujan** [comment]
> What am I missing?

Nothing :) That's an old problem in Dolphin's code.

**Comment by nortexoid** [comment]
Has a bug report been filed about this?

**Comment by tsujan** [comment]
It isn't limited to Dolphin anymore. This is `oxygen-demo5` with the Breeze widget style and the view-item has dark text on dark background when the focus is taken away from it:

![oxygen-demo5](https://user-images.githubusercontent.com/981076/95071013-e0abdf80-0715-11eb-9acc-0aef7fcbffbf.png)

Maybe, KDE devs see it as a feature. Anyway, it's forced by KDE and doesn't happen in purely Qt widgets.

If you report it, limit your report to Breeze for them not to dismiss it as a problem outside KDE.

**Comment by tsujan** [comment]
Oh, there is a problem with reporting:

The above screenshot is taken with Breeze but inside LXQt. The fact is that their settings work fine with Breeze and *inside* KDE. So, they can say there's no problem ;)

**Comment by nortexoid** [comment]
Interesting. Last time I reported a bug that popped using a specific kvantum theme, they told me it was a bug in kvantum. If it works in KDE using breeze, I'm sure they'll tell me the same again.

It might become relevant for the KDE devs later because recently when I suggested they use an svg theming engine, one of the developers said they're "investigating" it for Plasma 6.

**Comment by tsujan** [comment]
@nortexoid 
These problems could be reported "forcefully" if we find the bad code lines. But finding them requires reading a lot of KDE codes and I have no time to find their mistakes for them. As a matter of fact, I've found several mistakes and added workarounds for them to Kvantum but, sooner or later, you reach a point, where you say to yourself, "enough is enough!"

Don't get me wrong; I admire the work behind KDE. What I dislike is KDE's bad styling codes. And there are lots of them...

If I find the time, I might search for the cause inside KDE, but no promise.

**Comment by tsujan** [comment]
LOL! I think I found the cause after 15 minutes. It's here: https://code.woboq.org/qt5/kf5/kwidgetsaddons/src/kpageview_p.cpp.html#405. The code:

```c++
const QIcon::Mode iconMode = (option.state & QStyle::State_Selected) && (option.state & QStyle::State_Active) ? QIcon::Selected : QIcon::Normal;
```

Apparently, it says that if the item is selected but its state isn't active, the icon is considered to be in the normal mode. That's wrong because the icon *is* still selected (see https://doc.qt.io/qt-5/qicon.html#Mode-enum).

Kvantum supports three state for selected view-items, which are called "press", "toggle" and "toggle.inactive" (in most Kvantum themes, "toggle.inactive" is ignored but, for example, KvAmbiance has it). With the above-mentioned code, they've tried to support two states for the selected view-items but in an inconsistent way.

**Comment by nortexoid** [comment]
Nice work! I can a file a bug with this information if you don't want to. The bug also occurs in the open/save dialog. One strange thing is if you click on the same folder a lot it can change its selected state.

**Comment by tsujan** [comment]
> I can a file a bug with this information if you don't want to.

Although I have KDE (for testing), the only KDE components I use are KWin and its dependencies, most of my apps being purely Qt-based. So, I'm not in a good position to report the issue.

Anyway, it's wrong to suppose that all styles should use a light color for the background of inactive selected view-items — to say nothing of the fact that an inactive selected view-item can be inside an active or an inactive window and Kvantum can distinguish between the two.

I took the following screenshot inside KDE, with `oxygen-demo5 -style gtk2`. It shows active and inactive windows beside each other and it's obvious that something's wrong (see the white text and black icon of the inactive window):

![inactive_window](https://user-images.githubusercontent.com/981076/95119226-7e280300-0758-11eb-9c18-159f055fe99a.png)

**Comment by nortexoid** [comment]
I can reproduce the bug with Breeze if the color scheme option "Use different colors for inactive selections" is unchecked. I've reported it here: https://bugs.kde.org/show_bug.cgi?id=427374\

You might want to chime in there with your discovery since it would likely be very helpful for the devs.

**Comment by tsujan** [comment]
> I can reproduce the bug with Breeze if...

Well done! It can't be dismissed when it's reproducible with Breeze too.

> You might want to chime in...

They know their code much better than I do. I was just lucky to have found it quickly.
