### ISSUE TITLE
[Feature Request] Plata theme colors for Kvantum

### ISSUE THREAD

**Issue by ceyhunnabiyev** [tsujan/Kvantum#326]
Adapta hasn't been developed anymore. It would be nice to add [Plata theme](https://gitlab.com/tista500/plata-theme) colors for Kvantum. I use this in Manjaro. It looks cool:
![screenshot from 2019-01-05 19-56-13](https://user-images.githubusercontent.com/5506156/51308329-4b594b00-1a5b-11e9-9601-a5312b7c7f61.png)

**Comment by tsujan** [comment]
I'm afraid my free time is taken by coding and will remain so indefinitely. Apart from that, I've never been interested in imitating/cloning GTK+ themes.

There are Kvantum theme developers with high quality works and there are so many Kvantum themes that can be used for making new ones.You might want to ask them for it.
