### ISSUE TITLE
focusFrame not applied for Qt4-apps

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#327]
Maybe it's Clementine bug or Kvantum or Qt4...
`focusFrame=true` not worked for `Slider` on Clementine.
Example with **KvCurves3D**:
![image](https://user-images.githubusercontent.com/8083855/51494741-3837d980-1dd3-11e9-8f9f-84f2e9f7b339.png)

- Clementine: 1.3.1 (Qt 4.8.7)
- Kvantum: 0.10.8

**Comment by tsujan** [comment]
Qt4 is dead and Kvantum's Qt4 support is frozen ;) I neither add any new feature to its code nor fix its probable problems (if any, they're tolerable).

I might edit README but I don't think it's important.
