### ISSUE TITLE
Single Click behavior when using non-KDE DE

### ISSUE THREAD

**Issue by Marko1000Marko** [tsujan/Kvantum#336]
Similar to issue #1 , using kvantum in i3 WM without a DE causes it to make dolphin open files with a single click, ignoring KDE system settings (I do have KDE installed)

In my ~/.config/kdeglobals I have 
[KDE]
SingleClick=false

Is there any way to set a force override in kvantum to make dolphin and others use double click? I would really like to use kvantum themeing but single-click destroys is my workflow and is unusable to me

Thanks

**Comment by Marko1000Marko** [comment]
Never mind, I missed the option to toggle this exact behaviour under 'Miscellaneous'

**Comment by tsujan** [comment]
Yes, it depends on the DE you work in. Kvantum prefers single-click but it has an option for it. It may also recognize KDE or Gnome and follow them in some regards.
