### ISSUE TITLE
Periodically theming loses its HiDPI

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [tsujan/Kvantum#337]
I am unsure that this is a Kvantum bug - but it might be.

I have Linux Mint 19.1 x64 Cinnamon and Kvantum 0.10.9. I have Cinnamon set to use HiDPI and have the following in my `~/.profile` file:

```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_STYLE_OVERRIDE=kvantum
```

Everything works most of the time, but occasionally suddenly all qt apps - including the Kvantum manager itself - become smaller, until I logout. Perhaps I should remove the `QT_AUTO_SCREEN_SCALE_FACTOR` line.

**Comment by tsujan** [comment]
The scaling is done by Qt and Kvantum just supports it. So, no, it isn't Kvantum's fault.

I recommend you use `QT_SCALE_FACTOR` instead; it has been always reliable here. If you want to give it a non-integer value like 1.5, be sure to upgrade to the latest git Kvantum and don't use translucent themes (because of a Qt bug). Integer values (like 2) work flawlessly with translucent themes though.

**Comment by tsujan** [comment]
And you need a DE that can set EVs correctly on logging in. Setting them inside a terminal emulator won't help.

**Comment by LinuxOnTheDesktop** [comment]
QT_SCALE_FACTOR: I will try that. I need to set it to '2' for what I want, I think. (Also: is Kvantum-dark translucent? I end up with some translucent menus in applications, though I do not want them.)

> And you need a DE that can set EVs correctly on logging in. Setting them inside a terminal emulator won't help.

Does use `.profile` counts as inside a terminal editor? And do you know whether Cinnamon does this stuff correctly? Thanks.

**Comment by LinuxOnTheDesktop** [comment]
Also: I think that Cinnamon is passing its DPI setting to qt apps; for, setting QT_SCALE_FACTOR to 2 makes qt apps _huge_.

So, it seems that either qt or Cinnamon is failing to maintain that setting.

But perhaps, in `.profile`, having substituted `export QT_SCALE_FACTOR=1` for `QT_AUTO_SCREEN_SCALE_FACTOR=1` will fix the problem.

I note also that the Cinnamon devs have denied that the the problem is their fault.

**Comment by LinuxOnTheDesktop** [comment]
Actually, I was using the the 'KvSimplicitDark' and, even with all its transparency settings (all that I can find, anyway) disabled, `ksyslog` still shows transparent menus. See screenshot attached. 
![image](https://user-images.githubusercontent.com/47056543/52179394-0448b500-27d2-11e9-9a7a-9921df4337a1.png)
But never mind.

Scale-factor: ah yes, of course.

Everything else: thank you.

**Comment by tsujan** [comment]
> even with all its transparency settings (all that I can find, anyway) disabled, ksyslog still shows transparent menus

Window translucency and menu translucency are different things. You could disable all kinds of translucency by disabling compositing in Kvantum Manager but menus seem OK in your screenshot.

BTW, what a beautiful theme ;)

**Comment by tsujan** [comment]
Your screenshot shows that your Kvantum isn't the latest git. If you want a non-integer scale factor (regardless of Cinnamon's problem with setting a Qt EV), you'll need the latest git Kvantum.

I'll make a release soon though.

**Comment by LinuxOnTheDesktop** [comment]
Well, the menus are usuable, but they also are not wholly opaque, and I would prefer them to be. But, thanks, totally disabling compositing made the menus wholly opaque.

The theme is, as I said, KvSimplicity - I had presumed you had designed that one!

Newer versions of Kvantum and scaling: I think I downloaded the source and compiled it a while ago; but I don't need non-integer scaling. I just need scaling that . . sticks. If I find that it continues not to stick, I'll speak to the QT folks and/or Mint devs and/or Mint users. Thanks again. Tremendous program you have there.

**Comment by tsujan** [comment]
> The theme is, as I said, KvSimplicity - I had presumed you had designed that one!

Yes; I was joking ;)

Last but not least, this is what a correct scale factor should look like:

![scalefactor](https://user-images.githubusercontent.com/981076/52179582-8f857300-27f1-11e9-8bc5-d8da0a38c515.png)

With a scale factor, you don't need to (and shouldn't) touch fonts. Everything -- including icons, checboxes and round corners) will be bigger automatically.
