### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by qjzTreeZ** [tsujan/Kvantum#338]
It has been 167 commits since the last release, so maybe it is time for a new release?

**Comment by tsujan** [comment]
Yes, I know; should find time to make a release note. I might also make a very small change to a theme.

I was thinking about increasing the version to 1.0.0 because Kvantum is quite stable but decided to do so after some Qt bugs are fixed.

**Comment by tsujan** [comment]
Done. 0.10.9 is released.
