### ISSUE TITLE
Compile error on KDE Plasma 18.04

### ISSUE THREAD

**Issue by pyunramura** [tsujan/Kvantum#339]
I'm trying to compile on a fresh install of KDE neon using plasma 5.14.5, and after installing build dependencies and running qmake without issues I'm running into a compile error with the following output.

```
cd style/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jer/Downloads/Kvantum 
/style/style.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc 
QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_QMAKE=/usr 
/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before ) && make -f Makefile
Project ERROR: Library 'libatomic' is not defined.
Makefile:47: recipe for target 'sub-style-make_first' failed
make: *** [sub-style-make_first] Error 3
```
Any insight into what may be the problem? Thanks for any help

**Comment by tsujan** [comment]
Since I have plasma 5.14.5 and see no problem here, the only things that come to my mind are a build directory that wasn't clean, a corrupted qmake, or a wrong compilation command (`&` instead of `&&`).
