### ISSUE TITLE
missing widget 'whats this'(shift+f1)/help>whats this

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#34]
This widget seems to be missing 

![aaa](https://cloud.githubusercontent.com/assets/3780774/6939181/2ea78364-d86a-11e4-9a8f-31abc9ed9aab.png)

**Comment by tsujan** [comment]
Which widget do you mean? This is my screenshot with the Kvantum default theme:
![1781](https://cloud.githubusercontent.com/assets/981076/6939489/69a01f86-d882-11e4-9ca3-2503869a2617.png)

**Comment by tsujan** [comment]
Oh, you mean "whats this". As you see, it's OK under KDE. What DE do you use?

**Comment by sixsixfive** [comment]
You are probably using KDE which will overwrite the default tooltip color? if i change the tooltip color in qt4config it works but qt5 knows no colorshemes

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6939610/b7a48c8a-d86e-11e4-93ee-ff2708b8d387.png)

**Comment by tsujan** [comment]
They aren't ordinary tooltips. I'll investigate why they get a black background under KDE but not under lxqt with the default Kvantum theme.

**Comment by tsujan** [comment]
Now the WhatsThis tooltip background cab be explicitly set with the key "tooltip.base.color" under the GeneralColors section. However, even without that key, the backgound color will be set automatically for the tooltip text to have enough contrast with the backgound (please test this).

**Comment by sixsixfive** [comment]
ok this looks better but there is still an ugly dotted line on the right and bottom border

https://github.com/tsujan/Kvantum/issues/33#issuecomment-88533656

**Comment by tsujan** [comment]
Oh, those ugly lines are drawn in qwhatsthis.cpp (from Qt source) and appear with Oxygen too. As I don't want such an ugliness in Kvantum, I'll try to remove it. But let me first study the issue #33 .

**Comment by tsujan** [comment]
Removed the ugly shadow (dotted lines) of QWhatsThis :)

**Comment by sixsixfive** [comment]
ah, nice ;)
