### ISSUE TITLE
App's layout is broken after changing Qt Widget Style

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#342]
This is likely not a Kvantum bug.
But I just want to ask if you have any workaround for this? E.g: do something in the Kvantum side...

STEPS TO REPRODUCE:
- Open Falkon with 2 tabs
- Change Qt Widget Style: e.g Breeze->Kvantum, or vice versa.
- See Falkon's tabbar. The layout will be broken like this:

![image](https://user-images.githubusercontent.com/11857205/52492622-20968880-2bfc-11e9-9463-fd36788a4cbf.png)

**Comment by tsujan** [comment]
Yes, it's an old Falkon bug but not important.

**Comment by trmdi** [comment]
[Reported](https://bugs.kde.org/show_bug.cgi?id=404124) to Falkon's devs.
Thanks @tsujan !

**Comment by tsujan** [comment]
You're welcome!

Falkon enforces left-aligned tabs (not a good practice, IMO) but it forgets to do so after a style change. It isn't an important issue because a global style change can't be perfect until apps are restarted (or after logging out and in).
