### ISSUE TITLE
Working directory in CMakeLists.txt required

### ISSUE THREAD

**Issue by omni6** [tsujan/Kvantum#344]
Hi @tsujan, 

got an issue for the kvantum-qt5-git PKGBUILD

```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
```

Here issue report for cmake:
https://gitlab.kitware.com/cmake/cmake/issues/18817

Patch for CMakeLists.txt for another application:
https://gist.github.com/ulyssesrr/d7c93e121bc9c5c7a4e0564be5e4ac21

**Comment by tsujan** [comment]
Backward incompatible changes in cmake again?! That's why I dislike cmake; have never seen such issues with qmake.

Thanks for letting me know about this problem and its solution! I'll investigate it as soon as I find time.

**Comment by tsujan** [comment]
@omni6 

The problem wasn't in Kvantum's cmake file -- a standard cmake compilation works OK -- but in the AUR PKGBUILD of git kvantum: it should have made a build directory before compilation.


### SOLUTION:

Please make these changes to PKGBUILD's `build()` and `package()` blocks (the last 2 blocks):

```sh
build() {
   cd ${srcdir}/${_gitname}/${_gitname}
   mkdir -p build ; cd build

   cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr
   make
}

package() {
   cd ${srcdir}/${_gitname}/${_gitname}
   cd build

   make DESTDIR=${pkgdir}/ install
   cd ..
   install -Dm644 ChangeLog ${pkgdir}/usr/share/doc/kvantum/ChangeLog
   install -Dm644 COPYING ${pkgdir}/usr/share/licenses/kvantum/COPYING
   cp -r doc ${pkgdir}/usr/share/doc/kvantum
}
```

It works here without problem but please test it before making the change.

Please also close this issue after you made the change successfully! Thanks in advance!

NOTE: There may be simpler ways but the above-mentioned one seems to work.

**Comment by omni6** [comment]
Oh my... need to review some pkgbuilds now ;)

Tested and build is fine now, but added a line to remove the /usr/share/kde4 directory because i think it is not needed anymore. Maybe you can remove it in source.

**Comment by tsujan** [comment]
> added a line to remove the /usr/share/kde4 directory because i think it is not needed anymore.

Right! It's just a relic from very old times. I'll remove it later.

**Comment by tsujan** [comment]
Oh, I still have one Qt4 app; so, `/usr/share/kde4` may remain for a while.

**Comment by omni6** [comment]
backward compatiblity... :+1:
