### ISSUE TITLE
color selection buttons won't work

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#35]
same dialog (=

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6996370/9cb578d0-db84-11e4-84af-b18e2e48c29f.png)

as you can see the buttons won't show the selected colors

**Comment by tsujan** [comment]
Using a whole pushbutton for showing a color is somehow unusual and presupposes that no SVG image is used in drawing widgets. In all apps I know of, itemviews (inside buttons) are used for that purpose.
However, I found a simple compromise. As I can't install lxqt here, I rely on your tests.

**Comment by sixsixfive** [comment]
works ;)
