### ISSUE TITLE
error: PM_TitleBarButtonIconSize was not declared in this scope

### ISSUE THREAD

**Issue by malczykk33** [tsujan/Kvantum#356]
System: Debian 4.9.144-3

I downloaded Kvantum using git clone and went to Kvantum directory.
I typed qmake && make and this error occurs:
    
Info: creating stash file /media/kacper/dane/Linux/Downloads/Kvantum/Kvantum/.qmake.stash
cd style/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /media/kacper/dane/Linux/Downloads/Kvantum/Kvantum/style/style.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/media/kacper/dane/Linux/Downloads/Kvantum/Kvantum/style'
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o ThemeConfig.o themeconfig/ThemeConfig.cpp
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o shortcuthandler.o shortcuthandler.cpp
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o Kvantum.o Kvantum.cpp
Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawControl(QStyle::ControlElement, const QStyleOption*, QPainter*, const QWidget*) const’:
Kvantum.cpp:9721:33: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
             int s = pixelMetric(PM_TitleBarButtonIconSize, option, widget);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawComplexControl(QStyle::ComplexControl, const QStyleOptionComplex*, QPainter*, const QWidget*) const’:
Kvantum.cpp:11607:39: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
       const int btnSize = pixelMetric(PM_TitleBarButtonIconSize, &btnOpt, widget);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
Kvantum.cpp: In member function ‘virtual int Kvantum::Style::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const’:
Kvantum.cpp:12301:10: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
     case PM_TitleBarButtonSize : return 16; // sets the space on menubar
          ^~~~~~~~~~~~~~~~~~~~~
Kvantum.cpp:12302:10: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
     case PM_TitleBarButtonIconSize : return 12; // sets the real button size on menubar
          ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:452: recipe for target 'Kvantum.o' failed
make[1]: *** [Kvantum.o] Error 1
make[1]: Leaving directory '/media/kacper/dane/Linux/Downloads/Kvantum/Kvantum/style'
Makefile:45: recipe for target 'sub-style-make_first' failed
make: *** [sub-style-make_first] Error 2

**Comment by tsujan** [comment]
At least, Debian Testing is needed for compiling the latest version of Kvantum.

You could try an older [release](https://github.com/tsujan/Kvantum/releases) of Kvantum -- definitely, there should be a version that compiles with your installed Qt  -- but you couldn't use newer themes with it, although you could use all themes included in that version; there may be some bugs but they're tolerable.
