### ISSUE TITLE
Allow to use a different slider style for color sliders

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#36]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6996532/92802780-db8d-11e4-83a7-96e3a0b03073.png)

they look a bit weird to me :) maybe we could give them a different theme than usual sliders

**Comment by tsujan** [comment]
Should be fixed with the latest commit.
Those sliders are relatively new. They belong to QtColorPicker (https://github.com/mbasaglia/Qt-Color-Picker), which is a nice replacement for the ordinary QColorDialog. Thanks for reporting!

**Comment by sixsixfive** [comment]
yepp works now
