### ISSUE TITLE
Application theme for libreoffice in Kvantum Manager

### ISSUE THREAD

**Issue by wheelsofsteel** [tsujan/Kvantum#364]
Good morning,
I would like to make Libreoffice (using kde integration) use a specific kvantum theme instead of the global one. I am able to do this with other applications by providing the name under the "Application Themes" section  as per normal. However, with libreoffice I am not able to do so. I believe this is because you run libreoffice programs by supplying a flag (libreoffice --writer, for example); just putting "libreoffice" in the text field is not enough. 

How could I change this? I want a light theme for libreoffice, not my global dark theme.

**Comment by trmdi** [comment]
Try soffice instead. Because:
```
~ ❯ pgrep -a office
15480 /usr/lib64/libreoffice/program/soffice.bin --calc...
```

**Comment by tsujan** [comment]
@wheelsofsteel 

It's `soffice.bin`.

Whenever I use a dark Kvantum theme, I assign a light one to `soffice.bin` because LibreOffice has problems with dark themes. `soffice.bin` has always worked here.

**Comment by tsujan** [comment]
BTW, if you use libreoffice-fresh ≥ 6.2, you'll see the best Qt skin support that LibreOffice has ever had. It may not be complete but is better than its other skins.
