### ISSUE TITLE
Errors while using cmake - Debian 9.8

### ISSUE THREAD

**Issue by cherkie** [tsujan/Kvantum#366]
Hi there, unable to follow the steps from install file. 

I am on clean Debian 9.8, fresh install. I am following these steps:

`First install X11 and Qt development packages. In Debian-based systems, they are:

 * g++
 * libx11-dev and libxext-dev (for X11)
 * qtbase5-dev, libqt5svg5-dev and libqt5x11extras5-dev (for Qt5)
 * libkf5windowsystem-dev (required with Qt >= 5.11)
 * qttools5-dev-tools (for localization if you need it)`

Install everything and I move on to the next step:

`With cmake
==========
Open a terminal inside this folder and issue the following commands:

	mkdir build && cd build
	cmake ..
	make`

And I receive following output from terminal:

`albert@albertnix:~/Downloads/Kvantum-0.10.10/Kvantum/build$ sudo make
Scanning dependencies of target kvantum_automoc
[  1%] Automatic moc and rcc for target kvantum
Generating moc source kvantum_automoc.dir/moc_Kvantum_MI7C7BNOB73ZMI.cpp
Generating moc source kvantum_automoc.dir/moc_KvantumPlugin_34Z4MBHSZDJBWS.cpp
Generating moc source kvantum_automoc.dir/moc_animation_WB2SCIJPCLTAKL.cpp
Generating moc source kvantum_automoc.dir/moc_blurhelper_3QBXIS5QGANME4.cpp
Generating moc source kvantum_automoc.dir/moc_windowmanager_QGJ4AYKHDHD725.cpp
Generating moc source kvantum_automoc.dir/moc_shortcuthandle_GZN7D7XK7722QM.cpp
Generating moc compilation kvantum_automoc.cpp
Generating qrc source kvantum_automoc.dir/qrc_defaulttheme_KNGF4VFZ62XUPX.cpp
[  1%] Built target kvantum_automoc
Scanning dependencies of target kvantum
[  3%] Building CXX object style/CMakeFiles/kvantum.dir/Kvantum.cpp.o
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawControl(QStyle::ControlElement, const QStyleOption*, QPainter*, const QWidget*) const’:
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp:9652:33: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
             int s = pixelMetric(PM_TitleBarButtonIconSize, option, widget);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawComplexControl(QStyle::ComplexControl, const QStyleOptionComplex*, QPainter*, const QWidget*) const’:
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp:11541:39: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
       const int btnSize = pixelMetric(PM_TitleBarButtonIconSize, &btnOpt, widget);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp: In member function ‘virtual int Kvantum::Style::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const’:
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp:12235:10: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
     case PM_TitleBarButtonSize : return 16; // sets the space on menubar
          ^~~~~~~~~~~~~~~~~~~~~
/home/albert/Downloads/Kvantum-0.10.10/Kvantum/style/Kvantum.cpp:12236:10: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
     case PM_TitleBarButtonIconSize : return 12; // sets the real button size on menubar
          ^~~~~~~~~~~~~~~~~~~~~~~~~
style/CMakeFiles/kvantum.dir/build.make:62: recipe for target 'style/CMakeFiles/kvantum.dir/Kvantum.cpp.o' failed
make[2]: *** [style/CMakeFiles/kvantum.dir/Kvantum.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'style/CMakeFiles/kvantum.dir/all' failed
make[1]: *** [style/CMakeFiles/kvantum.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

As I said, it's a clean debian install, I am also kinda crap with compiling. Tried using qmake && make to no avail as well. 

Any help appreciated.

Thanks.

**Comment by tsujan** [comment]
That's expected. Please see https://github.com/tsujan/Kvantum/issues/356

**Comment by cherkie** [comment]
thank you!

**Comment by tsujan** [comment]
You're welcome. And sorry that I can't always support Debian Stable in the latest git -- I try but it isn't possible sometimes.

**Comment by cherkie** [comment]
It's fine! I have knowingly went to stable, because I don't have the time
to maintain rolling Debian.

Thanks
