### ISSUE TITLE
Plasma crash when configuring widgets.

### ISSUE THREAD

**Issue by arun54321** [tsujan/Kvantum#367]
Plasma crashes when configuring widgets.
Only crashes when kvantum is used.

![Alt Text](https://w.allthepics.net/output.gif)

Plasma: 5.15.3
Kvantum Manager: 0.10.10

**Comment by tsujan** [comment]
Thanks but it was reported at https://github.com/tsujan/Kvantum/issues/365 and prevented by https://github.com/tsujan/Kvantum/commit/438de186ca975c17d333d0293c1764c0e9a676a0 

Please upgrade to the [0.11.0](https://github.com/tsujan/Kvantum/releases/tag/V0.11.0) (published minutes ago).

**Comment by tsujan** [comment]
And don't forget to log out and in after upgrade.

**Comment by emilio-aburto** [comment]
Came here to report, read this, updated and it's already fixed <3.
Thank you a lot :)

**Comment by tsujan** [comment]
You're welcome!

A KDE dev kindly told me about it yesterday. I'd made a mistake and hadn't considered QQC2 (what I briefly call "QML") in a previous commit.
