### ISSUE TITLE
Remove alternating row colors for list in KVGnome, for conformity with original theme.

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#369]
![image](https://user-images.githubusercontent.com/45201036/55433143-62f59980-559d-11e9-80a6-af5c00d98ec8.png)

**Comment by tsujan** [comment]
That's decided by the developer of the Qt app -- a property of QListView/QTreeView -- and shouldn't be suppressed by the theme.

Qt ≠ GTK
