### ISSUE TITLE
Make kde dependency optional

### ISSUE THREAD

**Issue by ChrisOboe** [tsujan/Kvantum#370]
Since 125e7721a089bb96c13a427e26bb1f5b08748687 a KDE dependency was added.
It would be great if this dependency could be optional because there are users that don't use KDE (and don't want to install it) and could do without the blur feature.

**Comment by tsujan** [comment]
It isn't KDE but `KWindowSystem`, which is a nice contribution to Qt by KDE devs. `KWindowSystem` doesn't depend on KDE and is needed under Wayland.

If  `KWindowSystem` depends on KDE on your distro, you could file a bug report to its maintainers.

**Comment by tsujan** [comment]
And I assure you that Kvantum will never depend on KDE.
