### ISSUE TITLE
Plata Noir & Questions

### ISSUE THREAD

**Issue by Izaic** [tsujan/Kvantum#372]
Recently solus switched over to Plata Noir as their main theme. The problem for me however is that the solus plasma (testing) edition only has the breeze theme, and doesn't look like the other desktops solus offers. 

The developer of Plata Noir told me that he refuses to make a Kvantum theme because he dislikes KDE (due to a bad experience with Slackware a decade ago). 

Since you are busy and the developer wont do anything, i was planning on doing it myself. I was hoping to just reuse the Kvantum Adapta theme and recolor it's SVG file (and change the general colors in the config). The problem however is that I'm not fully sure how kvantum works (It's configs got alot more going on than i anticipated), and how to implement the biggest component of the theme (the rounded corners, especially in the file manager and gnome settings where the one corner is flat but the other is rounded off). Further, kvantum has alot more buttons in the SVG file than the original GTK3 and GTK2 adapta themes have (not sure if that's your own personal touch, or if they are required for some QT apps?)

**Comment by tsujan** [comment]
> The developer of Plata Noir told me that he refuses to make a Kvantum theme because he dislikes KDE 

Tell him/her that Kvantum is not a KDE theme. KDE ≠ Qt. But if he's in love with GTK+, he won't hear you.

> how to implement the biggest component of the theme (the rounded corners

There are several themes with partially or fully rounded corners that are installed with Kvantum. You could check them. This is an example of partially rounded corners:

![corners](https://user-images.githubusercontent.com/981076/55922492-988e2880-5c16-11e9-92c7-04ccf40dc6d0.png)

But, the most important thing is reading the documentation that comes with Kvantum -- maybe not completely but, at least, those parts that are related to your work. In Kvantum, extreme corner rounding isn't for all widgets. Buttons, combos, line-edits, tabs,....? Yes! Menus, windows, container widgets? No!

> Further, kvantum has alot more buttons in the SVG file than the original GTK3 and GTK2 adapta themes 

Kvantum is a style for Qt. It has nothing to do with GTK. Therefore, the elements of its SVG file have totally different meanings compared to GTK. Please consult the doc!

The only similarity between making GTK and Kvantum themes is that both need patience and hard work. However, Kvantum never breaks its themes.

**Comment by tsujan** [comment]
> Since you are busy and the developer wont do anything,...

It's not that, as a developer, I don't make themes. I've made many themes and included them in Kvantum.

However, the busy part is correct. My free time is completely taken by several projects: 4 projects of mine (actually 5 but one them -- BreezeEnhanced -- doesn't need much work) , 2 heavy projects belonging to LXQt and other LXQt projects that I sometimes have to work on.

**Comment by Izaic** [comment]
I didn't mean that, i just meant he wouldn't do anything. Sorry.

**Comment by tsujan** [comment]
> I didn't mean that, i just meant he wouldn't do anything. Sorry.

No need to be sorry! I knew that. I just meant that I enjoy making themes but, unfortunately, coding doesn't leave me any free time -- for now, I hope. Once in a while, I polish the existing themes.

> Also i am sorry for not reading the documentation

Again, don't be sorry! Consider it as a reference, not something to be read from start to end. Believe me or not, I had to consult it while making some themes ;)
