### ISSUE TITLE
WPS-Office and kvantum with theme Arc

### ISSUE THREAD

**Issue by erikdubois** [tsujan/Kvantum#373]
I was wondering if it was possible if I can set Wps-office on Arch Linux - [Wps-Office](https://aur.archlinux.org/packages/wps-office/) with the help of kvantum-manager to use the Arc theme.

Standard I have the Arc Dark theme. The popup window to open and save a file looks like this then.
![wps-arc-dark](https://user-images.githubusercontent.com/10594806/55942736-57f9d380-5c45-11e9-884c-1d35227b21ce.jpg)

If I set the theme to Arc then we get this result.
![wps-arc](https://user-images.githubusercontent.com/10594806/55942764-6647ef80-5c45-11e9-8e25-25fe0552a450.jpg)

This is ofcourse better.

I have told kvantum manager to use Arc for the application wps but that is not working.

It does seem that wps is launched via /usr/bin/wps but there is also a wps in the /opt folder as well. It leads to two processes. Maybe that is why... Just trying to figure it out.

Do you know if it might be possible for wps to use the Arc theme.

I have read somewhere that it is a QT based app.

**Comment by tsujan** [comment]
It's simple! This gigantic closed-source app has problem with dark themes (bad design). It has nothing to do with Kvantum. I tested with a dark Breeze color scheme and the same thing happened.
