### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by tomjedusor** [tsujan/Kvantum#374]
Hello and thank you for this great app.
I have installed it following the instruction in the INSTALL text file and using cmake. I have installed the software because it was advised to install Materia theme, but i figure that i don't need it.
Can you tell me the steps to follow to uninstall it properly ?

(I have another issue but I'm not sure it is linked to, it's that my systray's icons don't synchronize with the icon theme I set in the configuration. They have done one time with Papirus theme, but since I have used Kvantum AND Hardcode tray (`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus-Dark`), they are a melt of Breeze and Papirus theme. And it seems that the systray need a high level to modify in plasma 5, I don't have.)

**Comment by tsujan** [comment]
This explanation isn't specific to Kvantum:

Most sources don't have an uninstall command because that's the job of package manager. You could do one of these:

  * Install Kvantum (or another program you've installed manually) completely from the repository of your distro (if it exists) and then uninstall it by using the package manager of your distro (apt, pacman, ....).

Well known distros have installable packages for Kvantum.
  * Or see the list of installed files inside the terminal when you install something from its source and remove them manually, one by one.

> I have another issue but I'm not sure it is linked to, it's that my systray's icons don't synchronize with the icon theme I set in the configuration.

That's absolutely not related to Kvantum.

**Comment by tomjedusor** [comment]
> Or see the list of installed files inside the terminal when you install something from its source and remove them manually, one by one.

I see that the make install command modify some files in the /usr/include/x86_64-linux-gnu/qt5/QtCore/ directory, do I remove them too ?

`~/repos/tsujan/Kvantum/Kvantum/build $ make list_install_components
Available install components are: "Unspecified"`

**Comment by tsujan** [comment]
> I see that the make install command modify some files in the /usr/include/x86_64-linux-gnu/qt5/QtCore/ directory, do I remove them too ?

Kvantum doesn't put anything in that folder.

Since obsession usually results in bad things, if you damage your system by removing an important file, the responsibility will be completely yours.

**Comment by tomjedusor** [comment]
Since obsession usually results in bad things, if you damaged my system by modifying an important file, the responsibility will be completely yours. Your software is really suspicious and I could warn people in the kde store and elsewhere.

>     Install Kvantum (or another program you've installed manually) completely from the repository of your distro (if it exists) and then uninstall it by using the package manager of your distro (apt, pacman, ....).
> 
> Well known distros have installable packages for Kvantum.

No, it's not "well known", and it's a "transition package". If it's possible why don't just mention that in the install text file ???
I will not tell you my life, but yes, people do weird things like installing something without checking every modified files.

It's the first time of my life I see a software without uninstall command ! I don't know what's your problem, but I know I'm a newbie geek and that's why I install software to modify theme in plasma ! I only ask a step by step guide to remove your software and back up to a standard configuration of plasma and qt (for me). If you can't give us one, it's disturbing, no ?

**Comment by tsujan** [comment]
If you understood the meaning of sharing one's work freely, you'd also understand that I'm not here to be at your service, let alone to fulfill your obsession.
