### ISSUE TITLE
High GPU usage in opengl mode

### ISSUE THREAD

**Issue by abijahm** [tsujan/Kvantum#376]
kvantum themes causes 80-100% gpu utilization,when using compositor opengl renderer

my gpu is integrated intel hd 4400

**Comment by tsujan** [comment]
That's related to graphic driver and/or compositor and has absolutely nothing to do with Kvantum.

The most Kvantum does is using translucency and blurring, which can be disabled with graphic cards or compositors that don't support it well.

**Comment by tsujan** [comment]
BTW, I have also integrated Intel on 2 laptops and have never seen high gpu usage with Kvantum.
