### ISSUE TITLE
Build errors on Launchpad

### ISSUE THREAD

**Issue by krisives** [tsujan/Kvantum#378]
I have a build script setup on Launchpad to automatically build for Ubuntu, but with the changes made yesterday it started failing:

https://launchpadlibrarian.net/419545306/buildlog_ubuntu-cosmic-amd64.kvantum_0.10.8-0~201904161746~rev1038~pkg2~ubuntu18.10.1_BUILDING.txt.gz

```
error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
                                               ^~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/Kvantum/style/Kvantum.cpp:11970:47: note: suggested alternative: ‘WA_StyleSheet’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
                                               ^~~~~~~~~~~~~~~~~~~
                                               WA_StyleSheet
/<<PKGBUILDDIR>>/Kvantum/style/Kvantum.cpp:11977:47: error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
                                               ^~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/Kvantum/style/Kvantum.cpp:11977:47: note: suggested alternative: ‘WA_StyleSheet’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
                                               ^~~~~~~~~~~~~~~~~~~
                                               WA_StyleSheet
/<<PKGBUILDDIR>>/Kvantum/style/Kvantum.cpp:11995:47: error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget))
                                               ^~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/Kvantum/style/Kvantum.cpp:11995:47: note: suggested alternative: ‘WA_StyleSheet’
       if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget))
                                               ^~~~~~~~~~~~~~~~~~~
                                               WA_StyleSheet
```

Any idea what's up?

**Comment by tsujan** [comment]
That's because `WA_StyleSheetTarget` didn't exist before Qt 5.12; I guess Launchpad doesn't have 5.12 yet.

`WA_StyleSheetTarget` is the final solution I found for a nagging problem in Qt (see https://bugreports.qt.io/browse/QTBUG-67767) . Nothing could replace it. I was glad when I saw it.

I should add minimum Qt version to the cmake file -- actually, I should have done so a long time ago ;) Will do it and  make a release.

Thanks a lot for telling me about that!

**Comment by krisives** [comment]
Thank you for the help. Not much I can do about Launchpad not having 5.12 yet, but that problem will sort itself out over time.

**Comment by tsujan** [comment]
> but that problem will sort itself out over time.

It definitely will. Please tell me here when it's solved!

**Comment by tsujan** [comment]
I can do another thing: adding a condition for `WA_StyleSheetTarget`. Although I like it very much because of what it fixes and had waited for it a long time, its lack isn't a disaster with Qt < 5.12. Will do so tomorrow.

Reopening this...

**Comment by krisives** [comment]
Cool. You're a legend.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/f1674c455fa718dc8a9cf00fffb3269aa3f20d7a (among other things). Please retry!

**Comment by krisives** [comment]
It appears to be working again:

https://code.launchpad.net/~krisives/+recipe/kvantum-daily

Thanks friend.

**Comment by tsujan** [comment]
Thanks for the confirmation and for making up-to-date Ubuntu deb packages!

**Comment by tsujan** [comment]
@krisives
Having consulted https://code.launchpad.net/~krisives/+recipe/kvantum-daily and searched in Ubuntu repository, I explicitly set the minimum Qt version to 5.9.0 in cmake and pro files.

I don't think there's a problem but if you encounter one, please tell me! There's no rush.
