### ISSUE TITLE
compile error on Kubuntu 18.04

### ISSUE THREAD

**Issue by jfariasf** [tsujan/Kvantum#379]
I'm receiving this error when trying to compile with QT5:

> Kvantum.cpp:11970:47: error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum

> Kvantum.cpp:11970:47: note: suggested alternative: ‘WA_StyleSheet’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
>                                                ^~~~~~~~~~~~~~~~~~~
>                                                WA_StyleSheet
> Kvantum.cpp:11977:47: error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
>                                                ^~~~~~~~~~~~~~~~~~~
> Kvantum.cpp:11977:47: note: suggested alternative: ‘WA_StyleSheet’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget)) // not drawn by Kvantum
>                                                ^~~~~~~~~~~~~~~~~~~
>                                                WA_StyleSheet
> Kvantum.cpp:11995:47: error: ‘WA_StyleSheetTarget’ is not a member of ‘Qt’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget))
>                                                ^~~~~~~~~~~~~~~~~~~
> Kvantum.cpp:11995:47: note: suggested alternative: ‘WA_StyleSheet’
>        if (widget && widget->testAttribute(Qt::WA_StyleSheetTarget))
>

**Comment by tsujan** [comment]
Please read https://github.com/tsujan/Kvantum/issues/378 and wait until tomorrow. Thanks for your patience!

In short, it's a new thing in Qt 5.12 but I'll add a condition for it tomorrow, so that the new Kvantum could be compiled with Qt < 5.12 too.
