### ISSUE TITLE
Rename KvGnome to KvAdwaita

### ISSUE THREAD

**Issue by FrancescoCuiusIuculano** [tsujan/Kvantum#381]
The KvGnome and KvGnomeDark themes should be renamed to KvAdwaita and KvAdwaita-dark respectively, this would allow qgnomeplatform to automatically pick the right theme according to gtk.

**Comment by tsujan** [comment]
That would break the theme for those who already use it (I don't let that happen in Kvantum). And the theme is for Gnome, after all. But thanks for your comment!

**Comment by tsujan** [comment]
Oh, found a small problem in its spin-box inactive separator. Will fix it soon.
