### ISSUE TITLE
Seg Fault on "Save" in Manager

### ISSUE THREAD

**Issue by noee** [tsujan/Kvantum#382]
Tumbleweed latest, with QT 5.12.3 (Unstable repo).  Opening manager, change any option under "Config current theme", get a segfault, here is bt from gdb:

`#0  0x00007ffff6f06d80 in operator<(QString const&, QString const&) () from /usr/lib64/libQt5Core.so.5
#1  0x00005555555aa940 in QMapData<QString, QString>::findNode(QString const&) const ()
#2  0x00005555555aca83 in QMap<QString, QString>::remove(QString const&) ()
#3  0x0000555555599c25 in KvManager::KvantumManager::writeConfig() ()
#4  0x00007ffff7067363 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff7b1e182 in QAbstractButton::clicked(bool) () from /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff7b1e39a in ?? () from /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff7b1f75f in ?? () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff7b1f935 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff7a74ba8 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff7a35551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff7a3cb77 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff703d839 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#13 0x00007ffff7a3bebf in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff7a8f5eb in ?? () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff7a925af in ?? () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff7a35551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff7a3c930 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff703d839 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#19 0x00007ffff742b0c4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib64/libQt5Gui.so.5
#20 0x00007ffff742c495 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)
    () from /usr/lib64/libQt5Gui.so.5
#21 0x00007ffff74062fb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib64/libQt5Gui.so.5
#22 0x00007ffff3b3d86a in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#23 0x00007ffff5fccc2e in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#24 0x00007ffff5fccec8 in ?? () from /usr/lib64/libglib-2.0.so.0
#25 0x00007ffff5fccf5c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#26 0x00007ffff7090e93 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib64/libQt5Core.so.5
#27 0x00007ffff703c50b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#28 0x00007ffff7044422 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#29 0x000055555557cced in main ()
`

**Comment by tsujan** [comment]
Not reproducible here.
Something may be wrong in Tumbleweed's unstable repository (incompatible package versions?). I keep this open until Qt 5.12.3 comes to my distro (soon).

**Comment by trmdi** [comment]
@noee
Did you try compiling Kvantum on your system?

**Comment by tsujan** [comment]
@trmdi It shouldn't make a difference because Kvantum doesn't use private headers. Actually, if it makes a different, that shows there are incompatible packages.

**Comment by noee** [comment]
I'll try a local compile a bit later, see what happens.

Right now, I'm just using the base TW repos and the trmdi repo in addition to the 4 unstable QT/KDE repos for QT5, Frameworks, Applications and Extra.

I do see a different set of gtk libs different between the trmdi repo and TW, if that even matters.  Doesn't appear to matter since the segfault is in QTcore:

`appmenu-gtk2-module obs://build.opensuse.org/home:trmdi
appmenu-gtk3-module obs://build.opensuse.org/home:trmdi
libappmenu-gtk2-parser0 obs://build.opensuse.org/home:trmdi
libappmenu-gtk3-parser0 obs://build.opensuse.org/home:trmdi`

**Comment by noee** [comment]
I just uninstalled, dropped the trmdi repo, cloned master and built/installed.  Same segfault, as it appears you expected.  Anything else I can do to help track the probable imcompatibility?

**Comment by tsujan** [comment]
> Anything else I can do to help track the probable imcompatibility?

Incompatibility was my guess -- it isn't unusual with unstable repositories.

If it's really about 5.12.3, I'll see it soon and tell you (mine is 5.12.2) but I don't think something can drastically change from 5.12.2 to 5.12.3. Moreover, I checked and didn't find a suspicious line of code in Kvantum Manager.

**Comment by NickLion** [comment]
openSUSE Tumbleweed latest, Qt 5.12.2, Kvantum from my repo ( https://download.opensuse.org/repositories/home:/NickLion:/qt5:/Unstable/openSUSE_Tumbleweed/ )
Save button works fine.

**Comment by tsujan** [comment]
@NickLion Thanks for the feedback!

**Comment by noee** [comment]
Yeah, I just tested another machine here that is TW vanilla, Qt 5.12.2 and it works fine.  So, there's probably something wrong with 5.12.3, though, you wouldn't expect drastic changes.  I'll keep my eye on it and keep up with git master as well.

**Comment by tsujan** [comment]
Qt 5.12.3 came here. No crash. To be sure, I recompiled Kvantum Manager but no crash either.
