### ISSUE TITLE
Invisible text on some Kirigami apps

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#384]
This is the KDE software manager Discover:

![image](https://user-images.githubusercontent.com/45201036/56850622-ada0d200-690d-11e9-92d3-3a76eb716052.png)

To reproduce open the app and click on any available package.

**Comment by tsujan** [comment]
Kirigami means QQC2 (QML) and QQC2 is terrible, regarding QStyle. But if you tell me which theme that is and which version of Kvantum you have, I *might* be able add a workaround.

BTW, I prefer not to have install Discover for this ;)

**Comment by ripefig** [comment]
0.11 (Latest release) and KVGnome

**Comment by tsujan** [comment]
OK. I see what I can do -- but no promise.

**Comment by ripefig** [comment]
It's the same for all KVantum themes, AFAIK.

**Comment by tsujan** [comment]
I had to install Discover :( But I found the cause and yet another workaround for QML. Will tell you when the commit is made.

**Comment by tsujan** [comment]
Worked around in https://github.com/tsujan/Kvantum/commit/f2d6c9a69ce3788fea8f2e66e52866fafc0dfddd

![discover](https://user-images.githubusercontent.com/981076/56852337-780ce080-692f-11e9-9d87-e1ee26045474.png)

You could upgrade to the latest git Kvantum.

Please tell me if you counter extreme cases like this with QQC2! Thanks for this report!
