### ISSUE TITLE
White on white text in container while window is active

### ISSUE THREAD

**Issue by Dunked0n** [tsujan/Kvantum#386]
All of the header, subwindow text, and group box texts are appearing white while the window is active and makes the text unreadable. While inactive, the container goes back to normal
![help1](https://user-images.githubusercontent.com/50301900/57198509-43a1b180-6f39-11e9-9440-c43b5593c01f.png)
![help2](https://user-images.githubusercontent.com/50301900/57198511-47353880-6f39-11e9-9d0a-d928684f7e1b.png)

**Comment by tsujan** [comment]
The problem is in *the theme* and it isn't my theme -- you couldn't see that in any theme that comes with Kvantum.
