### ISSUE TITLE
Kvantum blur only works on certain windows

### ISSUE THREAD

**Issue by StarrKiss** [tsujan/Kvantum#387]
It works completely fine for some windows, like Dolphin, but for others, like Discover, the background is transparent but not blurred. 
![image](https://user-images.githubusercontent.com/13007697/57201569-27653b00-6f60-11e9-8633-8aac57f02b84.png)

![image](https://user-images.githubusercontent.com/13007697/57201571-34822a00-6f60-11e9-8aae-bdbbacdb8da4.png)

This is happening all of a sudden and was fine for several months up until recently. How to fix?

**Comment by tsujan** [comment]
Discover is in QML. Kvantum neither makes QML windows translucent nor adds blurring to them.

Using of QML apps inside KDE is a discrepancy created by KDE devs. They've tried to make them look like other apps but that isn't possible. While I admire what KDE devs have done and do, I don't like this discrepancy and can't do anything about it.

**Comment by StarrKiss** [comment]
But, this worked blurred up until literally today. So something must have changed.

**Comment by tsujan** [comment]
> But, this worked blurred up until literally today.

Kvantum didn't do it. Kvantum applies the blur effect only to `QWidget` (see `blurhelper.cpp`). QQC2 (QML) doesn't have `QWidget`.

> So something must have changed.

Definitely but not in Kvantum.

**Comment by StarrKiss** [comment]
Is there any way i can 'go back'?

**Comment by tsujan** [comment]
Sorry, I have no answer to your question, being neither a KDE developer nor the developer of Discover.

**Comment by StarrKiss** [comment]
It isnt just Discover, even non QML applications like latte-dock settings refuse to work. How do I fix this?
