### ISSUE TITLE
compile error on Debian 9.9 KDE5

### ISSUE THREAD

**Issue by FxOmar** [tsujan/Kvantum#389]
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  3%] Automatic moc and rcc for target kvantum
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  3%] Built target kvantum_automoc
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  3%] Building CXX object style/CMakeFiles/kvantum.dir/Kvantum.cpp.o
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawControl(QStyle::ControlElement, const QStyleOption*, QPainter*, const QWidget*) const’:
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp:9666:33: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
             int s = pixelMetric(PM_TitleBarButtonIconSize, option, widget);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp: In member function ‘virtual void Kvantum::Style::drawComplexControl(QStyle::ComplexControl, const QStyleOptionComplex*, QPainter*, const QWidget*) const’:
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp:11555:39: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
       const int btnSize = pixelMetric(PM_TitleBarButtonIconSize, &btnOpt, widget);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp: In member function ‘virtual int Kvantum::Style::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const’:
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp:12249:10: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
     case PM_TitleBarButtonSize : return 16; // sets the space on menubar
          ^~~~~~~~~~~~~~~~~~~~~
/home/fx-omar/Downloads/Kvantum-0.11.0/Kvantum/style/Kvantum.cpp:12250:10: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
     case PM_TitleBarButtonIconSize : return 12; // sets the real button size on menubar
          ^~~~~~~~~~~~~~~~~~~~~~~~~
style/CMakeFiles/kvantum.dir/build.make:62: recipe for target 'style/CMakeFiles/kvantum.dir/Kvantum.cpp.o' failed
make[2]: *** [style/CMakeFiles/kvantum.dir/Kvantum.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'style/CMakeFiles/kvantum.dir/all' failed
make[1]: *** [style/CMakeFiles/kvantum.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tsujan** [comment]
Please see https://github.com/tsujan/Kvantum/issues/356 and https://github.com/tsujan/Kvantum/issues/366

Kvantum's cmake file sets the required minimum Qt version to 5.9.0 now (in the latest git source).
