### ISSUE TITLE
Some minor whishes

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#39]
Since I can't currently find any issues in my tested qt-apps ;)

* 1 As mentioned earlier I still would love to define all icon sizes

* 2 the tab close button could be loaded from the x11 icon theme(window-close)

* 3 Maybe a rule for make to disable the theme loading/lookup.(this would be great for my pkgbuilds)

Also is the app specific theme loading from quantum style still available?

**Comment by tsujan** [comment]
> Since I can't currently find any issues in my tested qt-apps

Good to know that :)

I'll think about implementing the features you asked for.  I just don't understand No. 3; what do you mean by disabling theme loading/lookup?

**Comment by sixsixfive** [comment]
mainly to make it easier for people to install a theme / directly setting the theme in qt style settings, eg:

checkout kvantum/style>replace the default style> replace the [kK]vantum strings in the json/plugin.cpp with a theme name>build>install

now the built style can be selected directly(and people don't need to install the manager) but it will also conflict with kvantum(if installed) so it would be nice to disable the theme loading for that case (other way of course would be to uncomment them all manually with sed & co which is a PITA)

**Comment by tsujan** [comment]
That's simply impossible. Let me explain:

Kvantum is a style plug-in and like all other style plug-ins, it provides the user with a style. The fact that Kvantum also supports additional styles is something BEYOND the plug-in system; it is specific to Kvantum. Therefore, additional styles can only be selected and activated INSIDE Kvantum (with Kvantum Manager, for example), not outside it.

Of course, you could replace 'default.kvconfig' and 'default.svg' with your files, as you could make ANY other change too (it's GPL after all), but the result would be a (personal) fork of Kvantum, not Kvantum itself. And if you want your fork to have no conflict with Kvantum, you should re-program it.

**Comment by sixsixfive** [comment]
>but the result would be a (personal) fork of Kvantum

which is exactly what i not want ;) I basically thougt about someting like -DCMAKE:DISABLEFEATURE or ./configure --disable , anyway its not bad how it is people/maintainers can still edit the config file by hand or uncomment the theme loading by hand

**Comment by tsujan** [comment]
The default theme is neither loaded nor a feature added to the engine later but an integrated part of it. This is true not only about Kvantum or any other Qt style plugin but also about other Toolkits like GTK2 and GTK3.

That being said, I'll think about (1) icon sizes, (2) tab close button, and (3) app specific themes.

**Comment by tsujan** [comment]
Tab close button is an indicator, not a simple icon. Since it can have 4 different states, it should be included in the SVG image. You could import png icons into your SVG image for it if you like.

App specific theme is a luxury, to which I don't give priority. I might add it at some point.

Adding keys for icon sizes seemd a good feature. I implemented it in r186. Use Kvantum Manager or read Theme-Config.pdf for working with the new keys.

**Comment by sixsixfive** [comment]
nice, but i would still like to adjust it more eg:

PM_IconViewIconSize(icon views like the settings mangers)
PM_MessageBoxIconSize(error diags)
PM_ListViewIconSize( i would love to keep them in 16px if small icons are set to 22px eg: for detail views)

also does the slim toolbar key still makes sense? maybe you could convert it to another icon size key to set this individually?

@close button
well it was just an idea but it doesn't really matter that much

**Comment by tsujan** [comment]
PM_IconViewIconSize is set by large_icon_size, and PM_ListViewIconSize by button_icon_size. If those sizes aren't changed for you, that's because you have KDE settings in your home or your app sets them itself. Kvantum gives priority to KDE settings even outside KDE.

PM_MessageBoxIconSize seems too specific to be worthy of a separate key. Also giving separate keys to the above-mentioned sizes seems to me like bloating Kvantum with impractical variables.

The slim toolbar key works as before and I think it's good for toolbars (many apps tend to set their toolbar sizes).

**Comment by sixsixfive** [comment]
hm is it not possible to get the same icon settings as in kdes systemsettings? they are very similar to the settings available for gtk

>PM_MessageBoxIconSize seems too specific

maybe for you it looks to specific but since i'm providing an icon theme with glare i would need to recreate all icons in 64px(thats the qt default size)

>The slim toolbar key works as before and I think it's good for toolbars (many apps tend to set their toolbar sizes).

yeah but i would love to get my gtk themes in sync, and 22px is now the forced on gtk3 - also did you test kvantum on a hidpi screen? a hidpi user will probably use bigger icons

**Comment by tsujan** [comment]
For now, I added toolbar icon size to Kvantum Manager (the key is toolbar_icon_size) and removed the "Slim toolbars" checkbox. The key "slim_toolbar" still works but the key "toolbar_icon_size" takes priority over it.

KDE apps only follow KDE setting for toolbar sizes. Some apps may have hard-coded sizes too. The above key has effect when the toolbar icon size isn't set in any other way.

**Comment by sixsixfive** [comment]
>App specific theme is a luxury, to which I don't give priority. I might add it at some point.

I guess i have a better idea:

What about a env. variable which can override the current set theme? 

eg: KVANTUMTHEME=/usr/share/kvantum/<supercooltheme> ./qtapp

**Comment by tsujan** [comment]
> I guess i have a better idea

OK. I'd left this issue open for it but it's proposed in #39 too.
