### ISSUE TITLE
LyX environment dropdown is black in light theme

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#390]
I'm not sure whether this is a bug in kvantum or in the materia light theme. And I can't take a screenshot because the dropdown immediately closes itself, not even with a timer.

Nevertheless I'm attaching a screenshot below. You can see that the Materia Light theme is having effect. My main qt theme is Materia Dark but I've set an override for LyX in Kvantum Manager (the configuration file is dumped below). To reproduce the problem, open the menu at the top left, the one that says "Standard". After doing that a pitch black dropdown opens that would be out of place even in Materia Dark. I've tested this with non Kvantum themes configured from qt5ct and the menu is ok. I've not tested it with other Kvantum themes besides Materia though.

![image](https://user-images.githubusercontent.com/2845433/57497369-c619d080-72ad-11e9-856f-6dfef44e69bc.png)

My configuration is:

* Arch linux up to date
* Gnome 3.32
* Kvantum 0.11.0
* Kvantum Materia 20190506
* qt5ct 0.39 
```
~:: cat .config/Kvantum/kvantum.kvconfig 
[General]
theme=MateriaDark

[Applications]
MateriaLight=lyx
```

```
~:: cat .config/qt5ct/qt5ct.conf 
[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/airy.conf
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=gtk3
style=kvantum
...
```

**Comment by memeplex** [comment]
With KvGnome, for example, it's just a black rectangle, text is not even legible. So the problem seems to be in kvantum, indeed.

**Comment by tsujan** [comment]
Lyx is among those apps that I use frequently. This is with KvGnome:

![combo](https://user-images.githubusercontent.com/981076/57520987-4d118c00-7334-11e9-88ea-683aa2c51434.png)

Materia is not my theme but I guess your problem is elsewhere.

**Comment by tsujan** [comment]
I closed this because it wasn't reproducible — as I said, I use LyX often, under KDE or LXQt — but you could add comments if you find something. Don't see `qt5ct` as completely innocent!

**Comment by memeplex** [comment]
@tsujan have you tested it under gnome+qt5ct? Because I've tried using another non-kvantum themes with qt5ct under gnome and I wasn't able to reproduce the problem. That's why I think it is something with kvantum or with the interaction between qt5ct and kvantum. Besides, I don't believe it could be the compositor or something similar, because even when under adwaita the rectangle is pitch black, under other themes like materia it's just dark with readable text over it, it's just like "inverted" wrt what one would expect for the theme.

**Comment by memeplex** [comment]
Indeed, disabling "Combo popup as menu", which was checked by default, fixed the problem. Is this a bug? Is that expected to malfunction under a gtk based environment? Maybe it shouldn't be a default, in that case?

**Comment by tsujan** [comment]
@memeplex 

When there's no problem with full-fledged Qt platform plugins like those of KDE and LXQt, it can be suspected that qt5ct may have some issues. A user kindly added https://github.com/tsujan/Kvantum/commit/05d39b0c0ae630f73566603c074fc252b060e22f for one of them — I'd call it a workaround but I cannot find qt5ct's issues one by one and add workarounds for them.

"Combo popup as menu" is a valid property that most of Kvantum theme use.
