### ISSUE TITLE
request for addition: KvFlatTeal to match Mint-Y-Dark-Teal

### ISSUE THREAD

**Issue by oberon-manjaro** [tsujan/Kvantum#391]
I am in the process of adjusting the theming for the Manjaro Cinnamon edition.
The new default gtk-theme will (most likely) be Mint-Y-Dark-Teal.
For qt-integration of course we will need a matching kvantum-theme and KvFlat seems to match almost perfectly, just the highlight color is unfortunately blue of course :wink: 
I was wondering if you could by any change imagine to contribute a slightly adjusted version of this theme with matching teal highlight colors?

![Screenshot from 2019-05-23 00-50-26](https://user-images.githubusercontent.com/11800714/58214098-d0e45480-7cf4-11e9-91d8-2c5c0907dde4.png)

That would be awesome!

**Comment by tsujan** [comment]
I'm afraid almost all of my free time is given to coding and, apart from that, I have no plan to add another GTK-matching theme to Kvantum.

However, as far as I am concerned, you could change any of my themes, *in any way*, or make it match a GTK theme of your choice, without a need to mentioning the name of the original theme.

**Comment by oberon-manjaro** [comment]
Thank you for your kind reply.
We have now attempted to create a teal version of **KvFlat** and it seems we managed quite well:
[**KvFlatTeal**](https://gitlab.manjaro.org/artwork/themes/kvantum-manjaro/commit/0376dfe29347037cdec6eca4e9d0408d8b56809c)
We only have one remaining issue that we seem unable to figure out. It's the blue highlight line in the virtualbox menu. Would you maybe have a hint for us where in the code this is addressed? That would be totally awesome!

![image](https://user-images.githubusercontent.com/11800714/58307137-06289980-7dfe-11e9-8d6a-56c8a00d7646.png)

**Comment by oberon-manjaro** [comment]
Looks like meanwhile we have found a solution by modifying KvFlatRed instead of the regular KvFlat. Seems we are sorted. Thank you.
