### ISSUE TITLE
Some elements stuck together

### ISSUE THREAD

**Issue by alexferman** [tsujan/Kvantum#393]
Is it possible to add spaces to this places?

![kvantum-fix1](https://user-images.githubusercontent.com/24989924/58642784-cb53c380-831f-11e9-82c9-a47b48ffe0ea.png)
![kvantum-fix2](https://user-images.githubusercontent.com/24989924/58642797-cee74a80-831f-11e9-83d0-42b08a76f5a9.png)

**Comment by tsujan** [comment]
Yes, of course. As an exaggerated example:
```
group_toolbar_buttons=false
toolbar_item_spacing=20
````
![example](https://user-images.githubusercontent.com/981076/58646900-a1989d80-831b-11e9-86b0-c6491ab3fb32.png)

But you don't want to do so with a theme that groups toolbar buttons (and so, ignores `toolbar_item_spacing` — see doc → Theme-Config).

App designers should add an extra layout there if they want a hard-coded space with all styles.
