### ISSUE TITLE
Yaru dark theme?

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#395]
I saw you had some issues with the new Ubuntu dark theme about a year ago that dissuaded you from providing a Kvantum YaruDark variant. I'm using the dark theme in Ubuntu 19.04 and seems quite accomplished to me. Would you please revise your decision? Has something relevant changed since then?

**Comment by tsujan** [comment]
Frankly, cloning GTK themes isn't attractive to me, especially when I don't like any of them. I've already cloned several GTK themes but have no incentive to do more. I'll maintain KvGnome(Dark) and KvYaru though.

I prefer to spend the fraction of my free time that I don't give to coding to make themes that are interesting to me — although it's zero for now.

**Comment by gsbhasin123** [comment]
Would anyone else be interested in maintaining a dark version of KvYaru? I would be happy to help, since Yaru Dark is one of the best GTK themes I have found, and I really would like to see a matching Qt variant.

**Comment by remlap** [comment]
Any one come up with a Yaru Dark theme since this has been posted?

Thanks.

**Comment by wassou93** [comment]
@remlap I think this is what you're looking for: https://github.com/GabePoel/KvYaru-Colors
