### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by gcjuan** [tsujan/Kvantum#398]
Hello @tsujan,

first of all I've to thank you so much for such a cool project!

Here comes my question:

I compiled Kvantum a few months ago and have been using it happily :smiley: but I recently realized that there's a new release and I wanted to update it to enjoy the last features and bug fixes. I'm currently on version 0.10.10 (taken from Kvantum Manager -> About).

What would be the best way to have Kvantum up to date? should I uninstall the current version somehow and then compile the new one? if it's the case, what happens with my current configs?

Sorry if the question sounds a little bit silly but I expected to find an answer to it here in the GitHub repo and unfortunately couldn't find nothing (you could maybe include update instructions on the installation instructions file or make a little repo-wiki with this kind of FAQ).

Thanks so much in advance from Spain

Juan :wink:

**Comment by tsujan** [comment]
First, I'd recommend the latest git version, which can be downloaded by git or, directly, from https://github.com/tsujan/Kvantum. Latest git version usually contains the latest fixes and features and is quite stable 99% of the time.

Second, you could compile and install Kvantum over the existing installation. There's no need to uninstalling. Actually, that's what I always do when I change something.

That's the case with most programs, although not all. Your question was pertinent in the sense that some programs may change the name of an important file in their later versions. Kvantum doesn't.

That being said, if you uninstall Kvantum before upgrade, nothing bad will happen. Your settings are inside your Home (inside `~/.config/Kvantum`) and won't be touched by package uninstallation.

If you have customized a theme that's included in Kvantum, backup `~/.config/Kvantum` and restore its new settings after upgrade by clicking `Restore` in `Kvantum Manager → Configure Active Theme`. Then you could customize it again.

One word about uninstalling: There's no "uninstall command" in the source. CMAKE doesn't provide "uninstall" for good reasons and I've followed it in this regard. Uninstalling is the job of package managers, not sources.
