### ISSUE TITLE
missing frame on lximages save dialog

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#40]
![bug](https://cloud.githubusercontent.com/assets/3780774/7102259/428d9ed6-e07b-11e4-9a48-2a7395eb5df1.png)

tada a bug ;) for some reasons the frame from the combobox is missing, also i'm not sure if this is the qt4 or qt5 save dialog since its running in kde@qt4(i guess it qt5 since it's using a different icon theme) the app is also lximage-qt(saving from the screenshot action)

there is also another small issue in the window behind: the selected arrow/expander(F5)? doesn't use the selected arrow color/image(which is white im my theme)

**Comment by tsujan** [comment]
The combo issue should be a problem in your new theme. With the version of Glare I have, it's OK:

![1922](https://cloud.githubusercontent.com/assets/981076/7102354/0f688c42-e093-11e4-9f31-95c90905e71e.png)

I'll look into the arrow issue later.

**Comment by sixsixfive** [comment]
yeah it seems to come from the min.size.height setting

**Comment by tsujan** [comment]
> yeah it seems to come from the min.size.height setting

How? Would you tell me how I can reproduce it?

As for the arrows, it seems that the KDE shortcut widget uses only the disabled arrows. I have to know why and find a way to fix that.

**Comment by sixsixfive** [comment]
>yeah it seems to come from the min.size.height setting

nope that was wrong, it has something todo with kde (i don't have this issue if i save something in LXQt or Lumina DE which both are built against qt5) so it only happens with qt5apps on KDE@qt4 -->weird

**Comment by tsujan** [comment]
Qt5 apps can't use the native open/save dialogs of Qt4-based KDE. Here, they use the Qt5 file dialogs, as they should. I think your KDE is partly Qt5. Have you installed KF5? I've seen some lx-qt apps that don't compile without it.

The arrow problem was because of a flaw in the design of the KDE shortcut widge. It uses PE_IndicatorArrowRight and PE_IndicatorArrowDown but doesn't give a state flag of "QStyle::State_Enabled" to the arrow. As Oxygen and all other theme engines except for Kvantum don't distinguish between arrow states, the problem isn't visible with them. No clean workaround seems possible, so, for now, I leave it as it is.

**Comment by sixsixfive** [comment]
>Have you installed KF5

indeed i have them installed since some kde apps(gwenview, dolphin, plasma) required them

**Comment by tsujan** [comment]
Although I can't have KF5 on Debian yet, I remembered that I have it in the latest Kubuntu on VirtualBox. I installed Kvantum on it and activated Glare. This is the same dialog in your screenshot but it's OK here:

![snapshot1](https://cloud.githubusercontent.com/assets/981076/7103034/f331ccd8-e0aa-11e4-92f8-4d033b53ed9d.png)

As the latest KDE isn't stable yet, various issues may arise and we can't be sure about causes. Let's wait until KF5 gets stable to see if any problem exists.

**Comment by sixsixfive** [comment]
hm stange, but its also weird that you can set your qt5 icon theme in kde4(this doesnt work for me), anyway i guess this issue will disappear with kde5

**Comment by tsujan** [comment]
Hi,

Yesterday I installed LXQT and encountered a strange phenomenon. I wanted to ask you if you see the same thing, in case you still use Kvantum with LXQT:

With X11 dragging enabled, a flash-like effect occurs when Qt5 windows are dragged quickly from their interiors. For me, this doesn't happen with Qt4 windows. It even doesn't happen with Qt5 under Enlightenment, Gnome, KDE4, KF5 or  IceWM.

**Comment by sixsixfive** [comment]
hm i don't see such things but i also use xfwm instead of openbox

**Comment by tsujan** [comment]
Thank you! Most probably it's an Openbox problem. I haven't seen it anywhere else either.

**Comment by tsujan** [comment]
At last, I found why it happens in Openbox :) I'll fix it with the next commit.
