### ISSUE TITLE
Color sheme issue.

### ISSUE THREAD

**Issue by edpil02** [tsujan/Kvantum#400]
Just try  Kvantum 0.11.1 for the first time but when trying to change the color scheme, the
color is changed only  in the kde configuration menu not in the others application (dolphin ...)
Thanks and sorry for my english.

**Comment by tsujan** [comment]
"Color scheme" is just a property of some KDE themes. Kvantum colors are defined by Kvantum themes.

Also, read the second paragraph of `Kvantum Manager → Change/Delete Theme`.
