### ISSUE TITLE
KvGnome checkbutton not fully identical to Adwaita's one.

### ISSUE THREAD

**Issue by MLDamazigh** [tsujan/Kvantum#401]
As you can see in the pictures below there is a difference between KvGnome theme's checkbutton and stock adwaita's one. can you fix this please, it's very annoying for me. Thanks in advance.

Adwaita theme's checkbutton (Ubuntu 19.04)
![image](https://user-images.githubusercontent.com/15183134/59941421-b1a02a80-944c-11e9-8b6b-1a8211841989.png)

KvGnome theme's checkbutton (Vlc media player)
![image](https://user-images.githubusercontent.com/15183134/59941465-c5e42780-944c-11e9-8673-c00851d49386.png)

**Comment by tsujan** [comment]
These are check and radio buttons of adwaita with gtk 3.24.9 — the screenshot is taken from `gtk3-widget-factory`:

![gtk](https://user-images.githubusercontent.com/981076/59942012-e70c3e80-9473-11e9-931b-680b1570a406.png)

Perhaps you have another version of gtk3 or use a customized version of adwaita.

**Comment by tsujan** [comment]
BTW, Ubuntu is known for not giving original programs to its users. It might have changed adwaita for itself -- just a guess, based on what Ubuntu had done with gtk3 for a long time.
