### ISSUE TITLE
Manjaro KDE - Cannot locate element to allow Dolphin's toolbar icons to change sizes

### ISSUE THREAD

**Issue by tortious** [tsujan/Kvantum#405]
[Here](https://old.reddit.com/r/kde/comments/c7wlb3/embarrassing_question_re_kvantum_dolphin/) is a link to the Reddit post I made describing my problem (just in case I somehow miss something here).

While using kvantum, and despite reading all of your (very thorough and awesome) docs on using kvantum. My problem is that I cannot seem to figure out which element to check/uncheck/number to change/etc so that I may change the size of Dolpin's toolbar icon sizes. It only allows me to choose "Default" now. I have exhausted all possibilities and variations with Dolphin already, which is why I am now bring the issue here. 

What is strange is that the shortcut sidebar icons (the one via F9) still are alterable as the toolbar used to be. Since that is somehow remaining unaffected, it leads me to believe that it is not one of the kvantum functions involving specific sizes (where I'd input a number) and instead just one of the check/uncheck options. However, through constant trial-and-error, and reading & rereading your supporting docs, I just cannot seem to figure it out.

I know this is somehow user error on my part, as your documentation is amazing, but it seems nothing I try ends up working. Also, I have made sure to log in and out between changes them, all of them, just to be safe.

Thank you

**Comment by tsujan** [comment]
As the tooltip (or "WhatsThis") of `Kvantum Manager → Seizes & Delays → Toolbar icon` says:

"The default value is 22 px **but some apps set it themselves. KDE apps get it from KDE setting**."

Dolphin's toolbar icon size is independent of Kvantum and can be set in `KDE System Settings → Icons → Configure Icon Sizes` (its name may be different from version to version). However, it needs an appropriate icon set (like Breeze and many other sets) to work: you may not see the size slider with some icon sets.

> I know this is somehow user error

It isn't user's error :) Some parameters, that can be set by the style, can also be overridden by the environment or the app.

**Comment by tsujan** [comment]
Oh, I opened this page again accidentally, clicked the reddit link and saw this:

> I cannot figure out the element of kvantum that no longer allows dolphin toolbar icon sizes to be changed

So, it seems that I misunderstood your question. I thought you asked how to change Dolphin's toolbar icon size with Kvantum but you asked why Kvantum didn't let you change Dolphin's toolbar icon size. That isn't true. Kvantum has nothing to do with it.

As mentioned above, what you see may be related to the icon set.

**Comment by tortious** [comment]
Sorry for any confusion. I doubt that is the case with the icons, though, since they are custom and added by me. They are able to be resized on the sidebar (and the same ones used to be sizable on dolphin).

[Here](https://imgur.com/a/5G1t2By) is a screenshot for context.

**Comment by tsujan** [comment]
> I doubt that is the case with the icons, though, since they are custom and added by me.

For an icon set to work with KDE size settings, its `index.theme` should contain `DesktopDefault`, `ToolbarSizes`, `ToolbarDefault`, etc. See the index file of the Breeze icon set.
