### ISSUE TITLE
KVGnome2: unclipped tabs

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#406]
The corners aren't clipped properly in some contexts:

![image](https://user-images.githubusercontent.com/45201036/60533938-6bc74a00-9d09-11e9-88d1-23a33a437c87.png)

**Comment by tsujan** [comment]
I have no theme named "KVGnome2" and your screenshot doesn't seem to be that of KvGnome.

You may need to be more specific.

**Comment by ripefig** [comment]
@tsujan my bad, I had seem to have used an older version of your theme by accident. Resolved.
