### ISSUE TITLE
remove bold and inset text from tabbars and toolbars in conformity with Adwaita-GTK

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#407]
Adwaita-GTK uses regular text for tabs: there is no inset effect and no bolding in the regular Adwaita theme.
![image](https://user-images.githubusercontent.com/45201036/60534037-a335f680-9d09-11e9-84bc-074968192afd.png)

There is also no inset effect for toolbar and headerbar text in regular Adwaita:

![image](https://user-images.githubusercontent.com/45201036/60534136-d24c6800-9d09-11e9-9025-b84638d402fe.png)

I suggest removing these effects from the Kvantum theme, since they diverge Adwaita and don't look very clean.

**Comment by ripefig** [comment]
Same problem with all buttons. Adwaita gtk doesn't use inset effects for text.

**Comment by tsujan** [comment]
Kvantum isn't made to "conform" to GTK+. Some themes have been added to match some GTK+ themes and KvGnome is one of them but the goal hasn't been to copy every ugly aspect of Adwaita.

Of course, "ugly" and "clean" are subjective and you could change any Kvantum theme according to your taste.
