### ISSUE TITLE
Plain close buttons on tabs in KVGnome

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#408]
![image](https://user-images.githubusercontent.com/45201036/60534712-19872880-9d0b-11e9-8239-ec31e6566f9a.png)

Adwaita GTK uses a plain X, no circle.

**Comment by tsujan** [comment]
Apparently, you don't don't have an original/up-to-date GTK+ installation. This is gtk3-widget-factory:

![gtk](https://user-images.githubusercontent.com/981076/60535226-e481d280-9d18-11e9-9916-e56e1eebf81c.png)

However, also read https://github.com/tsujan/Kvantum/issues/407#issuecomment-507782388
