### ISSUE TITLE
Increase padding for tabbar

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#409]
![image](https://user-images.githubusercontent.com/45201036/60535162-2ce6c380-9d0c-11e9-8ec8-f38a9a2c8af6.png)

There is no padding between the tabbar and toolbar. Is there a way to increase the padding?

**Comment by tsujan** [comment]
> Is there a way to increase the padding?

Yes there is, by increasing the frame thickness and grouping the bottom frame element with a transparent rectangle, or by doing a similar thing with tabs. See other Kvantum themes, like KvYaru, KvBeige or KvFlatLight.

Your reports have been mostly about your personal taste, which I respect. But please note that each theme is made based on its creator's preferences -- mine, in this case. As mentioned elsewhere, you could change any theme by consulting the documentation that comes with Kvantum.

**Comment by ripefig** [comment]
No problem. I am just making suggestions.
