### ISSUE TITLE
colored drop indicator

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#41]
It would be nice if you could rework the drop indicator for toolbar and mdi docks(like they are in fusion and oxygen)

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7102976/047916ca-e094-11e4-8cf3-3c738fb9677f.png)

**Comment by tsujan** [comment]
You mean to fill the rectangle with color? Why? What would be the gain? Kvantum gracefully draws the rectangle and let the background color to bee seen as it is. I see that as an advantage, even though a little one.

**Comment by sixsixfive** [comment]
>You mean to fill the rectangle with color? Why?

because it makes things easier to see (esp. for windows with many mdi docks like qtdesigner) the 1px border is also hard to see on medium sized screens with big resolutions

>I like the red color you use with your new theme

its still Glare just with a different hilight color

**Comment by tsujan** [comment]
Ok, I think it's a matter of preference. I'll add a key for it and leave the default as it is. I'll tell you when it's done. Now I'm a little busy with some features I've added recently (complete rounding).

**Comment by tsujan** [comment]
Implemented in r186. See Kvantum Manager ("Fill rubber-band rectangles"). The key is "fill_rubberband" under General.

**Comment by sixsixfive** [comment]
nice ;)
