### ISSUE TITLE
What should I do to create a theme?

### ISSUE THREAD

**Issue by CavaleriOmar** [tsujan/Kvantum#416]
I love Kvantum, but the lack of present themes is a bit daunting. So I would like to modify one to make one that I like on a chromatic level. How should I write the text file to modify or create a Kvantum theme from scratch? What languages are used?

Sorry for my english: I use Google Translate.

**Comment by trmdi** [comment]
There are doc files: https://github.com/tsujan/Kvantum/tree/master/Kvantum/doc

**Comment by tsujan** [comment]
Kvantum includes a comprehensive doc (see @trmdi's comment).

**Comment by CavaleriOmar** [comment]
Thanks.

**Comment by tsujan** [comment]
You're welcome.

I recommend choosing an existing theme and trying to change it by consulting the doc. When you get familiar with the meanings of keys and the names of SVG elements, you could make a completely new theme. However, it'll take time and won't be a piece of cake.
