### ISSUE TITLE
Issue with Virtualbox - vm window is not set to be opaque

### ISSUE THREAD

**Issue by longtomjr** [tsujan/Kvantum#418]
Hi

Don't know if this can be done for external themes, but at least in the included ones it might be worth adding `virtualboxvm` under the opaque apps list - since the machine and the vb window does not share a name.

More info in this manjaro forum topic 
https://forum.manjaro.org/t/kde-virtualbox-machine-visual-problem-with-kvantum-theme-enabled/100723/14

**Comment by tsujan** [comment]
Thanks for the info! I'll add `virtualboxvm` to the opaque list.

It's 2019 and we still see up-to-date apps that have problem with translucency!. The opaque list is a workaround for them.

**Comment by tsujan** [comment]
Oh, `virtualboxvm` is already in the opaque list of all (translucent) Kvantum themes. That's why I've never had problem with VirtualBox.

I guess you're using an external Kvantum theme.
