### ISSUE TITLE
Themed Plasma modules on Kvantum

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#423]
It's possible added on config - use another kvantum theme for Plasma modules?
For example, `kcmshell5 kcm_networkmanagement`
![image](https://user-images.githubusercontent.com/8083855/64433491-9f3ea000-d0cf-11e9-9cdd-80f4dc81e93f.png)
kcm_networkmanagement use QML and for hack opacity i need use another theme.

**Comment by tsujan** [comment]
The app name of all kcmshell5 windows is `kcmshell5`. Kvantum sees that -- you could use `kcmshell5` in Kvantum Manager → Application Themes.

Other Plasma widgets introduce themselves as `plasmashell`, which can also be used by Kvantum Manager. Beyond that, it's all about Plasma, not Kvantum.

I close this but feel free to add comments if you have other questions.

**Comment by tsujan** [comment]
> kcm_networkmanagement use QML and for hack opacity i need use another theme.

You could leave QML windows as they are. Except for a minimal styling (as Breeze does), nothing can be done for them. But yes, you could style them with a different Kvantum theme, based on their app names.
