### ISSUE TITLE
add a global config file

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#43]
I wonder why i haven't mentioned this yet but there should be a way to set the theme for all users(eg /etc/kvantum.conf or /etc/xdg/kvantum.conf)

**Comment by tsujan** [comment]
Themes can be installed for all users (see INSTALL) but setting a theme for all users is meaningless. Could you attribute any practical sense to it?

**Comment by sixsixfive** [comment]
>Could you attribute any practical sense to it?

yepp i'm usually lazy ;) and i often launch at least the file manger as root(or as different user to keep permissions) so the app will start with kvantums default theme instead of a selected theme(its a pain to copy the kvantum config file to all userdirs)

**Comment by sixsixfive** [comment]
also there is another reason i can think of. Many distributions use a custom theme but they will never use kvantum as their default style engine since there is no way to set this theme after installation

**Comment by tsujan** [comment]
Distros can surely set Kvantum, QtCurve or Bespin as their default theme engine with suitable user settings (neither QtCurve nor Bespin has a global setting file). Kvantum has the advantage that it can be set as the default Qt theme engine under any DE. With an appropriate default user setting, it should be even possible to set the default active Kvantum theme.

I labeled this issue as "invalid" but left it open, in case a really valid reason comes up.

**Comment by sixsixfive** [comment]
ok i close this now since i found another way, so it isn't really needed or wanted anymore
