### ISSUE TITLE
[Bug] QT5 icons in GNOME system tray have opaque backgrounds

### ISSUE THREAD

**Issue by MegaArthur** [tsujan/Kvantum#430]
When the current Qt5 theme is set using Kvantum, when a Qt5-based-app icon appears in the system tray, it will have an opaque background, looking ugly on transparent themes.

![Screenshot from 2019-09-23 10-25-44](https://user-images.githubusercontent.com/26827848/65440994-26527e80-de19-11e9-943f-52fa995b71fa.png)

Distribution (version): Arch (rolling)
Desktop environment: GNOME
Installing method: Arch repos

Also seen reported by vczm at: https://superuser.com/questions/1479724/gnome-system-tray-icons-white-background

**Comment by tsujan** [comment]
I'm afraid I can't do anything for a GTK based environment [that has removed systray functionality](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/). Whatever app that forces a systray on Gnome is responsible for showing icons correctly.

That being said, the Qt platform plugin you use can be the cause too. Sorry, I don't have Gnome to test.

**Comment by MegaArthur** [comment]
Switching the theme using Qt5ct fixes the issue, but this means an ugly theme due to not using Kvantum

**Comment by tsujan** [comment]
> Switching the theme using Qt5ct fixes the issue

That shows the systray itself may be innocent.

I recommend you give `lxqt-qtplugin` a try. It may have a few dependencies but they're light. You could activate it by setting `QT_QPA_PLATFORMTHEME`  to `lxqt` (and `QT_STYLE_OVERRIDE` to `kvantum`). I've tested it under Enlightenment and it has worked very well -- you can't find a DE weirder than Enlightenment ;)

**Comment by tsujan** [comment]
> but this means an ugly theme due to not using Kvantum

I know that Kvantum can be used with Qt5ct (by setting `QT_STYLE_OVERRIDE` to `kvantum`), although I can't recommend Qt5ct.
