### ISSUE TITLE
Kvantum Styles break under qt5 5.14-beta release

### ISSUE THREAD

**Issue by keiichiiownsu12** [tsujan/Kvantum#439]
Although the 5.14 seems to be a beta-release (downloaded from kde-unstable on arch) kvantum breaks under it. 

Namely appearances of buttoms and highlights are broken:
Adapta
![image](https://user-images.githubusercontent.com/37505464/66536036-81020080-ead0-11e9-92b7-07da4d3aae1d.png)

Arc Dark
![image](https://user-images.githubusercontent.com/37505464/66536090-a727a080-ead0-11e9-9832-4f8f6b65abf2.png)

**Comment by tsujan** [comment]
Thanks but I can't do anything with unstable Qt versions. When Qt 5.14 becomes stable, if any problem exists, I'll know about it and fix it.

**Comment by keiichiiownsu12** [comment]
Got it. Downgraded for the time being

**Comment by tsujan** [comment]
> Downgraded for the time being

That's a wise decision. With unstable Qt versions, there may be so many things that can break this or that program.

BTW, I've encountered several reports about program malfunctions with unstable Qt versions, which didn't exist later, when those versions got stable (only in one case, a malfunction persisted but it was a Qt regression that was reported and fixed quickly).

**Comment by keiichiiownsu12** [comment]
Thanks for the advice, will stick to stable versions of KDE and Qt from now on
