### ISSUE TITLE
Ellipsis kicks in too late on lxqt-panel taskbar buttons

### ISSUE THREAD

**Issue by jlindgren90** [tsujan/Kvantum#446]
**Current behavior:**
It looks like Kvantum does not account for padding when deciding whether to ellipsize text in a button.  So if the icon and text of a button, minus padding, still fits within the button size, Kvantum will not shorten the text but instead cram the icon and text more tightly together, ignoring the padding requested by the current theme.

As an example, see the image below.  In the left button, everything fits with padding and looks fine.  In the right button, the text is shortened and padding is respected, and it also looks fine.  It's the center button that is the problem: the text and icon fit but there is no room left for padding, so the padding is not drawn, and the button looks cramped.

![ellipsis](https://user-images.githubusercontent.com/1244737/67402336-75a5df00-f57e-11e9-978e-0e7ba8aec1a5.png)

**Desired behavior:**
I think it would look better if Kvantum shortened the text of the center button as well, so that it could be drawn with the normal padding.  Then the center button will look less cramped, and more consistent with the other two buttons.

**More info:**
I'm using qt5-style-kvantum 0.11.2+repack-1 from Ubuntu 19.10.  I can test newer versions if necessary, but I didn't find any already closed issues mentioning the problem, so I thought I'd go ahead and report it.

I'm using a slightly modified version of the KvGnomeDark theme, but I think this should be reproducible with any theme provided that the text of the button is exactly the right (wrong) length.

**Comment by tsujan** [comment]
You're completely right and I really appreciate your attention.

There is a problem that Kvantum needs to handle, while most of other styles don't; there are lots of codes in Kvantum for that. I try to explain it shortly:

`QStyle` has many parameters and Kvantum makes best use of them by treating them as parameters. While other widget styles set them to fixed values like "3", "true", "#fff", etc., Kvantum lets them be set by the theme.

If all Qt developers used `QStyle` correctly, no problem would happen. But so many developers don't. For example, they may add a hard-coded style to their codes with "#000" as text color without setting the background color. Or they may draw a button in their codes and think its frame width should be 3 px (as in Fusion or Breeze). So, I had to include many workarounds to compensate for these mistakes as far as possible.

Buttons are an example that's related to this case. Usually — in 99% of cases — a push or tool button text isn't elided. But when a developer wrongly supposes its frame should be 3-px and its icon-text spacing should be 2px, its text might be elided with Kvantum. As a workaround, I've avoided button text eliding as far as possible.

Now, in the rare case of LXQt panel, text eliding is natural but Kvantum doesn't treat it differently. Hence, what you correctly described.

I can make an exception for LXQt panel in the code but that's ugly. On the other hand, there's no way to know when button text eliding is "natural" (very rare) and when it's the result of a bad style code (not so rare, unfortunately).

Any sugestion?

**Comment by jlindgren90** [comment]
Hmm.  Thanks for the detailed explanation.  I don't like the idea of making an exception for lxqt-panel, either.

It looks like lxqt-panel already has some logic for eliding the button text itself.  I think I should study more closely the change you made in https://github.com/lxqt/lxqt-panel/pull/1163 and try to understand better how the lxqt-panel code before making any other suggestions.

**Comment by tsujan** [comment]
I can assure you that LXQt doesn't contain bad style codes like I described above — it did but they were fixed a long time ago. KDE has lots of them though, especially because of the QML that they use.

I could go with the ugly solution if there is no other important case of "natural" button text eliding —none comes to my mind. It's very easy to implement too.

**Comment by jlindgren90** [comment]
Totally up to you.  I think you have a better understanding of the relevant code on both sides (lxqt-panel and kvantum) than I do at this point.

**Comment by tsujan** [comment]
Since it only needed a simple check, I made an exception for LXQt Panel: https://github.com/tsujan/Kvantum/commit/3cae9fb6462139d679bf5bfc2326804e76b12b7f

At some point, I might remove the workaround altogether.

Thanks for your report!
