### ISSUE TITLE
[request] - option to not colorize menus

### ISSUE THREAD

**Issue by psifidotos** [tsujan/Kvantum#447]
In upcoming Latte versions the Plasma Window AppMenu will be possible to colorize the applications menus based on the active window scheme applied. I believe it would be a nice addition to give the user the freedom to disable kvantum menu coloring in order to be able to achieve the following:

from Breeze style:

![image](https://user-images.githubusercontent.com/2216474/67620817-96d32d80-f813-11e9-97a9-ae3e8da90f21.png)

**Comment by tsujan** [comment]
> I believe it would be a nice addition to give the user the freedom to disable kvantum menu coloring in order to...

I'm afraid that's an incorrect idea many developers have about colors (or "color schemes") and it could cause serious readability issues. For example, Kvantum doesn't colorize menus; it gives them an SVG background.

**Comment by psifidotos** [comment]
> > I believe it would be a nice addition to give the user the freedom to disable kvantum menu coloring in order to...
> 
> I'm afraid that's an incorrect idea many developers have about colors (or "color schemes") and it could cause serious readability issues. 

color schemes are used from KWin in order to colorize its menu when the user right clicks the window titlebar. For the applet this behavior will be optional.

> For example, Kvantum doesn't colorize menus; it gives them an SVG background.

is it possible for this to be disabled [optionally] or you just dont agree on the feature?

**Comment by tsujan** [comment]
> color schemes are used from KWin in order to colorize its menu when…

"Color scheme" is a KDE concept based on the idea that, for example, a menu is a just a rectangle with a background color, or a button is another rectangle that has a border, or… It fits in with elementary widget styles like Breeze.

In Kvantum, a menu is a rectangle filled by 17 SVG elements plus 4 other SVG elements that determine its shadow depth plus several properties that are set in the `kvcconfig` file. Other widgets are drawn in similar ways.

> is it possible for this to be disabled [optionally] or you just dont agree on the feature?

For the above-mentioned reason, it would be a serious and ugly regression, not a feature. So, the logical answer is "No".

Please don't get me wrong! I'd be really glad to make changes for compatibility with other styles — even GTK themes, let alone a nice app like Latte — but not when they damage Kvantum.

**Comment by psifidotos** [comment]
fair enough...
