### ISSUE TITLE
Widget sizing messed up in Kdenlive and a few other programs

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#451]
Fulll size toolbar:

![image](https://user-images.githubusercontent.com/45201036/68064931-4be57880-fd33-11e9-8702-bfcb8d2c6e4e.png)

Resized window:
![image](https://user-images.githubusercontent.com/45201036/68064924-31130400-fd33-11e9-94a4-1c026a5ef847.png)

So the buttons don't scale with the interface properly.

*Using KvGnome - can't speak for other themes

**Comment by ripefig** [comment]
also here the widgets are strangely sized regardless of window size:

![image](https://user-images.githubusercontent.com/45201036/68065089-19d51600-fd35-11e9-8082-69020cfaab4c.png)

**Comment by tsujan** [comment]
> Kdenlive and a few other programs...

Kdenlive's GUI is a mess. What other programs?

**Comment by tsujan** [comment]
LOL! I installed kdenlive and started it with the Breeze widget style. See the mess in the same window:

![kdenlive](https://user-images.githubusercontent.com/981076/68066771-86124280-fd52-11e9-9658-d9a5c0d8d8c6.png)

Who can work with that?!

You could report the bug to kdenlive but, as far as I remember, its GUI has been a mess for years.

**Comment by ripefig** [comment]
Lol!

**Comment by ripefig** [comment]
Props on the theme @tsujan - it actually performs BETTER than breeze (and looks much nicer to boot)

**Comment by tsujan** [comment]
> Props on the theme @tsujan - it actually...

Thanks! I made KvGnome and KvGnomeDark for Qt and GTK apps to have uniform looks and feels as far as possible. I'll update them if their corresponding GTK themes change.
