### ISSUE TITLE
Please make hardcoded 2px tabbar spacing configurable

### ISSUE THREAD

**Issue by jlindgren90** [tsujan/Kvantum#460]
So many aspects of the Kvantum engine are already configurable, that I was surprised to find this bit in Style::subElementRect():

        /* a 2px space between tab page and tab bar
           but no spece between tab pane and tab bar */
        if (element == SE_TabWidgetTabContents && !twf->tabBarSize.isEmpty())
          space = 2;

In my opinion, some QTabWidgets (for example, the playlist tabs in Audacious) would like nicer without this spacing.  Can it be made configurable by the theme?

Screenshots before/after crudely replacing "space = 2" with "space = 0":
![image](https://user-images.githubusercontent.com/1244737/69768679-7ae2e480-114f-11ea-9286-72e41bbe8399.png)
![image](https://user-images.githubusercontent.com/1244737/69768686-81715c00-114f-11ea-8184-ec7b31b60d3c.png)

**Comment by tsujan** [comment]
You're right but changing some values in `Kvantum.cpp` might have unpredictable effects because different parts of that huge file have close relations to each other (hence, not dividing it into smaller files). I don't think that's the case here but I should reread the code to know why I chose "2" years ago.

**Comment by tsujan** [comment]
After reading the code, I clearly remembered the reason for adding 2px:

The lack of a small space would cause the top child widgets of the tab widget to be attached to the tabbar's base line *in the document mode*. That may not create a visual problem in the special case of your screenshot but, *even with the same theme*, if the top child widget is a (check) button, slider, box frame, tab…, the attachment will be very ugly — I saw such cases in some apps years ago.

For example, remove the top 2-px spacing from the following screenshot in your mind (the theme is KvGnomeDark):

![example](https://user-images.githubusercontent.com/981076/69781009-1ca31980-11c2-11ea-999e-7c2989f3db0f.png)

Some Kvantum parameters have positive lower limits to prevent ugly widget attachments (like `layout_spacing` and `layout_margin`). In this case, I would also set the lower limit to 2 if I added a key but there was no need to a bigger space; hence, no parametrization.

**Comment by jlindgren90** [comment]
I would think that document-mode (which is opt-in on the application side) is precisely the case where an application would expect to have no extra spacing, and could add its own if necessary.  For comparison, Qt's built-in fusion theme, when in document mode, adds no spacing between the tab bar and the content.  So the application in your screenshot would probably have ugly clashing borders in the fusion theme as well.

It would be nice if the Qt developers could clarify the expected behavior here.  Their docs currently say, "When this property is set the tab widget frame is not rendered", but they say nothing specifically about spacing.

**Comment by tsujan** [comment]
> would probably have ugly clashing borders in the fusion theme as well.

To me, Fusion is the ugliest style ever -- but no! Breeze is uglier ;) I know that tastes differ and I won't get surprised if someone loves those styles but a developer's program reflects *his/her* taste.

> It would be nice if the Qt developers could clarify the expected behavior here.

Fortunately, there's no expected behavior; otherwise, different style engines wouldn't be possible ;)
