### ISSUE TITLE
Disabling arrows from toolbar breaks hover effect

### ISSUE THREAD

**Issue by ashahir05** [tsujan/Kvantum#462]
Apparently if the arrows beside toolbar is disabled, it churns out a weird hover effect. This is the case in Materia KDE. You can see the original issue here:

https://github.com/PapirusDevelopmentTeam/materia-kde/issues/53

As said, if you made a way to disable the arrows without breaking the hover effect, it would be great.

**Comment by tsujan** [comment]
That's a problem in the theme, not in Kvantum. The theme should contain the needed arrows/indicators -- as all themes that come with Kvantum do.

Disabling arrows of menu buttons doesn't make sense and would be a bug to fix, not a feature to add. See Theme-Making.pdf → Indicators → PanelButtonTool

**Comment by ashahir05** [comment]
What section in the kvconfig handles these buttons:
![image](https://user-images.githubusercontent.com/44367115/70030339-3a61eb80-15d3-11ea-9ddb-8ba50e8b332f.png)
In lets say dolphin:
![image](https://user-images.githubusercontent.com/44367115/70030291-1ef6e080-15d3-11ea-9fca-faffbe33d9c3.png)

**Comment by tsujan** [comment]
They are ordinary buttons. If they're push buttons, their appearance is controlled by `PanelButtonCommand`; if they're tool buttons, the section is `PanelButtonTool`, which may inherit the former. To know whether they're push or tool buttons, you need to either see the app's code or play with the kvconfig file but if you change them, other tool or push buttons will be changed too.

Everything is explained in `Theme-Config.pdf` and `Theme-Making.pdf`.

As for your original question, see https://doc.qt.io/qt-5/qtoolbutton.html#ToolButtonPopupMode-enum. Even if `indicator.size=0` is used under `PanelButtonCommand`, 12px will be added to the width of the menu-button (= a tool button with a popup menu) for its missing arrow, *which should not be missing*.

**Comment by tsujan** [comment]
@ashahir05 

I made a commit for a special case of arrow. See https://github.com/PapirusDevelopmentTeam/materia-kde/issues/53#issuecomment-561100499 for an explanation.

Previously, I added arrow in that special case to inform the user that there was a menu. Now, inspired by this discussion, I think there's no need to an arrow.

Please note that an arrow *is* needed in other cases and is provided by Kvantum.
