### ISSUE TITLE
The resize area on the window border is too small

### ISSUE THREAD

**Issue by ranomier** [tsujan/Kvantum#463]
So as far as i understand that the visible border matches the area in which it is possible to resize the window.

Is it possible to have a bigger resize border but to or little visible border?

Archlinux
latest KDE
Theme Canta

**Comment by tsujan** [comment]
Window border belongs to window decoration, which has nothing to do with Kvantum. It's created by the window manager -- under KDE, it's called "KWin".

**Comment by tsujan** [comment]
BTW, with KWin, you can remove the right, left and bottom borders completely but have a acceptable resize margin. If that's not enough for you, you could always use `Alt+Right Mouse Button` to resize windows (provided that you've configured that shortcut).

Anyhow, none of this is related to Kvantum.

**Comment by ranomier** [comment]
Okay, thank you for clarification.

Mmh then the issue is with kwin or the window decorator part of the theme.

Thanks again

**Comment by tsujan** [comment]
> Mmh then the issue is with kwin or the window decorator part of the theme.

Yes, it's related to KWin and its decorations (like Breeze decoration) but, actually, there is no issue. KWin provides three ways of window resizing: (1) by using the resize margin, (2) by adding a resize handle and (3) by using `Alt+Right Mouse Button` -- (2) and (3) can be found is System Settings.
