### ISSUE TITLE
[request] Would it be possible to make falkon's new (blank) tab or speed dial semi-transparent?

### ISSUE THREAD

**Issue by rbn42** [tsujan/Kvantum#464]
This is an eye candy of Safari which I do envy. Sorry, I don't have an account on kde.org, so I cannot open this issue in falkon's repo. I guess it requires you to cooperate to implement this feature.

**Comment by tsujan** [comment]
These things should be done in the app itself. I'm not a Falkon dev. You may want to make a feature request at Falkon's issue tracker: https://bugs.kde.org/describecomponents.cgi?product=Falkon

**Comment by tsujan** [comment]
> Sorry, I don't have an account on kde.org

Then, open an account ;) You want a feature, so you need to ask KDE developers for it.

**Comment by rbn42** [comment]
> These things should be done in the app itself. I'm not a Falkon dev. You may want to make a feature request at Falkon's issue tracker: https://bugs.kde.org/describecomponents.cgi?product=Falkon

Thanks, I will.
