### ISSUE TITLE
Translucency breaks when global scale is applied

### ISSUE THREAD

**Issue by LogicWavelength** [tsujan/Kvantum#465]
I am using Kvantum on a 4K screen, and when I apply any scale factor other than 1.0, the translucency (and possibly blur?) breaks, and all window backgrounds are solid/opaque.  

I'm not a good bug reporter, so please let me know what logs/configs/etc you want me to post to help solve this.

**Comment by LogicWavelength** [comment]
https://github.com/tsujan/Kvantum/issues/445#issuecomment-544578107

**Comment by tsujan** [comment]
Yes, translucency is intentionally disabled (and not accidentally broken) with non-integer scale factors.

Both translucency and blurring are OK with integer scale factors under X11 (for Wayland, see https://github.com/tsujan/Kvantum/issues/431).
