### ISSUE TITLE
Latest release isn't tagged

### ISSUE THREAD

**Issue by Thaodan** [tsujan/Kvantum#467]
Release 0.13.1 isn't tagged in git.

**Comment by tsujan** [comment]
The latest release is 0.13.0.

0.13.1 is the git version. With the next release (tag), I might change it to 0.14.0 or keep it as a point release, depending on the work done after 0.13.0.

Git versions change fast and contain the latest changes but, as far as Kvantum is concerned, they're quite stable.

**Comment by tsujan** [comment]
In other words:

After the release X.Y.Z, the version U.V.W is a work in progress, although it's stable and git users usually have it. Those who depend on their distro reporsitory, can only have X.Y.Z or an older release, depending of how up-to-date their distro is (Arch and a few other distros are an exception: they provide U.V.W too).

**Comment by Thaodan** [comment]
Ah thanks for the explenation.
Some kind of schema that is 
understandable would be great.
Like <stablever>.99  (this is what plasma 
does).

**Comment by tsujan** [comment]
I understand what you say but versions like X.Y.99 give the impression that they are unstable, while I do my best to keep git Kvantum *always* stable.

**Comment by Thaodan** [comment]
I think that indicates that there's something that 
is work in progress and that stuff can break 
between releases.
But I understand because also things are 
sometimes broken even in stable releases like 
fractional scaling.

**Comment by tsujan** [comment]
> broken even in stable releases like fractional scaling.

It's half broken in Qt -- up to 5.13 -- and Kvantum disables translucency as a workaround to make it tolerable.

**Comment by Thaodan** [comment]
At  least Kontact is  broken 
even in 5.13

**Comment by tsujan** [comment]
A screenshot -- with Breeze and Kvantum if possible?

**Comment by Thaodan** [comment]
Both are affected. I can add 
one later.

**Comment by tsujan** [comment]
> Both are affected

OK, never mind. I thought only Kvantum was affected and was surprised.

I read somewhere that Qt devs were trying to fix problems with non-integer scale factors but, until now, I've seen bad issues with all widget styles, Fusion included. Window translucency intensifies them; hence, removing it with non-integer scale factors in Kvantum.

**Comment by Thaodan** [comment]
Maybe it bugs more on multi 
manager setups.
Forcing the dpi for fonts was a quite 
ok workarond for me.

**Comment by tsujan** [comment]
I'm pretty sure that, somewhere in Qt's code, numbers are rounded incorrectly and that causes all kinds of problems in drawing widgets: missing frames, artifacts, wrong positioning, etc.

Yes, forcing dpi for fonts seems to be the most acceptable workaround for now.
