### ISSUE TITLE
change the width/height of a progressbar?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#47]
I wonder if this might be possible? It would be nice if i could make the qt style completely look like my gtk themes

eg:

https://raw.githubusercontent.com/sixsixfive/Glare/master/x-screenshots/gtk2.png
https://raw.githubusercontent.com/sixsixfive/Glare/master/x-screenshots/gtk3.png

**Comment by tsujan** [comment]
That was in my TODO list and is implemented now. Please test it by using the new key "progressbar_thickness". (see Theme-Config.pdf).

If you also set "textless_progressbar" to false, the ordinary progressbars won't have text but the unusual ones (like those in Krita) will.

**Comment by sixsixfive** [comment]
that looks a lot better ;)

**Comment by tsujan** [comment]
Now that progressbar thickness can be set and the text won't be shown if its height is greater than it, is textless progressbars of any use to you? I ask because I'm cleaning the code.

**Comment by sixsixfive** [comment]
I guess no
