### ISSUE TITLE
Renable blur and transcluent effects when fractional scaling is enabled

### ISSUE THREAD

**Issue by Thaodan** [tsujan/Kvantum#471]
I've reverted the commit that disables blur and translucent effects and its no longer broken for me.
I'm using Qt 5.14.x. Also other bugs related to fractional scaling seem to be gone.
Maybe tests this again and revert the change.

**Comment by tsujan** [comment]
it's still bad. See https://github.com/tsujan/Kvantum/issues/445#issuecomment-569312340

Whenever a new Qt version comes, I test it.

**Comment by extSunset** [comment]
What is the current state of this problem?  I am using kvantum 1.0.7 and Plasma 5.27.4.1.  I don't find the parameter mentioned here #123.  Translucency does not work for me with global scaling 150%.

**Comment by tsujan** [comment]
> What is the current state of this problem?

Which problem? Kvantum Manager has an option for enabling translucency with fractional scale factors. How well Qt handles it depends on Qt.
