### ISSUE TITLE
Building Kvantum on Linux

### ISSUE THREAD

**Issue by viniciusjl** [tsujan/Kvantum#473]
Hi,

I'm using Linux Debian 9 with KDE and Qt 5.14.

I had to make the following modifications to build Kvantum:

_Kvantum/style/Kvantum.h_
```
#include <QSvgRenderer>
//|class QSvgRenderer;
```

_Kvantum/style/shortcuthandler.h_
```
#include <QWidget>
//|class QWidget;
```

_Kvantum/style/themeconfig/ThemeConfig.h_
```
#include <QSettings>
//|class QSettings;
```

_Kvantum/style/style.pro_
```
#    QT += KWindowSystem
    INCLUDEPATH += /usr/include/KF5 /usr/include/KF5/KWindowSystem
    LIBS += -L/usr/lib/x86_64-linux-gnu -lKF5WindowSystem
```

BTW, there is no KWindowSystem module on Qt 5.14, but there is a KDE library for KWindowSystem.

**Comment by tsujan** [comment]
Hi,

> I'm using Linux Debian 9 with KDE and Qt 5.14. I had to make the following modifications to build Kvantum:

Debian 9 is too old. I don't know how you installed Qt 5.14 on it but your installation should have a serious problem. Most probably, Kvantum won't work as intended on your system.

> BTW, there is no KWindowSystem module on Qt 5.14

As is explained in `INSTALL.md`, you need `libkf5windowsystem-dev` on Debian.

I recommend you upgrade your Debian installation to Testing ("bullseye") at least.

**Comment by viniciusjl** [comment]
No, Debian 10 is the latest Debian version, but only for 4 months, and there is no problem to install Qt 5.14 on it, which kind of intallation problem should I have?

Yes, the libkf5windowsystem-dev is installed, but `QT += KWindowSystem` indicates the KWindowSystem module of Qt, this module does not exist in Qt (in any Qt version), that's the reason why I inserted the `LIBS` and `INCLUDEPATH` lines in pro file (so Qt can find this KDE library).

**Comment by viniciusjl** [comment]
BTW, is Kvantum installed only in `/usr/bin`?

Is it possible to install Kvantum in `/opt/kvantum` (for example)?

Like:
`qmake -r PREFIX=/opt/kvantum`

**Comment by tsujan** [comment]
> No, Debian 10 is the latest Debian version

You said "Debian 9" (see your first comment).

The latest Qt version in Debian is [5.12.X](https://packages.debian.org/sid/qt5-default). You should have installed 5.14 manually or from an unofficial repository. What you said shows that the installation has a problem.

If you want to always have the latest stable Qt *without problem*, you couldn't relay on Debian 10 -- actually, you couldn't rely on Debian sid either; you need Arch or a similar distro.

> BTW, is Kvantum installed only in /usr/bin?

Nonstandard paths are possible with the cmake installation but there's no guarantee they work fine without further action. So, they aren't recommended. See `INSTALL.md`.

**Comment by tsujan** [comment]
BTW, Qt 5.14 has no advantage over Debian's Qt 5.12. Actually Qt 5.13 and Qt 5.14 has regressions not found in 5.12. I really recommend you stay with Debian's official repository; they know what they do.

**Comment by viniciusjl** [comment]
> You said "Debian 9" (see your first comment).

Yes, Debian 9. :D

> The latest Qt version in Debian is 5.12.X. You should have installed 5.14 manually or from an unofficial repository. What you said shows that the installation has a problem.

Ok, but I always download the latest Qt sources and install it.

> BTW, Qt 5.14 has no advantage over Debian's Qt 5.12. Actually Qt 5.13 and Qt 5.14 have regressions not found in 5.12. I really recommend you stay with Debian's official repository; they know what they do.

Ok, I see it.

**Comment by tsujan** [comment]
> Ok, but I always download the latest Qt sources and install it.

The best way of installing important programs in Debian is the Debian way. Debian is well-known for its stability -- even Debian sid is more stable than Arch -- which require lots of work by Debian maintainers.

Of course, Linux is flexible but if you do things differently, you'll have to accept the consequences. And believe me: there may be many.

**Comment by viniciusjl** [comment]
> The latest Qt version in Debian is 5.12.X. You should have installed 5.14 manually or from an unofficial repository. What you said shows that the installation has a problem.

I was thinking about this, I think that the only way to `Qt += KWindowSystem` works is if the Debian staff added a new module on Qt framework. In Qt documentation there is no mention about KWindowSystem module.

BTW, anyone can download Qt official sources, see [Qt Official Releases](https://download.qt.io/official_releases/qt/).

**Comment by tsujan** [comment]
> I think that the only way to Qt += KWindowSystem works is...

Please note that Kvantum is compiled and tested by several distros. `QT += KWindowSystem` works in all distros -- on a standard Debian installation too. 

KWindowSystem doesn't belong to Qt. It's KDE developers' contribution to Qt5.

> BTW, anyone can download Qt official sources

Yes, of course. Anyone can download anything. But what one does with it is one's responsibility.
