### ISSUE TITLE
Option for QValidator in lineedit?

### ISSUE THREAD

**Issue by demmm** [tsujan/Kvantum#474]
There are several Qt & KDE apps that I know of that implement color changes for different line inputs. Konsole/kate/kwrite for example have in their find/search option the lineedit color set to green if a string is found, red if not.  This works on any application style I know of (fusion, breeze, qtcurve to name a few).  With Kvantum, any theme I tried, no such color change are implemented.
An app like Octopi changes color on different search results too, see:
https://github.com/aarnt/octopi/blob/0a7f7c782ed898a0580bcf78de248abe2fa4fe5a/src/searchlineedit.cpp#L200
If I set LineEdit > interior=false, then the notFound color is applied (yellow for Found is never applied).  With interior=true, the focus color is always applied, color that Octopi sets is ignored.
I have tried adding lineedit elements to a custom kvantum .svg file, normal and focused are shown as should. Is there currently a way to show lineedit elements for other events?  If not, is there a plan to add QValidator as a read option for lineedit output?

**Comment by tsujan** [comment]
Simply put, all of those apps do it wrong. Their codes were written when developers thought `QStyle` was only what they saw in a few style widgets. Unfortunately, some developers still have that idea.

To change the colors of a widget (line-edit included) correctly, there are two ways: (a) Either you should draw it completely in your code by using `QStyle` methods — in other words, you use a hard-coded style — or (b) you use stylesheets correctly; stylesheets override `QStyle` (but are ugly).

Kvantum rightfully resists hard-coded palettes as far as possible. It uses SVG elements to draw widgets.

**Comment by tsujan** [comment]
> Is there currently a way to show lineedit elements for other events?

They aren't Qt events but specific methods inside some apps. Kvantum covers all Qt events.

**Comment by demmm** [comment]
>It uses SVG elements to draw widgets

That was my first question.  Is there an option to use a lineedit element to show other events besides normal & focused? This is not a question about an app, just trying to see if I can get Kvantum to show same options as other application styles show.

**Comment by tsujan** [comment]
> That was my first question. Is there an option to use a lineedit element to show other events besides normal & focused?

I answered your question above but give a thorougher explanation here:

"Normal" and "focused" aren't events but `QStyle` states. For a line-edit, the states are normal, focused, inactively normal, disabled, and inactively disabled. Some Kvantum themes ignore the inactive states but Kvantum supports them (other widget styles don't).

What Kate and Konsole do doesn't have anything to do with states. They just change palettes, supposing that the widget style should follow the change. That's a false assumption in most cases. Sadly, other developers copy those codes in their apps...

**Comment by demmm** [comment]
>For a line-edit, the states are normal, focused, inactively normal, disabled, and inactively disabled.

Thanks for that, maybe that will do.  Will try some extra svg elements with those options.

**Comment by tsujan** [comment]
> Thanks for that

You're welcome.

> maybe that will do

It isn't related to what Kate does ;)

Actually, I've added workarounds to Kvantum for code mistakes that were very frequent. One example is "color button". Most developers think that once they change the palette of a button, the style should reflect that and they will have a "color button" in their apps. This mistake was so frequent that I added a workaround for it several years ago.

By "mistake" I mean something that contradicts Qt's methods. But even skillful developers might make them.

Anyway, I might add a workaround for this one too if it proves to be worth the effort — but no promise ;)

**Comment by tsujan** [comment]
A (complex) workaround is possible, although it temporarily makes rounded line-edits of some Kvantum themes as ugly as Breeze's line-edits:

![kate](https://user-images.githubusercontent.com/981076/73125273-44dca800-3fba-11ea-9eea-7701f276681f.png)

I should do lots of test before making sure that it's safe to add a commit.

EDIT: I added this comment an hour ago but GitHub had a problem. So, it might be duplicated later.

**Comment by demmm** [comment]
If you have a patch available, I sure will help with testing.

**Comment by tsujan** [comment]
@demmm 

My tests are only for finding probable cases where it might have a side effect for normal line-edits; otherwise, it works with palette change (as Kate and Konsole enforce). So far, so good :)

I'll tell you here when I add the commit -- now, I'm a little busy with other projects.

**Comment by demmm** [comment]
OK, thanks for all the work :).

**Comment by tsujan** [comment]
@demmm 

I added the commit. You could test the latest git Kvantum now. Thanks!

**Comment by demmm** [comment]
Fix is perfect here, tested mostly in the custom theme, but also in default Kvantum. Example:
![Screenshot_20200126_113738](https://user-images.githubusercontent.com/5360485/73133966-b5bea700-4030-11ea-9c31-38949fe17ddf.png)

**Comment by tsujan** [comment]
Thanks for testing! I really appreciate it. If you found any problem, please tell me.

**Comment by demmm** [comment]
A few more KaOS users have tested it, on a variety of themes, no issues found so far.

**Comment by tsujan** [comment]
That's good news :)

Anyhow, there's a lot of time for testing/reporting before I publish the next release.
