### ISSUE TITLE
ArcDarker as build-in theme

### ISSUE THREAD

**Issue by r34gzilla** [tsujan/Kvantum#477]
It would be cool to have also the missing third arc-style "ArcDarker" as build-in theme in kvantum. I'm sadly not good in graphics design nor creating themes, so i can't do that myself.

**Comment by tsujan** [comment]
I'm afraid — as I've explained in different places (please read https://github.com/tsujan/Kvantum/issues/395#issuecomment-499693642) — I won't add another GTK clone to Kvantum but will maintain/update KvGnome(Dark) and KvYaru. Adding KvArc and KvAdapta to Kvantum was my mistake (they aren't aesthetically appealing to me) but I might keep them as they are.

**Comment by flipwise** [comment]
@r34gzilla the ArcDarker theme already exists: https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/Kvantum/ArcDarker
