### ISSUE TITLE
qt4: kvantumpreview & kvantummanager

### ISSUE THREAD

**Issue by newsiberian** [tsujan/Kvantum#48]
Hello, @tsujan. Is there a way now to build kvantumpreview and kvantummanager for qt4?

**Comment by tsujan** [comment]
Yes, of course. Just issue a command like

    qmake && make

inside the folder "kvantummanager". Here, qmake should belong to Qt4 and you might need to use its path. Then use ""sudo make install" for installation. The same thing can be said about kvantumpreview.

**Comment by tsujan** [comment]
I forgot to say this:
If you want to compile kvantummanager against Qt4 just because the Qt5 version changed the order of keys on saving, that's not the case anymore. And kvantummanager controls both Qt4 and Qt5, regardless of its own compilation method.

**Comment by newsiberian** [comment]
Thank you, @tsujan.
