### ISSUE TITLE
Messed up homepage

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tsujan/Kvantum#482]
The homepage seems to be broken.
![image](https://user-images.githubusercontent.com/50847364/74210666-817bf500-4c84-11ea-8288-9e29fe706a9f.png)

This is how it should look. Repo:[Linux](https://github.com/torvalds/linux)
![image](https://user-images.githubusercontent.com/50847364/74210633-5b565500-4c84-11ea-94a9-49b569d52981.png)
My advice is to fix it, just to make it the most convenient and easiest to navigate as possible.

**Comment by tsujan** [comment]
Read https://github.com/tsujan/Kvantum/issues/230 and similar pages
