### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by GalacticLion7** [tsujan/Kvantum#485]
Hi.

CMake is failing to compile Kvantum. I am getting these errors:
`CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/marwan/Kvantum/Kvantum/build/CMakeFiles/CMakeOutput.log".`

Here is 'CMakeOutput.log,' but it doesn't say much:
`The system is: Linux - 5.4.12-144.current - x86_64`

I am using Solus 4.1.

Thanks.

**Comment by tsujan** [comment]
You might want to ask this question on Solus forums. I'm not familiar with Solus (it doesn't seem to have been derived from a well-known distro) but, apparently, you don't have the basic packages required for compilation on your system; probably, GCC (`g++` or whatever its name is in Solus) or `make`. Also, take a look at `INSTALL.md` inside Kvantum's folder, although you'll need to "translate" the names of required packages into Solus' package list.

All in all, I recommend you consult an expert in Solus on how to compile with `cmake` under Solus.

**Comment by GalacticLion7** [comment]
> You might want to ask this question on Solus forums. I'm not familiar with Solus (it doesn't seem to have been derived from a well-known distro) but, apparently, you don't have the basic packages required for compilation on your system; probably, GCC (`g++` or whatever its name is in Solus) or `make`. Also, take a look at `INSTALL.md` inside Kvantum's folder, although you'll need to "translate" the names of required packages into Solus' package list.
> 
> All in all, I recommend you consult an expert in Solus on how to compile with `cmake` under Solus.

I fixed the issue by installing a build essentials metapackage. Also, Solus is based on generic Linux, not a distro.

**Comment by tsujan** [comment]
> Also, Solus is based on generic Linux, not a distro.

According to [Wikipedia](https://en.wikipedia.org/wiki/Linux_distribution), "A Linux distribution (often abbreviated as distro) is an operating system made from a software collection that is based upon the Linux kernel and, often, a package management system." It should have had "open source" as a condition too (which Solus is).

[DistroWatch](https://distrowatch.com/table.php?distribution=solus) also calls it "a Linux distribution".

**Comment by GalacticLion7** [comment]
> > Also, Solus is based on generic Linux, not a distro.
> 
> According to [Wikipedia](https://en.wikipedia.org/wiki/Linux_distribution), "A Linux distribution (often abbreviated as distro) is an operating system made from a software collection that is based upon the Linux kernel and, often, a package management system." It should have had "open source" as a condition too (which Solus is).
> 
> [DistroWatch](https://distrowatch.com/table.php?distribution=solus) also calls it "a Linux distribution".

The package manager of Solus, eopkg, is based on the standalone version of PiSi. Would it be right to call it a PiSi distribution just because of that?

**Comment by tsujan** [comment]
The word "distro" is more generic than you might think and distros can be categorized in various ways. For example, based on whether they follow another distro or not. In that sense, Solus seems to be an independent distro, like Arch, Debian, OpenSUSE and Red Hat are.

Anyway, if you know the list of packages that are required for compiling Kvantum on Solus, I could add them under `INSTALL.md` → `Distributions`.

**Comment by GalacticLion7** [comment]
I was trying to find a way to refer to a Linux distro that isn't based on any other Linux distro. If I just said "Linux distro" then it would've seemed to vague on what this distro's origin is, which is what seemed to have happened when you initially assumed Solus is based on a distro:

> it doesn't seem to have been derived from a well-known distro

Anyways, I had to install the system.devel component (`sudo eopkg install -c system.devel`) in order to compile Kvantum and other software.
