### ISSUE TITLE
Concern about packages and INSTALL.md

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tsujan/Kvantum#486]
I've checked Kvantum in other repositories, and I have noticed that a lot of those packages aren't maintained and packaged by you. You should clarify that those packages aren't maintained by you because if someone starts a thermonuclear war because of the maintainer badly maintaining the package, the user might blame you.
![image](https://user-images.githubusercontent.com/50847364/74488400-fd12b780-4eb9-11ea-9aab-302fd76f60f8.png)
https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/

**Comment by tsujan** [comment]
Generally, in Linux, developers don't maintain installable packages for their programs. That's a distro job. Kvantum isn't an exception in this regard.

> because of the maintainer badly maintaining the package, the user might blame you.

That almost never happens. Specially, Arch users know these things very well. Moreover, the screenshot you attached is from https://www.archlinux.org/packages/community/x86_64/kvantum-qt5/ and it seems quite good to me (Arch packages are usually so).

**Comment by tsujan** [comment]
In other words, we have something called "downstream problems". They should be reported to distro maintainers.

Fortunately, I haven't received such reports here (or if I have, they should have been very rare) but I've seen such mistakes with other projects, in whose development I participate.

**Comment by TheEvilSkeleton** [comment]
> Fortunately, I haven't received such reports here (or if I have, they should have been very rare) but I've seen such mistakes with other projects, in whose development I participate.

Alright, that is good to know, though the [AUR](https://aur.archlinux.org/packages/kvantum-qt5-git/) package is not maintained by the distro, but by the community so do keep that in mind.

**Comment by tsujan** [comment]
> not maintained by the distro, but by the community so do keep that in mind.

LOL! Arch is nothing without its community. And I've used Linux for 15 years ;)

**Comment by TheEvilSkeleton** [comment]
LMAO, I agree. But because it's Arch, and it comes from the AUR, and a lot of people use Arch as a flex material, don't expect people to come after you saying that their package isn't working. I'm just looking out for you that's all.

**Comment by tsujan** [comment]
I appreciate your concern but let me put it this way:

Community is an important thing -- maybe the most important -- in Linux. No one does all jobs by himself/herself; others help (as you did) and this kind of cooperation would be impossible without trust.

Actually, most developers share their work in Linux because they know their works will become better and better once the Linux community finds them. IMO, that's the main reason why Linux has a high quality.
