### ISSUE TITLE
Aplication Cantata crashes

### ISSUE THREAD

**Issue by cesasol** [tsujan/Kvantum#49]
When using this style cantata (qt5) inmediatly crashes
https://github.com/CDrummond/cantata

$ cantata
[1]    27837 segmentation fault (core dumped)  cantata

**Comment by tsujan** [comment]
Yes, I'll look into that. Thanks a lot for reporting!

**Comment by tsujan** [comment]
For now, please disable "x11 drag" in Kvantum Manager > Configure Active Theme > Miscellaneous, until I fix the problem.

**Comment by tsujan** [comment]
Fixed. Please try the latest commit! The fix was easy but fundamental. I'll also update the deb package soon.
