### ISSUE TITLE
Inconsistency detected by ld.so: ../elf/dl-tls.c: 73: _dl_next_tls_modid: Assertion `result <= GL(dl_tls_max_dtv_idx) + 1' failed!

### ISSUE THREAD

**Issue by d4em0n** [tsujan/Kvantum#494]
kvantummanager can't run and showing this message
```
$ kvantummanager
Inconsistency detected by ld.so: ../elf/dl-tls.c: 73: _dl_next_tls_modid: Assertion `result <= GL(dl_tls_max_dtv_idx) + 1' failed!
```
my OS is KDE Neon 5.18

**Comment by tsujan** [comment]
That's a downstream problem, not Kvantum's.

Hopefully, the problem is in the Kvantum package that you've installed; otherwise, the message is about glibc failure. In the first case, you need to find an up-to-date Kvantum package.
