### ISSUE TITLE
How to install tutorial

### ISSUE THREAD

**Issue by TheEvilSkeleton** [tsujan/Kvantum#496]
Hello, I have found a great video that shows you how to install Kvantum themes. In case you are interested, you can add it if you want. https://youtu.be/Ei4dUD233k0

**Comment by tsujan** [comment]
Being specific to Ubuntu and KDE, the video can't be added to README but, yes, it's a nice video that explains very well how to use Kvantum under KDE; I especially liked that it emphasized the importance of KDE color schemes for some KDE apps (like systemsettings5). I might use its link if Kubuntu users ask me about Kvantum.

Thanks!

**Comment by tsujan** [comment]
BTW, I made and added `KvYaru` especially for Ubuntu users a year ago; there's no mention of it in the video, probably, because it's a little old.

**Comment by TheEvilSkeleton** [comment]
I will contact him and see if he's interested in doing another video about it while being a bit more "universal", though he seems to be inactive, so he may not answer.

**Comment by tsujan** [comment]
It's OK. Kvantum Manager has so many tooltips and explanations. I don't think anyone could have problem with using it.

As for installing the latest git version for Ubuntu, @krisives creates nice packages: https://code.launchpad.net/~krisives/+archive/ubuntu/kvantum/+packages

I should have added the info on @krisives's work to README but, not being an Ubuntu user, I don't know the proper way of doing so. @krisives, could you please tell me how I can add the info?
