### ISSUE TITLE
Kleopatra crashes when using Kvantum

### ISSUE THREAD

**Issue by xuzhao9** [tsujan/Kvantum#497]
Environment:
   openSUSE Tumbleweed 20200311 (latest)
Steps to reproduce:
1. Open Kleopatra (version 19.12.3-1.1)
2. Open menu "Settings-> Configure Kleopatra ->GnuPG System"
3. The program crashes (segmentation fault)

Segfault stack backtrace:
[KCrash Handler]
#6  0x00007fd6d9ee5035 in Kvantum::Style::styleHint (QStyle::StyleHint, QStyleOption const*, QWidget const*, QStyleHintReturn*) const () from /usr/lib64/qt5/plugins/styles/libkvantum.so
#7  0x00007fd6f2f60e01 in KDHorizontalLine::paintEvent (QPaintEvent*) () from /usr/lib64/libKF5Libkleo.so.5
#8  0x00007fd6ef234d18 in QWidget::event (QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007fd6ef2d7f2e in QFrame::event (QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#10 0x00007fd6ef1f4a0c in QApplicationPrivate::notify_helper (QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007fd6ef1fc020 in QApplication::notify (QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007fd6ee3c50d8 in QCoreApplication::notifyInternal2 (QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#13 0x00007fd6ef22db05 in QWidgetPrivate::sendPaintEvent (QRegion const&) () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007fd6ef22e2c5 in QWidgetPrivate::drawWidget (QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007fd6ef22ee40 in QWidgetPrivate::paintSiblingsRecursive (QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/libQt5Widgets.so.5

Could you please help reproduce this problem?

**Comment by tsujan** [comment]
Yes, I can reproduce it here. Will investigate it.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/a7ccc09813447441c141e608e6ccae602f29d21e

I'll release the fix point release 0.15.1 soon.

Thank you very much for your report!

**Comment by tsujan** [comment]
I released [0.15.1](https://github.com/tsujan/Kvantum/releases/tag/V0.15.1) just now. Hopefully it'll come to Tumbleweed soon (with @trmdi's work).

**Comment by xuzhao9** [comment]
I can confirm that the problem is fixed on my system. Thank you!

**Comment by tsujan** [comment]
Thanks for the confirmation and please don't hesitate to report any problem you might encounter.
