### ISSUE TITLE
Kvantum 0.8.21 deb fails to install on kubuntu 14.04 LTS

### ISSUE THREAD

**Issue by wolfland** [tsujan/Kvantum#50]
Kvantum 0.8.21 deb fails to install on kubuntu 14.04 LTS with the following error:

 sudo dpkg -i 166241-kvantum_0.8.21_amd64.deb 
(Reading database ... 205041 files and directories currently installed.)
Preparing to unpack 166241-kvantum_0.8.21_amd64.deb ...
Unpacking kvantum (0.8.21) over (0.8.20-1) ...
dpkg: dependency problems prevent configuration of kvantum:
 kvantum depends on libqt5core5a (>= 5.4.0); however:
  Version of libqt5core5a:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 kvantum depends on libqt5gui5 (>= 5.4.0); however:
  Version of libqt5gui5:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 kvantum depends on libqt5svg5 (>= 5.4.0); however:
  Version of libqt5svg5:amd64 on system is 5.2.1-1.
 kvantum depends on libqt5widgets5 (>= 5.4.0); however:
  Version of libqt5widgets5:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 kvantum depends on libqt5x11extras5 (>= 5.4.0); however:
  Version of libqt5x11extras5:amd64 on system is 5.2.1-1.

dpkg: error processing package kvantum (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Errors were encountered while processing:
 kvantum

This does not occur on kubuntu 15.04 with plasma5 only on kubuntu 14.04 LTS.
Kvantum seems to be expecting qt5 tools >=5.4.0 and 14.04 LTS only has 5.2.1.

I have gone back to kvantum 0.8.20-1 for now.

Thanks,
WolfLand

P.S. I really like the new kvcurves theme. Would a version with blue highlight color be in the
offing ?.  I really need to learn how to use inkscape so I can make minor changes myself but
so far I have not been able to get anywhere with it.

**Comment by tsujan** [comment]
Hello!
Yes, I know that. it's because Qt-5.4.2 (current in Debian) is the first version of Qt5, in which some bad bugs are fixed at last, and it isn't completely compatible with the previous versions. You have two options, at least:

(1) Compilation from the source. Kvantum can be compiled against any version of Qt4 and Qt5.
(2) Updating your Qt5.

The first way is much easier. Anyway, DO NOT update your Kubuntu to v15.10! I've tried it on VirtualBox and found it buggy.

**Comment by tsujan** [comment]
As for Inkscape, you could change colors and color gradients without it and with a text editor like Kate too. Just open the SVG file with Kate, search for any color, and play with it.

**Comment by wolfland** [comment]
Tsujan,

            I'll look into updating the Qt5 first as this will solve the 
problem for the future. If
            I can't update the Qt5 I will compile from source.

            Thanks for the info on Kubuntu 15.10. I will wait until 
Alpha2 or Beta1 to play with
            it.

WolfLand

**Comment by wolfland** [comment]
I will give that a try.

Thanks,
WolfLand

**Comment by tsujan** [comment]
For compilation from the source(which is easy) read the file INSTALL. Good luck!
As this wasn't a bug report, I close it.
