### ISSUE TITLE
kvantum causes System Settings crash on Wayland session of KDE Plasma when I set a kvantum theme

### ISSUE THREAD

**Issue by glaubersm** [tsujan/Kvantum#503]
Hi
This issue was already reported in KDE bugzilla. You can find steps to reproduce and backtrace in the following link:
https://bugs.kde.org/show_bug.cgi?id=418989

My system:
kvantum 0.15.1
Operating System: KDE neon Unstable Edition
KDE Plasma Version: 5.18.80 (Wayland session)
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.1

**Comment by tsujan** [comment]
Please see https://github.com/tsujan/Kvantum/issues/431.

KWin's blur effect has serious problems under Wayland.

**Comment by tsujan** [comment]
BTW, I can't reproduce the crash with Plasma Wayland 5.18.3. So, the problem can be in unstable version you have.

**Comment by glaubersm** [comment]
I can reproduce this crash even when blur effect is disabled.
I will test kvantum 0.15.1 on Arch when available.

**Comment by tsujan** [comment]
Apparently, it repeats every year, in March (read my explanations at https://github.com/tsujan/Kvantum/issues/357 to know why Kvantum cannot cause that crash). Unstable KDE means that it's unstable.
