### ISSUE TITLE
Invisible (transparent) tabs in Konsole

### ISSUE THREAD

**Issue by dennisfen** [tsujan/Kvantum#512]
Hi! I have this problem with transparent tabs in Plasma Konsole. Is it a bug or am I doing something wrong in configuration?

Kvantum v0.14.1
Arc KDE theme

![kvantum](https://user-images.githubusercontent.com/2673351/77745855-507d3700-701c-11ea-957a-7e3af7fda67c.png)

**Comment by whyman** [comment]
I had this problem, not sure what fixed it, some update to Qt 5.12 or KDE frameworks.

**Comment by dennisfen** [comment]
@whyman I'm on Qt 5.14 right now

**Comment by tsujan** [comment]
@dennisfen, upgrade to Kvantum 0.15.1, the latest release.

**Comment by tsujan** [comment]
> Is it a bug or am I doing something wrong in configuration?

It was a Kvantum bug, which was fixed in V0.15.0.

**Comment by dennisfen** [comment]
The update fixed the problem, thanks!
