### ISSUE TITLE
Untranslated button boxes into french

### ISSUE THREAD

**Issue by roxfr** [tsujan/Kvantum#516]
Hi,
In the overview of Kvantum, there are untranslated button boxes (see image below).
=> Yes / OK / Save / Open / No / Cancel / Apply
Regards,
roxfr

<a href="https://zupimages.net/viewer.php?id=20/15/w9sv.png"><img src="https://zupimages.net/up/20/15/w9sv.png" alt="" /></a>

**Comment by tsujan** [comment]
Hi,

The translations of those buttons are in `qt5-translations`; they belong to Qt. Make sure you've installed `qt5-translations`.

**Comment by roxfr** [comment]
Yes it's good with qt5-translations.
Thanks

**Comment by tsujan** [comment]
You're welcome.
