### ISSUE TITLE
Editable combobox and combobox dropdown menu

### ISSUE THREAD

**Issue by Hombremaledicto** [tsujan/Kvantum#52]
Hi, i'm here again to present what i do see as an issue in kvantum, as the title said it's about comboboxes. 
#### Issue #1 : editable comboboxes are painted with elements from two different widgets:

![schermata547](https://cloud.githubusercontent.com/assets/7595097/9423159/166e0448-48b9-11e5-93b2-9cd431cbefad.png)

![schermata545](https://cloud.githubusercontent.com/assets/7595097/9423160/1f1f71da-48b9-11e5-8d93-9c1ce9b7f19a.png)

As a matter of fact, i'm pretty sure this can be workaround pretty much by designing components awared of this, i do believe it is better to just use the whole frame/interior from lineedit, as it's done for spinboxes. Also to stress the concept that we're dealing with an editable widget:

![schermata548](https://cloud.githubusercontent.com/assets/7595097/9423169/6e798a86-48b9-11e5-997f-042ed8c9c504.png)
#### Issue #2 : The combobox dropdown menu could use a frame

![schermata546](https://cloud.githubusercontent.com/assets/7595097/9423173/9d3d5406-48b9-11e5-8ac4-72ee449d8ded.png)

This, of course, is an issue with the palette i chose in the first place, and i'm not sure if that's something already available to customize/fix it. 
I don't even think shadows are required (could be, but not necessarly) for this menu, just a frame IMHO.

**Comment by tsujan** [comment]
Thank you for telling me about your ideas!

Yes, in editable comboxes, three widget elements may be used: one for the combo itself (under the icon, if it's shown), another for its line-edit, and yet another for its drop-down part. These are really three different parts of an editable combo and Kvantum shows that correctly. However, I'll add an option for using the line-edit SVG elements for the whole combo.

I'll try to add another option for showing the combo drop-down menu as an ordinary menu. That was what I had in mind for a long time but forgot about.

**Comment by tsujan** [comment]
The first idea is implemented. Its key is "combo_as_lineedit" under the General section and is included in Kvantum Manager > Miscellaneous tab too. Theme-Config is updated but not "Theme-Config.pdf". Please test!

The implementation of the second idea takes more time.

**Comment by Hombremaledicto** [comment]
Awesome!! This was something that bothered me for a long time, but always forgot to ask. So nice to have it.
Testing right now, seems no issue so far and it is rendered as expected.

As for the second issue no problem, i'll keep an eye for future commits.

**Comment by tsujan** [comment]
Now the generic frame is used for combo menus too. In your theme its name is "common" (by inheritance from Kvantum's default theme). If you want more contrast, you could choose another color for the "common" elements and, perhaps, increase the frame widths under GenericFrame.

Because Kvanum uses SVG elements for menus, transforming combo menus to ordinary ones turned out to be possible only through the paint event. But that may cause unpredictable complications in some apps. So, I preferred to leave combo menus as they were.

**Comment by Hombremaledicto** [comment]
Trying right now, and it seems a better solution than using the shadows from menus to me, on the design perspective.
Thanks for accepting my request!

**Comment by tsujan** [comment]
Thanks for your suggestions!
I'll leave this issue open until I'm sure that I don't want to take the risk I mentioned.

**Comment by tsujan** [comment]
"Combo popup as menu" is added by Craig Drummond to v0.10.2. In Kvantum, combo menus can't look like ordinary menus because of several parameters added to in the latter. Closing this.
