### ISSUE TITLE
kde titlebar blur doesnt work

### ISSUE THREAD

**Issue by joe23rep** [tsujan/Kvantum#521]
is there a setting im missing? i cant get blur behind the titlebar to work. everywhere else it works fine. when i switch from kvantum to breeze widget style it works. so the issue is not within the compositor. 

the werid thing is- once u change back from breeze to kvantum the blur behind the titlebar works. the moment u reboot uve a transparent titlebar agin though. 

i assume this isnt a setting issue but rather a bug but i thought id ask anyways.

**Comment by tsujan** [comment]
Title-bar is a part of what is called "window manager" — in the case of KDE, it's KWin — and doesn't have any relation to Kvantum or any other widget style.

The default KWin's theme, which is called Breeze (like the default KDE widget style and the default KDE icon themes and…), doesn't support title-bar translucency/blurring. You need a fork that does, like [BreezeEnhanced](https://github.com/tsujan/BreezeEnhanced).

**Comment by joe23rep** [comment]
i do. i actually run hello. but i also have breezeway mod installed. i just wonder why it works with hello and breeze as widget style but with kvantum and hello the titlebar is just transparent?

**Comment by tsujan** [comment]
> i actually run hello. but i also have breezeway mod installed

I don't know about `hello`, so I can't tell anything about it. BreezeEnhanced, BreezeBlurred and similar forks of the Breeze KWin decoration follow its code line by line but add their enhancements to it.

Anyhow, this has nothing to do with Kvantum but with the KWin decoration fork you use.

**Comment by joe23rep** [comment]
ok. ill check out the mentioned ones and see how it goes. thanks
