### ISSUE TITLE
Gwenview status bar won't render properly with transparency

### ISSUE THREAD

**Issue by Zzombiee2361** [tsujan/Kvantum#522]
With transparency  
![Screenshot_20200425_204157](https://user-images.githubusercontent.com/37852137/80281461-8275dc00-8735-11ea-938e-4139c8f3ffd9.png)

Without transparency  
![Screenshot_20200425_204444](https://user-images.githubusercontent.com/37852137/80281485-af29f380-8735-11ea-82a6-33d785b9275e.png)

**Comment by tsujan** [comment]
Not reproducible:

![Gwenview](https://user-images.githubusercontent.com/981076/80284331-201bdc00-8733-11ea-857e-2ba2f216d980.png)

**Comment by Zzombiee2361** [comment]
Are you running the latest gwenview? Reproducible every time with gwenview 20.04, even with the default theme  
![Screenshot_20200426_000318](https://user-images.githubusercontent.com/37852137/80285827-cbd42480-8751-11ea-9d29-cad5135668df.png)

**Comment by tsujan** [comment]
> Are you running the latest gwenview?

Good question. No, it's still 19.12.3-1 here because I update the system once in 3 days. Will update it tonight and tell you. Please be patient.

However, if gwenview 20.04.0 (which is in my `/var/cache/pacman/pkg`) has this problem, *it'll be a gwenview bug*, not Kvantum's. The most I could do would be trying to find a workaround *if possible*.

**Comment by tsujan** [comment]
OK, I upgraded the system and rebooted. Now, gwenview's version is [20.04.0-1](https://www.archlinux.org/packages/extra/x86_64/gwenview/) and it has no problem whatsoever.

I'm afraid something on your part may be the cause. Incomplete updates? Bad packaging? Which distro?

**Comment by Zzombiee2361** [comment]
KDE Neon. I'm using kvantum 0.15.2 from papirus ppa, could that be a problem?

**Comment by Zzombiee2361** [comment]
Yep, definitely my config. Clearing gwenview config and cache fixes the problem

**Comment by tsujan** [comment]
> I'm using kvantum 0.15.2

It's the latest release.

> Yep, definitely my config. Clearing gwenview config and cache fixes the problem

Happy to know that your problem is solved -- although I don't know how gwenview config could have affected translucency.

**Comment by Zzombiee2361** [comment]
Yeah, I don't think it's the config either. Most likely broken cache, there's a qmlcache folder, probably that
