### ISSUE TITLE
Uneven margins/frame size for toolbars

### ISSUE THREAD

**Issue by zezic** [tsujan/Kvantum#525]
In the theme config documentation I read that `frame.top`, `frame.bottom`, `frame.left` and `frame.right` are not respected by toolbars and maximum value is used instead of exact values for each side. Is it possible to alter the toolbar layout to reduce the top margin or the top frame side but keep the bottom one? Shifting the toolbar contents a bit higher is also would be an option.

What I'm trying to achieve is a mimic of seamless toolbar+titlebar combination and I need to reduce the top margin:
![text861](https://user-images.githubusercontent.com/1945127/80871518-c4fb6380-8cb5-11ea-8887-714ef6d0b116.png)

I've tried some workarounds like reducing the toolbar margin to 0 and adding the transparent frames on each side of a button, it gave me almost what I wanted but it affected the horizontal spacing of buttons too much.

Altering the source code of Kvantum is also an option for me, but I didn't find the exact place where it can be done yet. Can you give some suggestions?

**Comment by tsujan** [comment]
Kvantum makes the best use of QStyle parameters. Just a small deviation from a QStyle parameter can result in serious bugs. `PM_ToolBarFrameWidth` and `PM_ToolBarItemMargin` don't distinguish between top, bottom, left and right.

I've seen signs in Qt's code that show Qt devs might, at last, separate horizontal and vertical toolbar parameters from each other. But that hasn't happened yet and I don't think it'll happen before Qt6. Moreover, there's no sign of distinguishing between top and bottom or right and left.
