### ISSUE TITLE
[bug] dolphin transparency

### ISSUE THREAD

**Issue by tiagocpontesp** [tsujan/Kvantum#529]
https://www.reddit.com/r/kde/comments/fnhv9u/kvantum_doesnt_make_dolphin_or_pcman_transparent/

**Comment by tsujan** [comment]
https://github.com/tsujan/Kvantum/issues/445#issuecomment-544578107

**Comment by anarchotaoist** [comment]
This effects me also.
Scaling to 100% reintroduces the transparency but scaling back up removes it.
Transparency is not working at a larger scale.

**Comment by tsujan** [comment]
With the latest release of Kvantum, uncheck `Kvantum Manager → Configure Active Theme → Hacks → Disable translucency with non-integer scaling`, after reading the warning.

**Comment by anarchotaoist** [comment]
> With the latest release of Kvantum, uncheck `Kvantum Manager → Configure Active Theme → Hacks → Disable translucency with non-integer scaling`, after reading the warning.

Thanks!
I had to install the ppa to get the newest version. It is great to see the translucency again! There is artifacting, so I will have to decide whether it is worth it.
Thanks for your reply and good work!

**Comment by tsujan** [comment]
You're welcome.

I thought it might be better if everyone saw the artifacts firsthand but only after seeing a warning. Also, with some themes, they may be tolerable. Qt 5.15 has reduced them a lot. Of course, they appear only with *non-integer* scale factors.

**Comment by anarchotaoist** [comment]
That makes sense!
I decided to enable the translucency but disable it for Dolphin as it seemed to be the only issue.
Thanks.
