### ISSUE TITLE
kubuntu 15.04 kded5 segfault after upgrade to plasma 5.3.2 from backports PPA

### ISSUE THREAD

**Issue by wolfland** [tsujan/Kvantum#53]
After upgrading to plasma 5.3.2 from the backports PPA I started getting segfaults from kded5 when
logging in. Today I worked on trying to determine what was causing the problem so I did the following:
- reset my account configuration to default (e.g. rm -f -R .cache .config .kde .kde4) from console.

Upon logging back in to a default configuration the segfault did not occur.

I then started adding my desktop configuration back one item at a time with a logout/login between
each step. After I set my style to Kvantum in the style dialog the problem re-appeared.

I then purged kvantum using sudo dpkg --purge kvantum and removed any items that were not
automatically removed and reinstalled kvantum 0.8.25 from deb and tried the logout/login again
and the problem was still there after setting the style back to kvantum. 

I then switched to the default Breeze style and the problem went away again.

I then purged kvantum again using the same proceedure from above and built kvantum from
source (qt4 and qt5) and installed them and the same problem occurred.

I tried using different kvantum themes and settings without any effect on the segfault.

I also checked my compositor settings and they were incorrect (e.g. openGL 2.0 and GLX)
so I changed them to the correct setting for my ATI card (openGL3.1 and EGL) this also
had no effect.

Kvantum seems to be working ok as far as I can tell once logged in so the kded5 segfault
just is an irritant at this point (e.g. having to close it every time you log in).

Kvantum was working fine on this machine before the upgrade to 5.3.2. Changing the
style to breeze works without any segfaults so it appears as if the upgrade from the
backports PPA is causing a problem for kvantum.

I will be going to plasma 5.4 as soon as it gets added to the backports repository and
will be starting a 15.10 build if the beta1 is stable enough to do so(on a different machine).

I realize this may be an untested configuration so don't spend too much time on it unless
you want to. I will let you know if this crops up on plasma 5.4 or 15.10 once I get a chance 
to get them up and running and feel free to close this as an untested configuration if you
want to.

Let me know if you need more info or need me to try anything.
Thanks,
WolfLand

Here is the kded5 segfault:

Application: kded5 (kded5), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f1593f31780 (LWP 12226))]

Thread 2 (Thread 0x7f1587c68700 (LWP 12227)):
#0  0x00007f15938ef8dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f158e43db72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f158e43f64f in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f1593ea1099 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#4  0x00007f1591bf6b0e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f159162d6aa in start_thread (arg=0x7f1587c68700) at pthread_create.c:333
#6  0x00007f15938faeed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f1593f31780 (LWP 12226)):
[KCrash Handler]
#6  0x00007f1591e348e0 in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f15932a8ab8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f15932ae000 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f1591e34c2b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f1591e6e27d in QObjectPrivate::setParent_helper(QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f1591e6e827 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f1591e734b9 in QSocketNotifier::~QSocketNotifier() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f1593f6c9df in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#14 0x00007f158f689cd3 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#15 0x00007f158f68830e in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#16 0x00007f158f688389 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#17 0x00007f158f68777b in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#18 0x00007f158f672542 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#19 0x00007f1593f6770a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#20 0x00007f1593f5ee22 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#21 0x00007f1593f5eea9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#22 0x00007f159382dd32 in __run_exit_handlers (status=0, listp=0x7f1593bb8698 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#23 0x00007f159382dd85 in __GI_exit (status=<optimized out>) at exit.c:104
#24 0x00007f1592a4f76f in KDBusService::KDBusService(QFlags<KDBusService::StartupOption>, QObject*) () from /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5
#25 0x00007f1593bcaf0c in kdemain () from /usr/lib/x86_64-linux-gnu/libkdeinit5_kded5.so
#26 0x00007f1593814a40 in __libc_start_main (main=0x400720 <main>, argc=1, argv=0x7ffe63d6f568, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe63d6f558) at libc-start.c:289
#27 0x0000000000400759 in _start ()

**Comment by tsujan** [comment]
Like issue #32, this may be temporary and due to incomplete PPA upgrade. At least, I don't see anything related to Kvantum in the segfault report.
Fortunately, I have a Manjaro installation on my other computer. If Plasma 5.3.2 has come to Manjaro, I'll test it and tell you about the result.

**Comment by tsujan** [comment]
This is the story about Manjaro (in short, everything's OK):

I did a full upgrade. Contrary to Debian based systems, in Arch based systems upgrading is often fast and clean, even with 400 Mb of download (don't get me wrong; may main system is Debian). I restarted Manjaro and everything worked fine with my older Kvantum installation. I upgraded Kvantum too, logged out/in and no problem. Finally, I restarted and ran some unusual KDE apps (kdenlive, digikam,...). Again no problem at all. The plasma version is 5.3.2, the Qt5 version 5.5.0.

So, I'm pretty sure that your problem is caused by the PPA upgrade.

**Comment by wolfland** [comment]
Ok.. I figured as much. Kvantum probably just uses the code that has the 
problem thus
triggering the segfault and not actually responsible for it.

Go ahead and close this as I will be going to 15.10 soon. I have to get 
going on my KDE
and Gnome spins so they are as complete as possible so I can concentrate 
on my "Elite"
spin when final beta hits.

Thanks Again,
WolfLand

P.S. almost forgot.. thanks for the tip on editing .svg files it has 
come in real handy.

**Comment by tsujan** [comment]
You're welcome.

Kvantum is purely Qt based, so if a Plasma version has any problem with it, it should have problem with the Qt plugin system. Such issues are often temporary.

BTW, I remembered that Debian also had plasma 5.3.2 and Kvantum had no problem with it. However, that Plasma was so buggy under Debian that I downgraded to KDE4. The same version is quite usable under Manjaro!
