### ISSUE TITLE
Kate - Close icon too small

### ISSUE THREAD

**Issue by gsbhasin123** [tsujan/Kvantum#532]
![image](https://user-images.githubusercontent.com/48339289/81758471-c6c3e480-9476-11ea-90a7-443d1975b92b.png)

Happens in all themes including inbuilt ones

**Comment by tsujan** [comment]
Kate draws its tabs itself.

**Comment by gsbhasin123** [comment]
@tsujan that may be true, but the breeze style isn't affected, so I still think this is a kvantum issue.
![image](https://user-images.githubusercontent.com/48339289/81831329-1398d100-94f2-11ea-837e-cfd80328558a.png)
that is breeze

**Comment by tsujan** [comment]
Whoever drew Kate's tab in Kate's code (why?!) is responsible for giving it the same look with all widget styles. Apparently, his/her code is incomplete and I can't compensate for others' mistakes in Kvantum.

**Comment by gsbhasin123** [comment]
Ah, thank you. I will report this upstream to the Kate editor.

**Comment by tsujan** [comment]
As far as I've seen their codes, they assume people should use Breeze -- not very dissimilar to Gnome dev's approach when it comes to styling.

**Comment by gsbhasin123** [comment]
Really? That sucks.

**Comment by tsujan** [comment]
Not as bad as in Gnome. I've optimistically considered it as a series of unintentional mistakes but  who knows?

There are workarounds in Kvantum for bad app codes but there is a limit to that. Developers should learn how to use `QStyle` in their codes if really needed. Breeze's code is 99% OK (I've found only one problem in it) but developers of other programs may make strange mistakes; hence my optimism ;)
