### ISSUE TITLE
Not applying styles to PyQt5 applications installed through Pip

### ISSUE THREAD

**Issue by nshiell** [tsujan/Kvantum#533]
When I run an application written in Python with the PyQt bindings it works and is styled correctly if installed PyQt5 by:
`sudo apt-get install python3-pyqt5`

However if I install with
`sudo pip3 install pyqt5` it does not apply styles.

This is an issue as Pip is needed to install PyQt as part of packaging for AppImages and with Snappy etc.

Is there any known solution for this for now?
Would changes need to be made in Kvantum to have this working or with other software?

**Comment by tsujan** [comment]
Problems like this aren't related to Kvantum.

Apart from that, I wouldn't recommend things like AppImages and Snappy. If you believe their advertisements, you should expect various problems that are never mentioned in the ads. *Always use your distro way of packaging!*
