### ISSUE TITLE
Question about Yaru theme and Ubuntu 20.04

### ISSUE THREAD

**Issue by MrAnon-dev** [tsujan/Kvantum#535]
Hi, 

The Ubuntu 20.04 default theme is Yaru or it´s a fork of Yaru? Because I have noticed that there are slight changes, such as the color of some elements, for example checkbox and radio buttons KvYaru (green), Ubuntu 20.04 (purple)

I have tried to edit the svg with inkscape but I have not made it work.

![KVyaru_vs_ubuntu-20 04-yaru](https://user-images.githubusercontent.com/65110156/83791234-bd0a5700-a699-11ea-8d01-3aab008c9f32.png)

Thanks!!

**Comment by tsujan** [comment]
Thanks! I'll update it as soon as I find the time.

Please tell me every time Yaru is changed, as you did now! I'm not an Ubuntu user and so, I won't know about that if no one tells me.

**Comment by MrAnon-dev** [comment]
thanks to you for all your work! 

I use several QT applications  (KeePassXC, VLC ...) and thanks to Kvantum look better for me, years before, I used a hack that now doesn't work well anymore.

regards

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/65d7a7089f35572ddc321e933f3dcdb651cf29aa

The GTK3 version of Inkscape made the job hard with its nasty bugs.
