### ISSUE TITLE
How can I let elements overlap other elements?

### ISSUE THREAD

**Issue by andrewaclear** [tsujan/Kvantum#539]
I'm trying to make round corners and larger shadows but if I do so it makes all the elements very spaced out and leaves large borders around everthing. How can I let a menu item and its shadow, for instance, overlap the menu border and its shadow?

**Comment by andrewaclear** [comment]
The `spread_menuitems=true` is cool thanks and yes I have used _frame expansion_, but I don't think 7 or 8 is a reasonable max for `menu_shadow_depth`. The only reason it kindof looks ok at that range is because the round corners are small, but the issue is still there.
![image](https://user-images.githubusercontent.com/51063733/84585083-e7ff5400-add9-11ea-8754-5f308750f29e.png)
I think I should be able to make round corners like this without the blur going into the shadow at the corners.

**Comment by tsujan** [comment]
> I think I should be able to make round corners like this without the blur going into the shadow...

No, because blurred regions are rectangular. This problem isn't specific to Kvantum's menu shadows.

Breeze uses KWin's shadow for menus too. Kvantum can't because it is independent of desktop environments and their window managers / compositors.

**Comment by andrewaclear** [comment]
So its **kwin** that needs to update?

**Comment by tsujan** [comment]
> So its kwin that needs to update/fix that issue?

No, KWin is OK -- actually, KWin's blurring is the best.

A region is approximated by rectangles. Regions consisting of curved boundaries need a lot of rectangles for a good approximation and that isn't worth the resource usage. So, no one cares.

Add to this the fact that, in Kavntum, it's practically impossible to know how much curved a boundary is because the curvature is in the SVG file, no hard-coded.

In old times, Compiz blurred regions based on their translucency, so that this problem wasn't so visible. KWin's blurring doesn't depend on translucency and that's good (some people like very translucent windows with a high degree of blurring).

**Comment by andrewaclear** [comment]
Ok I think I understand a bit more now. Thanks for your help!

For an artistic point of view, however, I think burring based on the region of the svg is the best. It might seem like not a bid deal to some but I'm an aspiring pretty serious UI designer and it just shouldn't look like that. If I have to hard code the blur boundary though that's fine, but how would I do that?

**Comment by tsujan** [comment]
> If I have to hard code the blur boundary though that's fine, just how do I do it?

Make a region out of the widget rectangle by artificially rounding its corners (which needs a lot of code as well as familiarity with `QRegion` and its related classes) and use it in `BlurHelper::blurRegion`. Whether KWin's blur effect will accept it or not, I don't know.

A more reasonable way could be removing small rectangles from the corners of the widget rectangle, if you want to play with the code.

However, the sizes of small rectangles or the radii of rounded corners can't be extracted from the SVG elements. So, as I said in my previous comment, there's no exact way to do it and it isn't worth the extra code.

**Comment by andrewaclear** [comment]
It does sound challenging unfortunately, but I think it should be implemented so that it is not so challenging. I think it is a big deal because it's these small things that really make the difference between like mac and other interfaces. I think linux is the best OS 100%, it's just not fully there yet and I'm hoping to help it get there!
