### ISSUE TITLE
Can you provide a software framework based on qss files?

### ISSUE THREAD

**Issue by libaineu2004** [tsujan/Kvantum#543]
Can you provide a software framework based on qss files?
Similar to this open source project:
https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle

Style is based on qss file loading, not source code.

**Comment by tsujan** [comment]
QStyle and Qt style sheet are not only very different from each other but also incompatible. Style sheets are too poor to be used by Kvantum.
