### ISSUE TITLE
qt5-style-kvantum not found in apt

### ISSUE THREAD

**Issue by meatnordrink** [tsujan/Kvantum#544]
When I try to install `qt5-style-kvantum` via `apt`, as per the readme, it says package not found. 

Is it still available via `apt`?

**Comment by tsujan** [comment]
If you mean Debian, [an old version is available](https://packages.debian.org/bullseye/qt5-style-kvantum), which I can't recommend. Apparently, the Debian maintainer of Kvantum disappeared without transferring the maintenance; so, I don't think Debian will have an up-to-date version of Kvantum soon.

If you mean another Debian-based distro, I don't know; there are many.

However, for Ubuntu, this PPA seems to have up-to-date packages: https://launchpad.net/~papirus/+archive/ubuntu/papirus

@varlesh, it seems the above-mentioned PPA is actually for your works (Papirus). Are its Kvantum versions kept up-to-date? If so, do you know how I can add the info to Kvantum's `INSTALL.md`? I don't have Ubuntu.

**Comment by varlesh** [comment]
@tsujan Yes it's our PPA and actually @SmartFinn maintainer

**Comment by tsujan** [comment]
@varlesh 
Thanks! I'll search the Internet to know how the info can be added to `INSTALL.md`.

**Comment by meatnordrink** [comment]
Thanks!

**Comment by tsujan** [comment]
@varlesh 
Are these commands OK for Ubuntu?
```
sudo add-apt-repository ppa:papirus/papirus
sudo apt update
sudo apt install qt5-style-kvantum qt5-style-kvantum-themes
```
And do I have the permission to add them to Kvantum's `INSTALL.md`?

**Comment by varlesh** [comment]
Yes, why not?!
