### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by RJVB** [tsujan/Kvantum#547]
- Why not respect the icons in buttons/menu choice set through the platform theme plugin, possibly as a global option and/or through optional inheritance of the KStyle class?
- How does one control the highlight colour? Why is it not obtained from the active (KDE) colour palette?
- would it be possible to write an application that renders all the widgets Kvantum knows how to theme to SVG files that can be used to create a Kvantum theme, or directly to such a theme - and if so, has anyone written such a utility? You'd be able to create a true copy of the native Macintosh theme, for instance.

**Comment by tsujan** [comment]
> Why not respect the icons in buttons/menu choice set through the platform theme plugin

If you mean their parameters, they are there to be customized by the widget style. That's how Qt is designed. Also, Kvantum Manager has options that say "Follow Style".

> How does one control the highlight colour?

Please consult "Theme-Config" in the doc folder (`highlight.color`, `inactive.highlight.color`, `highlight.text.color`,...).

> Why is it not obtained from the active (KDE) colour palette?

First, Kvantum is independent of KDE and, second, KDE's color scheme isn't suitable for Kvantum because Kvantum draws many backgrounds by using SVG elements, not colors.

> ... You'd be able to create a true copy of the native Macintosh theme, for instance.

No. A macOS theme depends on macOS and has a completely different structure.

In general, simple themes are easier to make. However, Kvantum isn't supposed to be limited to simple themes — otherwise, I'd have no reason to write it ;) Making a good theme usually requires patience and takes time.

**Comment by RJVB** [comment]
>> Why not respect the icons in buttons/menu choice set through the platform theme plugin
>
>If you mean their parameters, they are there to be customized by the widget style. That's how Qt is designed. 

Maybe, but if you use a style through a platform theme plugin that provides choices for those parameters, then you might expect that every style respects those choices (an expectation often broken, but still).

>Also, Kvantum Manager has options that say "Follow Style".

Which don't appear to have any impact on these 2 parameters.


>> Why is it not obtained from the active (KDE) colour palette?
>
>First, Kvantum is independent of KDE

But it does advocate itself as a theme engine for Qt and KDE

>> ... You'd be able to create a true copy of the native Macintosh theme, for instance.
>
>No. A macOS theme depends on macOS and has a completely different structure.

Yes, you could. Qt recreates the native Macintosh style entirely, by calling into lowlevel functions most people don't know exist, and then rendering its own widgets with the obtained information. Should I attach a screenshot of a Qt5 window rendered over remote X11 on a Linux system, using the native theme? It came as a suprise to me too that it worked, but after looking at the code I can assure you that it has to work. Only the entries in the toplevel menubar are drawn using higher level platform SDK functions (and won't render with the XCB QPA).

So, yes, if you can render a widget to an offscreen representation (preferably vectorial) and determine exactly what you'd need to extract to create an svg file that you can then use in a Kvantum theme, you could recreate an almost (or 100%) perfect clone of any widget style

>In general, simple themes are easier to make. However, Kvantum isn't supposed to be limited to simple themes — otherwise, I'd have no reason to write it ;) Making a good theme usually requires patience and takes time.

Who says you'd have to stop at the auto-generated theme? The best ones are those that look simple but contain enough clever not-so-simpleties so they not only NOT get in your way but also help you being productive. Those are the only themes that interest me in any case, I have no use for themes that make my desktop look like an angry teenager got his hands on it, nor those that burn CPU cycles I'd prefer to burn myself (or make me wait because they can't get those cycles).

R.

**Comment by tsujan** [comment]
> Maybe, but if you use a style through a platform theme plugin that provides choices for those parameters

Kvantum is DE-independent and handles as many Qt parameters as possible. I've no plan to change that.

> But it does advocate itself as a theme engine for Qt and KDE

Qt ≠ KDE

> Yes, you could. Qt recreates the native Macintosh style entirely...

If you compare Kvantum codes with the style codes included in Qt, you'll see how different they are. You could also guess that by comparing some Kvantum themes with those styles...

> The best ones are those that... Those are the only themes that interest me... I have no use for themes that...

Obviously, tastes differ. People who like basic themes can use Breeze or Fusion. They can also use/make simple Kvantum themes.

> ... nor those that burn CPU cycles

Kvantum doesn't do that. Actually, a basic style like Breeze may sometimes use more RAM/CPU time than a complex Kvantum theme does.

**Comment by RJVB** [comment]
On Saturday July 04 2020 10:28:00 tsujan wrote:

>> Yes, you could. Qt recreates the native Macintosh style entirely...
>
>If you compare Kvantum codes with the style codes included in Qt, you'll see how different they are. 

So? I don't know exactly what you mean with "style codes" but I think you're making the same point as I am, and that difference is exactly why I made my point.

An analogy: if I had had a utility as I invoked for use with GTk <= 3.14 (= a version that still had proper theme support) I could have "photographed" the theme I was using then and use the png files to make something to dress up later GTk3 versions to look as before.
This kind of application may not particularly interest you but I am undoubtedly not the only one who is, and writing the kind of utility required is probably an interesting exercise too. ... And my question wasn't if you'd want to write it!

>Kvantum doesn't do that.

I'm not going to go down that rabbit hole (but it cannot be the cheapest style either because of the use of SVGs).

>Actually, a basic style like Breeze may sometimes use more RAM/CPU time than a complex Kvantum theme does.

The keyword being "sometimes" (and Breeze only looks basic)

Not that benchmarking a GUI is particularly useful but there's a simple benchmarking tool in github:RJVB/qstyle-demo.git (untick "grab mouse", tick "run at max speed" and click "run simulation") on the bottom page).

**Comment by tsujan** [comment]
I understood your first comment (questions) but don't get the points of the others.

 * If you want a different kind of widget style that "photographs" GTK/macOS/... themes, you could start to be the first developer who makes one. If you succeed in writing the core code, those who like the idea will help you. I won't be among them — have neither the time nor the incentive.

 * Kvantum isn't meant to copy themes. The fact that it can create good visual matches is only a byproduct of its flexibility.

 * People usually think, the more feature-rich a program is, the "heavier" it should be. That's a myth. It depends on the code and how developers value or ignore system resources. Of course, Fusion is the lightest style and those with very old systems (> 10-year-old) should prefer it to other Qt styles.
