### ISSUE TITLE
Create a systemsettings module for Kvantum

### ISSUE THREAD

**Issue by christiantosta** [tsujan/Kvantum#548]
How about create a systemsettings5 module for Kvantum and made it 100% plasma compliant?

Please see:
[Plasma VDG T13361](https://phabricator.kde.org/T13361)

**Comment by tsujan** [comment]
I'm afraid that was proposed before and rejected. Kvantum is DE-independent.

Apart from that, systemsettings5 has become like an ugly patchwork of QML/QtQuick parts. With each new version of Plasma, a working Qt widget is replaced by a defective QML monstrosity in systemsettings5. I wouldn't want Kvantum to be related to it in anyway even if Kvantum was a Plasma program.

**Comment by christiantosta** [comment]
Thanks for your reply. 

Systemsettings is going to be rewriten according to KDE VDG. They want Plasma to go a big competitor to MacOS and Windows for OEM builders look to it. So Kvantum can be a great adition to allow this, but its not fully integrated into Plasma. Perhaps Kvantum-manager can be embedded in a KCM module, not imposing your project to be directly linked to Plasma project. 

What do you think about?

**Comment by tsujan** [comment]
> They want Plasma to go a big competitor to MacOS and Windows for OEM builders look to it.

I don't know. What I've seen -- the actual thing -- is that KDE is becoming more and more like a mobile phone environment. More QML → less platform integration → heavier, less efficient and uglier GUIs for something that was supposed to be a *desktop* environment.

For now, KDE consists of two incongruous GUIs: Qt Quick and `QWidget`. Who knows? KDE devs might have to abandon `QWidget` altogether at some point, in which case, Kvantum will have no place in Plasma.

So, I really prefer to keep my distance from this mess and focus on Qt and its `QWidget`.

**Comment by christiantosta** [comment]
Ok. Thank you for your feedback. Keep good work!

**Comment by tsujan** [comment]
You are very welcome.
