### ISSUE TITLE
Kvantum + qbittorrent = invisible fonts in execution log

### ISSUE THREAD

**Issue by moonburnt** [tsujan/Kvantum#552]
Kvantum 0.15.3 + qbittorrent 4.2.5. With any kvantum theme selected, fonts in execution log have the same color as background, making them effectively invisible (so the only way to read text in this tab is to ctrl+c -> ctrl+v it into some text editor or something like that). For example: https://files.catbox.moe/xm4vzq.png

**Comment by tsujan** [comment]
It should be reported to qbittorrent's developer(s). qbittorrent also has other style problems; hopefully, its developer will find and fix all of them.

**Comment by tsujan** [comment]
BTW, this bug of qbittorrent is reproducible with the Breeze widget style too:

![qbittorrent_breeze](https://user-images.githubusercontent.com/981076/88083950-e8d59380-cb98-11ea-9a84-555edf8dde25.png)
