### ISSUE TITLE
toolbar color independent of window color

### ISSUE THREAD

**Issue by mojtaba82** [tsujan/Kvantum#555]
Firstly thank you for this nice theme style and excuse me for my bad English.
In kvantum is it possible that toolbar color be independent from window color. I mean when toolbar is semi transparent, in behind of toolbar, desktop be seen not window itself.

**Comment by tsujan** [comment]
In Qt, a window contains every widget. So, the toolbar is drawn on the top of its parent window, like other widgets. That's how Qt draws a window and its widgets.

Therefore, when you use a transparent or translucent toolbar in your Kvantum theme, the window will be seen behind it.

See the theme `KvantumAlt` for a translucent toolbar on a translucent window.

**Comment by mojtaba82** [comment]
You are right. Thanks for your reply.

**Comment by tsujan** [comment]
You're welcome.
