### ISSUE TITLE
Transparent view w/seperators on Dolphin

### ISSUE THREAD

**Issue by StarrKiss** [tsujan/Kvantum#556]
So, I am having this problem with Dolphin. This is what dolphin currently looks like:
![image](https://user-images.githubusercontent.com/13007697/90039453-4470d980-dc8c-11ea-829d-cea0ad97156d.png)

Which is nice in terms of transparency, but unfortunately, there are no 'grooves' or seperators between sections. Here is a mockup of what I mean:

![Screenshot_20200812_111106](https://user-images.githubusercontent.com/13007697/90039705-a29dbc80-dc8c-11ea-87af-6c18353c9e2c.png)

I suppose this is a twofold question-
Part 1- 
On other themes, the seperators appear but ONLY if this setting
![image](https://user-images.githubusercontent.com/13007697/90039809-c5c86c00-dc8c-11ea-883f-1788b444ef8a.png)
is turned off. Can you please make it so that seperators appear even with Transparent Dolphin View on?

Part 2- 
This specific theme I am using, Moe, doesn't have seperators at all. I am not afraid of editing the svg and kvconfig of it to tweak it and add seperators, my only question is how would I do that? I can't seem to find it in the documentation?

**Comment by tsujan** [comment]
> Can you please make it so that seperators appear even with Transparent Dolphin View on?

By separators, you mean splitter grips. They are independent of the transparent Dolphin view setting; you could check that with themes that come with Kvantum, like KvAmbience:

![kvambience](https://user-images.githubusercontent.com/981076/90042845-7a3fad80-dce0-11ea-8845-8df171c0a5bb.png)

> This specific theme I am using, Moe, doesn't have seperators at all. 

And so, it doesn't show them, with or without a transparent Dolphin view.

> how would I do that? I can't seem to find it in the documentation?

`Theme-Making.pdf` → `Indicators` → `Splitter` (you'll find it inside the table)

BTW, it's understandable why you didn't find it. Qt has lots of widgets and making a complete Kvantum theme is a complex job. However, I've explained almost everything in the documentation. Once you make/edit a few themes, the job will become easier.
