### ISSUE TITLE
Combo box too wide.

### ISSUE THREAD

**Issue by royalbisht** [tsujan/Kvantum#557]
The combo box in setting are too wide in kvantum but this is not the case with oxygen as application style. what should i change to make it look like oxygen.
![kvantum](https://user-images.githubusercontent.com/16011976/90202677-f549b680-ddfb-11ea-9837-22514a4c8019.jpg)
![oxygen](https://user-images.githubusercontent.com/16011976/90202679-f67ae380-ddfb-11ea-9f2b-ad88e3dc34db.jpg)

**Comment by tsujan** [comment]
Kvantum Manager → Configure Active Theme → Hacks → Centered form layouts.
