### ISSUE TITLE
LibreOffice with kvantum

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/Kvantum#56]
It's not possible to make LibreOffice use kvantum without installing KDE, is it?

**Comment by tsujan** [comment]
Unfortunately, it isn't. In Debian based systems, libreoffice-kde should be installed, which needs ~ 130 MB of KDE stuff.

**Comment by ozky** [comment]
Libreoffice can only use native gtk+2 or 3 theme,native qt theme like kvantum is not supportted even with libreoffice-kde. 
Tsujan can close this as i don't think kvantum will going to have gtk theme support.
https://bugs.libreoffice.org/show_bug.cgi?id=48611

**Comment by tsujan** [comment]
> as i don't think kvantum will going to have gtk theme support.

Thanks for the link! And you're right: Kvantum won't support GTK+ because gtk2 is too old and, being changed whimsically by Gnome devs, gtk3 it isn't reliable.
