### ISSUE TITLE
building with qmake in OpenBSD

### ISSUE THREAD

**Issue by rjl6789** [tsujan/Kvantum#560]
Hi,

(OS = OpenBSD  -current;  Kvantum version = V0.16.1)

I was trying to build with qmake in OpenBSD i.e. `qmake && make` - which returns:
```
root:~/.local/src/Kvantum/Kvantum $ make
cd style/ && ( test -e Makefile || /usr/local/bin/qmake -o Makefile /root/.local/src/Kvantum/Kvantum/style/style.pro ) && make -f Makefile
Project ERROR: Unknown module(s) in QT: KWindowSystem
*** Error 3 in /home/rob/.local/src/Kvantum/Kvantum (Makefile:53 'sub-style-make_first')
```

However building with cmake works fine i.e.

```
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/lib/qt5/cmake/ ../
make
make install
```

I'm not sure if this is an OpenBSD issue or something you can add to the qmake files (similar to how you fixed in issue #542 )

Anyway, thanks for Kvantum. Really appreciate all the work you must put in.

Regards

Rob

**Comment by tsujan** [comment]
I don't think it's related to https://github.com/tsujan/Kvantum/issues/542. According to the error messages you pasted, for some reason unknown to me, OpenBSD's qmake doesn't recognize `KWindowSystem` in this line: https://github.com/tsujan/Kvantum/blob/86bd3bb070bfe9dccf5ceda4f1a45c57bfb79687/Kvantum/style/style.pro#L31

However, it's good news that cmake works under OpenBSD. cmake is better than qmake everywhere.

I leave this issue open for a while, hoping that a *BSD user may know the answer and add a comment.

Thanks for the info!
