### ISSUE TITLE
Missing dropdown menu in Okular

### ISSUE THREAD

**Issue by StarrKiss** [tsujan/Kvantum#561]
Hello, Using the 'MoeDark' theme on Kvantum, there is a missing drop-down menu on Okular:
![image](https://user-images.githubusercontent.com/13007697/91322502-72bee080-e785-11ea-804a-9bb1f23a8f35.png)
Next to text selection should be a drop down triangle:
![image](https://user-images.githubusercontent.com/13007697/91322570-866a4700-e785-11ea-8257-5fdede9c088a.png)

**Comment by tsujan** [comment]
> Using the 'MoeDark' theme...

"MoeDark" isn't made by me. You may want to report the problem to its author.

The arrow exists with all themes that come with Kvantum:

![okular](https://user-images.githubusercontent.com/981076/91325385-5d26d680-e7d8-11ea-8d41-abfb30596203.png)
