### ISSUE TITLE
[Question] How can I explicitly disable blur for an app?

### ISSUE THREAD

**Issue by Zzombiee2361** [tsujan/Kvantum#562]
WIth Compositing & General Look > Blurring for translucent windows enabled, how can I explicitly request kvantum to not blur my window as an app developer? Or is there some config that I can change on kvantum side?
Also, how can I contact you if I have more questions? Discord? Telegram? IRC?

**Comment by tsujan** [comment]
Kvantum does not blur windows; KWin does. Kvantum just uses KWin's blurring if available (see `blurhelper.cpp`). KWin's blurring can be disabled/enabled in KDE's System Settings (I don't remember the exact place).

> Also, how can I contact you if I have more questions?

You could email me. My email address is in `README.md`.

**Comment by Zzombiee2361** [comment]
That doesn't really answer my question. With Compositing & General Look > Blurring for translucent windows settings checked, kvantum tells kwin to blur all translucent window. How can I intervene this with my code? For reference, I'm using pyqt. Should I ask kvantum or kwin to not blur my window? And how do I do that exactly? I'm sorry, I'm a beginner and it surely doesn't help that this kind of information is quite lacking on the web.

**Comment by tsujan** [comment]
> How can I intervene this with my code?

You can't freely control aspects of a widget style in your code. But you could replace the active widget style with a hard-coded style. For example, if you don't want your buttons to be drawn by the active widget style, you'll need to make a style for them in your code and give it to all buttons. And the same for other widgets. See https://doc.qt.io/qt-5/qstyle.html and the rellated Qt doc.

However, in this special case, you could make your windows opaque by using `setAttribute(Qt::WA_TranslucentBackground, false);` in an appropriate place of your code. No translucency, no blurring.

> I'm a beginner and it surely doesn't help that this kind of information is quite lacking on the web.

Qt has the most comprehensive documentation.

You could ask your questions that are related to Kvantum here and I'll answer them if I find the time but please be specific.

**Comment by Zzombiee2361** [comment]
> However, in this special case, you could make your windows opaque by using setAttribute(Qt::WA_TranslucentBackground, false); in an appropriate place of your code. No translucency, no blurring.

Well, unfortunately I'm trying to make my window transparent. It works fine on breeze but not on kvantum. Can I tell kwin to not blur the window? Can I disable that kvantum setting just for my app? Or is there some kind of environment variable that I can use?

> Qt has the most comprehensive documentation.

Oh that's not the problem. The problem is linux specific documentation like xorg, kwin, and kvantum.

> You could ask your questions that are related to Kvantum here and I'll answer them if I find the time but please be specific.

How does kvantum tell kwin to blur certain window? And how can I prevent or reverse that?

**Comment by tsujan** [comment]
> It works fine on breeze but not on kvantum.

Breeze doesn't activate KWin's blurring for translucent windows. So, that's expected.

> Can I tell kwin to not blur the window?

Try to do what's done here:

https://github.com/tsujan/Kvantum/blob/9eb5efb3e40b5e769db4280277bfcaefdb6f9e18/Kvantum/style/blur/blurhelper.cpp#L212

Namely, `KWindowEffects::enableBlurBehind (widget->internalWinId(), false);` But there's no guarantee that it'll work.

> Can I disable that kvantum setting just for my app?

No. I haven't added such a setting to Kvantum and have no plan for it either. Only opaqueness can be set.

> Or is there some kind of environment variable that I can use?

I don't know of any.

> The problem is linux specific documentation like xorg, kwin, and kvantum.

X11 has a detailed documentation but it can given you a headache. KWin has some documentation but it's far from comprehensive.

As for Kvantum, there is a practical doc on theme making and changing settings. The rest is the code. Almost no one adds a documentation for his/her code. You'll need to *read the code* if you want to know how it works. Code reading is a necessary skill that is acquired by practicing.

> How does kvantum tell kwin to blur certain window?

→ `blurhelper.cpp` (as mentioned above).

**Comment by Zzombiee2361** [comment]
Thanks for the guide, I'll read more about it
