### ISSUE TITLE
kvantum makes spyder hang

### ISSUE THREAD

**Issue by AchmadFathoni** [tsujan/Kvantum#563]
* OS : EndeavourOS
* KDE : 5.19.5
* Qt : 5.15.0
* Spyder: 4.1.5, installed via pacman
* Kvantum : 0.16.1

When I enable kvantum in my application style, the `spyder` always hang. Using breeze theme makes it work again. I am not the only one, [check it](https://archived.forum.manjaro.org/t/spyder-4-x-x-freezes-at-startup/154204/3). This is my [config](https://pastebin.com/Ya9viJP3). I have already add `spyder` in opaque application list.

**Comment by tsujan** [comment]
The problem is in Spyder. Spyder -- at least its version 4.1.4 -- seems to ignore the widget style and use its own hard-coded style. I tried it by entering `export QT_STYLE_OVERRIDE=fusion`, `export QT_STYLE_OVERRIDE=breeze` or... before `spyder` but its style didn't change. I also tried changing the value of `windows_style` in ~/.config/spyder-py3/config/transient.ini` but it had no effect.

In short, something is seriously wrong in spyder's styling code and I'm afraid I can't do anything about it. There's no terminal output to trace the issue. Kvantum only triggers it somehow.

**Comment by tsujan** [comment]
Oh, in addition, there's no trace of Kvantum in the log that the first reporter attached at https://archived.forum.manjaro.org/t/spyder-4-x-x-freezes-at-startup/154204

**Comment by tsujan** [comment]
OK, narrowed down the problem in Spyder:

The issue happens only when `Spyder → Preferences → Appearance → Interface theme` is set to `Automatic`. If it's set to `Light`, the Spyder code that's responsible for the infinite loop won't be called. (Here, `Light` isn't related to a light Kvantum theme).

I think Spyder users might want to report this to Spyder's developer(s). IMO, it isn't a good idea to sweep the problem under the carpet by saying, "Don't use Kvantum with Spyder." Sooner or later, the issue will show up elsewhere or in another form.

**Comment by AchmadFathoni** [comment]
Thank, but do yo have any idea why light theme is the only one that work? dark theme is also hang too beside automatic theme.

**Comment by tsujan** [comment]
I have no idea because I'm not familiar with Spyder's code. It just seems that `Automatic` and `Dark` call a function or code block that causes an infinite loop but `Light` doesn't.

One thing is clear: `Light` doesn't necessarily mean a light theme. So, Spyder's styling code may have more than one problem.

**Comment by ArchangeGabriel** [comment]
This is becoming a bigger issue with Spyder 5.x, since even `light` does not work…

**Comment by ArchangeGabriel** [comment]
(`export QT_STYLE_OVERRIDE=breeze` does work though)

I don’t understand what fails with kvantum, but since it is only failing with it and not with the other, and knowing upstream (Spyder) reaction to bug due to non-default configuration, I don’t expect any support from them unless we can show precisely what the issue is.

**Comment by tsujan** [comment]
> I don’t expect any support from them

If you have a backtrace *that contains Kvantum*, please attach it here! I'd really appreciate it. There was no trace of Kvantum in the log provided by the original reporter.

If you have a backtrace that does *not* contain Kvantum, the developers of Spyder should consider it as a good bug report; whether the bug is triggered by this or that widget style will be irrelevant.

**Comment by ArchangeGabriel** [comment]
There is nothing in the log that even says something is blocked. Logs are just fine:
[spyder-debug.log](https://github.com/tsujan/Kvantum/files/6254628/spyder-debug.log)

So if we go by logs they are no issues… Since the only information I have is, it does not work with Kvantum, and I don’t have anything else to show, I’m really reluctant to re-open a bug they will close right away: https://github.com/spyder-ide/spyder/issues/11623

**Comment by tsujan** [comment]
> There is nothing in the log that even says something is blocked

Yes, that log seems normal.

What if you use `gdb`? `gdb APP_NAME` → type `run` at `(gdb)`, and see if a problem is reported. In the case of crashes, `where` can be typed for getting a good backtrace.

WARNING: `gdb` can be very slow.

> I’m really reluctant to re-open a bug they will close right away

I understand. I can also understand why they may close a report.

**Comment by ArchangeGabriel** [comment]
`spyder` is a python program, so not sure `gdb` is appropriate. Anyway, `gdb python` and `run /usr/bin/spyder` gives this:
```
[New Thread 0x7fffdea76640 (LWP 90349)]
[New Thread 0x7fffdcd35640 (LWP 90350)]
[New Thread 0x7fffcbfff640 (LWP 90351)]
[New Thread 0x7fffd0d3c640 (LWP 90352)]
[New Thread 0x7fffcb7fe640 (LWP 90353)]
[New Thread 0x7fffcaffd640 (LWP 90354)]
[New Thread 0x7fffca7fc640 (LWP 90355)]
[New Thread 0x7fffc9ffb640 (LWP 90356)]
[New Thread 0x7fffc97fa640 (LWP 90357)]
[New Thread 0x7fffc8ff9640 (LWP 90358)]
[New Thread 0x7fffa3fff640 (LWP 90359)]
[New Thread 0x7fffa37fe640 (LWP 90360)]
[New Thread 0x7fffa2ffd640 (LWP 90361)]
Icon theme "breeze-dark" not found.
[Detaching after fork from child process 90367]
[New Thread 0x7fff9b63f640 (LWP 90369)]
[New Thread 0x7fff9a534640 (LWP 90370)]
[New Thread 0x7fff99d33640 (LWP 90371)]
[New Thread 0x7fff99532640 (LWP 90372)]
[New Thread 0x7fff98d31640 (LWP 90373)]
[Detaching after fork from child process 90375]
[New Thread 0x7fff7ffff640 (LWP 90376)]
[Detaching after fork from child process 90377]
[Detaching after fork from child process 90378]
[Detaching after fork from child process 90379]
[New Thread 0x7fff7f7fe640 (LWP 90382)]
[New Thread 0x7fff7effd640 (LWP 90383)]
[New Thread 0x7fff7e7fc640 (LWP 90384)]
[New Thread 0x7fff7dffb640 (LWP 90385)]
[New Thread 0x7fff7d7fa640 (LWP 90387)]
[New Thread 0x7fff7cff9640 (LWP 90386)]
[New Thread 0x7fff5ffff640 (LWP 90388)]
[New Thread 0x7fff5f7fe640 (LWP 90389)]
[New Thread 0x7fff5effd640 (LWP 90390)]
[New Thread 0x7fff5e7fc640 (LWP 90391)]
[New Thread 0x7fff5dffb640 (LWP 90392)]
[New Thread 0x7fff5d7fa640 (LWP 90393)]
[Thread 0x7fff98d31640 (LWP 90373) exited]
[New Thread 0x7fff98d31640 (LWP 90395)]
[New Thread 0x7fff5cff9640 (LWP 90396)]
[Detaching after fork from child process 90397]
[New Thread 0x7fff57fff640 (LWP 90408)]
[New Thread 0x7fff577fe640 (LWP 90419)]
[New Thread 0x7fff56ffd640 (LWP 90420)]
[New Thread 0x7fff567fc640 (LWP 90421)]
[New Thread 0x7fff55ffb640 (LWP 90425)]
[Detaching after fork from child process 90439]
[Detaching after fork from child process 90440]
[New Thread 0x7fff557fa640 (LWP 90441)]
[New Thread 0x7fff54ff9640 (LWP 90442)]
[New Thread 0x7fff27fff640 (LWP 90443)]
[New Thread 0x7fff277fe640 (LWP 90444)]
[New Thread 0x7fff26ffd640 (LWP 90445)]
[New Thread 0x7fff267fc640 (LWP 90446)]
[New Thread 0x7fff25ffb640 (LWP 90453)]
[New Thread 0x7fff257fa640 (LWP 90454)]
[Detaching after fork from child process 90455]
[Detaching after fork from child process 90456]
[Detaching after fork from child process 90457]
[New Thread 0x7fff24ff9640 (LWP 90458)]
[New Thread 0x7fff121d9640 (LWP 90459)]
[Detaching after fork from child process 90460]
[Detaching after fork from child process 90461]
[Thread 0x7fff257fa640 (LWP 90454) exited]
[New Thread 0x7fff257fa640 (LWP 90462)]
[Thread 0x7fff257fa640 (LWP 90462) exited]
[Thread 0x7fff24ff9640 (LWP 90458) exited]
[Thread 0x7fff25ffb640 (LWP 90453) exited]
[Thread 0x7fff267fc640 (LWP 90446) exited]
[Thread 0x7fff56ffd640 (LWP 90420) exited]
[Thread 0x7fff57fff640 (LWP 90408) exited]
[Thread 0x7fff98d31640 (LWP 90395) exited]
[Thread 0x7fff5d7fa640 (LWP 90393) exited]
[Thread 0x7fff5effd640 (LWP 90390) exited]
[Thread 0x7fff5f7fe640 (LWP 90389) exited]
[Thread 0x7fff7d7fa640 (LWP 90387) exited]
[Thread 0x7fff7cff9640 (LWP 90386) exited]
[Thread 0x7fff7e7fc640 (LWP 90384) exited]
[Thread 0x7fff7ffff640 (LWP 90376) exited]
[Thread 0x7fff99532640 (LWP 90372) exited]
[Thread 0x7fff99d33640 (LWP 90371) exited]
[Thread 0x7fff7f7fe640 (LWP 90382) exited]
[Thread 0x7fff9a534640 (LWP 90370) exited]
[Thread 0x7fff7effd640 (LWP 90383) exited]
[Thread 0x7fff9b63f640 (LWP 90369) exited]
[Thread 0x7fff7dffb640 (LWP 90385) exited]
[Thread 0x7fff5ffff640 (LWP 90388) exited]
[Thread 0x7fffa2ffd640 (LWP 90361) exited]
[Thread 0x7fff5e7fc640 (LWP 90391) exited]
[Thread 0x7fffa37fe640 (LWP 90360) exited]
[Thread 0x7fff5dffb640 (LWP 90392) exited]
[Thread 0x7fffa3fff640 (LWP 90359) exited]
[Thread 0x7fffc8ff9640 (LWP 90358) exited]
[Thread 0x7fff5cff9640 (LWP 90396) exited]
[Thread 0x7fffc97fa640 (LWP 90357) exited]
[Thread 0x7fff577fe640 (LWP 90419) exited]
[Thread 0x7fffc9ffb640 (LWP 90356) exited]
[Thread 0x7fff567fc640 (LWP 90421) exited]
[Thread 0x7fffca7fc640 (LWP 90355) exited]
[Thread 0x7fff55ffb640 (LWP 90425) exited]
[Thread 0x7fffcaffd640 (LWP 90354) exited]
[Thread 0x7fff557fa640 (LWP 90441) exited]
[Thread 0x7fffcb7fe640 (LWP 90353) exited]
[Thread 0x7fff54ff9640 (LWP 90442) exited]
[Thread 0x7fffd0d3c640 (LWP 90352) exited]
[Thread 0x7fff27fff640 (LWP 90443) exited]
[Thread 0x7fffcbfff640 (LWP 90351) exited]
[Thread 0x7fff277fe640 (LWP 90444) exited]
[Thread 0x7fffdcd35640 (LWP 90350) exited]
[Thread 0x7fff26ffd640 (LWP 90445) exited]
[Thread 0x7fffdea76640 (LWP 90349) exited]
[Thread 0x7ffff7895740 (LWP 90338) exited]
```

**Comment by ArchangeGabriel** [comment]
(And `where` returns `No stack.`)

**Comment by tsujan** [comment]
> spyder is a python program,

Oh, I forgot that!

I avoid PyQt apps here because of my bad experience with PyQt many years ago, under KDE4: I'd installed a nice PyQt Plasmoid but it caused hangs on login whenever KDE4 was upgraded.

**Comment by ArchangeGabriel** [comment]
Well I don’t have the choice to use Spyder or not. But thank you anyway for your help, I’ll just document the new workaround and be done with that. If someday upstream starts supporting modern version of software, I’ll try to re-open this bug with them. ;)

**Comment by tsujan** [comment]
Sorry that I couldn't be of more help.

In any repository of mine, closing an issue doesn't mean the end of discussion. If you found a trace of Kvantum in a backtrace or log related to Spyder, please add a comment here. I'll reopen a closed issue if a good evidence is found.

**Comment by qouoq** [comment]
@tsujan, I made a reproduction case, here: spyder-ide/spyder#16826

What I understand happens is that resize events are repeatedly fired on the Spyder console scrollbar, but only if Kvantum is used _and_ some custom CSS is applied on the corresponding text area.

All indicates that a solution should be implemented on Spyder's side, but what would be helpful is to detect that the Qt style in effect is from Kvantum. Would you have some advice on how to do that?

**Comment by tsujan** [comment]
> Would you have some advice on how to do that?

I saw this on that page: "It seems Kvantum doesn't allow Spyder to set its own Qt style but instead it wants to impose its own". I'm afraid this comment makes no sense at all. Kvantum *is* a Qt style plugin. It's like saying KWin "imposes" itself on title-bars when you use it as your window manager, or that VLC "imposes" itself on the screen when you see a video with it!

As a matter of fact, usually the opposite is true: an app may try to impose its wrong hard-coded style. Having a hard-coded style is possible but it should be done with due care, by considering every detail that's explained in [`QStyle` doc](https://doc.qt.io/qt-6/qstyle.html). It may be complex but everything about `QStyle` can be known by consulting it or by following its links.

**Comment by ArchangeGabriel** [comment]
@tsujan That’s part of why I stopped using Spyder, they changed from following system theme to a completely forced custom one that I find ugly. So yes, they are trying to enforce their styling.

**Comment by tsujan** [comment]
> So yes, they are trying to enforce their styling.

I know.

As I implied, it's possible to force a hard-coded style on an app *correctly*. But, first, it's bad practice (because it damages platform integration) and, second, it isn't as easy as some may think, considering the complexity of `QStyle`. The desktop version of Telegram is an example of a Qt app that has a correct hard-coded style.
