### ISSUE TITLE
[Q] How do I reduce the padding/spacing between elements?

### ISSUE THREAD

**Issue by txtsd** [tsujan/Kvantum#570]
This is pcmanfm-qt with the Adapta-Eta theme. The spacing problem is consistent across qt apps though.

Here is how it looks with the gtk2 qt theme
![2020-11-26-123257_960x1053_scrot](https://user-images.githubusercontent.com/768728/100318512-2c775880-2fe4-11eb-9325-53ece4a6dc5e.png)

And here is how it looks with the kvantum Adapta theme.
![2020-11-26-123325_960x1053_scrot](https://user-images.githubusercontent.com/768728/100318490-241f1d80-2fe4-11eb-9eb9-e683239b0739.png)

pcmanfm-qt shows 46 folders at once with gtk2, but only 35 with kvantum.
Notice how the menus have a ton of padding in the kvantum theme too.

How do I get rid of all this excess padding so I can have a compact UI?

**Comment by tsujan** [comment]
Kvantum has a comprehensive documentation.

**Comment by txtsd** [comment]
> Kvantum has a comprehensive documentation.

So rude of you to just close the issue with a dismissive statement.

It would help if you at least pointed me to the relevant part of the documentation. It's just a pdf file. I don't know what to look for, and it can't be indexed by search engines either.

**Comment by txtsd** [comment]
That pdf file was useless. I found more info [here](https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Config) but I don't see anything relevant. The closest thing I found is `min_height`. Is that it?

**Comment by tsujan** [comment]
> So rude of you to just close the issue with a dismissive statement.

So narcissistic of you to think that I should waste my time for you.
