### ISSUE TITLE
[Q] How do I remove this space between the checkbox and the menu text

### ISSUE THREAD

**Issue by txtsd** [tsujan/Kvantum#571]
The other icons are correctly spaced right next to the text, but I can't find a way to get rid of the space after the checkbox.
Problem persists across themes.

![2020-11-26-160226_612x336_scrot](https://user-images.githubusercontent.com/768728/100341201-44f66b80-3002-11eb-8f98-e7e954feb8e8.png)

![2020-11-26-161224_1920x1080_scrot](https://user-images.githubusercontent.com/768728/100341204-47f15c00-3002-11eb-9e36-50a0084546a0.png)

**Comment by NickLion** [comment]
It's just a space for an icon. No icon — empty space. Reload has icon — icon takes that space.

**Comment by tsujan** [comment]
Kvantum aligns texts, icons and checkboxes in menus, giving them separate positions; hence the spaces. Breeze does that too. You could use another style, like Fusion, if you don't want those spaces.

BTW, please don't attach a 2-MiB image just to show a small menu.

**Comment by txtsd** [comment]
> Kvantum aligns texts, icons and checkboxes in menus, giving them separate positions; hence the spaces. Breeze does that too. You could use another style, like Fusion, if you don't want those spaces.
> 
> BTW, please don't attach a 2-MiB image just to show a small menu.

How does fusion do it differently?

**Comment by tsujan** [comment]
> How does fusion do it differently?

You can check it yourself. Or you want me to read its code for you (like you did at https://github.com/tsujan/Kvantum/issues/571)?

> If fusion and gtk2 themes can do it, why can't the kvantum themes do it?

Weird question! Kvantum is a different style, as Breeze it. It's not about "can do".

**Comment by NickLion** [comment]
It's not about "it can't" it's about "it shouldn't". It's not nice when text jumps left-right.

**Comment by tsujan** [comment]
> It's not about "it can't"

@NickLion 
Exactly :) Different styles, different looks, different choices. I wonder if anyone has asked such a question about Breeze!

**Comment by txtsd** [comment]
> > How does fusion do it differently?
> 
> You can check it yourself. Or you want me to read its code for you (like you did at #571)?
That would be great, actually!

> > If fusion and gtk2 themes can do it, why can't the kvantum themes do it?
> 
> Weird question! Kvantum is a different style, as Breeze it. It's not about "can do".
I'm sure no one wants this behavior in a menu, and regular users do not care about the internals of why it happens. They expect icons and checkboxes and whatever else that goes in that space to align properly with the text without introducing superfluous whitespace.

**Comment by txtsd** [comment]
> It's not about "it can't" it's about "it shouldn't". It's not nice when text jumps left-right.

What? The text doesn't jump. This is about excessive whitespace that other themes don't have.

**Comment by tsujan** [comment]
>  They expect icons and checkboxes...

"They" don't; *you* do. Use Fusion or..., as mentioned above.

**Comment by txtsd** [comment]
> > They expect icons and checkboxes...
> 
> "They" don't; _you_ do. Use Fusion or..., as mentioned above.

Why are you so hostile, man? I come here asking for help to use your brainchild, and you're just flippant af.

**Comment by NickLion** [comment]
> What? The text doesn't jump. This is about excessive whitespace that other themes don't have.

Look at your example, if you'll remove space between checkbox and text, "Reload" would be shift to right comparing to other menu texts.

**Comment by txtsd** [comment]
> > What? The text doesn't jump. This is about excessive whitespace that other themes don't have.
> 
> Look at your example, if you'll remove space between checkbox and text, "Reload" would be shift to right comparing to other menu texts.

You're thinking about the internals. I'm thinking about UX. Just make the icons and the checkboxes occupy the same column.

**Comment by tsujan** [comment]
> This is about excessive whitespace that other themes don't have.

Do you read replies? Breeze does; I said that twice.

> Why are you so hostile, man?

I'm not hostile. Learn how to open an issue without wasting people's time. This is the same attitude you had at https://github.com/tsujan/Kvantum/issues/570

**Comment by txtsd** [comment]
> > This is about excessive whitespace that other themes don't have.
> 
> Do you read replies? Breeze does; I said that twice.

I don't use Breeze and I don't care about it. It's ONE theme.
 
> > Why are you so hostile, man?
> 
> I'm not hostile. Learn how to open an issue without wasting people's time. This is the same attitude you had at #570

If you think I'm wasting your time, don't reply. Let someone else help me. Don't just close my issue after dismissing me because of your opinions on how I should use certain software.

**Comment by NickLion** [comment]
> You're thinking about the internals. I'm thinking about UX. Just make the icons and the checkboxes occupy the same column.

No. I'm thinkingg about UI. they can't occupy same space, look, some items has checks AND icon at the same time, some don't.
<img width="272" alt="Screenshot_20201126_132041" src="https://user-images.githubusercontent.com/744015/100344995-592e6e80-2fea-11eb-8459-d932b038aa61.png">

**Comment by txtsd** [comment]
> > You're thinking about the internals. I'm thinking about UX. Just make the icons and the checkboxes occupy the same column.
> 
> No. I'm thinkingg about UI. they can't occupy same space, look, some items has checks AND icon at the same time, some don't.
> <img alt="Screenshot_20201126_132041" width="272" src="https://user-images.githubusercontent.com/744015/100344995-592e6e80-2fea-11eb-8459-d932b038aa61.png">

Alright, that's fair. I've never seen a menu entry with both an icon and a checkbox or radio button.

**Comment by tsujan** [comment]
> I don't use Breeze and I don't care about it.

Narcissism again.

> If you think I'm wasting your time, don't reply. 

Yes, I do. and this is *my* repository; Kvantum is *my* program. You sometimes need to see things beyond yourself.

**Comment by tsujan** [comment]
I'm afraid I might need to block you if you continue this attitude. For now, I don't do that.
