### ISSUE TITLE
Hack for Dolphin on side panel Headers Item Groups

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#573]
Hi @tsujan 
Dolphin use  `inactive.window.color` with opacity for Headers Item Groups
https://github.com/KDE/dolphin/blob/master/src/kitemviews/kitemlistgroupheader.cpp#L208
It's strange - use inactive window color for text item...
![dolphin](https://user-images.githubusercontent.com/8083855/101738111-1f2b9500-3adf-11eb-8557-acecc663bae0.png)

Maybe possible hacked on Kvantum engine?

**Comment by varlesh** [comment]
I think it's mixed colors...
For example **kvGnome** **inactive.window.color=**`#ff0000`
![image](https://user-images.githubusercontent.com/8083855/101739125-8b5ac880-3ae0-11eb-97a3-db6ec19659c7.png)

**Comment by varlesh** [comment]
It's mix **inactive.window.color** + **inactive.text.color**

**Comment by tsujan** [comment]
@varlesh, this is Dolphin with Breeze:

![dolphin](https://user-images.githubusercontent.com/981076/101750683-9adc1080-3ae4-11eb-9e49-ab71cf399073.png)

They've made a pale color out of inactive window and inactive window text colors for their headers. That's their choice and not our concern. This isn't the first example of bad text colors in KDE apps.

**Comment by tsujan** [comment]
@varlesh 

BTW, I activated GitHub's "Discussions" for Kvantum yesterday. I think it's a better place for topics like this. After all, here, Dolphin was the subject, not Kvantum.

**Comment by varlesh** [comment]
@tsujan But it's spoil style with transparent window. Because they merged inactive window & text colors.
Why this can not be hacked on Kvantum and use only inactive text color?

**Comment by varlesh** [comment]
It's stupid use window color on text. KDE devs very strange guys ))

**Comment by varlesh** [comment]
@tsujan You know... KDE devs do not pay attention styling bugs reports & not fix this. I can open issue on KDE bug tracker, but this pointless. Only Breeze!!! On Breeze all looking fine ((

**Comment by tsujan** [comment]
@varlesh,
I'm sure you understand that I can't make Kvantum a place for correcting every mistake that KDE devs make. Kvantum is an Independent program and includes more than enough workarounds.

Yes, KDE devs think only in terms of Breeze. There are so many mistakes in KDE's hard-coded styles, some of which are ridiculous.

I think in terms of Qt.

**Comment by varlesh** [comment]
Yes, you right... but Kvantum already have some hacks. Why not this hack too?
Idea this Header Item Groups - pale color. **It's inactive text**. But not mix inactive window & inactive text.
Breeze not support transparency, styling and more more cool stuff as Kvantum, but this bug it's problem for transparent windows or colorized windows (it's supported on Kvantum).
For example, inactive text color `#ffffff` & inactive window color `#000000`:
![image](https://user-images.githubusercontent.com/8083855/101758923-5eafac80-3af2-11eb-878d-4f682e064ca1.png)

**Comment by tsujan** [comment]
With every workaround you add to a code, you make it dirtier and harder to maintain. Some workarounds are worth adding — like those for Qt bugs — and some were added in old times.

I have no reason at all to make my code dirty just to hide the mistakes that other devs make in their codes.

if Dolphin is important you, you need to use colors that make those texts visible enough.

PCManFM-Qt distinguishes headers by using indentation and without making up colors that may not be visible with all styles:

![pcmanfm-qt](https://user-images.githubusercontent.com/981076/101761267-29ef2580-3af1-11eb-83ea-fbf5bab8d4fa.png)

**Comment by varlesh** [comment]
Ok, thx. I hack this with window color
