### ISSUE TITLE
Icon sizes in the open file dialogs?

### ISSUE THREAD

**Issue by PJSingh5000** [tsujan/Kvantum#582]
How can the size of the icons in the Open Dialog be adjusted to match the native icon size and theme?

QT based file open dialog using Kvantum...

Note the icons are very tiny, and they are not using the symbolic icons set by the current icon theme.
![image](https://user-images.githubusercontent.com/19394936/102956669-8fa2c080-44a6-11eb-91c3-a712cfa66926.png)

Native (Gnome/Ubuntu) file open dialog...

![image](https://user-images.githubusercontent.com/19394936/102957111-9a118a00-44a7-11eb-98a5-4c7da6fd7699.png)

**Comment by tsujan** [comment]
→ https://github.com/tsujan/Kvantum/issues/581#issuecomment-749914246

But if you insist on not using a scale factor (not a good idea), see Kvantum Manager → Configure Active Theme → Sizes & Delays

**Comment by PJSingh5000** [comment]
This icon sizes are much better. Thanks for pointing this out to me.

The Icon theme can not be changed?
Or am I stuck with the KDE breeze icons in this dialog?

(My screen resolution is 3840x216 on a 14" screen, so scaling is the only way to get a consistent desktop that I can actually see. Just adjusting font sizes and icon sizes separately leaves most applications looking "off").

**Comment by tsujan** [comment]
> The Icon theme can not be changed?

Of course, it can. These things depend on the Qt plugin you use. They aren't related to Kvantum. If you don't have a GUI for changing Qt's icons, you could discuss the problem in the forum(s) of your distro.

Please note that you should never need to change icon sizes in Kvantum Manager. With a scale factor of 2, *everything* should be scaled: fonts, icons, button shapes, slider handles,....

Compare your screenshot in https://github.com/tsujan/Kvantum/issues/581#issue-773340200 with mine in https://github.com/tsujan/Kvantum/issues/581#issuecomment-749919612. My screenshot is taken with a scale factor of 2. Not only icons have different sizes, but also the shape of buttons are different (mine is sharp, yours is blurry).

**Comment by tsujan** [comment]
Another thing:

Your screenshot shows that you have an old (outdated) version of Kvantum. The bg color of KvYaru is `#f7f7f7`; but it's `#f5f6f7` in your screenshot.

**Comment by PJSingh5000** [comment]
I see.
I am on Ubuntu 20.04.
Based on your comment, I suspect that they have not packaged the latest version of Kvantum.
I'll check the repos for Ubuntu 20.10. If it hasn't been updated there, I'll open a bug report with them.

**Comment by tsujan** [comment]
There's also another possibility: You may have a recent version of Kvantum but had customized KvYaru before the upgrade.

To check that possibility, you could click `Kvantum Manager → Configure Active Themes → Restore`. If the bg color isn't changed, Kvantum's version is too old. Of course, you'll lose your probable customization by doing so.
