### ISSUE TITLE
Possible Aeroglass-like theme for Kvantum

### ISSUE THREAD

**Issue by ryu-ketsueki** [tsujan/Kvantum#587]
Hello. Currently I'm trying to continue the Breeze-Kv theme, as in fork it and continue it myself. Then I had an idea for an alternative theme. It would use Breeze Enhanced feature of transparent titlebar and merge with a possible transparent toolbar in the same translucensy percentage of 50%. The thing is that the background svg is always behind the toolbar svg, revealing the background instead of making the toolbar 50% transparent like I was planning to do with the titlebar. I don't know if this can be solved only on the config file for the theme so I'm opening this issue to ask if this is a limitation of the Kvantum engine and that can be solved, or if it is not possible to limit the background svg to not take the space of the toolbar.

**Comment by tsujan** [comment]
> The thing is that the background svg is always behind the toolbar svg,

Of course, it is. That's one of the basic concepts of Qt (or any toolkit). If you don't want the toolbar background, just don't give toolbars an interior.

**Comment by ryu-ketsueki** [comment]
So it is not possible to make a translucid toolbar with Kvantum?

**Comment by tsujan** [comment]
What I said above means the opposite: remove the toolbar's interior and make the window translucent.

But if want to keep toolbar's interior, the answer is, "No, it isn't possible with any style, not just Kvantum."

**Comment by ryu-ketsueki** [comment]
> But if you want to keep toolbar's interior, the answer is, "No, it isn't possible with any style, not just Kvantum."

I just learned that it is possible, yes. It is a Breeze fork called Lightly and it does what I wanted to do with Kvantum. A semitransparent toolbar while the rest of the window is opaque.
![Flameshot_20210114_133251](https://user-images.githubusercontent.com/39316730/104619804-075ea800-566d-11eb-82d0-6910ab21dfad.png)
