### ISSUE TITLE
Mouse single click

### ISSUE THREAD

**Issue by ozky** [tsujan/Kvantum#59]
Kvantum still use old ~/.kde4/share/config/kdeglobals to read mouse single click on off,i suggest to change it to something better as kde4 is now orphan and discontinued.

**Comment by tsujan** [comment]
Oh, thanks for mentioning! I didn't know if they'd decided on the final location of such KDE (KF5?) settings. Do you know the path of the new config file(s)?

**Comment by ozky** [comment]
~/.config/kdeglobals .

**Comment by tsujan** [comment]
Done! It seems that they've made single-click the default behavior. If so and if Kvantum is set to double-click, the KDE config will take priority *only when* it's set explicitly.
