### ISSUE TITLE
Qt6 Support

### ISSUE THREAD

**Issue by nullobsi** [tsujan/Kvantum#591]
now that qt6 is released, it would be awesome for Kvantum to support qt6! locally I have gotten it to work by modifying the source code however it was very hacky and involved editing the cmakelists in a not good way

the edits I had to make were:
- remove Qt5X11Extras and instead use xlib directly (hacky?)
- upgrade cmakelists to use qt6
- fix some deprecreated/removed functions and properties
- fix qhash for WindowManager::ExceptionId
- update some includes

i don't have very much experience with c++ but I hope this helps! the fork I made with my changes can be found at https://github.com/nullobsi/Kvantum

**Comment by tsujan** [comment]
I checked Qt6.0.0 the same day it was released in Arch and compiled Kvantum against it after some sacrifices and a few changes to the code.

Qt6.0.0 is far from ready for real use. They shouldn't have pretended that its a stable release...

**Comment by tsujan** [comment]
OpenSUSE seems to be aware of the Qt6 mess, trying to compensate for it: https://build.opensuse.org/package/show/home:jonaski:qt6/qt6-x11extras

Kvantum aside, I've encountered so many important Qt5 methods, whose future is suspicious in Qt6. It isn't clear what plans Qt devs have for Qt but if they want to "deprecate" all methods in [core5compat](https://doc.qt.io/qt-6/qtcore5-index.html), they should first replace them and tell users about those replacements.
