### ISSUE TITLE
Applying Themes to AppImage Apps

### ISSUE THREAD

**Issue by krafi99** [tsujan/Kvantum#594]
How to apply themes to apps which are AppImage files. I use some apps with appimage files by integrating them with my desktop. But, Kvantum themes don't automatically apply to them. How to do it manually?

**Comment by tsujan** [comment]
AppImage is responsible for inconsistencies, if any. I neither support nor recommend it.

**Comment by vadi2** [comment]
I'm an author of an AppImage - I haven't got the time to build for the many of Linux distros out there. When using Kvantum with an AppImage, the following message is given:

```
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
```

How does Kvantum work? Is there a library I can ship with my appimage for it to be compatible?

**Comment by tsujan** [comment]
> How does Kvantum work?

In a nutshell, Qt has a plugin system and style plugins are a part of it. All Qt apps that are installed *in the standard way* can "see" and use them.

There can be various reasons why an app can't "see" style plugins. It may force a hard-coded style (like Plasma) or a specific style (that's a bad practice), or it may be a Qt Quick app (Qt Quick has its own styling), or it may not be aware of the system as far as Qt is concerned (Google-Earth is an example).

AppImage fits into the last category. For whatever reason, it's isolated from the rest of the system. That should have various side effects, of which not seeing Qt style plugins is one example. Whether that's inevitable with AppImage or not, I don't know.

Sorry that I can't be of more help. Reading the code of AppImage and finding its probable issues is far beyond my free time.
