### ISSUE TITLE
Changing theme doesn't work in Fedora 33 Gnome

### ISSUE THREAD

**Issue by bryce-carson** [tsujan/Kvantum#599]
Kvantum is in the Fedora 33 repos, however the application doesn't seem to work as expected, even following the extra steps in INSTALL.

The Kvantum Manager reverts back to KvYaru itself after quitting the application; the kvantumconfig file reverts on disk even when the application is not running, so themes can not be applied manually either.

**Comment by tsujan** [comment]
> the kvantumconfig file reverts on disk even when the application is not running

And how can that be Kvantum's fault?! You say the "application" is not running.

Please be specific when reporting a problem. I have no control over what Fedora (or any other distro) may do with Kvantum.
