### ISSUE TITLE
add an override for the states... add alternative installation paths

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#60]
I think a great addition would be if we could override specific states eg:

I want to use the same svg group for the button and the toolbuttons but the toolbuttons should  not have a raise effect/hover effect.

currently I would need to clone the buttons interior and frame and change it if i could override the hover state i could simply do:

```
inherits=buttons
frame.element.focused={$emptyframe}
interior.element.focused={$emptyinterior}
```

this would slim down both my svg and my config file.

--------------------------------------------------------------------------------------
ok one more ;)

also could you add a setting to disable the bold default button?

**Comment by tsujan** [comment]
> I think a great addition would be if we could override specific states

"inherits" is not just for states. Besides, what you want is *too specific* to deserve a whole new setting -- and as you said, it can be achieved by cloning and editing.

> also could you add a setting to disable the bold default button?

Yes, that's possible.

BTW, several months ago, you'd made a feature request that I rejected. It was about alternative installation folders (`/usr/share/themes/$THEME_NAME/Kvantum`, `~/.themes/$THEME_NAME/Kvantum` and  `~/.local/share/themes/$THEME_NAME/Kvantum`). Now I think that it may be implemented in a way that doesn't cause a mess. I'm working on it now. Consider it included in this ticket for testing later.

**Comment by sixsixfive** [comment]
@specific states

meh I don't really care was just an idea ;)

>Consider it included in this ticket for testing later.

can't wait to see that ;)

**Comment by tsujan** [comment]
> can't wait to see that ;)

The implementation is in its final stages -- it was more complicated than I thought. I'll push it to git after doing some preliminary tests. The real tests will be yours ;)

**Comment by tsujan** [comment]
Added extra theme installation paths! Please first read the last section of "Theme-Making.pdf" for knowing about the new paths and their priorities, and then test the commit a thoroughly as possible (include Kvantum Manager in your tests)!

**Comment by sixsixfive** [comment]
;) all three theme paths work

**Comment by tsujan** [comment]
Good! It remains to have the possibility of normal font for default push buttons.

**Comment by tsujan** [comment]
Done! It's the hacking key "normal_default_pushbutton" and can be set by Kvantum Manager.

Please close this ticket if it works for you (and reopen it if you encounter any issue with the new paths).

**Comment by tsujan** [comment]
BTW, don't forget to tell your users that they should uninstall your Kvantum theme completely before using the new path(s) and that they should use the latest version of Kvantum for that.

**Comment by sixsixfive** [comment]
thx, this looks a lot better
