### ISSUE TITLE
add a padding settings

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#61]
It would be nice if we could add an extra padding for elements(free space to the left, right, top, bottom sides)

![screenshot-a6ee8184](https://cloud.githubusercontent.com/assets/3780774/11318589/f70da404-9058-11e5-8883-b79572a5c9ff.png)

as you can see all those elements are a bit to close to each other

(sure i could add a addiotional transparent space to the fame but with a setting i wouldnt need to rewrite the whole theme again

**Comment by tsujan** [comment]
Added the general key "layout_spacing". Its value is always between 2 and 10 (px).

Many apps set it in their codes. So, don't be surprised if it has no effect in some apps!

It's important that you test with a value of 10 as far as possible and see if all layouts are OK. Thanks in advance!

**Comment by sixsixfive** [comment]
>It's important that you test with a value of 10 as far as possible and see if all layouts are OK.

ok I tested all my qt5 applications and couldn't find any issues ;)
