### ISSUE TITLE
Unintuitive theme selector button

### ISSUE THREAD

**Issue by 2A4U** [tsujan/Kvantum#618]
The theme selector button is too small. Is that only 5 pixels tall? Greater effort than normal is needed to accurately press it. As a novice to Kavantum it was unclear how to select theme at first. And it's right next to a huge clear button. Fix this inconsistent design flaw.

**Comment by tsujan** [comment]
There's no theme selector button in Kvantum Manager but an editable combo-box, which supports search by typing a (part of a) theme name.

Nothing is 5-pix tall in Kvantum Manager. Either something's wrong with your installation or you've mistaken another app with Kvantum Manager.

**Comment by 2A4U** [comment]
Don't be willfully obtuse. You know there is an arrow pointing down right next to the clear theme button.

Gaslighting is a form of psychological manipulation in which a person or a group covertly sows seeds of doubt in a targeted individual or group, making them question their own memory, perception, or judgment...Instances can range from the denial by an abuser that previous abusive incidents occurred.--https://en.wikipedia.org/wiki/Gaslighting
