### ISSUE TITLE
allow a different tab theme for document views

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#64]
Tabs are nice but it would be nice if a completly different tab style could be used for document views

**Comment by tsujan** [comment]
Do you mean the document mode of tab widgets? If so, it's already possible: read the section "Floating Tabs" in "Theme-Making.pdf"!

**Comment by sixsixfive** [comment]
great i thought i could just use/add other bottom borders ;)

**Comment by sixsixfive** [comment]
so im looking at this again ;), would it be possible to use extra settings for the document mode? normal tabs left/floating centered? only floating joined_tabs?

i would like to make them look like buttons eg like the gtkstack(https://developer.gnome.org/gtk3/stable/GtkStack.html)

**Comment by tsujan** [comment]
You mean a key for joining the active tab to its adjacent (inactive) tab(s) only in the document mode?

I don't think adding a key only for the doc mode would be wise. IMO, this would be more logical: adding a key like `joined_detached_active_tab`, that joins the active tab to its adjacent (inactive) tab(s) if

(1) the tab widget is in the doc mode; *or*
(2) the tab widget is in the normal mode and `attach_active_tab` is false.

If I've understood your point correctly, what you want will be possible with such a key.

Please think about it carefully and tell me your opinion because I don't want any backward incompatible change in Kvantum.

**Comment by tsujan** [comment]
In fact, I wanted to add such a key for the extra themes KvGnome and KvGnomeDark but thought it might not be used by any other theme.

**Comment by sixsixfive** [comment]
just for clarification.

this is how my tabs look currently

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/14062791/a4186790-f3ac-11e5-8c48-a09dc58961b3.png)

I like them so i want to keep them that way, however even if i use different floating tab elements it will just look weird, so it would be nice to center them.

eg make the whole thing look like this:

![unbenannt3](https://cloud.githubusercontent.com/assets/3780774/14062860/a99a8034-f3ae-11e5-9888-891c43dacffe.png)

**Comment by tsujan** [comment]
Take a look at KvGnome with kvantumpreview's tabs in the normal mode! You want something like it but

(1) When the active tab is also joined to the inactive ones; and
(2) When there are "separators" between joined tabs.

Am I correct?

I wanted such an arrangement, so if you need it too, I'll try to implement it.

**Comment by sixsixfive** [comment]
correct,

http://kde-look.org/content/preview.php?preview=1&id=175050&file1=175050-1.png&file2=175050-2.jpg&file3=&name=KvGnome+for+Kvantum

the tabs in the find dialog are close, but they should be joined and yes it makes only sense with seperators

**Comment by tsujan** [comment]
OK! We reached a consensus :)

**Comment by tsujan** [comment]
I thinks this is exactly what we wanted:

![gtk-tabs](https://cloud.githubusercontent.com/assets/981076/14067085/48abe844-f471-11e5-8e6e-60381a707fdb.png)

After some tests, clean-up and adding the required info to the documentation, I'll make a commit.

**Comment by tsujan** [comment]
Done! The implementation was more complex than I thought.

I don't explain anything here but refer you to "Theme-making.pdf" → "Joined Tabs and Tab Separators" to see if the documentation is clear enough.

You could also take a look at the new KvGnome (installed by default) as an example.

BTW, I changed the key `joined_tabs` to `joined_inactive_tabs` but in a backward compatible way.

**Comment by sixsixfive** [comment]
nice, i will try this in the next few days

**Comment by tsujan** [comment]
> nice, i will try this in the next few days

Until then, I've added `inline_spin_indicators` (to Kvantum Manager), which may be useful to you too.

**Comment by sixsixfive** [comment]
ok I wasn't able to theme it like this, is there a special section name for floting tabs? it seems it will inherit the default tabsettings(eg its frame width etc.)

**Comment by tsujan** [comment]
First, there is no need to re-open an issue when you have a question; you could ask it and I would reply in the context of a closed issue.

As it's explained in the doc, if these three conditions are satisfied, all tabs will be drawn connected together:

(1) `joined_inactive_tabs` is true;
(2) `joined_active_tab` is true; and
(3) The value of `attach_active_tab` is false **or** the tab widget is in the document mode *(which means that the active tab is not attached to any tab widget)*.

Now, if, in addition, a "tab separator" object exists in your SVG image, Kvantum will use it too. If you do not use floating tabs, the name of the tab separator is made by adding `-separator` to the name of Tab frame. If you also use floating tabs and want tab separators for them too, add another object with the same name but starting with `floating-`.

The reason for all this is more flexibility, as is the rule in all parts of Kvantum. Some theme makers may want to use separator only for usual tabs; others may want it only for floating tabs; and yet some others may not use floating tabs at all or want it for both types.

You could see KvGnome's config file and SVG image for an example.

If you think the above explanation isn't enough, please tell me what I should add to the doc.

**Comment by sixsixfive** [comment]
well I reopened this since this isn't exactly what i wanted

now even normal tabs are joined, but I wanted the old tabs to stay the way I themed them and ONLY document views should look like buttons there is also no way to center them without keeping normal tabs left aligned.

so the current way is useless (at least for me) since i will lose the old tab theme

**Comment by tsujan** [comment]
> now even normal tabs are joined

That depends on how you play with all those possibilities/variables. With 2 booleans we have 4 possibilities; with 3, we have 8,... add to that the possibilities in the SVG image and it will feel like a chess game. So, first tell me what you want to achieve *specifically* and I might be able to tell you how.

**Comment by sixsixfive** [comment]
>2 booleans we have 4 possibilities; with 3, we have 8

ugh, wouldn't it not easier to have one config section for every possibility eg: [Tab], [TabFloating] ?

> So, first tell me what you want to achieve specifically and I might be able to tell you how.
ok

this as normal tab style
https://github.com/sixsixfive/Ivy/blob/master/gui/base/Ivy/Kvantum/src/tab.cfg
![bildschirmfoto4](https://cloud.githubusercontent.com/assets/3780774/14750510/73ce87f8-08c5-11e6-8cd0-584c49538ee8.png)

* left aligned
* not joined 
* attached

this as document style
![bildschirmfoto6](https://cloud.githubusercontent.com/assets/3780774/14750541/a871948c-08c5-11e6-9feb-a1d7585ff9a9.png)

* centered
* joined
* not attached

**Comment by tsujan** [comment]
> ugh, wouldn't it not easier...

A lot easier for me, as the developer, and a lot *less* flexible for Kvantum ;)

Are the images about what you want to achieve or about what you've done?

**Comment by sixsixfive** [comment]
the first one is my current theme the second one is the stack from my gtk3 theme(but this is what i have in mind for the document view)

**Comment by tsujan** [comment]
If I've understood you correctly, you want the first image intact but also want the document view to be like the second image. Am I right?

**Comment by sixsixfive** [comment]
exactly

**Comment by tsujan** [comment]
See this: https://dl.dropboxusercontent.com/u/7793460/Ivy.tar.gz

All is achieved except for the first image remaining intact. This is why:

In the code, I intentionally disabled tab separators *when the active tab was attached* because of technical reasons. I'll see if I could somehow remove that restriction. However, no promise!

BTW `tab-pressed` and `tab-disabled` objects aren't needed in any theme.

**Comment by tsujan** [comment]
OK, apparently removal of that restriction didn't have any side-effect. With the latest git commit and with the updated theme (again at https://dl.dropboxusercontent.com/u/7793460/Ivy.tar.gz), I think this is exactly you talked about:

![2016-04-23-02 42 28-scrot](https://cloud.githubusercontent.com/assets/981076/14756355/e75b77f2-08fd-11e6-8ab8-723e96c442b6.png)

Isn't it?

**Comment by sixsixfive** [comment]
thats it thx ;)

>BTW tab-pressed and tab-disabled objects aren't needed in any theme.

also would it be possible to use a empty theme as fallback? It would also be nice if it would work the same way like css, gtk (if there is no state(-disabled, -hover) available use the -normal one) since this would drastically decrease the needed svg size

**Comment by tsujan** [comment]
Happy to know that!

> also would it be possible to use a empty theme as fallback? 

No, because `Kvantum = config + SVG`; there should be a default SVG file, which is the default theme too. It could be either light or dark. Since most people had a bias toward light themes, I chose a dark theme as a compensation. So, if you make a dark theme, you could omit many elements from your SVG elements.

> It would also be nice if it would work the same way like css, gtk (if there is no state(-disabled, -hover) available use the -normal one)

I remember I thought about that for a long time when I started Kvantum and, for many reasons that I don't remember now, decided not to do it. Thinking about it again, after a year, doesn't hurt but this time *I can really give no promise* because of so many parameters ;)

**Comment by sixsixfive** [comment]
>there should be a default SVG file, which is the default theme too. 

ok empty might the wrong word, i thought about a theme with transparent elements since this would work for both dark and light themes

**Comment by tsujan** [comment]
> ok empty was the wrong word, i thought about a theme with transparent elements

Transparent means nothing ;)
Maybe this is what you mean: *no inheritance from the default theme by default!* If so, it's an idea worthy of thinking.

**Comment by tsujan** [comment]
OK, I changed the SVG inheritance rule in a backward compatible way. Now, if a "focused", "pressed" or "toggled" state object is missing, the "normal" object from the same SVG file will be used (if it exists).

**Comment by sixsixfive** [comment]
only for tabs or in general?

**Comment by tsujan** [comment]
> only for tabs or in general?

For all SVG objects that have the above states.

**Comment by sixsixfive** [comment]
nice (=

**Comment by sixsixfive** [comment]
I tried this and even if I workaround its limitations, I just couldn't get it to work (and I tried many different combinations)

[Raspberry.zip](https://github.com/tsujan/Kvantum/files/283141/Raspberry.zip)

**Comment by tsujan** [comment]
Tab separators don't have *state*. As I wrote in `Theme-Making.pdf`, their object names for floating tabs are "floating-tab-separator", "floating-tab-separator-top" and "floating-tab-separator-bottom". You have added "-normal" and "-toggled" to their object names in your SVG file. It's enough to rename one of those objects (preferably the gray one) to "floating-tab-separator".

**Comment by tsujan** [comment]
BTW, all your GeneralColors are commented out. GeneralColors are important on many occasions.

**Comment by sixsixfive** [comment]
>BTW, all your GeneralColors are commented out. GeneralColors are important on many occasions.

thats ok, for the current state of the theme ;)


@separator

yes but it won't work that way eg: Its impossible for me to get a tab separator in doc mode but not in normal mode, that with the states is weird because the selected button needs a dfferent color to get a better contrast(also grey besides a color looks just very weird...)

**Comment by tsujan** [comment]
> Its impossible for me to get a tab separator in doc mode but not in normal mode,

Now I'm looking at your theme after the above change and tab separators show up only for doc mode.

**Comment by tsujan** [comment]
This is your theme after the renaming:

![tabs](https://cloud.githubusercontent.com/assets/981076/15560406/5a31cd78-2300-11e6-82ce-7e9884ea836e.png)

**Comment by tsujan** [comment]
> also grey besides a color looks just very weird

That's up to the theme maker. You could use a semi-transparent separator with a proper opacity and color.

**Comment by sixsixfive** [comment]
as you can see in normal mode the tab lost its border

>You could use a semi-transparent separator with a proper opacity and color.

that picture above(first selected tab left border colord, right border grey)

**Comment by tsujan** [comment]
> as you can see in normal mode the tab lost its border

Because the active tab is supposed to join to the inactive ones (`joined_active_tab` is `true`) and there's no separator for ordinary tabs in your theme ("tab-separator").

I think I could make it possible with an extra condition in the code: "if there's no separator, don't join the active tab." I should do some tests.

**Comment by sixsixfive** [comment]
>I think I could make it possible with an extra condition in the code

no need for that I will not use different tab themes for now (in fact, I will probably even use breeze instead of kvantum for my next theme because with the exception of that tabstyle its almost the same ;)

**Comment by tsujan** [comment]
Yes, it worked! Is this what you wanted?

![tabs](https://cloud.githubusercontent.com/assets/981076/15561122/dae7e464-2307-11e6-832f-066a0f404ba0.png)

I should test it for a while before making a commit (perhaps tomorrow).

> no need for that, I will not use different tab themes for now

It was a good idea and won't be limited to your theme. I just have to be sure that it won't have any drawback.

**Comment by sixsixfive** [comment]
From your Screenshot it seems that the left border uses still the rounded border

**Comment by tsujan** [comment]
> From your Screenshot it seems that the left border uses still the rounded border

No, both are your toggled separator -- the left one is drawn on the right side of the left tab. Adding of two small top and bottom toggled separators in red will remove that roundness. Conversely, if the added top and bottom rectangles are in gray, the right border will seem rounded too.

**Comment by sixsixfive** [comment]
>I think this is exactly what you wanted:

yes =)

**Comment by tsujan** [comment]
Done!

You don't need to change your theme (no renaming). Just compile the latest Kvantum! BTW, IMO, the theme is potentially elegant.

I made the logic very simple by removing the key `joined_active_tab` because it was redundant. Now, provided that `joined_inactive_tabs` is true, if there is a separator, it'll be drawn between all tabs properly. It can have normal and toggled states (as in your theme). Floating tabs will have their own separator if they exist.

**Comment by sixsixfive** [comment]
nice that looks awesome, however it seems there is an issue with tabs in docks?

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/15623929/052b8bf2-247c-11e6-9392-c0e76b3dcfaf.png)

**Comment by tsujan** [comment]
> it seems there is an issue with tabs in docks

Tabs are tabs everywhere. That's another example of incomplete styling in apps:

![qelectrotech](https://cloud.githubusercontent.com/assets/981076/15627135/bc861fce-24ef-11e6-866c-b5022ec69255.png)

The developer of qelectrotech has removed the panel of normal tabs in the code, thinking that such a change should be enough everywhere.

Making exceptions for such cases in Kvantum is out of question ;)
