### ISSUE TITLE
Dolphin properties window opening off screen

### ISSUE THREAD

**Issue by wodger1912** [tsujan/Kvantum#640]
Hi there,

I have installed Kvantum this am and the "Ant-Dark" theme for Arch / KDE plasma and absolutely loving it!
I have 2 different res screens, one atop the main screen (can't put them side by side - no room at the moment)

I went to check a folders properties in dolphin, and the properties window did not appear, on minimizing and maximizing dolphin screens from task bar, it is there, just off screen at the top. If I switch to KDE default theme in KDE settings, the properties window appears on top screen top left corner, if I switch back, it stays put, but if closed and new properties window opened, its off screen again.

I tried the default Kvantum theme and same behavior so I'm thinking this is a Kvantum issue (or a setting I've missed?)

Attaching a screenshot done with spectacle showing the properties window sitting at 0,0 in screen space which is not visible

Pete
![Screenshot_20210428_143937](https://user-images.githubusercontent.com/16460827/116357950-af207000-a82f-11eb-9b94-3397f314f89f.jpg)

EDIT: - I did some more testing, opening properties for files seems fine, positions around mouse cursor area, its just folder properties sends it off screen

**Comment by tsujan** [comment]
It's not related to Kvantum at all. Positioning windows is the job of window manager, not style plugin.
