### ISSUE TITLE
Black screen when taking screenshot with Spectacle

### ISSUE THREAD

**Issue by new-sashok724** [tsujan/Kvantum#643]
Hello! I am using Kvantum with KvArc theme. When i try to select rectangle area in Spectacle, all screen goes black. I still can select area, but it is much harder when i don't see what i am selecting.

**Comment by tsujan** [comment]
I can't reproduce the problem you described with Spectacle 21.04.0 but I'm afraid, even if Spectacle had a problem, it would have no relation to Kvantum.

**Comment by new-sashok724** [comment]
You're right, it's bug in Spectacle, sorry. I forgot i also enabled HiDPI scaling.
https://bugs.kde.org/show_bug.cgi?id=400921

**Comment by tsujan** [comment]
> I forgot i also enabled HiDPI scaling.

Oh, it's related to HiDPI!

Kvantum has no problem with HiDPI (as far as Qt doesn't). I assure you that Kvantum can't interfere with Spectacle's job.

**Comment by new-sashok724** [comment]
You're right, it's not problem in Kvantum, my bad :)

Thanks for this awesome theme engine, by the way. Everything works perfectly :+1:

**Comment by tsujan** [comment]
> Everything works perfectly

If you encountered any issue, please don't hesitate to report it! This one wasn't related to Kvantum; the next one might be :)
