### ISSUE TITLE
Possibility of rounded blur hack?

### ISSUE THREAD

**Issue by pushqrdx** [tsujan/Kvantum#646]
I know that the corner blur glitch is because kwin blurs in rectangular regions but i wonder is it possible for kvantum to add a blur rounding hack so one can specify how much the blur region should be rounded? somewhat similar to how lightly has rounded blurred menus without this glitch

**Comment by tsujan** [comment]
It's practically impossible. for 2 reasons:

 * It needs approximation by using many rectangles, which would be resource-unfriendly.
 * There's no way for extracting "roundness" from an element in the SVG image.

If KWin's blur effect depended on alpha — as Compiz's did — the problem could be solved easily but I remember that KWin's devs had a good reason to avoid alpha dependency (although I don't remember the reason itself).

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/d87dcf284081876743b58abc379ec32e22fce752

It should be set manually. As said above, corner roundness can't be extracted from the SVG file.
