### ISSUE TITLE
Some buttons in plasma settings app have incorrect margins

### ISSUE THREAD

**Issue by pushqrdx** [tsujan/Kvantum#647]
![Screenshot_20210501_222951](https://user-images.githubusercontent.com/25884937/116794383-e2cbf600-aacc-11eb-8c5f-8e250f46c4d4.png)

This doesn't happen with Breeze, only with Kvantum (any builtin style) 

Kvantum Manager 0.19.0
Theme: KvFlat (but it happens with all other styles as well)

**Comment by tsujan** [comment]
It's explained in the doc (Theme-Making.pdf → Dealing with exceptions → (3)). In short, those buttons have a wrong hard-coded style and Kvantum has added a workaround for them.

**Comment by tsujan** [comment]
> This doesn't happen with Breeze

Because Breeze (like most other styles) doesn't have configurable parameters and hides such problems.

**Comment by pushqrdx** [comment]
> It's explained in the doc (Theme-Making.pdf → Dealing with exceptions → (3)). In short, those buttons have a wrong hard-coded style and Kvantum has added a workaround for them.

i assume that built-in kvantum themes already use that workaround? because the issue appears with the built-in KvFlat theme, if not how can i specifically target that button?

**Comment by tsujan** [comment]
> i assume that built-in kvantum themes already use that workaround?


Not the theme but the code. It calculates the current available space and compares it with the requested minimum available space. If the former is less than the latter (which is only a sign of a bad hard-coded style), the code minimizes the spaces/margins as a workaround.

Hard-coded styles can be made correctly but many devs do it wrong when it comes to `QStyle`. Why? I don't know.

Also what KDE has made out of QML/Qt Quick is terrible (→ doc).

**Comment by pushqrdx** [comment]
> Also what KDE has made out of QML/Qt Quick is terrible (→ doc).

@tsujan yeah Qt is very powerful and i too fail to see why there are so many badly designed or very obvious inconsistencies everywhere

**Comment by tsujan** [comment]
Qt has a very comprehensive doc about `QStyle` and yet many devs seem to not have time to read or follow it. And why a hard-coded style in the first place?! OK, in rare cases, it may be needed but it *can* be done correctly.

>  so many badly designed or very obvious inconsistencies everywhere

Many of them (but not all) are cause by how KDE uses Qt Quick. They aren't Qt's fault, as you already know, I think.

**Comment by Rmdhn1** [comment]
Used Qogir manjaro with qogir on plasma too, doesn't seem to work though

**Comment by tsujan** [comment]
Also, read Theme-Making.pdf → A word about QML/Qt Quick.

It's still valid with Qt6 (against which the git Kvantum can be compiled).

**Comment by tsujan** [comment]
Added a workaround: https://github.com/tsujan/Kvantum/commit/07267784d0f3766efb5377c4b02b7e538b103d79
