### ISSUE TITLE
RGBA text colors

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#65]
is this possible in Qt? 
explanation why it is better: http://www.google.com/design/spec/style/color.html#color-ui-color-application see #Use opacity for text, icons, and dividers

**Comment by tsujan** [comment]
Of course it's possible. The real question is, "Is its implementation worth the effort?" Since texts are there to be seen *clearly*, I see no good reason for using translucent texts.

**Comment by sixsixfive** [comment]
hm i personally allow people to change at least the hightlighted background so for me this would make sense. Apps that use some fixed themes(remember qelectrotech?) come also into my mind.

**Comment by tsujan** [comment]
On second thought and realizing that Qt>=5.2 already accepts #ARGB as the color name, I decided to add the possibility of #RGBA (and not #ARGB) as the color name for all colors and all Qt versions. My reason for preferring RGBA over ARGB is that most apps do so.

However, it isn't a simple change and will take some time.

**Comment by tsujan** [comment]
Done! Now *any* color string can have the '#RRGGBBAA' format. The last hexadecimal 'AA' will be the alpha value if it exists.

Please test it as far as possible! As far as I tested, the only place where rgba doesn't work is the GroupBox text and that's Qt's fault.

And thanks for the idea! If you didn't suggest it, someone might use 'AARRGGBB', which would be accepted by Qt>=5.2 but would give a wrong color with Qt<5.2.

**Comment by sixsixfive** [comment]
tested, works ;)
