### ISSUE TITLE
Toolbar drag handles disappear when using FreeCAD with Kvantum themes

### ISSUE THREAD

**Issue by E1k3** [tsujan/Kvantum#650]
When I use any of the Kv themes provided by Kvantum, the toolbar drag handles are missing and I am no longer able to move the them in FreeCAD (version 0.19.2-1 archlinux).

The drag handles in FreeCAD exist and work with all non-Kv themes and the drag handles in KvantumPreview exist and work with all Kv themes. Because of this, I am not sure what exactly is going wrong here.

It seems to be a specific incompatibility between FreeCAD and Kvantum, but I am not sure because I don't have any other Qt5 applications with draggable toolbars right now. If you know of any, please tell me and I will try to reproduce this problem.

**Comment by tsujan** [comment]
> It seems to be a specific incompatibility between FreeCAD and Kvantum

There's no incompatibility. If an app shows toolbar handles *explicitly*, they'll be shown by all styles, Kvantum included. If not, some styles will show them, some don't. Kvantum doesn't show toolbar handles *by default*.

FreeCAD needs to show its toolbar handles explicitly if its developers intend them to be visible. Apparently, it doesn't.

**Comment by E1k3** [comment]
How do you explicitly show toolbar handles? I couldn't find a  QToolbar property or function that allows me to do that.

**Comment by tsujan** [comment]
By setting the `movable` property inside the code or in the `ui` file: https://doc.qt.io/qt-5/qtoolbar.html#movable-prop

[QStyle](https://doc.qt.io/qt-5/qstyle.html) has `QStyle::SH_ToolBar_Movable`. Widget styles are free to set it or ignore it. Kvantum sets it to `false` for the sake of consistency (there's a story behind it, which I don't have time to tell).

**Comment by E1k3** [comment]
Thanks, I assumed movable defaults to true at compile time since that value is specified in the Qt Documentation you linked to. Didn't expect that the theme may have a say in that.

**Comment by tsujan** [comment]
> ... since that value is specified in the Qt Documentation...

That's a part of the story: Qt doc forgets to mention `SH_ToolBar_Movable`.

Another part: If `SH_ToolBar_Movable` is set to `true`, most apps that don't set `movable` explicitly won't remember the toolbar layout.
