### ISSUE TITLE
Glitched buttons in Kvantum

### ISSUE THREAD

**Issue by Prayag2** [tsujan/Kvantum#651]
Buttons with icons are glitched. The icons are not aligned properly. Please look at the buttons in the screenshot below:
![14:18:58](https://user-images.githubusercontent.com/39525869/117533076-565b8f00-b008-11eb-903d-8c571971b7b6.png)
It is happening with all the themes.

**Comment by tsujan** [comment]
That's KDE's fault. Those aren't real Qt widgets but Qt Quick elements. Qt Quick can't be drawn by `QStyle` consistently and yet KDE devs insist on imposing a half-baked appearance they've made for Qt Quick.

**Comment by tsujan** [comment]
Added a workaround: https://github.com/tsujan/Kvantum/commit/07267784d0f3766efb5377c4b02b7e538b103d79
