### ISSUE TITLE
allow frames in dialogs windows

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#66]
reason: I might wanna make a theme like those again: 

http://sixsixfive.deviantart.com/art/ACID-280889262
http://sixsixfive.deviantart.com/art/Desktop-April-364063090

so i want a seperator between the titlebar and the window, on windows there isnt a problem since i can set a bottom border for menubars but dialogs have no menubars :/

**Comment by tsujan** [comment]
That's the job of the window manager. Decent WMs have a setting for it (openbox does).

**Comment by sixsixfive** [comment]
I guess you misunderstand, I mean a frame inside the window (the same as a window background but with the ability to use frames around/over it

**Comment by tsujan** [comment]
Any frame around windows/dialogs is a WM job.

**Comment by sixsixfive** [comment]
not around, inside the window(around the window content)
on kvantum a frame for [window], [dialog], [translucentwindow] & [tanslucentdialog]

eg: 
```
[Dialog]
frame=true
frame.element=window
frame.top=3
frame.bottom=0
frame.left=0
frame.right=0
interior=true
interior.element=window
```

![text4196](https://cloud.githubusercontent.com/assets/3780774/11568809/8e8a93e8-99ee-11e5-992e-d055b6cc3221.png)

**Comment by tsujan** [comment]
I know but that's just your way of naming it. What if you labeled the green frame as "part of a wm" instead? In fact, the green frame should be considered as the *inner* frame of the WM decoration; the *outer* frame being around the whole decoration.

**Comment by sixsixfive** [comment]
sure i could do that but this will create a double line on normal windows(windows with a menubar)

the theme used a green bottom border to emphasize the menubar but dialogs(questions, settings, about dialogs) don't have a menubar so i set a top border to for dialogs to make the theme more consistent

![07](https://cloud.githubusercontent.com/assets/3780774/11569302/7fecd7da-99f1-11e5-8707-45516e9b8fa1.png)

![08](https://cloud.githubusercontent.com/assets/3780774/11569308/84f77870-99f1-11e5-9642-46c24e04fae7.png)

the way it worked in gtk2 and 3 won't work in kvantum since kvantum will always scale the windowbackground which will blur the 3px top line across the whole dialog

https://github.com/sixsixfive/simpliX/blob/master/gtk-2.0/theme/gtkdialogs.gtk2
https://github.com/sixsixfive/simpliX/blob/master/gtk-2.0/theme/xfceheaders.gtk2

**Comment by tsujan** [comment]
Just for a such a specific usage and according to a specific taste?! No!

Technically speaking, a "window frame" would have sense only if its size had sense, at least, in one of these functions: pixelMetric(), subElementRect(), or sizeFromContents().

BTW, IMO your problem in the above screenshots are the Breeze decoration and its color(s).

**Comment by sixsixfive** [comment]
also I have that issue now again

![test](https://cloud.githubusercontent.com/assets/3780774/12064930/e4b723bc-afce-11e5-8ff4-8df3e8c97d88.png)

the dialog just don't look nice without a dark stripe at the top

**Comment by tsujan** [comment]
I'm afraid this is related to the (Breeze?) decoration, not to Kvantum. It seems that your active and inactive titlebars have different colors (`#e7e8eb` and `#e7e8eb` respectively).

You could either add normal and inactive background rectangles for windows/dialogs to your SVG image (NOT recommended because that wouldn't work with other WM's), or find a way to make the decoration use the same color for active and inactive windows (a more reasonable approach).

I also remember that I couldn't get rid of an ugly (blue) line under the Breeze titlebar until I made suitable KDE color schemes and logged out/in. Kvantum's extra themes don't show this problem with Breeze when their color schemes are also applied with a the zero contrast.

All in all, I don't change my mind about WM's responsibility for lines below titlebars.

**Comment by sixsixfive** [comment]
>t seems that your active and inactive titlebars have different colors

yepp that isn't finished yet

>All in all, I don't change my mind about WM's responsibility for lines below titlebars.

adding the line to the wm theme would be dumb if i would do that there would be a stripe between the wm and the menubar/toolbar on normal windows, too. I metacity can have different themes for wm classes but neither kwin or openbox supports that. 

anyway I guess i need to find another way to do that, cheers & happy new year

**Comment by tsujan** [comment]
> neither kwin or openbox supports that.

No, they don't, and for such a configurable DE as KDE is, it's a shame.
BTW, I like integrated titlebars, which are possible with both Aurorae and Openbox, even when the toolbars/menubars have a vertical gradient (KvSimple is an example). Unfortunately, Aurorae makes KF5 freeze sometimes.

Happy new year to you!
