### ISSUE TITLE
.themes folder

### ISSUE THREAD

**Issue by bphd** [tsujan/Kvantum#665]
Kvantum only list themes in `/usr/share/Kvantum` (root owned) but my DE install themes in `~/.themes` (user owned)

Shouldn't one support another? (it's not the case)

**Comment by tsujan** [comment]
> Kvantum only list themes in /usr/share/Kvantum

Not true. See doc → [Theme-Making.pdf](https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Making.pdf) → Theme Installation Paths.

**Comment by bphd** [comment]
Ok it was `ocs-url`/`pling` fault, because they install at `/home/$user/.themes/$theme/$theme.kvconfig`, not at `/home/noe/.themes/$theme/Kvantum/$theme.kvconfig`

One of you should make an accord, either they change their path, either you change yours

**Comment by tsujan** [comment]
> either they change their path, either you change yours

The decision was made a long time ago, after long discussions. It wasn't based on tastes but facts: packing Kvantum themes alongside GTK themes. Although I don't care about GTK, many theme makers do.

**Comment by bphd** [comment]
Okay so the decision was made but someone still hasnt changed his path

**Comment by tsujan** [comment]
> Okay so the decision was made but someone still hasnt changed his path

It seems so. Or they may have ignored the doc.

Most discussions were made elsewhere or through emails, years ago. At first I didn't want to add alternative installation paths (well-known Qt styles didn't support them) but I was convinced by the argument about GTK themes. GTK defines "the standard" in this regard, whether we like it or not.

**Comment by bphd** [comment]
It's like in any project, working together means having compatibilities adjustments. I advice for theme creator to place their .kvconfig both in ./ and ./Kvantum/ to have better compatibility

**Comment by tsujan** [comment]
Theme makers need to install their themes in `SUPPORTED_DIRECTORY/$THEME_NAME/Kvantum/` (there are three possibilities for `SUPPORTED_DIRECTORY`, one of which is for root installation), probably alongside matching GTK themes with the same names.

`DIR/Kvantum/$THEME_NAME/` is mostly for Kvantum internal themes or saved configs.

**Comment by bphd** [comment]
It's always the most listener who bends to the least one (like for example Linux adapting exe files from scratch because MS community doesnt want even to make one quarter of a foot step towards linux)
You can wait for some times for people to adapt their paths, but if they still doing it not right, you should at final add paths to support w/o Kvantum folder everywhere

**Comment by tsujan** [comment]
> but if they still doing it not right, you should at final add paths...

Most theme creators do it right.

Adding the above-mentioned paths was a very complex job that needed lots of extra code lines and tests (KDE devs correctly mentioned that and refused to do it for their Qt styles). Doing it was justified only by good arguments, not by compensating for people's mistakes ;)
