### ISSUE TITLE
Different text colors when the window is active and white elements on theme

### ISSUE THREAD

**Issue by PoisonFrog** [tsujan/Kvantum#675]
I'm using Kvantum to theme Qt apps on Xfce, but I'm having some problems because the text becomes really hard to read when the window is active and goes back to normal when I focus on another window. Also some parts of Qt apps are white even though the theme is dark. I'm having this problem with all themes.

This is how it looks when the window is active (KvDark theme):

![kvantumactive](https://user-images.githubusercontent.com/74987652/127257658-f2947dbf-aa96-4c83-b076-eeae3309abb5.png)

An this is how it looks when it's not the active window:

![kvantumnormaltext](https://user-images.githubusercontent.com/74987652/127257816-f5f82b2c-8f8f-4ae7-810a-e7055ee02031.png)

Also, some part of app themes are white and I don't think they are supposed to be white, like this one:
![virtualboxwhite](https://user-images.githubusercontent.com/74987652/127257930-51652d7c-68f8-42a3-8eb1-08f19c711954.png)

I did not edit these themes or anything and it happens with all themes I tried (most of them came packed with Kvantum).
I don't know if I'm missing something, maybe it is my setup because all I did was download Kvantum, choose a theme and add the variable _export QT_STYLE_OVERRIDE=kvantum_ and nothing else.

**Comment by tsujan** [comment]
What's the output of `echo $QT_QPA_PLATFORMTHEME` in a terminal?

**Comment by PoisonFrog** [comment]
> What's the output of `echo $QT_QPA_PLATFORMTHEME` in a terminal?

It is blank.

**Comment by tsujan** [comment]
Does it happen with all Qt-based apps or only certain apps?

**Comment by PoisonFrog** [comment]
> Does it happen with all Qt-based apps or only certain apps?

All apps I tried which are Calibre, Virtual Box, Kvantum Manager and qimgv (settings panel).

**Comment by tsujan** [comment]
Would you please attach a screenshot of *Kvantum Manager* that shows the same problem?

**Comment by PoisonFrog** [comment]
> Would you please attach a screenshot of _Kvantum Manager_ that shows the same problem?

Inactive:
![kvantuminactive](https://user-images.githubusercontent.com/74987652/127261361-83b3bc9a-437c-4dcf-9c2d-de7f4905bc33.png)

Active:
![kvantumactive](https://user-images.githubusercontent.com/74987652/127261377-8a968bc1-6d93-474b-986e-5c4988e619e6.png)

Btw, I noticed Kvantum Manager doesn't have this problem with the KvDark theme, but it happens with some other themes.

**Comment by tsujan** [comment]
Your screenshots with KvGnome don't have any problem. KvGnome imitates the default Gnome/GTK theme, whose inactive text colors are pale.

But your screenshots with KvDark are weird; KvDark's active and inactive text colors are the same and it doesn't have those white backgrounds. This is a screenshot of VirtualBox settings with KvDark under a Qt DE:

![KvDark](https://user-images.githubusercontent.com/981076/127262105-accd40a3-7ab0-4a5d-b78b-65d1d76cf0f9.png)

`qt5ct` is a small Qt plugin for GTK DEs like Xfce. Please install it, keep its default settings but select Kvantum from its GUI. Then test again and tell me about the result (a logout and login may be needed, if I correctly remember). You could easily uninstall it later if you don't like it.

**Comment by tsujan** [comment]
Also tell me which versions of Kvantum and Qt you have.

**Comment by tsujan** [comment]
> It is working as it should with this method.

Good to know that :)

So, it seems that, under GTK DEs, a Qt plugin is needed. I'll add this info to `INSTALL.md`.

> I believe version is 0.20.0 for kvantum

0.20.0 is OK; 0.20.1 is a little better.
