### ISSUE TITLE
Move everything to root folder instead of "Kvantum" sub-directory

### ISSUE THREAD

**Issue by nazibalalam** [tsujan/Kvantum#677]
All the source code and files are within another sub folder called "Kvantum". It would be a lot more relevant and convenient to put all of those files directly over the root folder of this repo, hope I've cleared enough what I said. :+1:

**Comment by tsujan** [comment]
→ https://github.com/tsujan/Kvantum/pull/298, https://github.com/tsujan/Kvantum/issues/230
