### ISSUE TITLE
Scroll jump with middle click should respect DE settings

### ISSUE THREAD

**Issue by acarasimon96** [tsujan/Kvantum#679]
I use KDE Plasma as my desktop environment, and there is a setting that controls the behavior of scrollbars under System Settings > Workspace Behavior > General Behavior. By default, it is set to "Scrolls one page up or down," which allows moving the scrollbar to the clicked location with a middle click. However, Kvantum is currently unaware of that setting, forcing users manually set it in Kvantum Settings to match the scrollbar behavior in all Qt-based apps.

Here is a screenshot of the Plasma System Settings window with the scrollbar behavior setting shown:

![Screenshot_20210817_092216](https://user-images.githubusercontent.com/17580077/129754281-27be8e72-9cc2-4344-9122-a3ced4d34b10.png)

It would be awesome if the "Scroll jump with middle click" option follows desktop environment settings when "Respect current DE if possible" is checked. This can be helpful when a user switches between different Kvantum themes or restores default settings for a particular theme.

**Comment by tsujan** [comment]
I think it's possible. Will look into it. Thanks for the suggestion!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/3de0147d8d45297f268d9c6d39405c268c03b75c

Please note that, if you toggle that KDE setting, you'll need to restart the app to see the effect. The reason is that Kvantum doesn't depend on KDE; it just tries to respect some KDE settings as soon as an app is started.
