### ISSUE TITLE
make a few buttons flat

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#68]
Also would it be possible to make the tab(the scroll buttons that appear if the tab widget is bigger than the window) and the mdi buttons flat?

**Comment by tsujan** [comment]
I'll look into it.

**Comment by tsujan** [comment]
A tabbar scroll-button is a *real* tool-button with just an arrow. If I wanted to make an exception for it, I should add too many lines of code (to cover the case of dark-and-light themes) for such a trivial change. Not worthy!

The sub-window titlebar buttons had a different story. It was better they had the same look on both mdi titlebars and menubars. So, I revamped them and removed their panels on menubars.

Thanks for the suggestion!
