### ISSUE TITLE
Kvantum fails to compile with KDE Frameworks master

### ISSUE THREAD

**Issue by n3rdopolis** [tsujan/Kvantum#680]
Hi

I think it was more specifically https://invent.kde.org/frameworks/kwindowsystem/-/commit/61cfaf3b7389daf7f00da050da7a44b41d4b7632 that broke it

I get CMake error
```
CMake Error at /opt/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindXCB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "XCB", but
  CMake did not find one.

  Could not find a package configuration file provided by "XCB" with any of
  the following names:

    XCBConfig.cmake
    xcb-config.cmake

  Add the installation prefix of "XCB" to CMAKE_PREFIX_PATH or set "XCB_DIR"
  to a directory containing one of the above files.  If "XCB" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake:36 (find_dependency)
  style/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/srcbuild/Kvantum/Kvantum/build/CMakeFiles/CMakeOutput.log".
```

I am able to work around it by tossing 
```
find_package(ECM NO_MODULE)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
```
somewhere in Kvantum/style/CMakeLists.txt but before 

```
find_package(KF5WindowSystem REQUIRED)
```

Thanks

**Comment by tsujan** [comment]
I have kwindowsystem 5.84.0 and see no problem. kwindowsystem 5.85.0 came today but I haven't upgraded yet. Which version do you mean?

**Comment by n3rdopolis** [comment]
Bleeding edge kwindowsystem. I think it's this commit https://invent.kde.org/frameworks/kwindowsystem/-/commit/61cfaf3b7389daf7f00da050da7a44b41d4b7632

**Comment by tsujan** [comment]
> Bleeding edge kwindowsystem.

Oh, sorry, you'de said that in the title. My bad.

We should wait to see what will happen in the stable branch. If that commit is the culprit, several apps will be affected.

But thanks for your report! I keep it open for now.

**Comment by Chiitoo** [comment]
XCB was moved back to private [1], so this should not be an issue any longer (I hit it with lxqt-panel).

1. https://invent.kde.org/frameworks/kwindowsystem/-/commit/c7c49f9c421c5473aff2131f85468bd306c38de4

**Comment by tsujan** [comment]
@Chiitoo, thanks for the info!

**Comment by n3rdopolis** [comment]
Ok, this can be closed then probably...

**Comment by tsujan** [comment]
> Ok, this can be closed then probably...

I agree. If it happens with the next stable version of kwindowsystem, I'll do as you said (https://api.kde.org/ecm/manual/ecm.7.html) — it seems backward compatible:
```
  .....
  find_package(ECM REQUIRED NO_MODULE)
  set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
  .....
```
