### ISSUE TITLE
Wrong / Missing mouse event timestamp for the first event in a row

### ISSUE THREAD

**Issue by jmglogow** [tsujan/Kvantum#689]
I've had multiple Wayland LibreOffice (LO) bugs with broken click behavior. It looks like a bug in Kvantum on Wayland, but then I tested only with Debian Bullseye, which IMHO has an unusable Plasma Wayland session, so it's quite possible just an other bug in QtWayland. According to the report X11 works fine for the user and Breeze also seems to work correct.

You can read my analysis in https://bugs.documentfoundation.org/show_bug.cgi?id=143206#c21

It seems the first button press event gets a 0 timestamp when Kvantum is used, which breaks LO's click handler in interesting ways. I don't see a sensible way to work around this bug from LO.

Maybe you have some better setup to further analyze this bug?

**Comment by tsujan** [comment]
Kvantum doesn't treat Wayland differently from X11. Moreover, it can't cause any problem in a non-Qt app like LibreOffice. However, LibreOffice's Qt5 skin can cause problems and have bugs (it definitely does).

**Comment by hsantanna** [comment]
The LibreOffice bug is triggered only by using kvantum and only on Wayland.

Do you have any clue on why this click / double-click issues may be happening and maybe how it should be fixed?

**Comment by tsujan** [comment]
> Do you have any clue on...

Actually, I do. Since Wayland — and especially Plasma-Wayland — has terrible problems when it comes to dragging, please test by changing `Kvantum Manager → Configure Active Theme → Miscellaneous → Drag from:` to `Titlebar` and report back.

It worked here under Plasma-Wayland with Manajaro Testing (which has the latest versions of everything). It shows only one thing: a bug related to Plasma-Wayland; it can be in KDE's Wayland compositor itself or in LibreOffice's Qt5 skin.

**Comment by tsujan** [comment]
I'll add LibreOffice to the blacklist of window dragging soon but the problem is worse: *even with Breeze*, one can't change the font and its size by using toolbar popups under Wayland because no popup shows up. There may other problems too (with *all* widget styles and under Plasma-Wayland) but I didn't have time to check.

I really think that the developers of LibreOffice's Qt5 skin need to check it under Wayland. I admire their work but it has serious issues with Wayland.

**Comment by tsujan** [comment]
Blacklisting done in https://github.com/tsujan/Kvantum/commit/afacf078be805720d2af07039b87cb4ca84c3efa

**Comment by jmglogow** [comment]
LO actually has some minimal Wayland and X11 specific Qt code for Video embedding and workarounds for Qt bugs, but otherwise it's just "plain" Qt. And just looking at the amount of daily patches in https://invent.kde.org/qt/qt/qtbase and https://invent.kde.org/qt/qt/qtwayland/, I'm not even sure I should "already" start.

I was hoping for a better experience after my Debian Buster dist-upgrade to Bullseye, but currently I don't see me very motivated to fixing Wayland bugs, as I found basic broken stuff when testing the "Plasma Wayland" session, also reproducable with other KDE apps I tried as a reference.

FWIW: generally you can run LO with gtk3 or QPA xcb and get a much better Wayland experience. I have no idea, why this broken timestamp from Qt even happens for a mouse event; nothing should IMHO touch that. But then I don't know about complex Qt themes. And I'm not surprised you found broken Breeze behavior too. Correct popups is definitely a complex problem for Qt, even with X11 :-(

**Comment by tsujan** [comment]
> LO actually has some minimal Wayland and X11 specific Qt code for... but otherwise it's just "plain" Qt.

Kvantum also relies on Qt for Wayland. It doesn't (and won't) have any Wayland-specific code.

@jmglogow 
Wayland was problematic from start. It was easy to imagine that its core concept would lead to a chaos. And that has happened.

I have the latest Plasma-Wayland but can't tolerate it for more than an hour: dialogs aren't opened where they should, sometimes tooltips and menus show up at the opposite side of the screen, animations are choppy, there are freezes, Qt's DND has a terrible issue,...., in short, nothing is reliable.

Personally, I have no reason whatsoever to leave the comfort of X11. However, I make all my apps compatible with Wayland, as far as Qt allows that. I may also add workarounds for it, like the above-mentioned blacklisting.

**Comment by jmglogow** [comment]
> I have the latest Plasma-Wayland but can't tolerate it for more than an hour: dialogs aren't opened where they should, sometimes tooltips and menus show up at the opposite side of the screen, animations are choppy, there are freezes, Qt's DND has a terrible issue,...., in short, nothing is reliable.

And here I was hoping for something like: "Just try Neon (in a chroot / kvm) and (almost) everything will work with a fully patched Qt and Plasma". So it's not just my "old" Debian Bullseye. Guess I'll further postpone fixing non-obvious Qt+Wayland related bugs in LO; sorry for the users :-( … why I'm reminded by KDE4…?!
