### ISSUE TITLE
Application theme not work for mathpix

### ISSUE THREAD

**Issue by dianlujitao** [tsujan/Kvantum#699]
Mathpix is unreadable with a dark theme:
![t](https://user-images.githubusercontent.com/5774651/133870912-e1b8ae38-df83-4a6b-b136-449ce5d133c1.png)

I set MateriaLight as its theme but not work. However, changing both the global theme in kvantum manager and the application theme for other Qt apps such as dolphin worked well.
```
❯ cat .config/Kvantum/kvantum.kvconfig
[General]
theme=MateriaDark

[Applications]
MateriaLight=mathpix-snipping-tool
```

I use [this aur package](https://aur.archlinux.org/packages/mathpix-snipping-tool) and the executable is `/usr/bin/mathpix-snipping-tool`

**Comment by tsujan** [comment]
With some applications, the executable name may not be the app name. Some DEs (like KDE) have X11 tools for finding the real app name by clicking its window but, sadly, those tools can't be used under Wayland. Search for "window class" if you use one of them.

In the case of Mathpix, the app name is `Mathpix Snipping Tool` (with spaces).

Anyway, I installed Mathpix from AUR and it had no problem with dark themes that come with Kvantum. This screnshot is taken with a modified version of one of them

![Mathpix](https://user-images.githubusercontent.com/981076/133872003-8c677f0b-47ac-411f-85d7-a45db426631b.png)

**Comment by tsujan** [comment]
For the record, the following bash script does the same thing: It changes the cursor to a cross under X11 and gives info on the app by clicking:

```sh
#! /bin/bash

tmpFile=$(mktemp)

echo "Detecting all attributes"
echo "Click on a window"
echo

xprop >${tmpFile}

winType=$(grep 'WINDOW_TYPE' ${tmpFile} |sed 's/^.*_\([^_]*\)$/\1/')
winClass=$(grep '^WM_CLASS' ${tmpFile} |cut -d\" -f4)
className=$(grep '^WM_CLASS' ${tmpFile} |cut -d\" -f2)
winTitle=$(grep '^WM_NAME(STRING)' ${tmpFile} |cut -d\" -f2)
owningProg=$(grep '^_NET_WM_PID(CARDINAL)' ${tmpFile} |sed 's/.*= //g' |\
    xargs ps -o comm= -p)
classRole=$(grep '^WM_WINDOW_ROLE(STRING)' ${tmpFile} |cut -d\" -f2)

rm -f ${tmpFile}

cat <<EOF
window type     ${winType}
window class    ${winClass}
class name      ${className}
window title    ${winTitle}
owning program  ${owningProg}
class role      ${classRole}
EOF

exit 0
```
