### ISSUE TITLE
download ettercap with brew 

### ISSUE THREAD

**Issue by unikquentin** [tsujan/Kvantum#700]
Hello tsujan, 

I think i need your help. When i download ettercap my home-brew, i have a little issue. I follow a video on youtube, here the link : https://www.youtube.com/watch?v=f2gBA0mD42w. 

When i enter the command  cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_IPV6=ON -DOPENSSL_ROOTDIR='brew --prefix openssl'
I got the error below : 
If you can help me, i would appreciate. 

Thanks 
Unik

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:9 (include):
  include could not find requested file:

    MacroEnsureOutOfSourceBuild

CMake Error at CMakeLists.txt:10 (macro_ensure_out_of_source_build):
  Unknown CMake command "macro_ensure_out_of_source_build".

-- Configuring incomplete, errors occurred!
See also "/Users/"myname"/ettercap/CMakeFiles/CMakeOutput.log".
See also "/Users/"myname"/ettercap/CMakeFiles/CMakeError.log".

**Comment by tsujan** [comment]
I'm afraid you're on the wrong page. I'm not the developer of ettercap; this is Kvantum's bug tracker.

**Comment by unikquentin** [comment]
okay thank you

**Comment by unikquentin** [comment]
Tsujan, is kvantum's bug tracker on GitHub ? Because when i write his name in search bar i don't find him
I m new so i don't understand all 
Thank you for your help

**Comment by tsujan** [comment]
@unikquentin 
Ettercap's GitHub repository is at https://github.com/Ettercap/ettercap. You might want to ask your question at https://github.com/Ettercap/ettercap/issues.

*Ettercap has nothing to do with me at all.* I'm neither its developer nor its user.

**Comment by unikquentin** [comment]
Okay thank you very much for your help
