### ISSUE TITLE
Rounded Corners In Context Menu MenuItem

### ISSUE THREAD

**Issue by mepowerleo10** [tsujan/Kvantum#708]
How can I edit Theme.svg to have rounded corners for the MenuItem in the context menu? I've tried rounding the corners of the menuitem-pressed and menuitem-toggled, but I still don't have the rounded corners.

**Comment by tsujan** [comment]
Kvantum comes with a [comprehensive documentation](https://github.com/tsujan/Kvantum/tree/master/Kvantum/doc). It also includes several themes with rounded corners.

**Comment by mepowerleo10** [comment]
Hello @tsujan, so I've read the documentation and everything in it. I am trying to do the rounded corners for context menus. However, my theme does not seem to pick up the frame-left/right/top/bottom... etc elements from the SVG. Here is my `.kvconfig` file.

**Comment by mepowerleo10** [comment]
So, I'm having another issue with the context menus, all 4 corners have small white dots inside them. They can be clearly seen when you right-click a CopyQ item, but not very clearly seen in other contexts like Dolphin right-click menu. Here is the link to the theme I am editing if you would not mind trying [Qogir KDE ReImagined](https://github.com/mepowerleo10/Qogir-kde)

**Comment by tsujan** [comment]
> all 4 corners have small white dots inside them...

It's caused by a problem in your SVG file ("Qogir-dark.svg"). Your "menu-normal" element has rounded corners. It is an interior element and should cover the whole rectangle; roundness is only for the frame.

BTW, your themes look elegant.

**Comment by mepowerleo10** [comment]
> BTW, your themes look elegant.

I wouldn't take all the credit. It's built upon your foundations. I am going for the consistent look-n-feel between the Kvantum and the KDE global theme you created

**Comment by mepowerleo10** [comment]
> BTW, your themes look elegant.

I wouldn't take all the credit. It's built upon your foundations. I am going for the consistent look-n-feel between the Kvantum and the KDE global theme you created

**Comment by mepowerleo10** [comment]
I'll change the background in Inkscape and make the necessary corrections. Thanks a lot for the early feedback.

**Comment by tsujan** [comment]
> I have to run SVG Cleaner on the .svg?

It isn't necessary but it can reduce the size of the SVG file a lot. You could also use `Inkscape → File → Clean Up Document` instead. It isn't as effective as SVG Cleaner but is completely safe (read below).

However, if you use SVG Cleaner, you need to be very careful about its settings. Don't use settings that remove properties used by Kvantum; otherwise, your SVG file will be "corrupted", as far as Kvantum is concerned.

Always back up your original SVG file.
