### ISSUE TITLE
qt5 cutted text

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#71]
well it seems that some text in qt5 is now broken for me eg all full scale characters like g,j,y,p,_,

also i dont have this issue in qt4 designer but in qt5 designer so i guess its qt5 specific

![aaa](https://cloud.githubusercontent.com/assets/3780774/11986063/aea7390a-a9cb-11e5-9513-55f8ac302344.png)

**Comment by tsujan** [comment]
Which font do you use with Qt5?

**Comment by sixsixfive** [comment]
droid sans, also you can test it by yourself on arch: https://aur.archlinux.org/packages/glare-themes

**Comment by tsujan** [comment]
I have Glare and succeeded in reproducing the problem with font size >= 10 (my font size was 9).

**Comment by tsujan** [comment]
Should be fixed now.
As you said, the problem is in Qt5. Previously I thought it was in fonts like Noto Sans; hence an incorrect workaround. Please test wit a few fonts and font sizes! And thanks for reporting this problem :)

**Comment by sixsixfive** [comment]
it is ;)
