### ISSUE TITLE
LibreOffice Options dialog box

### ISSUE THREAD

**Issue by Sadi58** [tsujan/Kvantum#710]
I see this in all Kvantum themes: LibreOffice Options dialog box User Data input field border and background elements are either missing or have the same color as the panel background. Fixing at least one of these two issues would be nice.
There is also slightly a less important problem with the lines in the tree of categories in the left box which are too light to see clearly.
![image](https://user-images.githubusercontent.com/6375934/136815321-7aea4250-8352-4d64-b6aa-e8c9a73daf15.png)
This is how User Data input fields look with the breeze theme (which also has the same problem with tree lines):
![image](https://user-images.githubusercontent.com/6375934/136973187-f191a2be-27bd-4104-9eda-38c48e41693a.png)

**Comment by tsujan** [comment]
Please note that LibreOffice is not a Qt app. Its Qt skin is *forced* on it by the good and hard work of the developers of that skin. It's expected to have problems. Actually, it has many issues that show up differently with different Qt syles. For example, this is how those input fields appear with Qt's gtk2 style:

![gtk2](https://user-images.githubusercontent.com/981076/137284361-dc10c1ea-ff57-4c5d-93ef-90312eee3335.png)

The reason why they don't have a background or border with Kvantum is that Kvantum doesn't draw any background/border but uses SVG elements. LibreOffice's skin ignores the SVG elements here and the result is what you see,

However, I'll see if a workaround is possible for those input fields, without cluttering Kvantum's code. Thanks for mentioning it!

As for branch lines, their colors are the same in both screenshots. They're drawn by LibreOffice's Qt skin itself.

**Comment by tsujan** [comment]
By chance, I was able to find the cause of the problem in LibreOffice's Qt skin quickly and added a workaround in https://github.com/tsujan/Kvantum/commit/785e43bfe8297a2666e380422505bddfb4eb4dc0

The result:

![input](https://user-images.githubusercontent.com/981076/137297464-4089da0d-64db-4d86-824c-7bb86b01e1a4.png)

Thanks again for the report!

**Comment by tsujan** [comment]
You're very welcome.

The developers of LibreOffice's Qt skin have done a great job but making a non-Qt app have a Qt look is an extremely hard task. Problems are inevitable and some of them may be insolvable. Fortunately, this one was simple.
