### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by Hitmanfourtyseven** [tsujan/Kvantum#716]
Hello,
Something in Qt 5.15.1-5.15.2 changed and the scrollbar theming is apparently gone, a generic one appears instead in every theme.
My system uses platformtheme and styleoverride env variables and all other aspects of the themes are applied.
![image](https://user-images.githubusercontent.com/90115978/140642408-0e6cbf01-de44-467d-ae45-249ef10e2c18.png)
![image](https://user-images.githubusercontent.com/90115978/140642428-a767128d-ce92-49b2-8a3d-c22d0d640f3c.png)

**Comment by tsujan** [comment]
Please be more specific. I can't see any problem in your screenshots. Those are called "transient scrollbars".

**Comment by Hitmanfourtyseven** [comment]
I'm sorry, something was wrong with my config, i wiped /.config/Kvantum and it works now.

Basically a setting about transient scrollbars stuck even when i disabled it, and i thought Qt messed with the ui or something :).
This is what i meant, about the nothched/old design scrollbars
![image](https://user-images.githubusercontent.com/90115978/140643086-53c5b9c5-bf16-47dd-9638-61debdb3cf34.png)

**Comment by tsujan** [comment]
> This is what i meant, about the nothched/old design scrollbars

Some themes don't have that design, even without transient scrollbars. It's up to the theme maker to use a classic shape — with add/sub arrows, trough and glow — or a minimal one.

Transient scrollbars are always minimal though.
