### ISSUE TITLE
Kvantum possible on WINDOWS?

### ISSUE THREAD

**Issue by brainblowjob** [tsujan/Kvantum#72]
=)

**Comment by tsujan** [comment]
Theoretically speaking, it should be, with some changes. But, for many reasons, that isn't something *I* could do. My focus is on Linux. Perhaps someone knowledgeable about Qt under MS Windows could fork it for Windows. However, it would be a lot of work.

**Comment by mat0thew** [comment]
I'll see what can be done, it can be something interesting and get

**Comment by tsujan** [comment]
Good luck! Don't hesitate to tell me if I may be of any help, especially about why I've done this or that in the code.

**Comment by mat0thew** [comment]
@tsujan Even normally be compiled **kvantummanager** and **kvantumpreview**. left to deal only with the **x11extras** and **style plugin**

**Comment by tsujan** [comment]
Great!
kvantumpreview is just for previewing various widgets, so once it's compiled, it should work OK.
But the compilation of kvantummanager wouldn't be enough; its code needs to be greatly modified to work under Windows. Lots of work, as I told.

**Comment by mat0thew** [comment]
@tsujan Clean warm-up brain and can be played

**Comment by ozky** [comment]
I have simple solution to you move to linux. :)

**Comment by tsujan** [comment]
> I have simple solution to you move to linux. :)

LOL :) Most of us, Linux users, were "Windows refugees" at some point. But let's not turn this to an OS war, please!

**Comment by 01100100011010010110001101101011** [comment]
@ozky kek

**Comment by 01100100011010010110001101101011** [comment]
@tsujan war is life

**Comment by ozky** [comment]
> LOL :) Most of us, Linux users, were "Windows refugees" at some point. But let's not turn this to an OS war, please!
No we don't start any war here.

**Comment by 01100100011010010110001101101011** [comment]
war war war
