### ISSUE TITLE
Kvantum button margin, Manjaro KDE, happens on all theme

### ISSUE THREAD

**Issue by Rmdhn1** [tsujan/Kvantum#721]
![Screenshot_20211113_223320](https://user-images.githubusercontent.com/54092365/141649772-f5df19ac-bbe0-4d0f-bfd4-f44c5e22f790.png)
I am using Qogir-manjaro-dark in both kvantum and plasma global themes, but it still like that, i heard there's a workaround but how? i've also never seen this in any tutorial with Manjaro KDE

**Comment by Rmdhn1** [comment]
there's also the ugly line

**Comment by tsujan** [comment]
→ https://github.com/tsujan/Kvantum/issues/647

You already added a comment to that page and everything is explained there.

**Comment by tsujan** [comment]
Added a workaround: https://github.com/tsujan/Kvantum/commit/07267784d0f3766efb5377c4b02b7e538b103d79
