### ISSUE TITLE
full with button default?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#73]
Hi,

is there any way to use the button default indicator over the full button width?

Im looking for something like this:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/13903671/a6c5ed04-ee85-11e5-9d7c-4b2136bdb17d.png)

**Comment by tsujan** [comment]
As explained in `Theme-Making.pdf`, you could add a default frame but no default interior. I didn't see any need to include an interior when there can be a different frame for default buttons.

**Comment by sixsixfive** [comment]
ok i will just ignore this feature then ;)

**Comment by tsujan** [comment]
I don't think adding a default interior would cause any problem -- I just hadn't seen such a thing anywhere. Do you think it's needed?

**Comment by sixsixfive** [comment]
Would be a good way to make the default button more visible at first sight

**Comment by tsujan** [comment]
OK. I'll try to add it.

**Comment by tsujan** [comment]
Done! Now you could add a default interior object. See the new `Theme-Making.pdf` → The Default (Push) Button.

**Comment by sixsixfive** [comment]
yay!
