### ISSUE TITLE
Typo in weblate

### ISSUE THREAD

**Issue by hugok79** [tsujan/Kvantum#735]
There is a typo "wiindows" in the following string:

https://translate.lxqt-project.org/translate/tsujan/kvantum-manager/en/?checksum=575c8626d7876df

**Comment by tsujan** [comment]
Thanks a lot for telling me! It's fascinating how the brain corrects (= ignores) a misspelling while reading.

I fixed it in https://github.com/tsujan/Kvantum/commit/0fbd90bd88c1d0aa98b20e0d681ba640bb949bd0, without damaging the current translations. Weblate will be updated automatically after some time.
