### ISSUE TITLE
a way to hide the groupbox text

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#74]
there should be a way to hide the text of the groupbox fame or to put it above the frame

**Comment by tsujan** [comment]
Hiding the text would defeat its purpose -- like hiding the text of a tab or toolbox.

I'll think about adding an option for putting it above the frame.

**Comment by tsujan** [comment]
Added an option for it to Kvantum Manager. See "Configure Active Theme" → Miscellaneous → "Group-box label above frame". The boolean key is "groupbox_top_label" under the General section.

Please test it thoroughly!

**Comment by sixsixfive** [comment]
nice, that looks much better
