### ISSUE TITLE
Cut off buttons on KAlarm

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#740]
Cut off buttons on KAlarm with Kvantum engine:
![image](https://user-images.githubusercontent.com/8083855/145764457-bf896dd6-7b4e-4d2a-b6e3-bd1939a81f6a.png)
Fusion:
![image](https://user-images.githubusercontent.com/8083855/145764589-1c9e7ab5-8a75-4a26-8897-917b11e3ffc3.png)

**Comment by tsujan** [comment]
A terrible bug in the app's style, based on a lack of knowledge of `QStyle`!

`QAbstractSpinBox::ButtonSymbols` can have three values: `UpDownArrows`, `PlusMinus` and `NoButtons` (→ https://doc.qt.io/qt-5/qabstractspinbox.html#ButtonSymbols-enum). Qt provides no spin-box with 2 pairs of buttons.

A developer may want to invent a spin-box with 2 pairs of buttons; there's nothing wrong with that. However, if he wants to do so correctly, he should get the sizes of spin-box elements *from the widget style* and add the space needed by the extra buttons accordingly. Here, the developer has assumed fixed sizes for buttons and some other parameters (like in Fusion).

Qt doesn't set a fixed width but lets the widget style set it and, of course, Kvantum doesn't follow the ugly proportions that are copied by most styles.

**Comment by tsujan** [comment]
Apparently, KDE devs started to follow in Gnome devs' footsteps and have a monopoly on the Qt style that should be used under KDE. See https://github.com/tsujan/Kvantum/discussions/746.

As a result, problems like this might happen more and more with KDE updates. KDE devs don't have time to write correct style codes.

I have no reason either to waste my time by trying to compensate for that. Kvantum will be developed as a Qt style, without paying attention to the sabotage KDE devs might do. Fortunately, unlike Gnome that owns GTK, Qt isn't made by KDE.
