### ISSUE TITLE
Windows not interacting with top panel properly

### ISSUE THREAD

**Issue by Xenfo** [tsujan/Kvantum#742]
They were interacting fine about ~2-3 versions ago now it overlaps with dual monitor. I can't access close and minimize buttons or the title bar for the most part.

![Sun-Dec-19-2021](https://user-images.githubusercontent.com/46873232/146692491-c2ef852e-58cd-4c2a-b6e4-0a0928fc3eba.png)

**Comment by tsujan** [comment]
Close and minimize buttons, panels and title-bars are provided by the DE you use, not by Kvantum. Kvantum has no control over them; it's DE agnostic.

**Comment by Xenfo** [comment]
So KDE broke it?

**Comment by tsujan** [comment]
If you use KDE, yes. The fact is that the title-bar isn't drawn by Kvantum; that's the job of WM (window manager), which is KWin in the case of KDE. The WM is also responsible for positioning windows, preventing them from going off-screen, etc.

**Comment by Xenfo** [comment]
Alright thanks, I'll wait for an update.
