### ISSUE TITLE
[Help] Tree Branch Lines in the "kate" text editor do not respect theme color

### ISSUE THREAD

**Issue by VainlyStrain** [tsujan/Kvantum#743]
Hi! I have encountered a very specific theming issue.

I am using a dark Kvantum theme, with tree branch lines enabled. Notably, the tree branch line color (light.color) is set to a pretty dark color, so that they don't stick out too much.

However, in kate, the tree branch lines are very bright. Modifying any color in the config does not solve the issue. This is not exclusive to my Kvantum theme, but happens with every Kvantum theme. (including the default themes, with tree lines set to enabled)

Notably, tree lines in other applications do respect the intended color, so this is specific to kate.

Also, the issue does not occur when kate is started with the default KDE Breeze theme.

How do I resolve this? Thanks!

Specifics:
OS: Fedora Linux 34
KDE Plasma version: 5.22.5-1.fc34 (x86_64)
Kvantum version: 0.20.2-1.fc34 (x86_64)

**Comment by tsujan** [comment]
This is definitely not a Kvantum issue but a problem in Kate's style code.

I don't know which branch lines you mean (I don't use Kate). Those in Kate's side-pane? Kate's side-pane doesn't take its colors from the active widget style but from KDE color scheme (a bad design). So, when you switch to a dark Kvantum theme, change the KDE color scheme accordingly. That's already explained in Kvantum Manager → Change/Delete Theme.

If you mean another kind of branch lines, please be more specific, by adding a screenshot.
