### ISSUE TITLE
RFE: move i18n support to gettext

### ISSUE THREAD

**Issue by kloczek** [tsujan/Kvantum#745]
Most of the KDE/Qt projects already moved to gettext and it would be good to move Kvantum to have better in-memory code sharing between running applications.

**Comment by tsujan** [comment]
Kvantum is a Qt plugin; it doesn't have any translatable string.

As for Kvantum Manager, it's internationalized in the standard Qt way.

**Comment by kloczek** [comment]
What about:
https://github.com/tsujan/Kvantum/tree/master/Kvantum/kvantumpreview/data/translations
https://github.com/tsujan/Kvantum/tree/master/Kvantum/kvantummanager/data/translations

Out of those files are generated .qm files which are installed by install target.

**Comment by tsujan** [comment]
They don't belong to the plugin but its config GUI.

Anyway, I prefer to stick with Qt's way of localization. It's simple, effective and easy-to-use for translators.

BTW, Kvantum isn't a KDE app.

**Comment by kloczek** [comment]
Yes Kvantum isn't a KDE app but usually it is used with KDE apps and as long as even most of the qt5 components already have been moved to use gettext looks like it is time to to moves as well other apps/projects to use gettext to allow better in memory staring code handling i18n over gettext (which part of the libc).

**Comment by tsujan** [comment]
I know of so many Qt projects that use Qt's localization methods. KDE doesn't but that may have historical reasons (Qt's method might haven't been available or efficient with old versions). One thing that KDE doesn't care much about is memory management. Since Qt4, and especially Qt5, Qt added functionalities that KDE had to invent for itself with Qt < 4.

**Comment by kloczek** [comment]
Maybe I'm wrongbut looks like latest Kvantum supports only qt5 and qt6 :)

**Comment by tsujan** [comment]
KDE is a continuous project. It existed long before Qt5 and inherits parts of its current structure from the old times.

**Comment by tsujan** [comment]
> looks like latest Kvantum supports only qt5 and qt6

It supports Qt4 too but Qt4 is practically dead.

I've intentionally kept Kvantum independent of KDE and its methods, although I've also tuned it to KDE (and LXQt) as far as possible. It can be used under any DE that has a decent enough Qt integration. Under KDE, it can also use KWin's blur effect if present. To do so, it only depends on `kwindowsystem`, which is a nice Qt extension made by KDE devs and, fortunately, doesn't bring with itself any KDE stuff.
