### ISSUE TITLE
Kvantum theme not applied to Qt6/QML Application

### ISSUE THREAD

**Issue by dalto8** [tsujan/Kvantum#762]
I developed an application using Qt6 and I have been unable to get theming to work with kvantum.

* If I use QGnomePlatform for theming, it works.
* If I use qt6ct to set a Fusion theme, it works.
* If I use qt6ct to set a kvantum theme, it doesn't work.  However, other qt6 applications such as qbittorrent do get the kvantum theme applied.

I thought it might be something specific to my application so I created a trivial QML application which demonstrates the same behaviour, here: https://github.com/dalto8/kvantumqt6test

I am using Arch Linux as a test platform with kvantum 1.0.0 and Qt 6.2.3 from the Arch repos.

Is this a problem with kvantum or do I have to do something specific in my application to enable support for kvantum?

If I failed to provide any needed information, please let me know.

**Comment by tsujan** [comment]
Kvantum is a widget style plugin, not a Qt Quick theme.

KDE devs have made `qqc2-desktop-style` for forcing QML apps to use `QStyle` (with many problems and flaws). You need a version of it compatible with Qt6.

Of course, you also need to compile Kvantum against Qt6 too.

**Comment by dalto8** [comment]
Thanks for the quick response.

**Comment by tsujan** [comment]
You're welcome.
