### ISSUE TITLE
Compile error on Debian-testing and Arch | blurhelper.cpp | kwindowsystem_version.h

### ISSUE THREAD

**Issue by DrSky2007** [tsujan/Kvantum#766]
While compiling on Debian-testing I was facing this error:
```
blur/blurhelper.cpp:29:10: fatal error: KF5/kwindowsystem_version.h: No such file or directory
   29 | #include <KF5/kwindowsystem_version.h>
```
I use the repository from Norbert Preining so my KDE-Environment is up to date (Plasma 5.24).

While searching the net, I found a post from Arch AUR, where exact the same error appears: [https://aur.archlinux.org/packages/kvantum-qt5-git](https://aur.archlinux.org/packages/kvantum-qt5-git)

**Comment by DrSky2007** [comment]
Just now the problem was found by the arch-users:

_"They move it to /usr/include/KF5/KWindowSystem/kwindowsystem_version.h. Here the little patch that works"_
```
prepare() {
    sed -i '29s|/|/KWindowSystem/|' ${srcdir}/${_gitname}/Kvantum/style/blur/blurhelper.cpp
}
```

**Comment by tsujan** [comment]
That change in KF5 defeats the purpose of `kwindowsystem_version.h`; it means KF5's version can't be found by a code in a backward-compatible way anymore. Therefore, there's no use to finding it at all.

I'll remove KF5 version finding from Kvantum's code, make it dependent on ≥ 5.82.0 and make a release.

Thanks for reporting!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/96400cc3ad919c4ed274fe5d23c1e2e9ae7daec7. Old distros can't be supported anymore.

Will release 1.0.1 soon.
