### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by hackerkerala** [tsujan/Kvantum#769]
When i put a theme in kvantum. Uts loading the theme but transparency is not working is there any fix ffor that.. Im usubg kde plasma. Refered to google and yt but not working.. Help me out sir.. It is also reported by some of my frnds. They are using the latest version of kvantum manager

**Comment by tsujan** [comment]
Your description of the problem is very poor and lacks basic info — even the title you've chosen isn't relevant. I'm afraid no one can help you because of that.
