### ISSUE TITLE
Kvflatlight text color

### ISSUE THREAD

**Issue by ozky** [tsujan/Kvantum#77]
I have problems with kvflatlight text color in programs like qupzilla it's using wrong text color and makes hard to read things.
![kvflatlight](https://cloud.githubusercontent.com/assets/1551665/14104299/282bacfc-f5ad-11e5-8f4a-47aff350a684.jpg)

**Comment by tsujan** [comment]
That isn't limited to KvFlatLight. I haven't seen a single browser that doesn't have problem with dark themes by default but some, like Firefox, have hidden settings for working around such issues. I don't know about Qupzilla but remember that Rekonq had a nice way out of this (a setting file to load on start-up).

Qupzilla is a good browser indeed. If you search Internet you'll find similar problems (https://chakraos.org/forum/viewtopic.php?id=6296). I think the solution is making a dark theme for it (https://github.com/QupZilla/qupzilla/wiki/Themes) but I haven't tried that.

**Comment by ozky** [comment]
I found bug from qupzilla having same problem,only way to fix is to use own stylesheet in qupzilla.
https://github.com/QupZilla/qupzilla/issues/975

**Comment by tsujan** [comment]
Yes, like Firefox and Rekonq. You should play with various stylesheets, change their keys and values, until you find a solution.

As far as I remember, for Rekonq I used something like this:
````
body,
input, textarea, select {
background-color: #ECECEC;
color: black;
}
````
However, I don't know if Qupzilla understands it.

**Comment by ozky** [comment]
You fixed my problem thanks looks so much better.
![fixed](https://cloud.githubusercontent.com/assets/1551665/14116285/9b5e1838-f5e7-11e5-99f7-947cca30dd0f.jpg)

**Comment by tsujan** [comment]
Could you please tell how you did it? It could be useful to others too.

**Comment by ozky** [comment]
Yes i saved code to .css and loaded it in qupzilla stylesheet settings.
![stylesheet](https://cloud.githubusercontent.com/assets/1551665/14116496/ac80056c-f5e8-11e5-933b-b2db8afcf6b7.jpg)

**Comment by tsujan** [comment]
Thanks! Interesting to see that the same workaround works in Firefox, Rekonq and Qupzilla :)

So, I close this issue.
