### ISSUE TITLE
Kvantum theming

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [tsujan/Kvantum#776]
I would be interested in more integrated theming with KDE. 
While I know that KDE is specific and kvantum is meant to be agnostic, and that it uses a different color system and svgs, I would just really like to be able to theme it. I'm unhappy with many default themes and the base color options don't affect much. As svgs are fancy xml files, perhaps it would be feasable to allow mapping colors to specific colors in the sheet. 
Of course, this still wouldn't connect to KDE. Perhaps I (or someone with more knowledge) could write an auto config editor - however I think it would be nice to allow themes entirely driven by that config.

**Comment by tsujan** [comment]
I'm afraid it will never happen. Kvantum is a Qt style engine, not a KDE app. A "KDE theme" is a totally different concept that is limited to KDE.

**Comment by tsujan** [comment]
As for "color scheme", I've repeatedly explained that:

 1. It's actually a setting for KDE's widget style (Breeze) as well as KDE's decoration style.
 2. SVG elements don't have mere "colors" -- they can have complex gradients. A concept like "color scheme" is too poor for Kvantum.
