### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by SeagullisLearningToCode** [tsujan/Kvantum#778]
I am running Debian 11 Stable with KDE Plasma Ver. 5.20.5 and Qt Version 5.15.2

`cd style/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/something/GHProjects/Kvantum/Kvantum/style/style.pro ) && make -f Makefile 
make[1]: Entering directory '/home/something/GHProjects/Kvantum/Kvantum/style'
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/KF5/KWindowSystem -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o blurhelper.o blur/blurhelper.cpp
blur/blurhelper.cpp: In member function ‘void Kvantum::BlurHelper::update(QWidget*) const’:
blur/blurhelper.cpp:218:39: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  218 |     KWindowEffects::enableBlurBehind (win, true, region);
      |                                       ^~~
      |                                       |
      |                                       QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from blur/blurhelper.cpp:28:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:123:48: note:   initializing argument 1 of ‘void KWindowEffects::enableBlurBehind(WId, bool, const QRegion&)’
  123 | KWINDOWSYSTEM_EXPORT void enableBlurBehind(WId window, bool enable = true, const QRegion &region = QRegion());
      |                                            ~~~~^~~~~~
blur/blurhelper.cpp:229:49: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  229 |       KWindowEffects::enableBackgroundContrast (win, true,
      |                                                 ^~~
      |                                                 |
      |                                                 QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from blur/blurhelper.cpp:28:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:145:56: note:   initializing argument 1 of ‘void KWindowEffects::enableBackgroundContrast(WId, bool, qreal, qreal, qreal, const QRegion&)’
  145 | KWINDOWSYSTEM_EXPORT void enableBackgroundContrast(WId window, bool enable = true, qreal contrast = 1, qreal intensity = 1, qreal saturation = 1, const QRegion &region = QRegion());
      |                                                    ~~~~^~~~~~
blur/blurhelper.cpp: In member function ‘void Kvantum::BlurHelper::clear(QWidget*) const’:
blur/blurhelper.cpp:246:39: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  246 |     KWindowEffects::enableBlurBehind (win, false);
      |                                       ^~~
      |                                       |
      |                                       QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from blur/blurhelper.cpp:28:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:123:48: note:   initializing argument 1 of ‘void KWindowEffects::enableBlurBehind(WId, bool, const QRegion&)’
  123 | KWINDOWSYSTEM_EXPORT void enableBlurBehind(WId window, bool enable = true, const QRegion &region = QRegion());
      |                                            ~~~~^~~~~~
blur/blurhelper.cpp:255:49: error: invalid conversion from ‘QWindow*’ to ‘WId’ {aka ‘long long unsigned int’} [-fpermissive]
  255 |       KWindowEffects::enableBackgroundContrast (win, false);
      |                                                 ^~~
      |                                                 |
      |                                                 QWindow*
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from blur/blurhelper.cpp:28:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:145:56: note:   initializing argument 1 of ‘void KWindowEffects::enableBackgroundContrast(WId, bool, qreal, qreal, qreal, const QRegion&)’
  145 | KWINDOWSYSTEM_EXPORT void enableBackgroundContrast(WId window, bool enable = true, qreal contrast = 1, qreal intensity = 1, qreal saturation = 1, const QRegion &region = QRegion());
      |                                                    ~~~~^~~~~~
make[1]: *** [Makefile:567: blurhelper.o] Error 1
make[1]: Leaving directory '/home/something/GHProjects/Kvantum/Kvantum/style'
make: *** [Makefile:50: sub-style-make_first] Error 2
`

**Comment by tsujan** [comment]
Your KF5WindowSystem (`libkf5windowsystem` in Debian) is too old for this version of Kvantum. If you compiled with `cmake`, the output would inform you about that.

The latest version of Kvantum needs KF5WindowSystem ≥ 5.82.0 (see https://github.com/tsujan/Kvantum/releases/tag/V1.0.1 for the reason). You may be able to compile an older version on Debian 11.

**Comment by tsujan** [comment]
I think version 1.0.0 can be compiled on Debian 11 (but I can't test) because I did my best to support both old and new distros. Unfortunately, the recent changes in KF5WindowSystem made that impossible.
