### ISSUE TITLE
force normal tab use document mode

### ISSUE THREAD

**Issue by alca7raz** [tsujan/Kvantum#781]
I'm using a theme full of blur effect and I like blur effect very much. I found some apps such as systemsettings cannot be blurred. I found tabs in the document mode in the preview are blurred correctly. So can I force all the tabs to use document mode?
This is my systemsettings app.
![Y0410_174427](https://user-images.githubusercontent.com/7345998/162612439-4569ccaa-e315-496c-8f21-867a4606ee13.jpg)
normal tabs
![Y0410_174406](https://user-images.githubusercontent.com/7345998/162612504-61b34f73-5afd-49a5-b4cd-35358a162034.jpg)
tabs in the document mode
![Y0410_174415](https://user-images.githubusercontent.com/7345998/162612465-208eb763-b5a1-4008-a874-5e39de5c8bd9.jpg)

**Comment by tsujan** [comment]
>  I found tabs in the document mode in the preview are blurred correctly. So can I force all the tabs to use document mode?

It depends on `interior.element` of `[TabFrame]` in your theme. If it has translucency, the tab widget will be translucent in the usual mode too. You could either make that interior SVG element completely transparent or just use `interior=false` under `[TabFrame]`.

> I found some apps such as systemsettings cannot be blurred.

systemsettings has many QML-based parts. Read `Theme-Making.pdf` → `A word about QML/Qt Quick`.
