### ISSUE TITLE
Buttons are cropped on every theme

### ISSUE THREAD

**Issue by TheKarion** [tsujan/Kvantum#783]
Custom or built in themes buttons are cropped meaning they jut out of the box
![image](https://user-images.githubusercontent.com/64805993/163481042-bf5748e0-356a-4d80-a6a4-b0ba0981ea27.png)
![image](https://user-images.githubusercontent.com/64805993/163481096-f335b392-74fa-4500-9d03-f80a5411fd65.png)
This is after logging out and logging in rebooting and numerous testing.

**Comment by tsujan** [comment]
Theme-Making.pdf → A word about QML/Qt Quick

**Comment by TheKarion** [comment]
For a long time it wasn't an issue till I got into a new install of EndeavorOS

**Comment by tsujan** [comment]
> For a long time it wasn't an issue

It *is* an issue but, for whatever reason, KDE devs don't want to accept that their `qqc2-desktop-style` can't do an impossible job.

**Comment by TheKarion** [comment]
Is there any hope for them to fix it?

**Comment by TheKarion** [comment]
> > For a long time it wasn't an issue
> 
> It _is_ an issue but, for whatever reason, KDE devs don't want to accept that their `qqc2-desktop-style` can't do an impossible job.

By what I mean is that awhile back I didn't the cropping issue, it was only on my 4th endeavor os install that the bug showed up

**Comment by tsujan** [comment]
I've explained these things in several places. In short:

 * `qqc2-desktop-style` causes an ugly and sometimes wrong styling in QML apps. KDE devs can't fix it. They bring more and more QML apps into KDE. At some point, KDE might transform to "QMLDE".
 * On the top of this problem, several wrong style codes are constantly being added to KDE. They can be fixed but KDE devs show no willingness to do so.
 * Kvantum has lots of codes to circumvent wrong style codes in apps but there's a limit to that. The apps themselves should be fixed.

**Comment by TheKarion** [comment]
Is qqc2-desktop-style required or is it possible to get rid of?

**Comment by tsujan** [comment]
It is required by KDE. Without it, many QML config dialogs and QML apps of KDE will have completely alien looks and feels.

**Comment by NickLion** [comment]
Maybe it's worth to add it to README as `Known (not) issues` section?

It pops up again and again: https://github.com/tsujan/Kvantum/issues/647 https://github.com/tsujan/Kvantum/issues/651 https://github.com/tsujan/Kvantum/issues/721

**Comment by tsujan** [comment]
> Maybe it's worth to add it to README as Known (not) issues section?

Yes, I'd thought about it too.

But there are workarounds in Kvantum for code problems of some apps (like Krita, Kate,...). I like to be informed as soon as those workarounds stop working, due to changes in the codes of the apps in question (like what happened in Krita 5.0.0). Most people don't know what QML or Qt Quick is. So, it's better to let them report issues.

And thanks for the links! I didn't have time to find them.

**Comment by TheKarion** [comment]
Is there anyway I could get involved and try to resolve it? Cause the issue really hurts the look of themes. Is it exclusive to kde plasma?

**Comment by tsujan** [comment]
@TheKarion 
Did you even read the above comments?

**Comment by tsujan** [comment]
→ https://github.com/tsujan/Kvantum/issues/333#issuecomment-459472496

**Comment by TheKarion** [comment]
> @TheKarion Did you even read the above comments?
Hey no need to be rude, I'm trying to understand.

**Comment by tsujan** [comment]
Added a workaround: https://github.com/tsujan/Kvantum/commit/07267784d0f3766efb5377c4b02b7e538b103d79

The commit also shows why I'm reluctant to add such workarounds (search for "// because of a mess in kate5/new KMultiTabBarTab").

**Comment by TheKarion** [comment]
Oh nice. I'm hoping KDE add official support for your application style, cause it's the best one out there for customization

**Comment by tsujan** [comment]
Will release 1.0.2 soon, which includes a collection of new workarounds for LibreOffice and `qqc2-desktop-style`. Hopefully they'll be valid with Qt6 too.

**Comment by TheKarion** [comment]
I threw in a bug report to be another voice so kde might listen to us and help fix the incompatiblity.

**Comment by tsujan** [comment]
> I threw in a bug report to be another voice so kde might listen to us and help fix the incompatiblity.

KDE devs like to believe that `qqc2-desktop-style` solves the QML problem. Obviously, it neither does nor can. So, they turn a blind eye to inconsistencies.

The problem is deeper than QML. Here and there, there are lots of wrong style codes in KDE. `KMultiTabBarTab` (which has nothing to do with QML) is just one example.
