### ISSUE TITLE
Inconsistent Transparency in Menus w/ Every Transparency Enabled Theme

### ISSUE THREAD

**Issue by TheKarion** [tsujan/Kvantum#784]
A persistent issue in any theme with transparency 
![image](https://user-images.githubusercontent.com/64805993/163693409-81ef2a43-845d-46d4-a2cc-6393b89ec2f4.png)
![Screenshot_20220416_173642](https://user-images.githubusercontent.com/64805993/163693417-ca157e15-4585-4ab1-ab05-9ff722dd8cfd.png)

**Comment by tsujan** [comment]
You need to be more specific when opening an issue. I can't read minds.

**Comment by tsujan** [comment]
→ https://github.com/tsujan/Kvantum/issues/333#issuecomment-459472496
