### ISSUE TITLE
Kvantum FC System Settings Manjaro KDE Plasma 5.24

### ISSUE THREAD

**Issue by arghyasinha** [tsujan/Kvantum#789]
Enabling Kvantum version of most themes like LACE, CHERRY, MIYA force closes System Settings. The app System Settings opens normally. However, if I try to open any tab in it, for example, appearance, it force close.
Kvantum is responsible for this because if I enable all other versions of same theme but change kvantum theme to some different working theme like ORCHIS, it works. I am adding links to themes if you need them.

https://github.com/yeyushengfan258/Lace-kde
https://github.com/nullxception/cherry-kde-theme
https://github.com/yeyushengfan258/Miya-kde
https://github.com/vinceliuice/Orchis-kde

**Comment by tsujan** [comment]
> However, if I try to open any tab in it, for example, appearance, it force close.

It crashes. And there's no trace of Kvantum in the backtrace:

```
#0  0x00007f7f474513dd in ?? () from /usr/lib/libQt5Widgets.so.5
#1  0x00007f7f47451a2e in ?? () from /usr/lib/libQt5Widgets.so.5
#2  0x00007f7f4745751b in ?? () from /usr/lib/libQt5Widgets.so.5
#3  0x00007f7f4740ff1e in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007f7f4688e5aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#5  0x00007f7f4740eabf in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007f7f4745f927 in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007f7f474614dc in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007f7f4740b2c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007f7f4688e5aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007f7f46d67fd0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#11 0x00007f7f46d526f5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Gui.so.5
#12 0x00007f7f40ce2f60 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#13 0x00007f7f4454b163 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007f7f445a19e9 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007f7f445486c5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007f7f468da57a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#17 0x00007f7f4688688b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#18 0x00007f7f46891fd7 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#19 0x0000560b1a60cbe8 in ?? ()
#20 0x00007f7f461fd310 in __libc_start_call_main () from /usr/lib/libc.so.6
#21 0x00007f7f461fd3c1 in __libc_start_main_impl () from /usr/lib/libc.so.6
#22 0x0000560b1a60d545 in ?? ()
```

The reason is kinetic scrolling. If you disable it in Kvantum Manager, there will be no crash. As it's explained in the tooltip of its checkbox:

```
Warning: Qt's kinetic scrolling has bugs and may
seriously interfere with other jobs.
```

The bugs are in Qt, not in Kvantum.

Kinetic scrolling shouldn't be enabled by theme makers. Users can enable and enjoy it where it works but, sooner or later, they might encounter a QML-based app (like systemsettings5) that crashes.

**Comment by tsujan** [comment]
Please tell the creator(s) of those themes to disable kinetic scrolling in their themes! You could add a link to this page.

The more people know about this Qt bug, the better. Since no other Qt style has this option, the problem has remained hidden for a long time.

**Comment by tsujan** [comment]
Minutes ago, I added a warning dialog for it to git:

![warning](https://user-images.githubusercontent.com/981076/166863716-675fcfea-7eed-427a-9126-5255dde3a31f.png)

Will release 1.0.2 soon.

**Comment by arghyasinha** [comment]
Thanks a lot for your quick reply. As you pointed out, disabling kinetic scrolling works as intended. I will tell the theme makers about this. Thanks again.
