### ISSUE TITLE
Eggwm window manager

### ISSUE THREAD

**Issue by ozky** [tsujan/Kvantum#79]
I started to use this eggwm qt5 based window manager and need some help to get kvflatlight openbox to eggwm qss style.
https://github.com/xiangzhai/eggwm
[oxygegg.zip](https://github.com/tsujan/Kvantum/files/232021/oxygegg.zip)

**Comment by tsujan** [comment]
I haven't tried eggwm yet. Is it better or, at least, as good as openbox in terms of flexibility and lightness?

**Comment by ozky** [comment]
Yes it's very light and flexibility it's acctually supports wayland too.

**Comment by tsujan** [comment]
> Yes it's very light and flexibility it's acctually supports wayland too.

So, why isn't it developed for 2 years? Is it so complete and bug-free already?

**Comment by ozky** [comment]
I have no idea maybe original developer didn't have time to development it.
Project is looking good we have no too many qt5 window managers right now.

**Comment by tsujan** [comment]
I tried eggwm under Manjaro. Unfortunately, it had only basic functionalities of a wm, and that in a very buggy way. The idea behind is surely good but it isn't developed to a *working* wm. Perhaps someone should take it and make a full-fledged wm out of it. I have no motivation to do so. I think the reason why it isn't developed is that (1) there are already lightweight, stable and very flexible WMs like Openbox and (2) Wayland is comming.

**Comment by ozky** [comment]
Yeah you are very right it's way more better to stick with openbox and wait for lxqt move to kwin/wayland.

**Comment by tsujan** [comment]
Who knows, Openbox might be updated to work with Wayland too. A problem with Wayland is that it's "comming" for years ;) So, I won't be surprised if we stay with X for a long time.

**Comment by mckaygerhard** [comment]
here 2017 and wayland its still comming ka ka ka.. distros still using X as default..

**Comment by tsujan** [comment]
Wayland, systemd and gnome-shell are the bad "inventions" of our time, IMO. Inexperienced developers suddenly think they could change everything but ruin everything instead.
