### ISSUE TITLE
"toolbars" not draggable in QtQuick apps like KDE Discover and KDE system settings

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#792]
I'm not sure what those things are under the hood but they are not draggable with Kvantum AFAIK
![image](https://user-images.githubusercontent.com/45201036/167639275-47f92d25-5875-4c64-9cae-7518ed82fc13.png)

(I'm talking about the horizontal strip that says "Application Style" - which is where a regular toolbar would be in a normal QT application, and by "draggable" I mean you can drag the window by it)

This are is draggable with the Breeze theme. 

Will you consider making this area draggable in Kvantum?

**Comment by tsujan** [comment]
Theme-Making.pdf → A word about QML/Qt Quick

**Comment by tsujan** [comment]
> This are is draggable with the Breeze theme.

Breeze's drag code is very old and has bugs. Kvantum's code was rewritten in 2020  (→ https://bugs.kde.org/show_bug.cgi?id=418891#c7) for Qt ≥ 5.11 and excludes `QQuickWidget`.

**Comment by ripefig** [comment]
Fair enough.
