### ISSUE TITLE
Double click whitespace in toolbars to maximize?

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#793]
Since the toolbars get visually blended into the decoration these days, it would make sense from a user perspective to be able to double click the whitespace in the toolbar to maximize the window. Can this be accommodated, at least as one of the optional "hacks"?

**Comment by tsujan** [comment]
Window maximization is the job of WM (KWin in KDE), not QStyle.

**Comment by ripefig** [comment]
So why is window dragging available in Qstyle?

**Comment by tsujan** [comment]
→ https://doc.qt.io/qt-6/qwindow.html#startSystemMove

**Comment by ripefig** [comment]
`void QWindow::showMaximized()`

But whatever, your project.

**Comment by tsujan** [comment]
Since `QWindow::startSystemMove()` calls the WM interactively, it can be used safely. Methods for maximization, minimization,… aren't safe at all.

Sorry, code explanation is beyond my free time.

**Comment by ripefig** [comment]
QT officially supports client side decorations on X11 and Wayland (for Wayland this _required_), and therefore supports minimization and maximization. Some applications are already using it.

> Sorry, code explanation is beyond my free time.

I wasn't asking.

**Comment by tsujan** [comment]
> for Wayland this required

It seems you haven't logged into a Plasma-Wayland session.

> I wasn't asking.

Good.
