### ISSUE TITLE
Feature Request: Seperator between non-toggled toolbuttons

### ISSUE THREAD

**Issue by simply1233** [tsujan/Kvantum#796]
Recently I've been working on a theme which as connected toolbuttons and I discovered that it is impossible to add a separator between non toggled buttons. The main benefit of a separator would be greater distinction from one toolbutton from another. Here is an example of why I believe this would be a good feature

**Unedited**
![leopardKvantum](https://user-images.githubusercontent.com/51336658/169350036-f2f955e4-aa40-42c6-9b3b-b651c4d86f14.png)

This theme lacks distintion and the toolbar buttons blend together easily

**Edited**
![leopardKvantumEdited](https://user-images.githubusercontent.com/51336658/169350053-d01fe6d3-dde6-4793-b579-31d3de894505.png)

Each button is more distinct thing now.

I hope this is enough for this feature to be added as it already exists in some minor form as a separator between toggled toolbar buttons

**Comment by tsujan** [comment]
You're right; a normal button separator would be nice. And I'd thought about it.

It may sound strange but the main reason I haven't added it is that `button-separator-normal` is already taken by the separator between toggled and non-toggled buttons. There's no other good string, and I strongly avoid backward-incompatible changes. Using `button-separator-normal` was my mistake, which I can't correct now :(

On the other hand, there's no practical drawback. Breeze, Fusion, Oxygen,… and even GTK don't have button separators and no one has had any problem in distinguishing between adjacent tool buttons ;)

Your idea is quite good; sadly, it's too late for its implementation.
