### ISSUE TITLE
Can not compile yefsmisc_cmp.cpp

### ISSUE THREAD

**Issue by ceday** [tsujan/Kvantum#80]
From my Updated archlinux system get errors on 
line 110 of yefsmisc_cmp.cpp:
return UnrollTailLoop<7>::exec(l, 0, lambda, lambda);
cpp msg: UnrollTailLoop was not declared
cpp msg: ::exec not declared
These are are from the Master Download or a git clone as of 5/1/2016.
May need templates for that line to work?

**Comment by tsujan** [comment]
Where has `yefsmisc_cmp.cpp` come from? There isn't such a file in Kvantum.

On an updated Manjoro (which should be like an updated Arch at this time) I see no error.

**Comment by tsujan** [comment]
Inside the `Kvantum` folder (which contains `kvantum.pro`) use these commands for Qt5:
````
qmake && make
sudo make install
make distclean
````
And these for Qt4:
````
qmake-qt4 && make
sudo make intsall
make distclean
````
````

**Comment by tsujan** [comment]
Oh! You'd opened the terminal insdie `yefm` (https://github.com/yede/yefm) instead of Kvantum; hadn't you?
