### ISSUE TITLE
Weird theming inconsistency

### ISSUE THREAD

**Issue by KaspianDev** [tsujan/Kvantum#800]
Hello, I installed kvantum and here is how my apps look (adapta maia theme but applies to all)
![image](https://user-images.githubusercontent.com/34658474/173412739-8d8278ff-e3dd-4ef5-9b30-bff9a70534f8.png)
and that's for all apps

**Comment by tsujan** [comment]
I'm not the creator of "adapta maia". You may want to ask its developer about the problem but, frankly, you need to be much more specific about it.

Here, qBittorrent doesn't have any problem with themes that come with Kvantum:

![qbittorrent](https://user-images.githubusercontent.com/981076/173433209-45529bc6-1f8a-42bd-a9a6-fbb4598deb65.png)

If you see a problem with a theme that come with Kvantum, please first check the Qt6 plugin you've installed.

**Comment by KaspianDev** [comment]
> I'm not the creator of "adapta maia". You may want to ask its developer about the problem but, frankly, you need to be much more specific about it.
> 
> Here, qBittorrent doesn't have any problem with themes that come with Kvantum:
> 
> ![qbittorrent](https://user-images.githubusercontent.com/981076/173433209-45529bc6-1f8a-42bd-a9a6-fbb4598deb65.png)
> 
> If you see a problem with a theme that comes with Kvantum, please first check the Qt6 plugin you've installed.

yea well that happens with all themes

**Comment by tsujan** [comment]
> yea well that happens with all themes

Although the problem isn't in Kvantum (and that's why I closed the issue), I might be able to help you find its cause if you provided more info on how you run a Qt6 app like qBittorrent with Kvantum.

**Comment by tsujan** [comment]
> Now the problem only occurs with Flatpaks

It's very simple: you can expect any kind of problem with things like Flatpak. My advice: https://github.com/tsujan/FeatherPad/issues/563#issuecomment-968125439

**Comment by tsujan** [comment]
> i am using linux for desktop for like week now so i'm not experienced that well.

To get rid of false problems, you could install everything from the repository of your distro. Avoid Flatpak and similar stuffs. Since you use Manjaro, you have access to AUR; so, there's virtually nothing you couldn't make a clean installable package from.

In Linux, re-installation is almost never required. In the 17 years of using Linux, I've never needed to re-install anything. It's an MS Windows myth.

Of course, it'll be a totally different story if you want to join Flatpak testers, who are ready to encounter Flatpak's problems and report them to Flatpak.

**Comment by KaspianDev** [comment]
doesnt flatpak fix security issues tho?

**Comment by KaspianDev** [comment]
By the way i noticed some small theming issues in normal Krusader version
![image](https://user-images.githubusercontent.com/34658474/173561859-b1e47646-4987-4afe-af0e-c2e23bc5da61.png)
these should be more white (as it is in flatpak version)

**Comment by tsujan** [comment]
> doesnt flatpak fix security issues tho?

Which security issues?!

> By the way i noticed some small theming issues in normal Krusader version

Your attached image isn't loaded or, for whatever reason, I can't see it here.

**Comment by tsujan** [comment]
> it isolates apps so they cannot access entire system

In Linux/Unix, the user has no write access to root, and user apps run as user.
