### ISSUE TITLE
Kvantum scales pixmaps in QLabel even though QLabel::hasScaledContents() == false.

### ISSUE THREAD

**Issue by sommerluk** [tsujan/Kvantum#804]
Kvantum scales pixmaps in `QLabel` even though `QLabel::hasScaledContents() == false`.

**Steps to reproduce**
```
QLabel *myLabel = new QLabel();

// The “scaledContents” property is “false” by default:
assert(myLabel->hasScaledContents() == false);

// Load some pixmap with a size that is bigger than myLabel->size():
myLabel->setPixmap(myPixmap);
```

**Actual behaviour**
The pixmap is scaled.

**Expected behaviour**
The pixmap is not scaled.

**Additional information**
- If the `scaledContents` property is `false` and the loaded pixmap _smaller_ than `myLabel->size()` in both, `width()` and `height()`, then Kvantum behaves correctly and does _not_ scale the content. If `width()` is smaller but `height()` is bigger, it does a strange scale, changing only the `height()`.
- If the `scaledContents` property is set to `true`, Kvantum behaves correctly: Is scales the content as expected.
- Issue found on Kvantum version 1.0.1, using Kubuntu 22.04 package.

**Comment by tsujan** [comment]
Yes, Kvantum doesn't let big pixmaps go out of the drawing  rectangle, and this behavior may contradict the `scaledContents` property of `QLabel`.

I think I made it so as a workaround to a bug in old versions of Qt. The bug was fixed later but the workaround didn't have a side effect in other cases, while I failed to see this special case.

Thanks for reporting!

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/c03a03356efbba2570cb35fb7f74b23d6b988c92

Qt5 has a small problem with fractional scale factors, which is fixed in Qt6. But Qt6 still has a tiny problem that isn't visible to most users. Now Kvantum has workarounds for both.

**Comment by sommerluk** [comment]
Thanks a lot for the very fast fix!
