### ISSUE TITLE
a different radio and checkbutton for menuitems

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#81]
Since the size for menu checks/radios is limited to ~13px it would be nice to use a different image for those e.g like:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/15259911/26671d64-1954-11e6-8d2b-2b633479f4af.png)

**Comment by tsujan** [comment]
I'd included the required code several months ago but commented it out because I thought no one needed it. It's time to revive it!

**Comment by tsujan** [comment]
Done! KvGnome and KvGnomeDark have it now.

Just add a set of SVG objects, whose names starts with "menu-" -- see `Theme-Making.pdf` → "Menu Check Boxes and Radio Button"!
