### ISSUE TITLE
icons are painted incorrectly when scaling is enabled

### ISSUE THREAD

**Issue by Kolcha** [tsujan/Kvantum#812]
since 1.0.3 icons in toolbar or menus are painted incorrectly (see attached screenshots) when scaling is enabled (200%) and no `Qt::AA_UseHighDpiPixmaps` is set in application. icons on the buttons on system dialogs (e.g. "Open File Dialog") are also affected. 

master branch at the time of writing (commit 00f7ba8f7c93f7adee93f30c1b19f3f8b5ebc83c) also has the same behavior.

1.0.3, scaling 200%, no `Qt::AA_UseHighDpiPixmaps`, toolbar
![Screenshot_20220725_051258](https://user-images.githubusercontent.com/947647/180693794-e2ae01b7-a729-4464-b81c-f0a2ff11a631.png)

1.0.3, scaling 200%, no `Qt::AA_UseHighDpiPixmaps`, menu
![Screenshot_20220725_051317](https://user-images.githubusercontent.com/947647/180693797-cffcd707-6f8a-4d50-bbae-ede86bfef576.png)

1.0.3, scaling 200%, no `Qt::AA_UseHighDpiPixmaps`, File Dialog
![Screenshot_20220725_051528](https://user-images.githubusercontent.com/947647/180693804-ccdb7532-4f04-46f8-a509-740a6d7f3205.png)

setting `Qt::AA_UseHighDpiPixmaps` fixes the issue, but this is not an option, as so as many Qt/KDE apps doesn't have it, and with Kvantum 1.0.2 and below it seems even no difference regardless flag is set on not.

OS: Debian Unstable, KDE
Qt: 5.15.4
KDE Frameworks: 5.94.0

Kvantum 1.0.3 was installed from official repository, but also the same behavior if compiled from source. 1.0.2 (and few versions below) was compiled from source.

**Comment by tsujan** [comment]
I can't reproduce it with any app or any icon set (SVG- or PNG-based), whether I use KDE systemsettings for global scaling or `QT_SCALE_FACTOR` for app scaling.

If there's some missing info, please provide it, so that I can reproduce it.

**Comment by tsujan** [comment]
> setting Qt::AA_UseHighDpiPixmaps fixes the issue, but this is not an option

Oh, I didn't see this part. Quite conversely, forgetting `Qt::AA_UseHighDpiPixmaps` isn't an option with correct scaling. All KDE and LXQt apps set it and it's the default in Qt6.

**Comment by tsujan** [comment]
Added a commit for the lack of `Qt::AA_UseHighDpiPixmaps`: https://github.com/tsujan/Kvantum/commit/14256c7f503821c0c765805948bc97408321b9af

However, `Qt::AA_UseHighDpiPixmaps` should never be ignored in any Qt5 app; otherwise, icons will be blurry with scaling (they were disproportionate with Kvantum before the above-mentioned commit, because of a very HDPI workaround).

With Qt6, `Qt::AA_UseHighDpiPixmaps` is deprecated because all pixmaps  are HDPI.

**Comment by Kolcha** [comment]
> However, `Qt::AA_UseHighDpiPixmaps` should never be ignored in any Qt5 app;

I know, but unfortunately there are some apps which don't set it still exist (or at least no updated in repos yet)...

> With Qt6, `Qt::AA_UseHighDpiPixmaps` is deprecated because all pixmaps are HDPI.

also know that as Qt enthusiast :) and helped to port some code to Qt 6

thanks for solution, blurry icons are acceptable (and expected) behavior for the apps not aware of HiDPI. the same was in many apps on old macOS 10.9 with first Retina displays. and I have to deal with it in Qt... before 5.6 it was too hard, a lot of things/hacks were implemented on app side or sometimes I even patched Qt...

**Comment by tsujan** [comment]
I don't remember exactly why I added that workaround — it was related to the terrible state of icon engines in old times — but, without your report, I might never notice it, especially with Qt6. Thank you!
