### ISSUE TITLE
Unmatching Icons

### ISSUE THREAD

**Issue by re-hub** [tsujan/Kvantum#815]
I was wondering how to change the icon theme. Mine looks like this:

![Screenshot from 2022-08-10 00-53-12](https://user-images.githubusercontent.com/71829000/183783001-3625465b-1630-4884-ba90-48ac9a3f5d9c.png)

I am using Gnome 42.3.1 on archlinux

I tried changing org > gnome > desktop > interface > icon-theme in dconf editor but even though it is already "Adwaita" without alteration, kde apps do not honour it.

**Comment by tsujan** [comment]
Setting the icon theme isn't Kvantum's job.

To set the icon theme in Qt apps, you need a Qt config tool. There may be one specifically for Gnome (you need to ask Gnome users), but `qt5ct` should work under all non-Qt DEs.
