### ISSUE TITLE
The border of windows doesn't work 

### ISSUE THREAD

**Issue by starsareintherose** [tsujan/Kvantum#816]
I configure the kvantum using [this theme](https://github.com/vinceliuice/Graphite-kde-theme)

and then I found the theme doesn't work with the border, but the select box works, is it kvantum issue or this theme issue?

see also

https://github.com/vinceliuice/Graphite-kde-theme/issues/9

**Comment by tsujan** [comment]
Window borders (aka. decoration) aren't related to Kvantum. They're drawn by the window manager.
