### ISSUE TITLE
Can't get kvantum to respect / apply my colorscheme

### ISSUE THREAD

**Issue by Smart-Helper** [tsujan/Kvantum#818]
- Garuda-Linux
- KDE Plasma 5.25.4
- KVantum 1.0.4-1

I was using the Layan-Solid Kvantum theme for quite a while now and i want to change things up a bit. I found a very nice catppuccin colorscheme for KDE Plasma and applied it. I wanted to have my Layan-Solid-Kvantum-Application-Theme because i really like the minimalism of it. 

However, kvantum will always overwrite the colorscheme of apps that use this global-colorscheme. Apps where i can define what colors i want (GTK apps and konsole for example) aren't affected by that.

https://user-images.githubusercontent.com/38812603/184870563-cb212391-4243-45a1-bd5e-ca4bab7a0b4d.mp4

As you can see here, when i change the colorscheme while Dolphin is open - it will take over that colorscheme perfectly fine. But as soon as i close dolphin and open it again, it will take the "old" kvantum colorscheme.

I already tried to edit the /.config/Kvantum/Layan-solid/Layan-solid.kvconfig file and change the colors there, but it doesn't do anything. I don't know what i'm doing wrong here. 

Please help me out :-)

**Comment by tsujan** [comment]
KDE color schemes belong to KDE settings. Kvantum is a Qt widget style, independent of KDE and its settings. Read Kvantum Manager → Change/Delete Theme

**Comment by Smart-Helper** [comment]
I'm sorry but i don't know what exactly to do with that info.

Accoring to google and pamac, this is the github repo for the Kvantum Manager, i don't know what you want me to read "Kvantum Manager → Change/Delete Theme" sorry.

**Comment by tsujan** [comment]
If you have Kvantum, you should have Kvantum Manager too. Kvantum Manager is the app that can switch Kvantum themes, change them, etc. It's a part of Kvantum.

**Comment by Smart-Helper** [comment]
OH i'm so sorry, yeah since i didn't know that kvantum and kvantum manager are two different things, i said kvantum only in my post. But i mean i use kvantum manager.

So i use the kvantum manager, installed layan-solid, tweaked it as i wanted, but this comes with the colorscheme of that kvantum theme. And i cannot change that; Atleast i don't know how to do it properly as it seems.

**Comment by tsujan** [comment]
This is what you see in that section:

![km](https://user-images.githubusercontent.com/981076/184895109-dbac9b2c-d810-436b-868d-11cc5b1a4c47.png)

It explicitly says that Kvantum is independent of all desktop environments. KDE is a desktop environment. You can't control Kvantum by changing KDE settings.

**Comment by Smart-Helper** [comment]
yes exactly that i use. And i know that i cant change it with KDE Settings. But i also can't change it with the config file.

When i change the colors for example base-color it doesnt do anything

**Comment by Smart-Helper** [comment]
i understand that my post here was kind of misleading. Sorry

**Comment by Smart-Helper** [comment]
Alright, thank you very much.

I crunch through the PDF and i will try to work with those SVG Files. I'll figure it out.

Thanks again!

**Comment by tsujan** [comment]
You're welcome.

Please note that making new Kvantum themes isn't an easy task. It needs practice and patience. That's the cost paid for versatility. However, there are many Kvantum theme makers who create high-quality themes.

**Comment by zeule** [comment]
Breeze icons encode references to color scheme colors into SVG files, perhaps KVantum could do the same?

**Comment by tsujan** [comment]
> Breeze icons encode....

That would be a disaster for Kvantum, because a huge amount of code should be added just to introduce an artificial limitation that Kvantum is free of and doesn't want.

Kvantum is a style that doesn't follow palettes, let alone KDE color schemes. See this warning in Qt doc: https://doc.qt.io/qt-6/qpalette.html#details

**Comment by zeule** [comment]
It's not immediately obvious for me what Kvantum wants, but KDE users want Qt theme engines to follow the KDE color scheme, that's for sure. With QtCurve death we have no alternative to the Breeze engine left, sadly.

**Comment by tsujan** [comment]
> It's not immediately obvious for me what Kvantum wants

To be versatile and DE-independent, while actualizing the potentials of `QStyle` beyond what was done before — definitely not what Breeze aimed at.

> With QtCurve death

Used it many years ago. It was a nice style but still limited to specific shapes.
