### ISSUE TITLE
Guest Window of VirtualBox translucent in Linux Systems, entry "VirtualBoxVM" missing in Opaque apps list

### ISSUE THREAD

**Issue by cb-studi** [tsujan/Kvantum#819]
Hello tsujan, 
Under Manjaro and other OS, the guest window of VirtualBox is almost transparent and unreadable. I found out that the reason for this problem is in the setting within Kvantum Manager that affects the translucent windows in some themes of my main system (Manjaro Xfce)
In the list of apps that should be ignored by the translucency in the selected theme, there is already the entry “VirtualBox”, it can be found under:
Configure active theme → compositing & General look → Translucent windows
As soon as I manually add the entry “VirtualBoxVM” to the Opaque apps list, the guest window looks completely normal again. I therefore think that the entry is missing. Could you please (re)add this entry to the list so that one does not have to do this manually on multiple systems where Kvantum Manager is used? Thank you very much. :)

**Comment by tsujan** [comment]
Hello,

Thanks for caring, but `VirtualBoxVM` is already in the list of excluded windows of the default Kvantum theme. So, all themes will automatically inherit it, unless they have their own lists — which should be the case with the theme you use.

You might want to report this to the creator of the Kvantum theme you use.
