### ISSUE TITLE
Search field in menu not styled

### ISSUE THREAD

**Issue by stefonarch** [tsujan/Kvantum#82]
As title, in every kvantum theme the search field in the menu works but is invisible white.
Latest git version on Arch.

**Comment by tsujan** [comment]
You mean LXQt menu? It's OK here, maybe because the LXQt theme I use doesn't style the menu at all. I'll test the themes that come with LXQt. Thanks for reporting!

**Comment by tsujan** [comment]
Wow! That's a problem in the new version of Frost (LXQt's default theme). The older version is OK. As usual, such problems aren't revealed by non-SVG theme engines. I'll make one or two PRs at LXQt. Thanks for mentioning it!

**Comment by tsujan** [comment]
I preferred not to make a PR but to report the issue with some explanation (https://github.com/lxde/lxqt/issues/1052).

**Comment by stefonarch** [comment]
I forgot to test the other themes, they  are all ok, even   my own themes which do not use (palette) -just because I simple do not understand what's that ;)

**Comment by tsujan** [comment]
Fixing menu titles didn't take time. Download again: https://dl.dropboxusercontent.com/u/7793460/lxqt-panel.qss

If everything is OK now, please tell that at https://github.com/lxde/lxqt/issues/1052. I close this ticket because it wasn't a Kvantum issue.
