### ISSUE TITLE
Kvantum not making windows transparent

### ISSUE THREAD

**Issue by NetRunnerBlackwall** [tsujan/Kvantum#822]
X11 compositor, KDE plasma, Arch OS,

I'm trying to configure transparency on several windows, namely dolphin, but transparency won't take effect. The colors change, the theme does, but no transparency. My application style is kvantum, as are my window decorations, and my colors. 

Disable compositor effects off, disable translucency with non-integer scaling off, global scaling at 100% anyways.

My opaque apps are kaffeine,kmplayer,subtitlecomposer,kdenlive,vlc,smplayer,smplayer2,avidemux,avidemux2_qt4,avidemux3_qt4,avidemux3_qt5,kamoso,QtCreator,VirtualBox,VirtualBoxVM,trojita,dragon,dig

The default ones. Compositor, kwin_x11 is running.

![2022-09-14-014901_1920x1080_scrot](https://user-images.githubusercontent.com/103293327/190107743-1ce999ad-1a92-4508-8d49-70c73f2c561e.png)

**Comment by tsujan** [comment]
If you expected that, by checking "Transparent Dolphin view", Dolphin should get transparent, please read its tooltip. Kvantum Manager also has "Help"  for each option.

For translucency in Dolphin (and other apps that are written in Qt, *not in Qt Quick*), check `Kvantum Manager → Compositing & General Look → Translucent windows` and change `Reduce window opacity by` in addition to checking the above-mentioned option. Then restart Dolphin.

**Comment by tsujan** [comment]
Also, note that some Kvantum themes don't need `Reduce window opacity by` because they already have translucent SVG backgrounds for windows. The theme in your screenshot is an opaque theme without a translucent SVG background. Therefore, translucency should be forced on it by `Reduce window opacity by`. Please read tooltips or context helps.
