### ISSUE TITLE
Size grip doesn't work correctly in high dpi mode

### ISSUE THREAD

**Issue by amezin** [tsujan/Kvantum#83]
With 2x pixel ratio, dragging the size grip immediately doubles the size of the window.

The size should be divided by devicePixelRatio() somewhere, I think

**Comment by tsujan** [comment]
I can't see this problem here, with Qt-5.5.1. On the other hand, QStyle doesn't control resizing.

**Comment by tsujan** [comment]
Oh, I see the problem on my other machine with Qt-5.6.0. It's definitely a Qt bug -- a regression, indeed -- because it happens with Fusion too.

**Comment by amezin** [comment]
Reported: https://bugreports.qt.io/browse/QTBUG-53389
