### ISSUE TITLE
Reversed sorting arrow in KDE Plasma

### ISSUE THREAD

**Issue by Creepercdn** [tsujan/Kvantum#835]
Reproducible: Always

Steps to Reproduce:
1. Open Dolphin (or another app with sorting capabilities)
2. Sort files ascending
3. The arrow of the interface is pointing down

See other:
https://bugs.kde.org/show_bug.cgi?id=356305
https://bugs.kde.org/show_bug.cgi?id=297807

**Comment by tsujan** [comment]
Why did you report it here? It's a bug in the Breeze widget style; it doesn't happen in Kvantum.
