### ISSUE TITLE
No margins in Dolphin side pane

### ISSUE THREAD

**Issue by doncsugar** [tsujan/Kvantum#840]
Hey Pedram,

I noticed that Dolphin seems to have lost its margins for `itemview` (?) elements under Kvantum. In Breeze, there appears to be space between the item and the border of the window, but with Kvantum, it now meets directly with the border of the window.

![image](https://user-images.githubusercontent.com/46570709/204179452-18547ea7-db0a-4f0a-92a9-33025e87b75a.png)

Breeze appears to have a slight 2px margin: 
![image](https://user-images.githubusercontent.com/46570709/204179962-4968b179-e975-418b-af25-b44250c84bad.png)

Can anything done about this?

**Comment by tsujan** [comment]
> I noticed that Dolphin seems to have lost its margins for itemview (?)

Yes, it had real margins before.

> In Breeze, there appears to be space between the item and the border of the window

That may be a style-specific code (which is a bad thing in KDE) but not a real margin. I don't have time or motivation to search for the cause in Dolphin's code, but here are some proofs:

With Fusion:

![fusion](https://user-images.githubusercontent.com/981076/204189930-6f1cd3b7-28ee-4851-8e0a-32b83382b65a.png)

With Qt's GTK2 style:

![gtk2](https://user-images.githubusercontent.com/981076/204189959-821f5c60-2320-4c1c-984e-211b5f2459f4.png)

With QtCurve:

![qtcurve](https://user-images.githubusercontent.com/981076/204189979-7e8ec359-9e13-40be-82d1-504883f02ad4.png)
