### ISSUE TITLE
Enable Qt6 build of apps.

### ISSUE THREAD

**Issue by KottV** [tsujan/Kvantum#841]
Hi,

`kvantummanager` and `kvantumpreview` can be compiled with Qt6 but are strictly disabled. Is this intentional and temporary for now?

**Comment by tsujan** [comment]
> Is this intentional and temporary for now?

Yes.

I'll make Qt6 the default target of compilation when the stable version of the biggest Qt-based DE — namely, KDE — is made based on Qt6, because a full port will need KF6.
