### ISSUE TITLE
clear button in lineedit ignores frame padding...

### ISSUE THREAD

**Issue by Nevro** [tsujan/Kvantum#843]
![scr](https://user-images.githubusercontent.com/2953887/208028169-61fb547c-6a4d-4e92-89a2-1a21980ee83c.png)

```
[LineEdit]
inherits=PanelButtonCommand
frame=true
frame.element=lineedit
frame.top=3
frame.bottom=3
frame.left=14
frame.right=14
frame.expansion=6
interior=true
interior.element=lineedit
text.iconspacing=8
text.margin=true
text.margin.left=0
text.margin.right=0
min_width=0
```

Like title says, clear button in lineedit ignores frame padding!  Also content size are false calculated?
Some stuff in this screenshot are patched, but i am total Qt/C++ rookie and i have problem with this one! I'm learning with your code :)

I try set geometry on associated "QLineEditIconButton" widget of  "_q_qlineeditclearaction", but it doesn't move! :)

**Comment by tsujan** [comment]
It's drawn (and animated) by Qt itself, not by Kvantum. Actually it was terrible in older versions of Qt. They made it much better after I opened https://bugreports.qt.io/browse/QTBUG-65627

Kvantum tries to force its parameters on Qt — Qt doesn't have most of them — and that's not possible on all occasions.

**Comment by Nevro** [comment]
Ok. But anyway, this can be for sure somehow patched! Problem here is only in x position of icon.

**Comment by tsujan** [comment]
> this can be for sure somehow patched

No, it can't. Its parameters are hard-coded in `QLineEditPrivate::SideWidgetParameters()`.

**Comment by Nevro** [comment]
![scr1](https://user-images.githubusercontent.com/2953887/208109786-c69b5878-464c-402f-afa4-ad593c2f97f6.png)

Done! Actually I was on right path..
