### ISSUE TITLE
feature: add "interior.element.fullscreen" to the [Window]

### ISSUE THREAD

**Issue by Brayozin** [tsujan/Kvantum#847]
I want to make an rounded corner in my window element, but i don't want that it stays rounded in fullscreen mode. Sorry if already exists something that make this possible, but i didn't find anything

**Comment by tsujan** [comment]
Corners belong to the frame, not the interior. However, Kvantum doesn't and can\t draw any frame for whole windows. The frame of a window is called its "decoration" and is drawn by the window manager (KWi in KDE, xfwm4 in Xfce, etc.) and its themes.
