### ISSUE TITLE
When will QT6 be available on Flatpak?

### ISSUE THREAD

**Issue by linlinxza** [tsujan/Kvantum#849]
Some apps I use are using QT6. So, I am curious when QT6 of Kvantum will come to Flatpak. Is there any plan for this?

**Comment by tsujan** [comment]
I don't make binaries or package Kvantum. Packaging is done downstream.

**Comment by linlinxza** [comment]
Can you refer me to the people manage packing then?

**Comment by tsujan** [comment]
I have no contact with them.

**Comment by linlinxza** [comment]
Well, that's very helpful.
