### ISSUE TITLE
Question:  Column Sizing Issue (Demonstrated with transmission-qt)

### ISSUE THREAD

**Issue by prg318** [tsujan/Kvantum#854]
Hi,

I'm not certain whether this is a kvantum issue or not, but I wanted to start a discussion to to get some ideas.
The issue is that when kvantum is used, the "Open Torrent" dialog in transmission-qt will have an extremely narrow "File" column - to the point of where it can't be read.
In addition, as soon as the window is resized, the column reverts back to the smallest possible size.
This does not occur with any other QT5 theme that I've used.
I've also tried fiddling with all the options in Kvantum Manager and used all the themes I have and the issue always occurs.
I'm not using any qt5 stylesheets or anything.

I know this issue is a little difficult to explain, so I've attached a screencast with audio to demonstrate the issue (apologies for the audio volume)

https://user-images.githubusercontent.com/549291/218151231-5c2e413f-c02f-442e-a839-a5fbdcc5cd3a.mp4

edit: there is audio in this video; if your browser has trouble with it feel free to open the direct video link in a video player like vlc or mpv (`https://user-images.githubusercontent.com/549291/218151231-5c2e413f-c02f-442e-a839-a5fbdcc5cd3a.mp4`)

I would love any thoughts anyone might have on why this might be happening.  Kvantum is my absolute favorite QT style solution, but I seem to have issues with this one specific application.

(Followup question; unrelated to the issue):  Is there a way to override the QT theme for a certain app?  So that kvantum could be configured systemwide, but a problematic application could be configured (through a shell script or something) to use another QT theme?  EDIT:  Yes, you can use the `QT_STYLE_OVERRIDE` environment variable

FWIW:  I'm using transmission-qt 3.00 on arch linux 64 on KDE.  But I've had the same issue on every other WM that i've tried and qt5ct.  Issue also exists when selecting "kvantum" as a theme in KDE and bypassing qt5ct

**Comment by tsujan** [comment]
Thanks for telling me about it!

Actually, the problem is in transmission-qt: it gives an enormous size to that item-view, and Qt shrinks it. The problem is revealed only by Kvantum because other styles skip it by copying `QCommonStyle` in this case.

Anyway, I've added a workaround in https://github.com/tsujan/Kvantum/commit/f64a34788bf4989578cd98fcc8329d05efdad57f for Kvantum to skip the issue like other styles do (I tested it with transmission-qt).

Will release 1.0.9 soon.

**Comment by prg318** [comment]
Just tested this and successfully works around transmission-qt's suspect item-view code.
Kvantum 1.0.9-git works with both transmission-qt 3.00 (Qt5) and transmission-4.00 (Qt6).
Thank you so much!  This was a huge annoyance for me!  Cheers!

**Comment by tsujan** [comment]
Thanks for the confirmation!

I released 1.0.9 just now (because of a regression in 1.0.8).
