### ISSUE TITLE
Will there be Kvantum for Flatpak apps using Qt6?

### ISSUE THREAD

**Issue by linlinxza** [tsujan/Kvantum#859]
Will there be Kvantum for Flatpak apps using Qt6? It would be great if there was.

**Comment by tsujan** [comment]
Duplicate of https://github.com/tsujan/Kvantum/issues/849 and https://github.com/tsujan/Kvantum/issues/786

**Comment by linlinxza** [comment]
Here: https://github.com/flatpak

Communicate with each other. Please.

**Comment by tsujan** [comment]
Oh, I didn't notice that you had opened https://github.com/tsujan/Kvantum/issues/849. Please don't do it again. Instead, you could search Google to understand the difference between "upstream" and "downstream".
