### ISSUE TITLE
A way to disable/modify the pressed child-displacement for pushbuttons

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#86]
It would be nice if we could modify this(eg disable the horiz displacement)

description here:
https://developer.gnome.org/gtk2/stable/GtkButton.html#GtkButton--s-child-displacement-x

edit: this one:

![vokoscreen-2016-05-22_20-29-10](https://cloud.githubusercontent.com/assets/3780774/15455678/fd7667de-205b-11e6-939e-a32365f38f73.gif)

**Comment by tsujan** [comment]
The implementation would be easy but I'm worried about too many unimportant General settings.

**Comment by sixsixfive** [comment]
>unimportant General settings.

its not, it will fix the current inconsistent situation that the displacement is displayed for pushbuttons but not for comboboxes and toolbuttons

**Comment by tsujan** [comment]
> it will fix the current inconsistent situation that the displacement is displayed for pushbuttons but not for comboboxes and toolbuttons

I think Qt devs would say (and I couldn't disagree with them) that it isn't about inconsistency but about distinguishing between push-buttons and tool-buttons visually. But OK, I'll add a key for disabling it -- it'll be according to the whole spirit of Kvantum, namely super-customizability ;)

**Comment by tsujan** [comment]
Done!

See `Kvantum Manager → Configure Active Theme → Miscellaneous → Shift push-button contents`. The new key is `button_contents_shift` under the General section.

**Comment by sixsixfive** [comment]
thx, ;)
