### ISSUE TITLE
no instant update of windows

### ISSUE THREAD

**Issue by slynobody** [tsujan/Kvantum#861]
when using "kvantummanager --set XYZ" the kvantum-theme does indeed change to XYZ, great.
but only for new windows.
old stay rendered in the old theme.
how do i refresh them (without complete restarting according applications)?

currently you have to restart each application (and if you changed plasma-themes too, you sometimes have to even replace everything, giving a hugh mess at least memorywise (not to mention the picture of the process itself).

Could you please supply a more elegant solution? Thank you!

**Comment by tsujan** [comment]
Kvantum is a DE-independent style plugin. It can never make apps see the new settings on the fly. Apps are controlled by the platform integration.

**Comment by Nevro** [comment]
If you use `qt5ct`, just touch configuration file..
```
kvantummanager --set <themename>
touch ~/.config/qt5ct/qt5ct.conf
```
