### ISSUE TITLE
Kvantum is not installed on your system (Kvantum style)

### ISSUE THREAD

**Issue by paulcarroty** [tsujan/Kvantum#865]
Got the error on `kvantummanager`:
```
Kvantum is not installed on your system.
Please first install the Kvantum style plugin!
```
Installed with `prefix=/opt`, the `kvantumpreview` works and `qt6ct` is able to pick the Kvantum theme. Environment - GNOME 42 on Wayland.

[strace.log](https://github.com/tsujan/Kvantum/files/11052842/strace.log)

**Comment by paulcarroty** [comment]
Ohh, thanks.

**Comment by tsujan** [comment]
There's something I don't understand — or, perhaps, have misunderstood. Even if you use `prefix=/opt`, `libkvantum.so` should be installed in Qt's plugin install directory, and so, recognized. Where is `ibkvantum.so` in your case?

**Comment by paulcarroty** [comment]
`libkvantum.so` is in /opt and the Qt's plugin path is fixed with `QT_PLUGIN_PATH` environment variable.

**Comment by tsujan** [comment]
Thanks! That explains why the plugin isn't seen by Qt.

I think if you run `kvantummanager` after exporting `QT_PLUGIN_PATH` to the same place in a terminal emulator, it'll start (exporting it globally might have serious side effects).

**Comment by paulcarroty** [comment]
Nope, same error, with globally and locally `QT_PLUGIN_PATH`.

**Comment by tsujan** [comment]
Strange! Qt doc explains it here: https://doc.qt.io/qt-6/deployment-plugins.html.

If that EV sets the plugin path, then [`QStyleFactory::keys()`](https://doc.qt.io/qt-6/qstylefactory.html#keys) should see it, while your test shows that `QStyleFactory` doesn't consult `QT_PLUGIN_PATH`. That may be an inconsistency (or bug) in Qt.

Kvantum Manager needs `QStyleFactory::keys()` to check if Kvantum is installed as a Qt style plugin. because it should be styled only by Kvantum.

**Comment by paulcarroty** [comment]
Yeah:

> For example, on Windows, if the application is in C:\Program Files\MyApp and it has a style plugin, Qt looks in C:\Program Files\MyApp\styles.

I will test the next ways:

- `libkvantum.so` symlink in `/usr` /to `/opt`
-  edit plugin paths in `qt.conf`
- qt5 build

**Comment by paulcarroty** [comment]
Update: the `libkvantum.so` symlink and `qt.conf` both failed, but the **q5 build works out the box**, with local or global `QT_PLUGIN_PATH`.

**Comment by tsujan** [comment]
> q5 build works out the box

So, there may be a regression in Qt6. The documentation is the same.

**Comment by paulcarroty** [comment]
Reported to https://bugreports.qt.io/browse/QTBUG-112493

**Comment by tsujan** [comment]
Do you have the Qt5 plugin *alongside* the Qt6 one? Kvantum Manager is compiled against Qt5 by default.

In the above discussion, I supposed that you somehow enforced a Qt6 compilation for Kvantum Manager (that's possible with `qmake`). If not, and if you don't have the Qt5 plugin, there is no bug in Qt6 in this regard.

**Comment by paulcarroty** [comment]
> Do you have the Qt5 plugin?

Yeah, just checked it to be sure.

> you somehow enforced a Qt6 compilation for Kvantum Manager (that's possible with qmake)

[Yes](https://github.com/clearfraction/kvantum/blob/qt6/kvantum.spec#L55).

**Comment by paulcarroty** [comment]
It happened 'cause this command failed silently:

```
DESTDIR=%{buildroot} cmake --install build6
```

Fixed by 

```
install -Dm644 build6/style/libkvantum.so %{buildroot}/usr/lib64/qt6/plugins/styles/libkvantum.so
```
