### ISSUE TITLE
impossible to compile preview/manager as qt6

### ISSUE THREAD

**Issue by nekopsykose** [tsujan/Kvantum#870]
the root cmakelists.txt has:  

```cmake
if(NOT ENABLE_QT4)
  if(ENABLE_QT5)
    add_subdirectory(kvantumpreview)
    add_subdirectory(kvantummanager)
    add_subdirectory(themes)
  endif()
endif()
```

this only adds the preview/manager with qt5. then, they have:  

```cmake
if(NOT ENABLE_QT5)
  set(QT_VERSION_MAJOR 6)
  find_package(Qt6 "${QT6_MINIMUM_VERSION}" REQUIRED COMPONENTS Core Gui Widgets Svg)
else()
  set(QT_VERSION_MAJOR 5)
  find_package(Qt5 "${QT5_MINIMUM_VERSION}" REQUIRED COMPONENTS Core Gui Widgets Svg)
endif()
```

qt6 enablement when qt5 is disabled.  

it would be nice if it was possible to build them as qt6 (maybe this is intentional as it's not supported anyway?)

**Comment by tsujan** [comment]
That's intentional. Distros may want to create a package with both Qt6 and Qt5 plugins, as Arch does. The binaries should be compiled only with one version to prevent a conflict. Qt5 will take the priority until Qt6 becomes the default version in important distros.

**Comment by tsujan** [comment]
BTW, until then, you could issue a `qmake6 && make` inside those folders to have Qt6 binaries (depending on your distro, you might need to put the full patch of `qmake6` there). Kvantum is my only program that still supports `qmake` alongside `cmake`.
