### ISSUE TITLE
Allow building only for Qt6

### ISSUE THREAD

**Issue by RushingAlien** [tsujan/Kvantum#875]
Currently it is impossible or difficult to build Kvantum against the `org.kde.Platform//6.4` runtime, which only hosts Qt6, Qt5 is not available in this runtime. This makes kvantum impossible to apply to Flatpak Qt6 apps. https://github.com/flathub/org.kde.KStyle.Kvantum/issues/16

**Comment by tsujan** [comment]
→  https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md#with-cmake →  "When Qt6 becomes...."
→ https://github.com/tsujan/Kvantum/issues/870#issuecomment-1489464883

**Comment by RushingAlien** [comment]
I got it to build, thank you

**Comment by tsujan** [comment]
> I got it to build

Good.

I'll prioritize the compilation against Qt6 when Qt6 becomes the default version of Qt in Arch Stable *at least*. It's too soon now, although Kvantum has supported Qt6 since 2021.
