### ISSUE TITLE
Option to always show keyboard accelerators (ie: without needing to press Alt key)

### ISSUE THREAD

**Issue by volt4ire** [tsujan/Kvantum#876]
Would you consider adding an option to always show the application shortcut underlines, in addition to the current option of "Underline shortcuts with Alt"?  This is currently offered in similar projects such as Klassy and Breeze (see screenshot) and is the only thing keeping me from switching to Kvantum. Thanks so much!

![image](https://user-images.githubusercontent.com/8772017/234013970-4e84351f-270b-4955-aa6f-25ddf9f82829.png)

**Comment by tsujan** [comment]
Sorry, no. Their removal was intentional; they were too ugly for Kvantum.
