### ISSUE TITLE
YaST modules are not transparent

### ISSUE THREAD

**Issue by hifinerd** [tsujan/Kvantum#878]
I have set root's Qt and Kvantum theme correctly, as opening dolphin as root shows transparency correctly, and the base YaST launcher is transparent, but any modules loaded by YaST are not. I am using openSUSE Tumbleweed.
![image](https://github.com/tsujan/Kvantum/assets/69434858/1211294a-7bf3-4675-81b8-216dc97df69a)
![image](https://github.com/tsujan/Kvantum/assets/69434858/de64acfb-c264-4ff4-9b7b-a4d1bea99658)

**Comment by tsujan** [comment]
I don't have OpenSUSE or YaST, and the info you gave was minimal. but there's more than one possibility:

  * YaST may not be a Qt app;
  * It's a Qt app but written in QML;
  * It's a Qt app written with Qt widgets but with a hard-coded style;
  * It doesn't meet the conditions required for translucency (several `if`s in the code);
  * etc.

Anyway, Kvantum doesn't make an exception for YaST specifically.

**Comment by NickLion** [comment]
@hifinerd how have you set root's theme?

**Comment by tsujan** [comment]
Yes, that's another possibility: different configurations for root and user themes.

**Comment by hifinerd** [comment]
> @hifinerd how have you set root's theme?
I used `kdesu kvantummanager` to install the theme for root, and used `pkexec env "DISPLAY=$DISPLAY" "XAUTHORITY=$XAUTHORITY" "QT_QPA_PLATFORMTHEME=kde" systemsettings` to apply the Kvantum theme for root in Application Theme, same as a regular user.

**Comment by tsujan** [comment]
You could do a very simple test:

Run Kvantum Manager with root privileges. If it isn't translucent, there are two possibilities:

 1. Translucency isn't enabled in the root theme, in which case you could enable it with the root Kvantum Manager; or
 2. Something is wrong with KDE's root privilege handling.

Conversely, if the root Kvantum Manager is translucent, then YaST doesn't satisfy the conditions for translucency.

Under LXQt and with KWin, root Qt apps can be translucent when styled by Kvantum. LXQt uses `lxqt-sudo` to give root privileges.

**Comment by hifinerd** [comment]
When using `kdesu` to launch Kvantum Manager as root, it appears as transparent as expected.

**Comment by NickLion** [comment]
@hifinerd what theme are you using? I'm trying to reproduce it.

**Comment by hifinerd** [comment]
[FlatBlur-Blue.](https://store.kde.org/p/1326672/)

**Comment by tsujan** [comment]
There are many conditions in those parts of the code that deal with translucency, but yes, the important ones are in the function `setSurfaceFormat()`. Most apps pass have all requirements; some don't. Moreover, the conditions are necessary but cannot be sufficient; that's why there is an opaque list.

**Comment by NickLion** [comment]
So far, no luck. It sets QSS but playing around `/usr/share/YaST2/theme/current/wizard/*.qss` didn't changed a lot. It seems there are some extra QSS as background+color seems changed even with empty files.

**Comment by tsujan** [comment]
> So far, no luck. It sets QSS

If an app uses stylesheet for the background of its main window, it should be made translucent by its own code; Kvantum doesn't try to make it translucent: https://github.com/tsujan/Kvantum/blob/b50ad35274fd8fc132ccc45652ab411107471ef9/Kvantum/style/Kvantum.cpp#L13559-L13562C16
