### ISSUE TITLE
Insufficient text contrast in Audiotube (Kirigami Application)

### ISSUE THREAD

**Issue by JuniorSuperTux** [tsujan/Kvantum#880]
The title (Nowplaying section) should be displayed like right. Left is Kvantum.

![20230513_14h16m44s_grim](https://github.com/tsujan/Kvantum/assets/65844719/deba87e5-9ed1-4464-85fc-20025cce8e57)

**Comment by tsujan** [comment]
You may want to report it to the developers of that app.

**Comment by JuniorSuperTux** [comment]
Btw just a question, is this meant to be used independently (setting ``QT_QPA_PLATFORMTHEME`` to ``Kvantum``), or used with stuff like qt5ct? Because in the right instance I'm running it with [this patched qt5ct](https://aur.archlinux.org/packages/qt5ct-kde) using the Kvantum theme, where Kirigami apps themes just fine.

**Comment by tsujan** [comment]
When it comes to QML, there can be various causes: Kirigami itself, qqc2-desktop-style (which should be used with QML apps), developer's mistakes (not considering foreground color when setting a background color and vice versa; happens without QML too), not applying a proper KDE color scheme (user's mistake),...

> I'm running it with this patched qt5ct...

Under KDE, QML apps are styled by qqc2-desktop-style; it tries to use apply the Qt style to QML apps as far as possible, and it makes use of the KDE color scheme. `qt5ct` should not be used inside KDE; it would interfere with KDE's Qt plugin.

But if you're outside KDE, yes, you need `qt5ct`. Then I can't tell how QML apps might look...

**Comment by JuniorSuperTux** [comment]
Thanks for the explanation
