### ISSUE TITLE
Scribus font selection drop down menus are garbled when using Kvantum themes

### ISSUE THREAD

**Issue by shanesemler** [tsujan/Kvantum#885]
Scribus font selection drop down menus are garbled when using Kvantum themes. This doesn't happen when using the default QT [themes. Here is a screenshot: [https://i.postimg.cc/Gm1BFPJq/Scribus-Kvantum-Bug.jpg](url)

**Comment by tsujan** [comment]
This isn't a bug in Kvantum but a bug *revealed* by Kvantum: no other style sets `SH_ComboBox_Popup` to `true` for all combo-boxes. The bug may be in Scribus's `fontcombo.cpp` → `FontFamilyDelegate::paint`. I have neither the time nor the motivation to dig into others' codes.

As a workaround, you could uncheck Kvantum Manager → Configure Active Theme → Miscellaneous → Combo popup as menu.
