### ISSUE TITLE
Background preview Plasma theme on Plasma 5.7

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#89]
On System Settings (module Plasma theme) background preview not apply kvantum background color
![screenshot_20160708_111449](https://cloud.githubusercontent.com/assets/8083855/16681460/7592adac-44fd-11e6-9e0f-5aaa68ca9260.png)
Also on Look and Feel this too:
![screenshot_20160708_111728](https://cloud.githubusercontent.com/assets/8083855/16681471/92c95696-44fd-11e6-88dd-32ba6b7ad2e0.png)
kvantum 0.9.8

**Comment by tsujan** [comment]
Unfortunately, those KDE settings are misleading. `System Settings → Workspace Theme → Look and Feel` *forces Breeze on both widget style and color scheme*. In other words, if you use that setting, Breeze will be activated instead of Kvantum.

Kvantum is independent of KDE. You should first select it in `System Settings → Application Style → Widget Style` and then select a color scheme corresponding to the Kvantum theme you use in `System Settings → Color`.

This is also explained in `Kvantum Manager → Change/Delete Theme`.

**Comment by varlesh** [comment]
No, you not understand me. On System Settings use kvantum engine for all (Qt4/Qt5),  but not fully - because on preview background always WHITE.
![screenshot_20160708_171316](https://cloud.githubusercontent.com/assets/8083855/16690215/939b2694-452f-11e6-9cd8-f2701a541f30.png)

**Comment by tsujan** [comment]
In your first screenshots, you'd used the *Breeze widget style* with a dark color scheme and yet those backgrounds are white. In the following scrreenshot, I've also used the Breeze widget style with the Breeze Dark color scheme and there are white backgrounds again:

![2016-07-08-20 01 37-scrot](https://cloud.githubusercontent.com/assets/981076/16692779/9b9838f6-4547-11e6-8982-cf54ec7260b4.png)

Such problems belong to QML, neither to Kvantum nor to Breeze. Those widgets are written in QML and QML cannot use the full potential of Qt's styling yet.

**Comment by varlesh** [comment]
first screenshots - it's kvantum (my theme)/ OK, it's KDE bug...

**Comment by tsujan** [comment]
> first screenshots - it's kvantum (my theme)

Oh, sorry! I didn't notice that.

> OK, it's KDE bug...

Actually, it's a QML bug. Why KDE uses it, I don't know. Many people say good things about QML; personally, I dislike it ;)

**Comment by tsujan** [comment]
Your report made me remember that I'd included a workaround for QML menus in Kvantum. This screenshot is taken with Kvantum:

![2016-07-08-22 00 33-scrot](https://cloud.githubusercontent.com/assets/981076/16695986/fb794cd2-4557-11e6-8e50-f855232537ef.png)

Unlike with Breeze, the menu isn't white here (although it's obvious that it isn't an ordinary menu).

Maybe I could find a workaround for those item-views too. So, I reopen this issue.

**Comment by tsujan** [comment]
Unfortunately, unlike the case of QML popups, those white backgrounds seem to be hard-coded. So, no workaround seems possible :(

**Comment by varlesh** [comment]
Ok :(
