### ISSUE TITLE
qt6 applications doesn't work with kvantum

### ISSUE THREAD

**Issue by hsnfirdaus** [tsujan/Kvantum#891]
I'm running under Fedora 38 With GNOME 44.3 Wayland.

Kvantum does work in qt5 application (like vlc).
But apps doesn't detected kvantum in qt6 application like qt6ct or qbittorrent:

```
QApplication: invalid style override 'kvantum-dark' passed, ignoring it.
	Available styles: HighContrastInverse, HighContrast, Adwaita-HighContrastInverse, Adwaita-HighContrast, Adwaita-Dark, Adwaita, Windows, Fusion
```
Tried kvantum from official fedora repo, also try build & install manual from master branch using `cmake .. -DENABLE_QT5=OFF`. Same result, kvantum or kvantum-dark doesn't detected.

**Comment by tsujan** [comment]
First, Kvantum should be compiled against Qt6. The option `-DENABLE_QT5=OFF` does it, as you already know.

Second, you need a Qt6 style plugin to activate Qt6 Kvantum. As far as I know, only the Qt6 branch of LXQt and `qt6ct` provide such plugins. The last time I checked, KDE didn't.
