### ISSUE TITLE
Theming Mechanism ?

### ISSUE THREAD

**Issue by capecrusader-121** [tsujan/Kvantum#894]
Hey there @tsujan  can you take some time to explain me how does kvantum actually theme apps, i mean from which folder or location does other apps or system settings read kvantum configs ?
Is it ~/.config/Kvantum ? and if yes is this uniform for both kde or lxqt ?

**Comment by tsujan** [comment]
Explaining how a style plugin works is beyond my free time. You may want to consult Q doc for that.

Kvantum comes with a comprehensive documentation: https://github.com/tsujan/Kvantum/tree/master/Kvantum/doc
