### ISSUE TITLE
Kvantum Breaks KDE Squash Desktop Effect

### ISSUE THREAD

**Issue by NightBright199** [tsujan/Kvantum#922]
Simply, KDE doesn't play the animation anymore after I install kvantum and yes I enabled respect current DE

**Comment by NightBright199** [comment]
Huh it fixed itself somehow by removing all the panels and readding it again

**Comment by NightBright199** [comment]
Turns out KDE's WINDOW LIST is the PROBLEM ALL THE TIME :sob:

**Comment by tsujan** [comment]
Kvantum has nothing to do with KDE animations — as you've already known.
