### ISSUE TITLE
Possible to implement custom color for destructive buttons a la libadwaita?

### ISSUE THREAD

**Issue by developer91234** [tsujan/Kvantum#927]
e.g. this "discard" button:

![image](https://github.com/tsujan/Kvantum/assets/43324854/5ab892fe-e183-4d9c-9712-e0a6a91efd3f)

Suggested button style is already possible as far as I am aware.

**Comment by tsujan** [comment]
Not impossible, but I don't intend to make the code or styling more complicated than it is, especially when the code has proven to be fully stable in spite of its complexity.
