### ISSUE TITLE
Text color on first start instead of highlighting text color

### ISSUE THREAD

**Issue by avnibilgin** [tsujan/Kvantum#937]
Kvantum-Theme sets the text color when first started dolphin in "Places" to the general "text.color" and not to the highlighted text color even though it highlights the current folder. Only when you click on it again will the text color change to the highlighted text color.

First started:
![grafik](https://github.com/tsujan/Kvantum/assets/46962320/744c5031-b36b-49c7-af70-b6cb4aa61b6a)

if I click on it again:
![grafik](https://github.com/tsujan/Kvantum/assets/46962320/91150890-e4f6-45ec-aa2b-ab0fc27a677f)

**Comment by tsujan** [comment]
That's an old Dolphin bug, which probably isn't going to be fixed soon because KDE devs focus only on Breeze.
