### ISSUE TITLE
E: Unable to locate package qt6-style-kvantum-themes

### ISSUE THREAD

**Issue by interconnectedMe** [tsujan/Kvantum#956]
Hello,

I am trying to install on KDE Neon, Plasma 6, Wayland.

I've followed this:

"In Ubuntu, you can install Kvantum directly with:

sudo add-apt-repository ppa:papirus/papirus
sudo apt update
sudo apt install qt6-style-kvantum qt6-style-kvantum-themes"

After the 3rd sudo line
"sudo apt install qt6-style-kvantum qt6-style-kvantum-themes"

I got 
"E: Unable to locate package qt6-style-kvantum-themes" 

I tried separately
"sudo apt install qt6-style-kvantum"
entered 'Y' when prompted, and no errors.

"sudo apt install qt6-style-kvantum-themes"
this then outputs
"E: Unable to locate package qt6-style-kvantum-themes"

So I think I'm a bit stuck, or I've missed something maybe?
(new KDE user)

If any other information would be helpful just let me know,
Regards
DR.

About this system:

Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.5.0-25-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 15.6 GiB of RAM
Graphics Processor: llvmpipe
Manufacturer: ASUS
Product Name: All Series

**Comment by tsujan** [comment]
Here is where Kvantum is developed. Packaging is done downstream, not by me or contributors whose works are merged here. Please report packaging problems to the package maintainers of your distro.

However, you might want to wait until a stable version of kwindowsystem V6 comes to their distros; not everyone has it yet. My last commits to git are mainly for those who can compile Kvantum directly (please don't do that if you aren't familiar with it — wait until up-to-date packages come to your distro).

**Comment by interconnectedMe** [comment]
Thanks tsujan,

I think I will not play too much with this for now then, and wait for a stable plasma ;-)
Thanks for your efforts with kvantum, I can't wait to be able to use it.

Regards,
DR
