### ISSUE TITLE
Blur is broken in plasma 6

### ISSUE THREAD

**Issue by mcodax** [tsujan/Kvantum#959]
Name
plasma-desktop
Version
6.0.1-1

Blur is broken in plasma 6

After updating to plasma 6.0.1-1 a few days ago, I got themes that were updated and compatible with the new version.

Problem is that blur doesn't work, dolphin appears fully transparent, menus appear fully transparent and so on (note that I have blur on in desktop effects and in Kvantum), this happens on both X11 and Wayland. I have the latest Kvantum version in Arch.

**Comment by tsujan** [comment]
Until V1.1.0 is released, use the latest git Kvantum.
