### ISSUE TITLE
1.1.0 build broken with Qt5

### ISSUE THREAD

**Issue by 0323pin** [tsujan/Kvantum#960]
Hi,

Setting `CMAKE_ARGS+=	-DENABLE_QT5=ON` on the new release produces a broken build of `kvantum`. The only installed file in this case is `qt5/plugins/styles/libkvantum.so`, no binaries or themes are installed.

This make sense when I look at the `CmakeLists.txt`:
```
[...]
option(ENABLE_QT4 "Building Qt4 plugin." OFF)
option(ENABLE_QT5 "Building Qt5 plugin." OFF)
option(WITHOUT_KF "Compiling without KDE Frameworks..." OFF)

add_subdirectory(style)
if(NOT ENABLE_QT4)
  if(NOT ENABLE_QT5)
    add_subdirectory(kvantumpreview)
    add_subdirectory(kvantummanager)
    add_subdirectory(themes)
  endif()
endif()
```

This means, when `ENABLE_QT5` is `ON` the subdirectories are not created.

I don't think this is the intended behavior?

**Comment by tsujan** [comment]
You'll see that ChangeLog is correct once you remember the logic behind it: Qt6 and Qt5 plugins should be installable in parallel because the user may have both Qt5 and Qt6 apps.

Porting to Qt6 means that we say goodbye to Qt5. But Kvantum never says a complete goodbye — actually, Kvantum can still be compiled against Qt4 ;)

**Comment by 0323pin** [comment]
In which case, I will patch `CMakeLists.txt`, build it against Qt5 (hopefully for the last time) and update the package. We have a stable release coming out in a few weeks.

Personally, I've dropped Qt5 and only use Qt6. Unfortunately, for `kvantum` we still don't have KF6 else, I would switch to Qt6.

**Comment by 0323pin** [comment]
@tsujan is it possible to build using Qt6 against frameworks 5?

**Comment by tsujan** [comment]
I'm afraid not; KF5 doesn't work with Qt6.

**Comment by 0323pin** [comment]
> I'm afraid not; KF5 doesn't work with Qt6.

Expected that to be honest, thanks!

**Comment by 0323pin** [comment]
I've actually tried to build `kwindowsystem`-6.0.0 but, then I need `extra-cmake-modules`-6.x.x and ... unfortunately, the list will grow. I've asked if there's a draft package in the works. Would you suggest just keeping `kvantum`-1.0.10 until KF6 is available?

**Comment by tsujan** [comment]
> I've actually tried to build kwindowsystem-6.0.0 but, then I need extra-cmake-modules-6.x.x and ...

Yes, I remember I did exactly the same thing before KF6 cam here:) IMHO, waiting for KF6 is the best way.

> Would you suggest just keeping kvantum-1.0.10 until KF6 is available?

Yes. Or you could use this git commit if you want all workarounds/fixes available in 1.1.0 (only a few): https://github.com/tsujan/Kvantum/commit/acc46e083b65f65623e7be5ede29f2d0921aea5a

**Comment by 0323pin** [comment]
Thanks!

**Comment by tsujan** [comment]
You're very welcome!

**Comment by tsujan** [comment]
Oh, I forgot to mention this (read NOTE 1): https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md#compilation

Without KF, you'll only lose the blur effect under Wayland.

**Comment by 0323pin** [comment]
Nice 👍
I'll discuss the pros and cons of doing this. It might be worthy waiting for kf6 anyway, I'll need it for the LXQt update when it comes out.
