### ISSUE TITLE
Cannot change titlebar colour

### ISSUE THREAD

**Issue by micmalti** [tsujan/Kvantum#961]
Hi, first of all thank you for the work you've been doing on this project. 

I'm running Manjaro with KDE Plasma 5.27.10 and I'm trying unsuccessfully to change the titlebar colour of Konsole, first by using a window rule, then in Kvantum. Initially, I thought this might be due to a [Plasma bug](https://bugs.kde.org/show_bug.cgi?id=433059), but that wasn't the case. Then, I began to suspect that it had something to do with a setting in Kvantum, since switching to any colour scheme whatsoever was keeping the title bar intact. However, if that's the real culprit, I can't find which one it is. 

Attached is the currently active theme settings. This is how the titlebar looks like right now:

![Screenshot_20240319_173102](https://github.com/tsujan/Kvantum/assets/31540652/0bd1d02f-830e-4495-ad2f-f02d4b34a1af)

[Canta-light.txt](https://github.com/tsujan/Kvantum/files/14653597/Canta-light.txt)

**Comment by tsujan** [comment]
Kvantum is a Qt widget style; it doesn't have anything to do with title-bars.

Title-bars are handled by WMs — in your case, KWin. Make sure that you've applied the KDE color scheme that comes with the Kvantum theme you use. All Kvantum themes that come with Kvantum are accompanied by a matching KDE color scheme (not necessarily with the same name).

**Comment by micmalti** [comment]
Hi there, thanks for your reply. Just wanted to let you know that the issue was related to the window decorator theme not supporting KWin rules for app-specific themes. For anyone who may be facing the same problem, I found out that sticking with the default Breeze theme is the way to go (it's the only theme I came across that actually supports this):

![Screenshot_20240621_040334](https://github.com/tsujan/Kvantum/assets/31540652/76e6d0ce-5e44-47f7-ba10-872d663ed29a)
