### ISSUE TITLE
Transparency working intermittently 

### ISSUE THREAD

**Issue by peddy22** [tsujan/Kvantum#967]
Hi there, 

I clean installed 23.10 on my Thinkpad with the Sweet KDE theme. In the past the application launcher transparency has worked flawlessly. However now it seems to be working intermittently. 

See this screenshot showing how the launcher transparency functions correctly when there is no window behind it
![Screenshot_20240401_192852](https://github.com/tsujan/Kvantum/assets/58948206/0788c310-483a-46e9-9a8f-4cfc76c97ec0)

Next see how the transparency behaves when I have a window open behind the launcher, e.g. Google Chrome

![Screenshot_20240401_193538](https://github.com/tsujan/Kvantum/assets/58948206/951fcdaa-5289-4735-a9af-5dcc80de46f3)

Additionally if the window is only partially in the background the transparency works fine

![3](https://github.com/tsujan/Kvantum/assets/58948206/07986906-73c2-4b51-bd51-3ffa7c8fbc07)

When I collapse the menu I briefly see the blurred background in the background. I still have my old install and the issue is not present there.

Can you please help me to resolve this?

**Comment by tsujan** [comment]
That menu belongs to KDE Plasma and isn't drawn by Kvantum.

> I clean installed 23.10 

Whatever 23.10 means (which distro?!), there's a problem in the version of KDE that comes with it. The problem may be temporary, but as mentioned above, Kvantum doesn't control how that menu is drawn or blurred.

**Comment by peddy22** [comment]
Kubuntu!

I will keep trying to fix the issue. I have it working fine on another
machine, just not this one. I found it odd that it draws the transparent
background fine as long as there's not a Fullscreen window behind it.

Thanks for your quick response.

Arno

**Comment by tsujan** [comment]
Have you recently updated a KDE package?

**Comment by peddy22** [comment]
The issue was with a hidden configuration setting in the theme I was using (sweet KDE)

I discovered you could enable panel and launcher transparency in KDE for some themes without Kvantum on this site

https://forum.endeavouros.com/t/tip-panel-translucency-in-kde-plasma-without-kvantum/15048

This led to me finding the option in /home/arno/.local/share/plasma/desktoptheme/Sweet/metadata.desktop for "[AdaptiveTransparency]" which I simply set to false

Now everything is good and transparent

Thanks again, I will close this issue

**Comment by peddy22** [comment]
you should reboot compiz fusion or beryl desktop, we need 3d desktop cubes/polyhedra and the ability to paint fire in this day and age

**Comment by tsujan** [comment]
> This led to me finding the option in /home/arno/.local/share/plasma/desktoptheme/Sweet/metadata.desktop

Yes, that file belongs to the Plasma theme, not Kvantum.

In your case, "Sweet" is the name of a set of themes that match each other, probably including a Kvantum theme, a KDE color scheme, a Plasma theme, etc.

Please note that Kvantum is NOT a KDE app but a Qt style plugin. Of course, it works in KDE because KDE itself is made based on Qt. Kvantum is also tuned to KDE, using its blur effect if present. However, how Plasma is drawn is completely determined by KDE.

**Comment by peddy22** [comment]
Very interesting. I wonder if kvantum uses 'official' kde API calls or if
it's a bit more hacky. Because the only purpose I am using it for is to add
transparency in unsupported apps. And it seems to use KDE's built-in
transparency settings, rather than provide its own transparency.

Regardless, I am grateful for such a plugin to exist. It seems Linux,
especially GNOME, is going more and more Windows-macOS-like in terms of
reducing customizability and theme-ability. Of course, third-party apps
will always exist, but will be unmatched when it comes to the degree of
customization possible through Linux.

I am using a rather old Thinkpad (3rd gen intel) but it runs like new and
looks the part with all the customizations I have applied to it.

Good day!
Arno

**Comment by tsujan** [comment]
> I wonder if kvantum uses 'official' kde API calls

Kvantum uses standard Qt methods, and so, it can style Qt apps under any DE, even GNOME.

The only place where Kvantum (optionally) uses KDE API is in blurring: for it, Kvantum makes use of `KWindowSystem`, which is made by KDE devs but does not depend on KDE itself.
