### ISSUE TITLE
Is this qbittorrent UI issue related to kvantum?

### ISSUE THREAD

**Issue by peddy22** [tsujan/Kvantum#969]
Easier to link here

https://github.com/qbittorrent/qBittorrent/discussions/20657

A simple yes or no will suffice. 

Running different kvantum versions on the two machines. 

Cheers

**Comment by tsujan** [comment]
> A simple yes or no will suffice.

It's not that simple ;)

If you use a relatively old distro which doesn't support Qt6 styling (like an LTS distro), the problem you see can exist because qbittorrent has migrated to Qt6, while your DE may not support Qt6 styling.

However, even under a DE that supports Qt6 styling, there is a translucency issue that is caused by incorrect, hard-coded style codes in recent versions of qbittorrent, such that you need to add `qbittorrent` to the list of opaque apps in Kvantum Manager.

**Comment by peddy22** [comment]
Thanks for the detailed reply. I'm now wondering if there's a simple fix to
get at least the proper spacing back, or if I have to go back to the LTS
release. Even the current release I'm on is not qt6

Arno

**Comment by tsujan** [comment]
qBittorrent is a very good app but, sadly, it has started to include more and more incorrect/incomplete style codes. The problem with hard-coded styles is that, even when they are correct, they may break platform integration outside MS Windows or without the Fusion style.

> if there's a simple fix....

The real fix is extremely simple, but it can be done only in the app itself: leave theses things to the Qt style, and if you want your app to look differently under MS Windows, add OS checks to your code.

**Comment by tsujan** [comment]
> If you can fix the qbittorrent code...

My coding time is completely taken by my apps and LXQt.

As I mentioned, it's a matter of cleaning up ;) But qBittorrent's developer(s) preferred to go in the opposite direction. You have 4.5.4; what will you say when you get 4.6.4 (installed here)? Anyway, their app, their choice. We can only be thankful that they've shared it for free.

**Comment by peddy22** [comment]
I guess I will have all the coffees for myself!

Anyhow, all is well - I downgraded to the older version via a .deb package and locked it to prevent upgrading.

The AppImage of the old version had the interface issues still, probably due to static linking, but the deb file has resolved it nicely. 

Will you help me make a bug report to qbittorrent? I have the screenshots showing the issue, but a couple of technical languages will help I'm sure (you can just tell me what to say)

Or should the bug report go to KDE?

Cheers

**Comment by tsujan** [comment]
> The AppImage of the old version had the interface issues still

AppImage? Then I doubt that what you see is caused by qBittorrent. Nonstandard installations are known to have problem with Qt style.

**Comment by peddy22** [comment]
Are you saying appimage is considered a nonstandard installation? A bit
confused by your reply

Arno

**Comment by tsujan** [comment]
> Are you saying appimage is considered a nonstandard installation?

Of course, it is. You have a Debian system; so your standard installation is done by `apt` (or an app that uses `apt`) and with deb packages.

I'm not saying that other kinds of installation are necessarily bad (although I never use them), but they have their own problems, which should be reported to their maintainers.

**Comment by peddy22** [comment]
Ok, thanks for the clarification. The problem occurs with both appimage and
debian packages so I will file a bug with qb.

**Comment by tsujan** [comment]
I don't see the specific problem you mentioned in the latest version of qBittorrent — yes, it has GUI problems but not that one:

![side-pane](https://github.com/tsujan/Kvantum/assets/981076/076e1617-6c6d-48fc-a7d6-4f34c294c9d8)

**Comment by peddy22** [comment]
What qt/plasma version are you running?

Arno

**Comment by tsujan** [comment]
I don't use Plasma, although I have it. The screenshot was taken under LXQt+LabWC (LabWC is a Wayland compositor), but it's the same under LXQt+kwin_x11, or under Plasma.

I have qBittorrent 4.6.4 and Plasma 6.0.3 (Qt6-based). However, qBittorrent had the same look with older versions too.

**Comment by tsujan** [comment]
Another screenshot with another Kvantum theme:

![side_pane1](https://github.com/tsujan/Kvantum/assets/981076/62d7828a-9c17-4669-b01e-278a2a78d094)

**Comment by peddy22** [comment]
It sounds like it will be hard to determine which package is at fault. Hopefully by the next major distro release the issue will be resolved.

I just upgraded to the latest deb file via qbittorrent's official PPA and the issue returned. 

![image](https://github.com/tsujan/Kvantum/assets/58948206/24b81d56-a8e2-4f1a-90fb-287589574cfc)

I will file a bug with qbittorrent, and if that fails with Kubuntu for providing a qbittorrent version incompatible wit
h other system libraries (like qt). 

I'm not convinced you're not exhibiting this bug - for example in my screenshots you can see transparency behind the pause/add torrent toolbar at the top, in the older version. Also your left panel icons do not seem to be themed.

**Comment by tsujan** [comment]
As I said, they added hard-coded styles to their recent versions. That can't be called a bug; it's just a bad choice.

The only bug I see here is about total transparency of the left pane (mentioned above), but it didn't happen in the version you have. I didn't report it due to lack of time.

**Comment by peddy22** [comment]
So you're saying their decision to hard code styles has completely disabled transparency for the top toolbar and the left pane as well?

**Comment by tsujan** [comment]
> So you're saying their decision to hard code styles has completely disabled transparency for the top toolbar and the left pane as well?

In a recent version of qBittorrent, they added some wrong code which made the side-pane have a completely transparent background when translucency was enabled. The developers of qBittorrent can't see the problem because they use styles like Fusion or Breeze, which don't support window translucency. The workaround was adding `qbittorrent` to the list of opaque apps in Kvantum Manager.

**Comment by peddy22** [comment]
gotcha. it seems we are experiencing different bugs. i don't get transparency on the newest version at all, with or without qbittorrent added to the blacklist.

**Comment by tsujan** [comment]
Probably, for some reason, Kvantum isn't applied to qbittorrent at all with the version you have — only its color palette is.

**Comment by peddy22** [comment]
let me know if you want to investigate further. i am happy on the old version.
