### ISSUE TITLE
Under the light theme, some icons may become jagged when zoomed to non-integer times

### ISSUE THREAD

**Issue by jcfun** [tsujan/Kvantum#976]
OS: ArchLinux
DE: KDE Plasma 6.0.4
Theme: Monterey

I used multiple themes for testing and found that some icons (or fonts?) would be jagged when the light theme was scaled to non-integer times, but this problem did not occur under the dark theme. Here is an example of a Monterey theme:

Light:
![2024-04-26_01-24](https://github.com/tsujan/Kvantum/assets/58456995/c1eeac2c-c489-4229-82e1-a168feebba93)
![2024-04-26_01-52](https://github.com/tsujan/Kvantum/assets/58456995/79d23dd4-b4b5-4ffa-a274-a6e33447f445)

Dark:
![2024-04-26_01-49](https://github.com/tsujan/Kvantum/assets/58456995/4f07ff10-3c26-42c6-8721-c3798f50aed5)
![2024-04-26_01-52_1](https://github.com/tsujan/Kvantum/assets/58456995/112f94a3-47c5-4fe0-b37c-02326718338a)

**Comment by tsujan** [comment]
The problem can't be in Kvantum, especially because both dark and light themes are drawn by it in the same way.

Although fractional scale factors have known problems, this may be an issue in `qqc2-desktop-style`, because those widgets are based on QML.

Closing this, but comments could be added...
