### ISSUE TITLE
Persistent editor in QTreeView

### ISSUE THREAD

**Issue by evgeniy-harchenko** [tsujan/Kvantum#982]
Persistent editor in QTreeView (maybe not only) has wrong text color. As a result we have white text on white background. The problem occurs only with light themes.
![image](https://github.com/tsujan/Kvantum/assets/42656259/cb14e4b2-b4af-440e-bf78-8503908af005)
Here is a sample project: [link](https://github.com/evgeniy-harchenko/kv_bug). There is `MyQTreeView` class which inherits `QTreeView` and uses persistent editor. To reproduce the problem you should select any item and press F2, it invokes `openPersistentEditor` . Then you should deselect text.

**Comment by tsujan** [comment]
Thank you very much for reporting it — nice catch! Fixed in https://github.com/tsujan/Kvantum/commit/695b129c2da06b17c998c26e2e49e10e24ea2e39.

It was a side effect of an old workaround for apps like (old versions of) VLC.
