### ISSUE TITLE
Graphical issues with Kdenlive effects rack

### ISSUE THREAD

**Issue by jmfergeau** [tsujan/Kvantum#983]
Been a month i'm looking for this issue and it appears it's not caused by kdenlive itself but by the kvantum theme that is used.

The effects rack should display as filled width rack lines but it doesn't when using a kvantum theme like below:
![The glitch](https://github.com/tsujan/Kvantum/assets/6705075/cb2914c1-3ff8-491a-bdc5-f427d9f63b57)

Only happens when kdenlive is natively installed. Doesn't happen with flatpak since it doesn't use kvantum.

(The effect list is also glitched, showing a pitch white window instead. I'm not sure it's caused by kvantum but this problem doesn't occur with the flatpak version either so i suspect it as well.)

**Comment by tsujan** [comment]
Installed kdenlive 24.05.0-1 from Arch and didn't find any problem in its effects stack:

![kdenlive](https://github.com/tsujan/Kvantum/assets/981076/756c870a-c7fe-4d79-9258-0609c9e0ac3f)

Make sure you have the latest version of Kvantum.

Also, please be a little more specific when you talk about apps, noting that there's no reason a developer should know what this or that app does. I've never used kdenlive and didn't know what you meant by its "effects rack".

**Comment by jmfergeau** [comment]
Try with KvAquaDark

But fine. I'll just stop using kvantum then.
