### ISSUE TITLE
Feature request: respect CSS selectors in custom stylesheets

### ISSUE THREAD

**Issue by LeXofLeviafan** [tsujan/Kvantum#987]
Suppose I'm using an app which has customized button subclasses, and [alters appearance of such buttons (mainly the background color) depending on button state](https://github.com/AntiMicroX/antimicrox/blob/3.4.0/src/gui/mainwindow.ui#L30-L36).

Such settings rely on CSS selector specificity rules to work; but Kvantum appears to ignore those completely, effectively overriding such settings altogether.

<details><summary>without Kvantum: highlighted buttons are easy to tell apart</summary>

![flashing](https://github.com/tsujan/Kvantum/assets/16271003/9ba344df-e473-465e-9d9a-5846aaa1ca74)
![inactive](https://github.com/tsujan/Kvantum/assets/16271003/fafc5a88-5e79-4d81-aa03-a3dd248b2ddf)
</details>
<details><summary>with Kvantum: highlighted buttons are (near) identical to non-highlighted ones</summary>

![flashing](https://github.com/tsujan/Kvantum/assets/16271003/e233af23-a9cb-4ab7-8ffe-0ad84cef75a0)
![inactive](https://github.com/tsujan/Kvantum/assets/16271003/6f880793-810e-4177-be5b-efcfd6f4a182)
</details>

There doesn't seem to be any way to work around this from within the app code; and switching to a different Kvantum theme has no effect on the issue.

**Comment by tsujan** [comment]
Qt stylesheet style is incompatible with all other widget styles (Qt devs have been aware of that for a long time), especially with Kvantum. Kvantum includes codes to find and "tolerate" incompatibilities and inconsistencies, and that's the best it can do.

If you make a stylesheet, make it _complete_, such that it fully overrides the active widget style, whether you do it in your code or in a ui file. How good or ugly it'll seem against the background of the active widget style will be your responsibility.

However, working directly and correctly with `QStyle` in codes is the best approach *if you really need a widget of your app to look a little different from the platform theme.* Only in this way the new look is guaranteed to be self-consistent alongside all styles, **provided that you treat all the relevant `QStyle` parameters as parameters and not as constants.**
