### ISSUE TITLE
Kvantum made my maximize/ minimze windows animation speed instant

### ISSUE THREAD

**Issue by Achno** [tsujan/Kvantum#990]
Kvantum : extra/kvantum 1.1.2-1

DE: KDE Plasma 6.1.2

I just did a clean install of plasma 6.1.2, the animations were slow and nice and the moment i installed kvantum the minimize / maximize animations for windows became instant.

EDIT: the Close animation is perfectly fine its only the minimize/ maximize animation

Its like Kvantum is not respecting the Animation speed slider. I did not find an option in kvantum to tweak  that in the safe settings.

The closing animation when i press ctrl+q to exit an application or the animation of the plasma panel auto hide is perfectly fine though and follows the animation slider.

**Comment by tsujan** [comment]
Minimizing and maximizing is done by the window manager (KWin in KDE) and has nothing to do with the widget style (Kvantum).
