### ISSUE TITLE
Theme Request: Numix

### ISSUE THREAD

**Issue by gsantner** [tsujan/Kvantum#992]
Hello!

I've been checking kvantum a few times over the last years and unfortunately there is no support for the (I thought popular) Numix theme in LxQT & kvantum so I always went back to QPA=gtk2 + Numix loaded as gtk theme.

Would be supporting Numix be an option?  Or is there some place where a Kvantum Numix theme by chance has been made already? I couldn't find any at least unfortunately.

References:
* https://www.gnome-look.org/p/1013541
* https://github.com/numixproject/numix-kde-theme
* https://github.com/numixproject/numix-gtk-theme

Here are some screenshots to get a rough overview:

![Screenshot_20240729-155602](https://github.com/user-attachments/assets/8ac81a73-cfa1-4b90-8deb-6a4cde4fc607)

---

![Screenshot_20240729-155040](https://github.com/user-attachments/assets/4796a53a-dc8d-419b-a63e-e54c8ec47439)

Light background generally, but dark titlebar, windows, sidebars, menus etc. Orange-red focus/highlight/select color.  
KvAmbience (not Ambi**a**nce) is probably the one most basic matching, but still so much different [worse] then Numix-gtk3 and Qt-with-gtk2-Numix.

Thanks, hope it's OK to ask about this here.

**Comment by tsujan** [comment]
Sorry, I don't have a plan to add more themes here. My focus is on the code.

There are many Kvantum theme makers, whose works can be installed and activated through Kvantum Manager with user permissions.

That being said, Qt isn't happy with a light view color and dark window color, as in your first screenshot. See https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Making.pdf for details.

**Comment by gsantner** [comment]
OK so you would not accept a merge request to add the theme either? @tsujan 

I have a basic configured one basd on KvAmbiance here.

**Comment by tsujan** [comment]
Due to my limited time for maintenance, I'm afraid I don't intend to add more themes to the source.

> Unfortunately full light or full dark and nothing in between is getting more focus yes

Dark-and-light themes are quite possible — I like them, and I'm using one of them right now — but window and base colors shouldn't have a high contrast with each other. See `KvAmbience`, `KvMojaveMixed`, `KvMojaveMixed1` and `KvSimplicityTurquoise` for examples of dark-and-light themes.
