### ISSUE TITLE
transparent dropdown menus?

### ISSUE THREAD

**Issue by lightnignmc09** [tsujan/Kvantum#997]
![image](https://github.com/user-attachments/assets/c09d4b60-a687-451b-ac52-e997d9e48fdd)
This happens with both the built in themes and the one i added, im on linux mint 21.3 xfce

**Comment by tsujan** [comment]
Not reproducible. Here menus are OK under kwin_x11, xfwm4, kwin_wayland, LabWC, Wayfire,...

Your problem may be related to the compositor you use.

**Comment by sglbl** [comment]
@LightningRadiant I have the same problem. 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a9edd92c-1e2c-47a2-8226-18ff873766d6" />

When I try to select an extension:
<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/7ff2526d-d9a1-4205-96a8-56579fd458f1" />

System:
```console
(base) sglbl@ddspc:~$ inxi -S && echo "  Session: $XDG_SESSION_TYPE"
```
<pre><font color="#2A7BDE"><b>System:</b></font>
  <font color="#2A7BDE"><b>Host:</b></font> ddspc <font color="#2A7BDE"><b>Kernel:</b></font> 6.17.0-14-generic <font color="#2A7BDE"><b>arch:</b></font> x86_64 <font color="#2A7BDE"><b>bits:</b></font> 64
  <font color="#2A7BDE"><b>Desktop:</b></font> GNOME <font color="#2A7BDE"><b>v:</b></font> 46.0 <font color="#2A7BDE"><b>Distro:</b></font> Zorin OS 18 noble
  <font color="#2A7BDE"><b>Session:</b></font> x11
</pre>

Theme: Modified version of KvArcDark for Zorin OS

<img width="805" height="1162" alt="Image" src="https://github.com/user-attachments/assets/adb0ea81-12a0-4b59-a611-15f51bfd9a33" />
Only difference in the theme is:

```bash
sed -i 's/^base.color=.*/base.color=#2D3940/' ~/.config/Kvantum/KvArcDark#/KvArcDark#.kvconfig
```

**Comment by sglbl** [comment]
I solved the issue.
```console
(base) sglbl@ddspc:~$ sudo apt install kwin-x11 xfwm4 labwc wayfire
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
kwin-x11 is already the newest version (4:5.27.11-0ubuntu3).
xfwm4 is already the newest version (4.20.0-1~bpo24.04+zorin3).
labwc is already the newest version (0.7.1-1build1).
wayfire is already the newest version (0.8.0+git20240110-2.1build1).
The following packages were automatically installed and are no longer required:
  geany-common gir1.2-nautilus-4.0 libetonyek-0.1-1 libthunarx-3-0 thunar-data
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 5 not to upgrade.
```

I also tried to change the compositor from x11 to wayland as @tsujan suggested but nothing changed. At the end I found the solution by changing fusion css style sheets from Qt5 Configuration Tool `qt5ct`
